### ISSUE TITLE
在模板中怎么用 Request 对象

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#102]
在没有去掉 ACTION_NAME 的时候,  可以使用 {:U(ACTION_NAME)} 去生成当前页面URL
现在在模板语法中, 该如何直接获取 ACTION_NAME 等常量内容 ??

**Comment by momoca** [comment]
request()->action()

**Comment by liu21st** [comment]
其实你一样可以在应用中 自己定义常量的

**Comment by momoca** [comment]
@liu21st 是的.也可以自定义...
