### ISSUE TITLE
建议允许 protected $deleteTime = false; 关闭软删除

### ISSUE THREAD

**Issue by zuozhehao** [top-think/framework#1031]
建议允许 protected $deleteTime = false; 来关闭软删除.

**Comment by liu21st** [comment]
属性设置关闭 你不引入软删除就行了？

**Comment by zuozhehao** [comment]
目前数据表有20多张表都需要软删除,有个表不需要软删除.
所以我写了个父类,并引入软删除和设置了字段名.
问题就出来了.
要不我就不用软删除,要不我就得单独在20多个模型引入软删除.

虽然可以用User::withTrashed(),但这个又不能使用缓存了.

**Comment by liu21st** [comment]
不需要使用软删除的模型 不要继承你的父类

**Comment by zuozhehao** [comment]
@liu21st 父类不是只加了软删除而已,还有其它方法

**Comment by liu21st** [comment]
我改进支持了下
