### ISSUE TITLE
5.1.3 自定义app_path后出现不能加载扩展库

### ISSUE THREAD

**Issue by liuwave** [top-think/framework#1043]
\thinkphp\library\think\Loader.php  第67行：
  

> 
    
  $path = dirname($_SERVER['SCRIPT_FILENAME']);
        if (is_file('./think')) {
            $rootPath = realpath($path) . '/';
        } else {
            $rootPath = realpath($path . '/../') . '/';
        }

获取 $rootPath 和App.php中$this->rootPath    = dirname(realpath($this->appPath)) . '/';设置的不统一，

在自定义apppath后，

> 
define('APP_PATH', __DIR__ . DIRECTORY_SEPARATOR. '..' . DIRECTORY_SEPARATOR . 'run_path' . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR);
require __DIR__ . DIRECTORY_SEPARATOR. '..' . DIRECTORY_SEPARATOR . 'run_path' .
    DIRECTORY_SEPARATOR . 'thinkphp' . DIRECTORY_SEPARATOR . 'base.php';
Container::get('app')->path(APP_PATH)->run()->send();
会出现错误

致命错误: Class 'think\helper\Time' not found

**Comment by liu21st** [comment]
Loader类执行自动加载注册的时候是拿不到应用目录的~ 所以不要随便自定义应用目录

**Comment by mineyang** [comment]
有这样一个应用场景：
官方示例目录结构中，`public` 存放 H5 静态文件，而 `public/api/index.php` 为入口，这时 `$rootPath` 的计算就不准确了。

而在 5.0 版中，却可以通过定义 `ROOT_PATH` 来解决这个问题

**Comment by yunwuxin** [comment]
@mineyang 不要问为什么5.0可以 而5.1不可以   5.1就是要把目录结构固定下来  方便扩展的开发

**Comment by mineyang** [comment]
@yunwuxin 那就是不准备支持 `public/api/index.php` 为入口这种形式了？

**Comment by liuwave** [comment]
以后会支持么？  这样不能自定义应用目录，部署也不那么灵活了。 @liu21st

**Comment by kinosang** [comment]
@mineyang 对于目录层级，推荐使用内置路由处理。

**Comment by mineyang** [comment]
@kinosang  我把入口设置为 `public/api/index.php`，是因为public目录下是纯静态的H5，这里的默认页是 index.html，他可以这样去调用接口：`/api/user/info`

**Comment by kinosang** [comment]
@mineyang 你可以把去api的路由设置成`/api/user/info`，web 服务器合理配置，存在的文件不走 PHP，index.html 排到第一顺序。

**Comment by mineyang** [comment]
问题是现在的前端也会用重写的，比如使用 Vue 的 History 模式

**Comment by kinosang** [comment]
@mineyang Vue 的 history 模式不会影响 js 对 API 的调用
