### ISSUE TITLE
v5.1.3 auto_bind_module配置不生效

### ISSUE THREAD

**Issue by xiaoxintiaoda** [top-think/framework#1045]
thinkphp 版本: v5.1.3
php 版本: 5.6.x
直接修改config目录中的 app.php的auto_bind_module选项为项目中的某个模块，如:pay，然后访问该模块下面的controller,如:Alipay,然后就会报错"模块不存在:Alipay",如果正常的带上模块名 pay 去访问，则是正常的

**Comment by liu21st** [comment]
auto_bind_module不是你这样用的 仔细看手册
