### ISSUE TITLE
缓存BUG

### ISSUE THREAD

**Issue by zuozhehao** [top-think/framework#1046]
场景:
当前用户id,最大为100. 

User::get(101, true); // 为空,这边是正确的.

User::create(); // User::insert();// 新增一个用户(它的id是101)

`User::get(101, true);// 为空.(除了缓存过期或101 用户id有修改,才会正确)`

建议在新增的时候可以直接缓存数据.

**Comment by liu21st** [comment]
新增的时候直接缓存还不乱了 都是查询的时候指定的 数据更新的话 是会自动更新缓存

**Comment by zuozhehao** [comment]
那看我上面的场景,当数据不存在的时候,也缓存了空数据.

在缓存没过期或者没有更新的情况下.

查询到的始终是空的数据.

**Comment by liu21st** [comment]
你是哪个版本 数据不存在应该不会缓存数据

**Comment by zuozhehao** [comment]
5.1.3和5.1.4都会

**Comment by liu21st** [comment]
已经修正
