### ISSUE TITLE
5.1引入composer加载的包会报错

### ISSUE THREAD

**Issue by xiucaiwu** [top-think/framework#1049]
/var/www/application/tp5.0.13 # php public/index.php index/Index/start
^C
/var/www/application/tp5.0.13 # cd ../tp5.1
/var/www/application/tp5.1 # php public/index.php index/Index/start

Fatal error: Class 'think\swoole\Server' not found in /var/www/application/tp5.1/application/index/controller/Index.php on line 6

  [think\exception\ErrorException]
  Class 'think\swoole\Server' not found

Exception trace:
 () at /var/www/application/tp5.1/application/index/controller/Index.php:6
 think\Error::appShutdown() at n/a:n/a

同样的代码在5.0.13可以正常运行,在5.1就报错

**Comment by AxiosCros** [comment]
5.0和5.1是不兼容的，文件目录结构都不一样了
