### ISSUE TITLE
模型类关联缓存BUG

### ISSUE THREAD

**Issue by zuozhehao** [top-think/framework#1053]
修改关联表数据后,获取到的关联表数据并未更新.

$data = User::get(1, 'userData', true); // 第一次查询

UserData::update(['field' => 1], ['id' => 1]); // 更新关联表

$data = User::get(1, 'userData', true); // 再次查询,数据并未修改

@liu21st

**Comment by liu21st** [comment]
其实后来想了下 预载入查询的缓存意义不大 本来就是两次查询 缓存主表后就是一次查询
