### ISSUE TITLE
Url生成BUG

### ISSUE THREAD

**Issue by zuozhehao** [top-think/framework#1061]
aaa模块绑定www.test.com
bbb模块绑定绑定到bbb.test.com

在aaa模块下 url 第一个参数 `@bbb` 无效.无法生成bbb域名

@liu21st

**Comment by zoujingli** [comment]
url方法的第四个参数可以绑定域名

**Comment by zuozhehao** [comment]
输入全域名这个我知道可以,但是只输入前缀不行
