### ISSUE TITLE
助手函数input获取session数据错误，未开启session_start

### ISSUE THREAD

**Issue by ZoaChou** [top-think/framework#108]
代码示例：

```
class A{
    public function index(){
        input('session.abc');
    }
}
```

错误：
[8] ErrorException in Input.php line 135
Undefined variable: _SESSION

**Comment by momoca** [comment]
这个我之前提过.这不算错误,是session没有初始化所导致的.你可以使用session().或使用\think\Session::init();

**Comment by ZoaChou** [comment]
@momoca 如果“input本来就是输入输出并不需要处理session_start”这句话是正确的那和代码里面的`PHP_SESSION_DISABLED == session_status()`这个判断之后再处理session_start应该会有歧义？
上面提到的代码示例里面的`session_status == PHP_SESSION_NONE`，是否可以理解成状态的判断不完整？

**Comment by momoca** [comment]
https://github.com/top-think/think/issues/383

**Comment by ZoaChou** [comment]
理解，但官方回复还是和之前说的那处判断代码矛盾，既然要自己session_start又多一个判断自动session_start，实在无法理解……
