### ISSUE TITLE
MorphMany 里面的 eagerlyMorphToMany方法里面的第一行 removeOptions是什么鬼？作者细心点。。。

### ISSUE THREAD

**Issue by gml1994** [top-think/framework#1098]
MorphMany 里面的 eagerlyMorphToMany方法里面的第一行 removeOptions是什么鬼？作者细心点。。。找了半天我代码的问题。。。结果去看源码。。。发现这个方法根本就不存在。。。一看多了个s

**Comment by liu21st** [comment]
感谢反馈 已经修正
