### ISSUE TITLE
关controller name 自动转换下划线_和后面的单词小写字母为大写字母

### ISSUE THREAD

**Issue by hainuo** [top-think/framework#1099]
![image](https://user-images.githubusercontent.com/421861/36640117-40053ffa-1a54-11e8-8764-d4dbfc9cf025.png)

手动做权限控制时发现这个自动转换下划线的问题，想请教下为什么要这样做，为什么对控制器做了这样的处理，对action name并没有进行转换？
真正开始处理权限才发现这种设计方法有些不可捉摸。
@liu21st

**Comment by liu21st** [comment]
驼峰法的控制器名称才是实际的控制器名
