### ISSUE TITLE
应用程序目录下放置的tags.php 无法正确的调用行为的方法

### ISSUE THREAD

**Issue by tdcms** [top-think/framework#1112]
/application/tags.php 代码如下

`<?php`
`// 应用行为扩展定义文件`
`return [`
`	// 应用初始化`
`	'app_init'     => ['app\common\behavior\Test']`
`];`

------------------------------------------------------

/application/common/behavior/Test.php 代码如下

`<?php`
`namespace app\common\behavior;`
`class Test`
`{`
`	public function run( &$args )`
`	{`
`		echo 'Hello Test';`
`	}`
`}`

------------------------------------------------------

错误提示:
**method not exists: app\common\behavior\Test::run()**

# 请问改如何解决？？？？

@liu21st

**Comment by tdcms** [comment]
版本时5.1.5

**Comment by liu21st** [comment]
5.1的行为方法不支持引用传参
