### ISSUE TITLE
Route绑定模型使用闭包函数问题

### ISSUE THREAD

**Issue by 0377** [top-think/framework#1115]
文档是这样写的
`Route::rule('hello/:id',	'index/index/hello')
				->model(function	($param)	{
								$model	=	new	\app\index\model\User;
								return	$model->where($param)->find();
				});`
文档里面model方法里面直接是闭包函数；
Rule.php里面
`    /**
     * 绑定模型
     * @access public
     * @param  array|string      $var  路由变量名 多个使用 & 分割
     * @param  string|\Closure   $model 绑定模型类
     * @param  bool              $exception 是否抛出异常
     * @return $this
     */
    public function model($var, $model = null, $exception = true)
    {
        if (is_array($var)) {
            $this->option['model'] = $var;
        } elseif (is_null($model)) {
            $this->option['model']['id'] = [$var, true];
        } else {
            $this->option['model'][$var] = [$model, $exception];
        }
        //dump($this->option);
        return $this;
    }`
这里因为参数不是数组，所以进入elseif，导致闭包函数是在索引0 里面；
`   /**
     * 路由绑定模型实例
     * @access protected
     * @param  array|\Clousre    $bindModel 绑定模型
     * @param  array             $matches   路由变量
     * @return void
     */
    protected function createBindModel($bindModel, $matches)
    {
        foreach ($bindModel as $key => $val) {
            if ($val instanceof \Closure) {
                $result = Container::getInstance()->invokeFunction($val, $matches);
            } else {
                $fields = explode('&', $key);
`
这里遍历判断是否闭包的时候 直接使用$val 判断是否是闭包函数，而闭包函数现在在$val[0]里面；

我不知道是文档的错误还是代码的问题；
文档上面的代码改成数组里面存放闭包函数，就可以正常使用
``Route::rule('hello/:id',	'index/index/hello')
				->model([function	($param)	{
								$model	=	new	\app\index\model\User;
								return	$model->where($param)->find();
				}]);``

**Comment by liu21st** [comment]
我改进了下用法 还是按照文档的写法
