### ISSUE TITLE
建议 App 初始化时，提供 runtime 目录的注入

### ISSUE THREAD

**Issue by mineyang** [top-think/framework#1118]
在 `5.0` 中，我们的项目通过定义 `RUNTIME_PATH` 常量把该目录设置为一个独立的目录中，而现在 `5.1` 中却只能在项目的根目录下

**Comment by yunwuxin** [comment]
使用link就可以了 你爱放哪放哪  使用ln在根目录的runtime位置上创个软连接

**Comment by liu21st** [comment]
其实自定义runtime目录的需求没有必要 日志和缓存的目录本来就是可以单独定义的，而runtime目录系统需要统一规划便于管理及插件写入一些特殊的文件
