### ISSUE TITLE
快捷路由是否考虑可以指定任意一个可以被composer找到的类

### ISSUE THREAD

**Issue by bravelib** [top-think/framework#1122]
你好是有种想法。
想开发一些compser的模块作为TP的组件，类似laravel-admin这种，
当在指定路由这样指定的时候。
Route::controller('login','starnet\user\UserController');
Route::get('register','starnet\user\UserController@register');
使用这样的定义的路由规则虽然可以工作，
但是Module Controller Action 三个关键的参数都找不到了，导致视图文件也找不到了。
或者考虑一下laravel的publish功能。

**Comment by liu21st** [comment]
路由到一个类的话 和 模块/控制器/操作是没有任何关系的，至于模板渲染可以指定模板的
