### ISSUE TITLE
url 生成优化 建议

### ISSUE THREAD

**Issue by zuozhehao** [top-think/framework#1128]
url 生成地址(admin 二级域名绑定了admin模块)
如`admin.domain.com/controller/action`
当未配置路由规则的时候.
`url('controller/action@admin', '', '', true)`
无法生成`admin.domain.com/controller/action`

因无法使用正则,在多模块,多控制器,多方法.

`Route::domain('admin', [`
&nbsp;`'controller1/action1' => 'controller1/action1',`
&nbsp;`'controller2/action2' => 'controller2/action2',`
&nbsp;`'controller3/action3' => 'controller3/action3',`
&nbsp;`'controller4/action4' => 'controller4/action4',`
&nbsp;`'controller5/action5' => 'controller5/action5',`
&nbsp;`'controller6/action6' => 'controller6/action6',`
&nbsp;`'controllerN/actionN' => 'controllerN/actionN',`	
`]);`
目前发现路由配置文件越来越臃肿.每个模块下都得定义类似上面的路由规则,才可使用url助手函数生成对应的地址.

@liu21st

**Comment by liu21st** [comment]
嗯 我改进了下
