### ISSUE TITLE
model in 方法出错

### ISSUE THREAD

**Issue by adcbguo** [top-think/framework#1143]
模型使用in方法查询一直报错
thinkphp 5.1.5版本

**Comment by adcbguo** [comment]
我的使用方法是这样的
where(['id'=>['in',[1,2,3]]])

**Comment by adcbguo** [comment]
这样也不行
whereIn('id',[1,2,3])

**Comment by adcbguo** [comment]
我们前面使用5.0的项目都一切正常

**Comment by adcbguo** [comment]
thinkphp\library\think\db\Builder.php
list($exp, $value) = $val;
一直报这个文件363行出错，未定义索引1，应该是where解析错误，打印$val的值确实有时候没有第二个数组值

**Comment by adcbguo** [comment]
NOT也有问题

**Comment by adcbguo** [comment]
like 的模糊查询也有问题

**Comment by liu21st** [comment]
仔细看过5.1的手册了么？查询不是这样查的 whereIn('id',[1,2,3]); 是没问题的

**Comment by adcbguo** [comment]
都是parseWhereItem where子单元分析函数

**Comment by adcbguo** [comment]
return $this->where('is_default', 1)
            ->whereNotIn('parent_id', 0)
            ->whereOr(['chain_id' => $chainId])
            ->select()->toArray();

我测试类，这种方式是可以的，但是不支持原来的这种方式类吗  ['id'=>['in',[1,2,3]]]

**Comment by liu21st** [comment]
建议你仔细看一遍 5.0升级5.1的升级指导 https://www.kancloud.cn/manual/thinkphp5_1/354155
