### ISSUE TITLE
关于路径配置问题

### ISSUE THREAD

**Issue by singfox** [top-think/framework#1148]
`        $this->runtimePath = $this->rootPath . 'runtime' . DIRECTORY_SEPARATOR;`
`        $this->routePath   = $this->rootPath . 'route' . DIRECTORY_SEPARATOR;`
`        $this->configPath  = $this->rootPath . 'config' . DIRECTORY_SEPARATOR;`
这些路径无法更改了，环境变量中定义也无法更改
若是多个项目共同使用一套application，该如何是好？

**Comment by liu21st** [comment]
设计如此 为了方便扩展
