### ISSUE TITLE
之前的程序继承Controller重写了 fetch方法，从5.0.15升级到 5.0.16，模板定位就出现了问题

### ISSUE THREAD

**Issue by liuwave** [top-think/framework#1154]
> 模板文件不存在:/www/wwwroot/***/default/index/fetch.html

有必要这么处理么？
> if ('' === $template) {
            $trace    = debug_backtrace(false, 2);
            $suffix   = Config::get('action_suffix');
            $action   = $suffix ? substr($trace[1]['function'], 0, -strlen($suffix)) : $trace[1]['function'];
            $template = Loader::parseName($action);
        }

**Comment by liu21st** [comment]
这个问题我回头改进下

**Comment by wwek** [comment]
同~ 这个改进导致历史项目不能兼容了

**Comment by liu21st** [comment]
最新版本我增加了template.auto_rule配置参数 设置为2 后 就和之前一样了
