### ISSUE TITLE
全局中间件问题

### ISSUE THREAD

**Issue by fangxingguang** [top-think/framework#1157]
现在全局中间件注册后会直接执行，使用不方便。建议增加单独注册机制，在需要的地方调用，如laravel中routeMiddleware属性。

**Comment by liu21st** [comment]
可以在路由中使用middleware注册

**Comment by fangxingguang** [comment]
嗯  可以这样 

    middleware(\app\common\middleware\Auth::class)

因为我不是用默认的http目录，所以要加命名空间，写着稍微有点长，如果注册多个就更长了，还是觉得能先注册比较方便

**Comment by liu21st** [comment]
后面版本改进吧

**Comment by fangxingguang** [comment]
秒回啊  哈哈    期待改进  谢谢解答  支持TP

**Comment by liu21st** [comment]
已经更新支持 可以git更新测试下

**Comment by fangxingguang** [comment]
赞  我去试试

**Comment by fangxingguang** [comment]
试了下没有问题 

同时再提个建议，对于应用目录下面定义middleware.php是否合并进配置文件好些？
比如config下的middleware.php中定义global、route分类，把中间件管理集中到一起。
