### ISSUE TITLE
中间件bug

### ISSUE THREAD

**Issue by fangxingguang** [top-think/framework#1158]
use traits\controller\Jump;

    class Auth {
        use Jump;

        public function handle($request, \Closure $next) {

            $this->result('auth fail', 401);

            $response = $next($request);
            return $response;
       }
    }

报错：

        HttpResponseException in Jump.php line 118

**Comment by liu21st** [comment]
result方法会抛出HttpResponseException异常，不建议这样用 直接用 response() 方法处理

**Comment by fangxingguang** [comment]
ok  thanks !
