### ISSUE TITLE
console 有没有文档可参考的?

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#116]
TP5 中的 console 模式有没有什么文档可以参考的?
或者 \think\console\helper 下面的助手类该怎么用?

**Comment by cbwfree** [comment]
这样玩的?
```
    protected function configure()
    {
        $this->setName('command');
        // 设置助手集
        $this->setHelperSet(new Set([
            new Process()
        ]));
    }
```

```
    protected function execute(Input $input, Output $output)
    {
        // 调用 Process 助手
        $process = $this->getHelperSet()->get('process');
        $output->writeln($process->getName());
    }
```

**Comment by cbwfree** [comment]
好像不设置助手集, 也能直接使用 `$this->getHelperSet()->get('process')`   - -||

**Comment by cbwfree** [comment]
另外在  `console`  中用 `process` 如何批量创建进程, 也就是异步操作

**Comment by cbwfree** [comment]
关于进程这块, 可以参考下 `https://github.com/hfcorriez/php-childprocess` 这个库. 异步fock进程

**Comment by momoca** [comment]
如果关于进程为什么不用http://php.net/manual/zh/intro.pthreads.php呢.这应该不是thinkphp首要任务.

**Comment by hainuo** [comment]
@momoca  使用pthreads 的话需要开启扩展    不知道现在这个扩展安全了吗？
