### ISSUE TITLE
thinkphp 5.1 复合条件查询好像没那么强了

### ISSUE THREAD

**Issue by adcbguo** [top-think/framework#1165]
$map = [['gt.type_id', 'eq', $typeId], ['g.chain_id', 'eq', $chainId]];
$where = "g.is_adapt = 1 OR (g.is_adapt = 0 and gcs.spec_id = {$carSpecId})";
return $this->alias('g')->join('lc_store_goods_type gt', 'gt.type_id = g.type_id')->join('lc_store_goods_car_spec gcs', 'gcs.goods_id = g.goods_id')->where($map)->where($where)->field($field)->order('g.create_time DESC')->select()->toArray();

thinkphp 5.1 这种复合条件好像只能写原生的了好像,不能where数组组装了

5.0以前好像还有 '_complex' '_logic' 这两个关键字来组装多层架的复合条件

**Comment by liu21st** [comment]
这种写法维护起来太麻烦了 还是建议使用查询表达式，都可以支持的

**Comment by adcbguo** [comment]
`gt`.`type_id` = '7'  AND `g`.`chain_id` = '1'  AND (  g.is_adapt = 1 OR (g.is_adapt = 0 and gcs.spec_id = 40) ) 
我的条件部分是这样的,不能组装啊 @liu21st 
https://www.kancloud.cn/manual/thinkphp5_1/354030
5.1文档where部分我都看了,没找到组装这种类型的
