### ISSUE TITLE
【bug】配置exception_handle后optimize:config 会产生错误的init.php

### ISSUE THREAD

**Issue by DongDavid** [top-think/framework#1169]
我的框架版本是5.0.15 (因为5.0.16要改模版命名规则所以不升级😂),php是7.1.7。

我在application/config.php 中配置了 exception_handle之后，
```
exception_handle'        => function (Exception $e) {
    if (request()->isAjax() && !request()->isPjax()) {
        // ajax请求则返回json格式的信息
        return json(['m' => '出错了', 's' => 0], 200);
    }
},
```
执行php think optimize:config
会生成一个错误的配置缓存文件，这个文件中的exception_handle会变成
```
'exception_handle' => 
	Closure::__set_state(array(
)),	
```
然后就整个应用无法执行了，出错图如下
![image](https://user-images.githubusercontent.com/18623095/38319234-e7cfb314-3863-11e8-8cbc-26d82e75bea3.png)
这个是我操作上的失误吗？

**Comment by DongDavid** [comment]
那只能是我生成缓存后，手动去吧init.php文件中错误的那一段改成对的了。。。。

**Comment by DongDavid** [comment]
@liu21st   对了，还有一个问题。
在thinkphp目录下面的.gitignore 文件的内容是不是有问题啊？ 里面还有/vendor这些

![image](https://user-images.githubusercontent.com/18623095/38417787-49999236-39cc-11e8-8b01-c30b24c2dd7b.png)

**Comment by liu21st** [comment]
vendor本来就不需要提交到版本库的

**Comment by DongDavid** [comment]
我说的是thinkphp目录下的gitignore.不是根目录下的gitignore哦。。。。
虽然这个并没有什么影响。。。。
