### ISSUE TITLE
内置验规则number更新后的疑问

### ISSUE THREAD

**Issue by weeisc** [top-think/framework#1177]
如图：之前的判断函数改成了ctype_digit 这样需要传入的就必须是个字符型或者大于255的数字了。
 想问下为什么改掉？
@liu21st
![](http://ooqv5ghsp.bkt.clouddn.com/18-4-10/86436372.jpg)

**Comment by liu21st** [comment]
我刚改进了下 因为这个函数最接近验证number的需求 需要小数点和负数的话 可以用float验证规则
