### ISSUE TITLE
关于Redis缓存类的疑问

### ISSUE THREAD

**Issue by onesy** [top-think/framework#1178]
尊敬的Thinkphp团队：
希望咨询个问题关于Redis缓存类的。版本5.0
thinkphp/library/think/cache/driver/Redis.php类中将Redis作为缓存实现了一些set get等方法。这里没有提供魔术方法以供更丰富的redis的方法使用。
于是我就在我本地的项目中的Redis添加了如下的代码，虽然我感觉打开方式不太对。
`public function __call($name, $arguments)
    {
        if (method_exists($this->handler, $name)) {
            return call_user_func_array([$this->handler,$name], $arguments);
        } else {
            throw new \RuntimeException("method {$name} not fund on handler");
        }
    }`
这样似乎可以实现更丰富的功能，但是总感觉哪里不太对。毕竟这里是一个缓存类而不是用来做NOSQL使用的类。希望得到指点正确的NOSQL存储应该使用什么方式？感谢。

**Comment by adcbguo** [comment]
我自己封装了一个Redis帮助类实现,还可以加个锁机制
`<?php
/**
 * Redis实例
 * User: 郭冠常
 * Date: 2018/03/01
 * Time: 17:50
 */
namespace app\common\help\base;
class Redis extends \Redis
{
    /**
     * @var object 对象实例
     */
    protected static $redis;

    /**
     * 连接配置
     * @var array $options
     */
    protected static $options = [];

    /**
     * 实例化连接Redis
     * @param array $options
     * @return static
     * @access public
     */
    public static function instance($options = [])
    {
        if (!is_object(self::$redis)) {
            if (!extension_loaded('redis')) {
                throw new \BadFunctionCallException('not support: redis');
            }
            self::$options = config('redis.');
            if (!empty($options)) {
                self::$options = array_merge(self::$options, $options);
            }
            $func = self::$options['persistent'] ? 'pconnect' : 'connect';
            self::$redis = new static();

            self::$redis->$func(self::$options['host'], self::$options['port'], self::$options['timeout']);

            if ('' != self::$options['password']) {
                self::$redis->auth(self::$options['password']);
            }

            if (0 != self::$options['select']) {
                self::$redis->select(self::$options['select']);
            }
        }
        return self::$redis;
    }

    /**
     * 加锁防止同步操作
     * @param $lock
     * @param int $lockTime
     * @return bool
     */
    public function getRedisLock($lock, $lockTime = 5000)
    {
        $currTime = intval(microtime(true) * 1000);
        $time = $currTime + $lockTime;
        //首先看看是否能加锁
        $res = self::$redis->setnx("{$lock}_lock", $time);
        if (!$res) {
            //不能加锁看看上一个加锁的时间
            $oldLockTime = self::$redis->get("{$lock}_lock");
            if ($oldLockTime < $currTime) {
                //如果上一个加锁时间小于当前时间,那么重新设置时间
                $res = self::$redis->getSet("{$lock}_lock", $time);
                //如果老的时间等于前面获取的时间那么获取锁
                if ($res == $oldLockTime) return true;
                unset($oldLockTime, $currTime);
            }
            usleep(10000);
            return $this->getRedisLock($lock);
        } else {
            return true;
        }
    }

    /**
     * 释放锁
     * @param $lock
     * @return int
     */
    public function freeRedisLock($lock)
    {
        return self::$redis->del("{$lock}_lock");
    }
}`

**Comment by adcbguo** [comment]
增加好配置直接这样使用
```
Redis::instance()->get();
Redis::instance()->set();

**Comment by onesy** [comment]
redis不是已经存在了一个乐观锁了嘛？这种应用层面上的悲观锁如果遇到“不安分分子”真的会有点头疼呢

**Comment by adcbguo** [comment]
redis 乐观锁是基于事务
可是如果没有开启事务呢?
总觉得redis好难搞懂,开启事务竟然不能读数据

**Comment by onesy** [comment]
redis的multi是基于pipeline实现的，也就是说，即使你的命令在不断的由程序写入，只要不exec，命令就根本没有达到服务器，也并没有执行。既然程序没有到达服务器别说读取，写入也是不可以的。

**Comment by adcbguo** [comment]
那如果开启事务,业务必须涉及到要读数据,怎么办呢?

**Comment by adcbguo** [comment]
我有一个大胆的想法,在php-redis扩展的基础了在封装一层PHP扩展
实现事务和事务内的读数据,就像Redis 的 lua脚本一样

**Comment by heikezy** [comment]
redis上跑太复杂的业务逻辑 还需要读取很多信息 不太合理吧。毕竟是个nosql 做点缓存 和 简单数据结构存储 比较适合。

**Comment by liu21st** [comment]
先调用handler方法 然后就可以调用原生的方法
