### ISSUE TITLE
这行不是该判断绑定的模块是否为默认模块吗？如果直接判断其存在值的话，那么二级域名时判断就根本不会执行到第二下个判断

### ISSUE THREAD

**Issue by lizhong43403** [top-think/framework#1193]
https://github.com/top-think/framework/blob/ee0c73937f5f30adef82f085e9661deb54a81fa8/library/think/App.php#L322

**Comment by lizhong43403** [comment]
这个问题在之前的版本中也有出现

**Comment by liu21st** [comment]
模块绑定是在入口文件指定的 优先级比域名的模块绑定要高，域名绑定是在路由定义里面的
