### ISSUE TITLE
希望能在改进一下Validate这个类

### ISSUE THREAD

**Issue by lxsea20150901** [top-think/framework#1197]
1.大部分表都是插入时字段必须验证，更新时字段存在就验证，希望这个能改进一下
2.模型使用验证器的时候可否可以直接Loader::model('MallCategory')->validate('.update')->allowField(true)->save($data);就可以在直接使用update场景

**Comment by liu21st** [comment]
尽量不要在模型中进行数据验证 5.1已经不支持了

**Comment by heikezy** [comment]
这不就是scene的用处吗。去文档看验证场景怎么定义咯
