### ISSUE TITLE
远程连接数据库Db::connect('remote_config')  ,造成远程数据库的connection数不断增加

### ISSUE THREAD

**Issue by stone512** [top-think/framework#1199]
问题是这样子的:
我想弄一个 全局的 远程数据库链接 ,**同时可以使用 tp5中 如 table ,insert等Query 类中的方法,**
但是我每次调用 Db::connect('remote_config') , 造成远程数据库mysql的连接数不断增加, 最后远程数据库禁止我的链接.....

我尝试过这样子写 , 但是每次 方法调用后,都会保留上一次的查询条件, 我不懂得怎么释放这个查询条件
只保留connection 对象

![image](https://user-images.githubusercontent.com/936938/39113818-6e6309e4-470f-11e8-9b27-318df56e04ce.png)

数据库的链接数
![image](https://user-images.githubusercontent.com/936938/39113907-b0a988a0-470f-11e8-8f05-49924258cae3.png)

**Comment by liu21st** [comment]
真搞不懂你为啥要这样处理，每次全新的查询就行了 默认是保留之前的查询条件的

**Comment by stone512** [comment]
@liu21st   默认的全新查询 , 是不是 $DB_remote->newQuery(); 这个方法??

**Comment by liu21st** [comment]
每次静态方法调用的查询都是全新查询 不支持设置不保存

**Comment by stone512** [comment]
@liu21st   我可能是没描述清楚 ,  close 吧~~ 谢谢了
