### ISSUE TITLE
where函数的一个BUG

### ISSUE THREAD

**Issue by jin123456bat** [top-think/framework#1202]
源代码如下：
![image](https://user-images.githubusercontent.com/2076638/39244690-0564fa4a-48c4-11e8-9a59-630c186a9ccc.png)

生成的SQL:
SELECT `id`,`username`,`realname`,`email`,`mobile`,`createtime`,`isdelete`,`islock`,`issupper` FROM `admin` WHERE `isdelete` = 0 AND `username` LIKE 'zzz' LIMIT 0,15

把第一个where去掉
![image](https://user-images.githubusercontent.com/2076638/39244763-3e0164a6-48c4-11e8-893a-5d0ac0031505.png)

生成的SQL变成这样了:
SELECT * FROM `admin` LIMIT 0,15

理论上keywords like '%zzz%' 和select的字段应该在，实际上不在了

PHP版本:7.0.23
APACHE:2.4.27
windows

**Comment by jin123456bat** [comment]
如果将红框内容改成
$model = Db::name('admin');
又导致软删除的条件没有了

**Comment by liu21st** [comment]
莫名其妙的写法 你的where条件是在查询之后附加的  然后后续又没有新的查询 你的条件怎么生效？
