### ISSUE TITLE
用git推送代码简直坑死？public/static 目录中文件传不上去！长点心吧啊

### ISSUE THREAD

**Issue by meiyoufengzhengdexian** [top-think/framework#1207]

**Comment by kinosang** [comment]
如需 commit public/static 目录中的文件，请手动 git add public/static/<文件名> 或删除 public/static/.gitignore

使用 git 请多加学习

**Comment by heikezy** [comment]
查阅git基础内容gitignore
🤔不熟悉git那还是不要用得好

**Comment by meiyoufengzhengdexian** [comment]
static 目录不就是放css的吗， 框架为什么自己有忽略配置？ 这个不合理吧？

**Comment by kinosang** [comment]
@meiyoufengzhengdexian 因为框架自身需要保持这个目录为空

**Comment by meiyoufengzhengdexian** [comment]
@kinosang 我不理解 框架就是来用的， 初始化的时候可以为空， 但是我们实际拉取的时候应该是可以传的， 这样也避免这种问题啊。 我这会是知道了， 肯定有不知道的。 

我建议， 为了框架开箱即用的原则 这里应该吧 static 下的 ignore 删掉、

**Comment by meiyoufengzhengdexian** [comment]
@kinosang  对啊， runtime 里的东西是忽略了， 但是因为不是php创建的所以没有写权限， 也建议放到根目录的 .ignore 里 直接不上传 runtime 让程序创建， 这样就有权限了

**Comment by kinosang** [comment]
@meiyoufengzhengdexian 权限问题还望自行解决，脚手架需要保持目录结构完整。

**Comment by meiyoufengzhengdexian** [comment]
@kinosang 我这也是同事给我的代码， 但我知道他肯定不会动 ignore 我负责部署， 用的是 git 的钩子
自动部署到www目录的那种， 我也是找了半天问题.. 有点上火。。。。

**Comment by meiyoufengzhengdexian** [comment]
权限问题， 只要把 runtime 加到根目录里的 ignore 里 不上传就好了， 让程序自动生成

**Comment by meiyoufengzhengdexian** [comment]
@kinosang 因为我也不可能每个目录都看下ignore .... 说实话， 心理挺不要意思的， 一开始是挺火大。。。。， 用着你们的免费框架。吐槽这么多。。。。。

**Comment by kinosang** [comment]
都会用钩子了不会自己设定权限？

文件和目录权限就一条命令的事，chown 一下就那么难？

回头其他人说为什么脚手架目录结构不完整我们是不是还得改回来？

我直说了，你提的这些问题全是你们自己使用 git 不当造成的，别说 ThinkPHP，你用其他框架照样遇到这些问题。

打铁还需自身硬，还望多多学习，提高自己的知识水平。

**Comment by meiyoufengzhengdexian** [comment]
@kinosang  
哥， 你runtime是自动生成的。 怎么会不完整

**Comment by kinosang** [comment]
自动生成是自动生成，[脚手架](https://github.com/top-think/think)是脚手架。

即使能自动生成，脚手架也要保留这些内容。

不然，我们为啥还要在脚手架里面提供一个 public/static？

直接不提供脚手架了多好，用起来多随心所欲？

到时候是不是又要问为啥不提供脚手架或者样例工程？

**Comment by meiyoufengzhengdexian** [comment]
- - 给我的版本应该是在官网下的。 他应该不是git拉取的。 

我也不知道怎么解决了。 我只是提下建议... 你们采纳不采纳 怎么权衡就看你们了。。

**Comment by liu21st** [comment]
@meiyoufengzhengdexian 说多了就没意思了 你反馈问题或者建议 官方自然会去评估是否合理以及应该如果处理和改进 ，既然自己都结帖了，就没必要再说这么多~

**Comment by meiyoufengzhengdexian** [comment]
手贱啊。回复。。。 看你打那么多字 不好意思不回

**Comment by kinosang** [comment]
抱歉，我也有些太激动了。

因为此问题已经偏离主题，且过于激动，已经将此 issue lock。

如果坚持此主题之提议，烦劳新开 issue。

十分抱歉
