### ISSUE TITLE
用git推送代码简直坑死？public/static 目录中文件传不上去！

### ISSUE THREAD

**Issue by meiyoufengzhengdexian** [top-think/framework#1208]
用git推送代码简直坑死？public/static 目录中文件传不上去！
runtime 没有加到.gitignore 里 官网的nginx配置根本走不通，何必弄得不三不四 不五不六

**Comment by kinosang** [comment]
runtime/.gitignore 文件同 public/static/.gitignore，已经将 runtime 下全部文件忽略

还望对自己的设置或配置多加检查

**Comment by meiyoufengzhengdexian** [comment]
我不知道你传没传过static目录下得css，我不改框架的git配置是传不上去的！除非把static里的.gitignore删掉
