### ISSUE TITLE
5.1.11版本（其实5.1.x都一样）空数据写入返回值错误

### ISSUE THREAD

**Issue by huye** [top-think/framework#1217]
在 library/think/db/Connection.php 文件的第 969 行：
` $sql = $this->builder->insert($query, $replace);`
当没传入数据（如果全部字段写错结果也一样）时会导致这里返回 0，没有判断就直接交给 execute 方法执行了，然后最后返回的数值成了这个表的字段行数（应该是读取字段信息后留下来的），导致 save 方法的最终返回结果为字段行数，为真，但其实是写入失败了的，逻辑不一致了。调用代码：
`$status = model('xxx')->save()`

**Comment by huye** [comment]
另外，作为国内的框架程序，请也处理下国内仓库的问题吧，让人觉得这框架都没人维护了的感觉，一共就两个，半年前的 issue 都未处理：
https://gitee.com/liu21st/framework/issues

**Comment by liu21st** [comment]
感谢反馈，已经修正
