### ISSUE TITLE
5.1 新版把 App 构造函数中的路径初始化移到 initialize 有何意义？

### ISSUE THREAD

**Issue by huye** [top-think/framework#1220]
以前自己写的 app 继承 App 后，只用覆盖构造函数就可以重定义这几个路径了，现在非得覆盖 initialize 或者 init 才行，几行代码只是移动了下，对框架来说又没有意义，但继承起来就一点不方便了。。。

**Comment by huye** [comment]
说实话，thinkphp5 这个改法真的没法子用下去，5.1.x 都不能做到对 5.1.0 的兼容，你说都已经是小版本更新了，增加功能可以，但是能不能不要改掉旧的定义啊，现在搞得开发的程序，如果用的是 5.1.0，你就不能升级到 5.1.8 什么之类的，还怎么正常使用？
现在 composer.json 里的 require 都只能写成 "topthink/framework": "5.1.11" 这样的绝对版本号，要不然更新一下包，直接整个项目就不能用了。。。

**Comment by liu21st** [comment]
没有必要自己扩展App类  你要改的无非就是应用目录 其它目录官方是不建议修改的

**Comment by liu21st** [comment]
就算你要改其他路径 直接继承后改initialize方法就行了 又不是不行

**Comment by huye** [comment]
但是要知道，在方法尾定义的内容方法继承修改的，但现在是被移到了方法的头上，就要把整个方法重写了

**Comment by liu21st** [comment]
我调整了下
