### ISSUE TITLE
5.1.12 url 生成有点问题

### ISSUE THREAD

**Issue by hawking007** [top-think/framework#1223]
当域名只绑定了模块时（无其他任何路由，域名只绑定了模块），生成地址错误
如 ：
route.php 文件

Route::domain('www.test.com', 'index');

控制器（模板）文件

url('index/index/login') =》 /index/index/login.html

期望 生成 这样  /index/login.html

注 5.1.8 版本是好的，我这一composer update 就挂掉了，希望能修复。

               if (!$this->bindCheck) {
                  $bind = $this->app['route']->getBind($domain && is_string($domain) ? $domain : null);
                  if ($bind && 0 === strpos($url, $bind)) {
                      $url = substr($url, strlen($bind) + 1);
                      $matchAlias = true;  // 新增代码
                  } else {
                    $binds = $this->app['route']->getBind(true);

                    foreach ($binds as $key => $val) {
                        if (is_string($val) && 0 === strpos($url, $val) && substr_count($val, '/') > 1) {
                            $url    = substr($url, strlen($val) + 1);
                            $domain = $key;
                            $matchAlias = true; // 新增代码
                            break;
                        }
                    }
                }
            }

**Comment by liu21st** [comment]
你应该安装的不是最新的 已经修正过的

**Comment by hawking007** [comment]
嗯，是的，5.1 分支改了，5.1.12 的tag是旧的 ，感谢
