### ISSUE TITLE
Use of undefined constant SYS_PATH - assumed 'SYS_PATH'

### ISSUE THREAD

**Issue by gmars** [top-think/framework#1229]
TP5.1是不是没有加载bootstrap.php这样这样的话constant.php也是没有被加载的使用常量会报错？

![20180511180109_](https://user-images.githubusercontent.com/9643824/39919392-0f99b2f6-5546-11e8-959f-fcd5fd54906d.png)

**Comment by momoca** [comment]
建议你看看升级手册
