### ISSUE TITLE
Db::table 没法使用子查询

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#125]
```
$subQuery = Db::table('think_user')
    ->field('id,name')
    ->where('id','>',10)
    ->buildSql();
Db::table($subQuery.' a')
    ->where('a.name','like','thinkphp')
    ->order('id','desc')
    ->select();
```

按手册上的方式写, 会出现异常 `SQLSTATE[42S02]: Base table or view not found: 1146 Table`

**Comment by liu21st** [comment]
我测试OK啊

**Comment by cbwfree** [comment]
我在 console 模式下使用, 会自动加上数据库名称
输出结果为 SELECT * FROM  `db_name`. (SELECT * FROM `thinkphp`)

**Comment by Xuchengen** [comment]
这个问题关注一下吧，我也遇到这样的问题。
@liu21st 我用的最新版本5.0.2，子查询采用的是数组方式。

**Comment by liu21st** [comment]
@Xuchengen 我用最新版本测试 数组方式的子查询的没问题的 字符串的不行

**Comment by Xuchengen** [comment]
待会儿试一下5.0.3版本，看看有没有修复。
[TP5使用buildSql构建查询语句使用问题](http://www.thinkphp.cn/topic/43495.html)

**Comment by Xuchengen** [comment]
@liu21st 昨天晚上测试5.0.3问题依旧，要不你贴一下你的代码。
