### ISSUE TITLE
thinkphp5.1 Model 问题

### ISSUE THREAD

**Issue by WuYunlong** [top-think/framework#1264]
现有model类Kv代码如下

``` php

class Kv extends Model
{
     public function setKv($key, $value, $type)
     {
          $info = self::getByKey($key);
          if(!$info){
              self::create([
                    'key'=>$key,
                    'value'=> $value,
                    'type' => $type
              ])
          }else{
               $info->value = $value;
               $info->type = $type;
               $info->save();
          }
     }
     
     public function getValueAttr($value, $data)
     {
            switch($data['type']){
                case 0:
                     return $value;
                     break;
                case 1:
                     return json_decode($value, true);
                     break;
            }
     }

     public function setValueAttr($value, $data)
     {
            switch($data['type']){
                case 0:
                     return $value;
                     break;
                case 1:
                     return json_encode($value);
                     break;
            }
     }

} 

```

现在存在这样的问题。
1. 数据字段中不能使用type 具体情况如下
数据库信息  
id: 1, 
key:'user.name', 
type:0, 
value:'along'

``` php
    $info = Kv::getByKey('user.name');
    echo $info->type;
    // 输出内容为 [];
```
> 解决方法 修改type字段为modl 问题解决

2. 调用 setValueAttr 时机问题
``` php
$info = Kv::get(1);
$info->value = ['user':'wuyunlong', 'age':'18'];
$info->modl = 1;
$info->save();
```
存在问题
按照上面的代码编写 在数据库中的value并不会按照新赋值的model进行json_encode 出现问题是调用setValueAttr时机问题  

> 解决方法
``` php
$info = Kv::get(1);
$info->modl = 1;
$info->value = ['user':'wuyunlong', 'age':'18'];
$info->save();
```

> 将modl赋值 和 value 赋值顺序修改即可解决。

请确认此处是否存在问题，应该在调用save之前再进行setValueAttr 不然这个模型在使用过程中还要注意重新赋值的顺序。

**Comment by liu21st** [comment]
1、在模型内部不能直接使用数据属性操作 而应该用getAttr或者getData
2、这个是修改器的设计机制 setAttr方法是在赋值的时候就执行的

**Comment by WuYunlong** [comment]
@liu21st 
关于第二个问题是否有改进的必要，为何设计是在赋值的时候就执行呢，这样执行的好处或者是必要性在哪里。

**Comment by yunwuxin** [comment]
@WuYunlong 因为赋值了后不一定执行save  可能是被其他地方用

**Comment by yunwuxin** [comment]
@WuYunlong 既然你的某个字段的修改器依赖其他的字段   那就应该把这两个字段的设置  封装成一个方法去设置

**Comment by WuYunlong** [comment]
@yunwuxin 
模型操作重新赋值 在其它地方使用的情况比较少吧 不知道什么场景会有这样的操作。
如果是这样的话 不应该 $data = $obj->value;    使用$data 吗  不应该赋值给模型对象吧。

**Comment by WuYunlong** [comment]
@yunwuxin  
封装为单独的方法不合适  在进行团队开发的时候 我们要修改数据 肯定是按照tp官网的规范进行，如果自己再去封装的话 团队的学习成本太高，你封装了就要告诉团队所有的人在修改这个数据的时候要调用我的方法。这样就得不偿失了。

**Comment by yunwuxin** [comment]
@WuYunlong 赋值后 整个对象传递到其他方法里去
tp官网什么时候规范 赋值必须是  $info->modl = 1; 这样的方式了。。
你可以直接定义个setValue($type,$modl); 这样的方法    这个怎么不规范了
要么就别有这种修改器   在外面根据type处理好了写进去
不然别人还不是不知道你这里有个这个修改器  还不是要你去告诉   那跟告诉别人有个setValue方法有什么区别
