### ISSUE TITLE
ThinkPHP5.1 Post 变量问题

### ISSUE THREAD

**Issue by WuYunlong** [top-think/framework#1277]
在使用thinkphp5.1 过程中出现如下问题

php代码如下

``` php

namespace app\index\controller;
use think\Controller

class Index extends Controller
{
  public function index()
  {
      return dump($_POST);
  }
}

```

出现问题如下：
当像这个控制器方法 Post 提交数据时。数据为数组格式。
数据值为
```
    name[]: 1
    name[]: 2
    name[]: 3
```
程序报错 `variable type error：array`
数据值为
```
    names[]: 1
    names[]: 2
    names[]: 3
```

的时候，可以正常打印出post过来的数据  `['names'=>[1,2,3]]`
请确认问题是否存在谢谢...

**Comment by JerryChaox** [comment]
控制器return是响应数据，要用tp的Response对象或者字符串响应。这个错误是响应类型错误，你可以用json($_POST)将数组以json响应

**Comment by WuYunlong** [comment]
@JerryChaox 不是响应类型的问题  是我只要是post数据名称为 name[] 就报错。

**Comment by liu21st** [comment]
框架和name变量没有任何关系，通过异常页面查看具体的错误原因和定位，然后多跟踪调试
