### ISSUE TITLE
5.1.14依赖注入request后出现bug，以及append追加关联模型bug

### ISSUE THREAD

**Issue by weiyechaocat** [top-think/framework#1285]
public function test(Request $request,$id=''){
dump($id);
}
url/test/id/2
此时是获取不到url里的id值的，如把$id=''放Request前是可以的。
User::get(1)->append(['profile'=>['email','phone']]);
该操作会把profile的所有字段都抛出。

**Comment by liu21st** [comment]
第一个问题已经修正过
至于第二个问题 只要你追加了profile就会把所有字段数据取出，这种方法是追加profile模型的非数据表字段数据

**Comment by weiyechaocat** [comment]
我已经composer update最新版了，第一个问题仍旧存在

**Comment by liu21st** [comment]
5.1.15版本
