### ISSUE TITLE
闭包中用whereor

### ISSUE THREAD

**Issue by jin123456bat** [top-think/framework#1287]
代码如下：
![image](https://user-images.githubusercontent.com/2076638/40820733-d6986c86-6594-11e8-8bcd-262b38fe3226.png)
生成的SQL居然是这样子的，我想用or
SELECT * FROM `coupon` WHERE ( deletetime is null ) AND `company_id` = 1 AND ( `hotel_id` = 11 AND ( hotel_id is null ) )

期望生成的SQL应该是这样子:
SELECT * FROM `coupon` WHERE ( deletetime is null ) AND `company_id` = 1 AND ( `hotel_id` = 11 OR ( hotel_id is null ) )

**Comment by jin123456bat** [comment]
代码中注释的部分，报错提示查询表达式错误:IS,如何通过表达式判断字段为null？

**Comment by liu21st** [comment]
whereOr('hotel_id',null);
