### ISSUE TITLE
软删除destroy有问题

### ISSUE THREAD

**Issue by fanite** [top-think/framework#1290]
当destroy的参数是一组数组的时候：
```
$params = $this->request->param();
$result = UsersModel::destroy($params['ids']);
```
生成这样的SQL：
`SELECT * FROM `auto_users` WHERE = '10076' AND = '10077' AND = '10079' AND = '10081' AND = '10082' AND = '10085' AND = '10086' AND = '10087' AND = '10088' AND = '10089'`
好像不无法获取主键

**Comment by liu21st** [comment]
调试下你的$params['ids'] 值是什么，我测试正常情况下没有问题，只要不是关联数组

**Comment by fanite** [comment]
确实是因为这个原因,`array_values()`重建索引后变为正常，虽然`dump($params['ids'])`和`array_values($params['ids'])`打印的结果是一样的
`D:\ProgramFiles\wamp64\www\test\thinkphp\library\think\Debug.php:226:
array (size=10)
  0 => int 10686
  1 => int 10687
  2 => int 10689
  3 => int 10692
  4 => int 10693
  5 => int 10694
  6 => int 10695
  7 => int 10696
  8 => int 10699
  9 => int 10703
D:\ProgramFiles\wamp64\www\test\thinkphp\library\think\Debug.php:226:
array (size=10)
  0 => int 10686
  1 => int 10687
  2 => int 10689
  3 => int 10692
  4 => int 10693
  5 => int 10694
  6 => int 10695
  7 => int 10696
  8 => int 10699
  9 => int 10703`
