### ISSUE TITLE
路由定义时使用多文件时require嵌套无效

### ISSUE THREAD

**Issue by heikezy** [top-think/framework#1293]
route/route.php
```php
Route::group('api', function(){
    require_once __DIR__. '/api.php';
});
```
route/api.php
```php
Route::any('login', function(){
    return 'login';
}
```

经测试，类似于Laravel一样，路由在分组路由内require文件而产生的定义是不生效的。
而以下写法是正常的：

route/route.php
```php
require_once __DIR__. '/api.php';
```
route/api.php
```php
Route::group('api', function(){
    Route::any('login', function(){
        return 'login';
    }
});
```

希望能对第一种写法进行支持~~~谢谢！

**Comment by liu21st** [comment]
route目录下面的文件是都会加载的，因为延迟解析的特性 所以当你的路由分组匹配后再加载是不会再次加载了的，其实你可以换个思路

**Comment by heikezy** [comment]
@liu21st Thx a lot，大概理解原因了。请教有什么比较好的方式组织嵌套分组路由吗？

在文档上看来5.1是弱化数组形式定义路由了，个人挺支持的，有利于分成清晰的多个文件。

但对于这种分成多个文件后嵌套分组路由，我能想到类似laravel的替代方法就只有include的时候被include的文件返回闭包，而不是去立即执行`Route::group()`了

route/route.php

```php
$apiGroup = include __DIR__. '/api.php';
Route::group('api', $apiGroup);
```

route/api.php

```php

return function(){
    Route::any('login', function(){
        return 'login';
    }
};
```

**Comment by liu21st** [comment]
你这样会导致混乱，因为TP是route和api两个文件都会加载的，除非是在其它的目录或者子目录
