### ISSUE TITLE
中间件config配置失效

### ISSUE THREAD

**Issue by fangxingguang** [top-think/framework#1294]
升级到V5.1.15后，config下middleware.php中定义的别名失效，错误去默认的app\http\middleware下加载了
@liu21st

**Comment by fangxingguang** [comment]
路由中间件别名注册   应该属于应用吧   不处理的话   在路由中 中间件还是默认去http下加载 
@liu21st

**Comment by liu21st** [comment]
应用中间件配置本来就会加载并生效的
