### ISSUE TITLE
Undefined variable: query

### ISSUE THREAD

**Issue by yazi-xiaofan** [top-think/framework#1297]
https://github.com/top-think/framework/blob/e20f6e8cadbbc6e246a0c121c89bfd278f30c76b/library/think/db/Builder.php#L805

**Comment by yazi-xiaofan** [comment]
5.0.20

**Comment by yazi-xiaofan** [comment]
Composer更新的

**Comment by liu21st** [comment]
哦 我看了下 这个是GIT版本修正的 Composer还没发布版本，等下一个版本更新吧
