### ISSUE TITLE
make命令创建model时不能区分父级路径的大小写

### ISSUE THREAD

**Issue by maoxuner** [top-think/framework#1298]
使用环境`deepin`
项目路径`/home/nono/Projects/wwwroot/samples/webpages`，使用命令`php think make:model Test`创建model会出现路径错误
```
[think\exception\ErrorException]                                            
file_put_contents(/home/nono/Projects/wwwroot/samples/webpages/application/common/model/MyNosql.php): failed to open stream: No such file or directory
```
此时，命令工具会创建小写名称的路径`/home/nono/projects/wwwroot/samples/webpages/application/common/model`，`Projects`变成`projects`，linux系统下是区分大小写路径的。
然而重新创建model，会报以下错误
```
[think\exception\ErrorException]  
mkdir(): File exists
```
但是model文件依然没有被创建。
即使手动创建`/home/nono/Projects/wwwroot/samples/webpages/application/common/model`目录，依然会报错。本质上就是不能区分大小写路径。

原来issue是在[think命令创建model时不能区分父级路径的大小写](https://github.com/top-think/think/issues/776)这里提的，但是被关闭了。后来研究发现，是框架本身的代码导致了这一问题。

`framework/library/think/console/command/Make.php`片段
```php
    protected function execute(Input $input, Output $output)
    {
        $name = trim($input->getArgument('name'));
        $classname = $this->getClassName($name);
        $pathname = $this->getPathName($classname);
        if (is_file($pathname)) {
            $output->writeln('<error>' . $this->type . ' already exists!</error>');
            return false;
        }
        if (!is_dir(dirname($pathname))) {
            mkdir(strtolower(dirname($pathname)), 0755, true);
        }
        file_put_contents($pathname, $this->buildClass($classname));
        $output->writeln('<info>' . $this->type . ' created successfully.</info>');
    }
```
第48~50行（第49行代码）
```
        if (!is_dir(dirname($pathname))) {
            mkdir(strtolower(dirname($pathname)), 0755, true);
        }
```
对路径整体取小写，因此在父级路径出现大写路径时，且在linux这样严格区分大小写的系统上就会出现路径不正确的问题。

诚然，tp5规定项目路径统一采用小写的方式。即使这样，也不能限制父级路径中是否存在大写的路径名称。因此应用根目录及父级路径采用原样，对于应用内的路径进行取小写处理才是合理的处理方式。

**Comment by liu21st** [comment]
改进了下

**Comment by maoxuner** [comment]
处理效率好高啊。现在是直接忽略了大小写，随之而来会出现另一个问题。

指定模块创建model的命令，如
```shell
php think make:model Index/User
```
会在`application`目录下创建一个大写的`Index`目录，并在这下面创建`model`目录以及对应的模型文件`User.php`。而正常的`index`目录下不会有文件生成。

因此在执行make相关命令时，要注意**参数中模块名使用小写，控制器、模型等类名要严格区分大小写**。如
```shell
php think make:model index/User
```
这样才能正确的在`application/index/model`下生成`User.php`文件
