### ISSUE TITLE
模型绑定多个bind的只能识别最后一个

### ISSUE THREAD

**Issue by xushuhui** [top-think/framework#1304]
一对一关联中，一个模型belongsTo多个其他模型，都设置bind，同时调用的时候只能成功最后一个。
类似这种
`   

public function room()
{
         return $this->belongsTo('Preorder')->field(['id','sum'])->bind([
            'sum' => 'sum',
        ]);
}

` 

` 

    public function room()
    {
        return $this->belongsTo('Room','room_id')->field(['id','name','room_type_name'])->bind([
            'room_name'	=> 'name',
            'room_type_name'	=> 'room_type_name',
        ]);
    }

`

**Comment by liu21st** [comment]
为啥你两个关联的方法是同名？

**Comment by liu21st** [comment]
我测试并没发现你说的问题的
