### ISSUE TITLE
为何将钩子 view_filter 取消了？

### ISSUE THREAD

**Issue by oyvfhp** [top-think/framework#1311]
因为钩子 view_filter 的取消，导致我们要全局进行替换时，只能使用 视图类的filter() 方法，从而必须将 Controller 重新封闭成另外一个方法来让其全局继承，增加了麻烦。

有钩子 view_filter时，我只要配置一下配置文件即可。

还有，使用$this->filter()后，做的相关替换什么的，交没有将替换后的内容写入模板缓存，如果这里做了大量替换等操作，就不太妥了。

**Comment by oyvfhp** [comment]
如何使用中间件来做模板里面的替换？ 我看源代码中，模板替换过程中，并没有与中件间相关代码。

**Comment by oyvfhp** [comment]
@liu21st 我主要是想做到一个点，在模板编译后，我想对模板有自定义的替换动作，同时能够将我的替换的结果一起写入模板缓存文件中。

**Comment by liu21st** [comment]
模板本来就有自己的替换规则，你仍然可以用。
我说的中间件不是指模板替换的 是类似于view类的filter一样 但是基于中间件方式实现，如果你不想写在控制器的话

**Comment by jin123456bat** [comment]
@liu21st 我也碰到类似的问题，希望能有demo之类的写道kancloud.cn的开发手册中

**Comment by oyvfhp** [comment]
@liu21st   如果我想在模板编译之前对模板进行统一的替换操作，有什么方案吗？
我看了一下，使用filter()是在模板编译之后再进行替换的，而且没有在写入模板缓存。

**Comment by liu21st** [comment]
模板引擎有tpl_replace_string配置参数
