### ISSUE TITLE
单元测试,安装报错

### ISSUE THREAD

**Issue by ylsds** [top-think/framework#1312]
Problem 1
    - topthink/think-testing v2.0.1 requires topthink/think-installer ~1.0 -> satisfiable by topthink/think-installer[1.0.1, v1.0.0, v1.0.10, v1.0.11, v1.0.12, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9] but these conflict with your requirements or minimum-stability.
    - topthink/think-testing v2.0 requires topthink/think-installer ~1.0 -> satisfiable by topthink/think-installer[1.0.1, v1.0.0, v1.0.10, v1.0.11, v1.0.12, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9] but these conflict with your requirements or minimum-stability.
    - Installation request for topthink/think-testing ^2.0 -> satisfiable by topthink/think-testing[v2.0, v2.0.1].

**Comment by saybabi** [comment]
还要等老大有空才能修复好这个问题
