### ISSUE TITLE
验证器number只能做纯数字检测，无法做小数检测

### ISSUE THREAD

**Issue by jin123456bat** [top-think/framework#1313]
![image](https://user-images.githubusercontent.com/2076638/41446824-58e68f2a-7084-11e8-90af-ebf94829174b.png)
假如是小数就检测失败，或者请问一下对于金额这样的小数如何检测？

**Comment by liu21st** [comment]
金额使用float进行验证

**Comment by zanemmm** [comment]
[is_numeric](http://php.net/manual/zh/function.is-numeric.php) 函数了解一下:-D
