### ISSUE TITLE
高级群里@foam提交了一个错误

### ISSUE THREAD

**Issue by linjialiang** [top-think/framework#1321]
@流年 群主。thinkphp高级群成员@foam发现一个问题，下面是原话：
> 上边同学写了这么段代码：

![default](https://user-images.githubusercontent.com/8848263/41825797-c3f4eff8-7856-11e8-9d2a-de42667c7ece.png)

> response传入的是个一维数组，think\rule的这个方法直接合并过去就变成了二维数组，所以导致tags是一个二维数组。因此最后execTag的时候报错了（期望$class是字符串，实际上是一维数组）

![default](https://user-images.githubusercontent.com/8848263/41825802-d42bd152-7856-11e8-8b59-a54806652537.png)

![default](https://user-images.githubusercontent.com/8848263/41825807-d8395e22-7856-11e8-922a-bfb3da628d47.png)

![default](https://user-images.githubusercontent.com/8848263/41825809-dd6d2f5e-7856-11e8-990f-af9331a19546.png)

**Comment by liu21st** [comment]
已经修正
