### ISSUE TITLE
路由上的可选变量会导致单行注释失效

### ISSUE THREAD

**Issue by linjialiang** [top-think/framework#1324]
![default](https://user-images.githubusercontent.com/8848263/41885615-4e28c6d4-792b-11e8-82f5-e4d559acec09.gif)

**Comment by momoca** [comment]
这只是ide显示问题吧.执行不会有问题呀.

**Comment by linjialiang** [comment]
是这样的吗？好吧

**Comment by linjialiang** [comment]
@momoca  执行会报错的，你试试

**Comment by linjialiang** [comment]
好像是没问题，不过对很多编辑器的支持确实不好

**Comment by jin123456bat** [comment]
ide可能认为?>这个已经到达php文件的结尾了，

**Comment by linjialiang** [comment]
> @momoca @liu21st 不对哦，个别的路由单号注释会失效,如图：

![default](https://user-images.githubusercontent.com/8848263/41967709-c5f665e0-7a34-11e8-900a-399ef8794151.png)

![default](https://user-images.githubusercontent.com/8848263/41967740-e68e211c-7a34-11e8-869c-a846af5dcabc.png)

**Comment by momoca** [comment]
哪你就使用块注释呗. @linjialiang

**Comment by linjialiang** [comment]
@momoca 把 `<value?>` 标签换成 `{value?}` 就不会有这个问题。我觉得应该选择 `{}` 标签

**Comment by linjialiang** [comment]
> 当然这只是一个新手的认知，不一定是符合的规范的，应该说这仅仅是我在学习 `tp5.1` 过程中，提出一些疑惑和想法！

**Comment by momoca** [comment]
定义不同的. 
====
使用`{}`不妥吧.因为大括号本身是变量引用时的定界符.[参考PHP手册](http://php.net/manual/zh/language.variables.variable.php)
但在命令行参数中.`<>`代表必要的,`[]`代表可选的.感觉tp就是遵循这个的.
还有我真心建议你多看看[thinkphp路由](https://www.kancloud.cn/manual/thinkphp5_1/353960)的章节.
@linjialiang

**Comment by liu21st** [comment]
TP本来就支持另外一种写法 [:name]

**Comment by linjialiang** [comment]
![default](https://user-images.githubusercontent.com/8848263/42013986-865b97fe-7ad2-11e8-97bf-c146be24e83d.png)

**Comment by linjialiang** [comment]
@momoca 我就是从头看下来的，路由章节已经看完，当然还有很多不理解的，等看完第一遍完全手册后，会重点研究的

**Comment by momoca** [comment]
@linjialiang "杀鸡焉用牛刀" 你理解一下这句话.

给我讲一个《张三吃豆》的故事吧:
>张三原用勺子吃东西..挺好...
干什么都用勺子.
有一次和李四吃火锅.发现一种叫筷子的工具.很高级...吃火锅也比勺子方便多了.
后来张三就用筷子.便干什么都用筷子.
吃豆就算用勺子方便.张三也要用筷子.
"显的高级"对么?!对吧.(筷子吃豆只能一个一个夹.勺子可以一下吃到好多)
你说哪个方便呢?

**你要是看懂了.我很高兴.看不懂就是我表达的不清楚.**
- 每个工具的设计都是有它的意义的,
- 设计者应该尽可能的遵循 `通用性` `常识性` 的原则.
- 使用者应该了解他的使用方法和场景.
- 5w2h
