### ISSUE TITLE
自定义验证,extend方法没有返回值

### ISSUE THREAD

**Issue by jin123456bat** [top-think/framework#1326]
文档中extend支持链式写法
![image](https://user-images.githubusercontent.com/2076638/41950427-ae4377bc-79f8-11e8-978a-defdd261b0f6.png)
实际中没有返回值
![image](https://user-images.githubusercontent.com/2076638/41950357-5c8d4c54-79f8-11e8-9e31-9e9e2d5d9e97.png)

**Comment by liu21st** [comment]
静态方法一般不设返回值 文档我改进下
