### ISSUE TITLE
很奇怪的错误

### ISSUE THREAD

**Issue by jin123456bat** [top-think/framework#1329]
源代码
![image](https://user-images.githubusercontent.com/2076638/41954212-bc7550a8-7a0c-11e8-9db1-cf8276e241e1.png)

错误信息，提示缺少参数
![image](https://user-images.githubusercontent.com/2076638/41954197-abfe1480-7a0c-11e8-8683-56fc1eb0334b.png)

buildSql的结果可以在mysql中正常运行
`( SELECT `id`,`name`,`type`,`price`,`rate`,`room_type_id` FROM `room_special` WHERE  `company_id` = 1  AND `hotel_id` = 11  AND `room_type_id` IN (12)  AND ( starttime is null or starttime <= '2018-06-27 13:20:32' )  AND ( endtime is null or endtime >= '2018-06-27 13:20:32' )  AND ( group_id is null or group_id='0' )  AND ( deletetime is null ) ORDER BY `sort` ASC,`id` ASC )`

**Comment by liu21st** [comment]
参数绑定的变量不能使用同一个
