### ISSUE TITLE
接着 #1329 的问题

### ISSUE THREAD

**Issue by jin123456bat** [top-think/framework#1330]
使用bind方法也有同样的问题

![image](https://user-images.githubusercontent.com/2076638/41959110-a2cd7d3a-7a1e-11e8-8aa4-51161322f61b.png)

**Comment by jin123456bat** [comment]
https://github.com/top-think/framework/issues/1329

**Comment by liu21st** [comment]
你怎么还没明白呢 你参数绑定用了同一个参数now 这是PDO不允许的
