### ISSUE TITLE
配置文件自定义地址 runtime自定义地址，怎样修改

### ISSUE THREAD

**Issue by PuShaoWei** [top-think/framework#1333]
我看`\think\App`下这几个是写死的。也没有提供方式去做修改，之前看到是有个常量，请问新版是移除这个功能了嘛？其实是对我们很有用的一个功能呢，我能否继承`APP`重写这一块儿呢？

**Comment by liu21st** [comment]
runtime不需要自定义 一般自定义的是日志和缓存目录

**Comment by PuShaoWei** [comment]
框架在初始化的时候其实还没有读配置文件里的自定义日志和缓存目录，他会默认先去runtime
