### ISSUE TITLE
linux PHP7.2版本 注解路由无效 runtime/build_route.php  无法获取设置的注解路由

### ISSUE THREAD

**Issue by tekintian** [top-think/framework#1338]
同样的设置，windows下面正常，放到linux下面无效， linux 下的目录权限正常。 经过检查  /runtime/build_route.php 此文件没有获取到设置的注解路由, 删除此文件，运行网站能自动生成这个文件，文件内容只有：

<?php 
//根据 Annotation 自动生成的路由规则

无法获取到具体的注解路规则

Linux 环境：  Debian 9,  php7.2+tengine

PS: 将路由规则直接写入到 /route/route.php 文件，则访问正常，使用注解路由无效

**Comment by axgle** [comment]
注解路由,我个人不太喜欢这种风格,很容易出错的感觉
