### ISSUE TITLE
不允许启动新事务，因为有其他线程正在该会话中运行。

### ISSUE THREAD

**Issue by 2250526295** [top-think/framework#1339]
SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]不允许启动新事务，因为有其他线程正在该会话中运行。

非隐形事务模式。

使用try ... catch之后， 第二条语句后正常。
`
foreach
   select
   insert or update
end foreach  
`
只要select之后的就提示不允许启动新事务，think\db\Connection.php 1678行，使用$this->linkID->inTransaction()也是无效。
`
foreach
   select
  try
   insert or update
  catch
end foreach  
`

**Comment by hainuo** [comment]
建议 粘贴下伪代码
