### ISSUE TITLE
mac composer 安装 5.1.X安装不成功 提示:控制器不存在:app\index\controller\Index

### ISSUE THREAD

**Issue by wengtinggui** [top-think/framework#1341]
mac composer 安装 5.1.X安装不成功 提示:控制器不存在:app\index\controller\Index
Mac 版本 10.13.5
环境: nginx/1.11.4 php7.1.1
git 分两步安装就正常
 5.1.6-5.1.8均运行不起来
> composer 和git 分别下载,直接运行,未修改任何文件

![image](https://user-images.githubusercontent.com/17006272/42265936-8d80fd4c-7fa7-11e8-90c5-f27a21dca84d.png)

![image](https://user-images.githubusercontent.com/17006272/42265919-804a1bb8-7fa7-11e8-8cb5-071a12fa3f68.png)

不是权限问题,app\index\controller\Index下文件也存在
经过试验是vendor目录的问题.git安装的vendor目录为空 composer安装的vendor目录不为空.vendor目录不为空就报错.是否vendor目录下有变量和系统变量冲突.
Windows下无这问题.
删除vendor目录下文件就能正常访问
![image](https://user-images.githubusercontent.com/17006272/42266093-fdb02ad4-7fa7-11e8-8286-7be36ef58f9e.png)
![image](https://user-images.githubusercontent.com/17006272/42266212-4b41877a-7fa8-11e8-97df-a84385a1cdf4.png)

**Comment by leestar54** [comment]
我也发现这个问题，需要执行
`php think optimize:autoload`
否则无法自动加载的样子
