### ISSUE TITLE
redis的set第三个参数可以是数组

### ISSUE THREAD

**Issue by he426100** [top-think/framework#1349]
不需要setex，直接用set($key, $value, $expire)， 而且还能实现更多功能

// Will redirect, and actually make an SETEX call
$redis->set('key','value', 10);

// Will set the key, if it doesn't exist, with a ttl of 10 seconds
$redis->set('key', 'value', Array('nx', 'ex'=>10));

// Will set a key, if it does exist, with a ttl of 1000 miliseconds
$redis->set('key', 'value', Array('xx', 'px'=>1000));

**Comment by guandeng** [comment]
在2.6.12以上版本才可以使用 https://redis.io/commands/set
