### ISSUE TITLE
Query 的注释问题

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#135]
1. 已经不存在 `DbException` 对象了, 但 Query 中还在 use
2. 不知道什么时候 Query 的 @return 注释修改成了 `@return $this`, 在链式写法时 PhpStrom 不支持此代码提示. 使用 `@return Query 可以正常提示
3. `db` 帮助函数 `@return ` 除了使用 `\think\db\Connection` 还应该加上 `\think\db\Query` 即 `@return \think\db\Connection|\think\db\Query`.  同样的 Db 类的 connect 方法 @return 也应加上 `\think\db\Query`  返回

**Comment by liu21st** [comment]
1 已经修正
2 应该没问题啊
3 db助手函数返回类型应该是 Query 但Db类的connect方法返回类型不变的
