### ISSUE TITLE
url生成错误问题

### ISSUE THREAD

**Issue by liushoukun** [top-think/framework#1353]
注册两个路由的后
Route::group('admin', function () {
    Route::resource('orders','admin/Order')->name('admin.order');
    Route::resource('users','admin/User')->name('admin.user');
});

Order 和 User  控制器中
     dump(url('admin/order/edit', ['id' => 1]));
     dump(url('admin/user/edit', ['id' => 1]));

User ：
 "/admin/order/edit/id/1.html"
 "http://xxx.com/admin/users/1/edit.html"

Order: 
 "http://xxx.com/admin/orders/1/edit.html"
"/admin/user/edit/id/1.html"
两个控制器输出生成的不一致

**Comment by liu21st** [comment]
对资源路由使用name是无效的

**Comment by liushoukun** [comment]
去除后name也还有这样的问题
