### ISSUE TITLE
library/think/Model.php save 方法问题

### ISSUE THREAD

**Issue by qinweixian** [top-think/framework#1357]
第428行
`// 重新记录原始数据
$this->origin = $this->data;`
更新完成为什么要给origin赋值？
这个样的话，下次再调用save方法更新其他数据时候，会用更新的数据去跟origin里的旧数据做对比，为什么是上一条数据和下一条数据对比呢？

**Comment by liu21st** [comment]
同一个模型实例只更新当前实例对应数据 这是规范
