### ISSUE TITLE
线上生产环境最近偶尔会报这个错误

### ISSUE THREAD

**Issue by jin123456bat** [top-think/framework#1369]
![image](https://user-images.githubusercontent.com/2076638/43600722-f87e89a2-96bd-11e8-8ecd-f68cc2624c4d.png)
![image](https://user-images.githubusercontent.com/2076638/43600749-06ea9ec2-96be-11e8-80af-b09f4a923907.png)

看样子貌似被人嗅探攻击，虽然没什么大问题，但是我有强迫症

**Comment by jin123456bat** [comment]
这个$this->ext()不用正则转义吗？

**Comment by lihaotian0607** [comment]
生产环境你居然不关闭调试模式,你也是厉害了

**Comment by jin123456bat** [comment]
@lihaotian0607 项目内测，打开调式模式配合邮箱，方便定位问题，一旦出现异常会给我发邮件，方便即使问题修复

**Comment by lihaotian0607** [comment]
你可以使用自定义异常处理类,在自定义异常处理类中出现500的或者其他错误的时候通知你,安全一点!!!!

**Comment by jin123456bat** [comment]
@lihaotian0607  就是在自定义异常处理类中捕获的异常信息，在没有开启调试模式下不能获取到stack等信息
