### ISSUE TITLE
在action里调用action的问题

### ISSUE THREAD

**Issue by hrbzcj** [top-think/framework#1374]
在A action里调用B action，
如果A和B最后都引用了模板$this->fetch();  //fetch方法里没有指定模板路径
那么在B action里fetch方法得到的模板路径和A action里fetch方法得到的模板路径一样的（因为都是通过request对象获取的），这样B action没有fetch正确的模板，而是渲染了A action对应的模板。结果就是页面出现了两块一样的内容。
如果不是在A action里调用B action，而是在A action对应的模板里调用B action，那么由于B action也会渲染A action对应的模板，那么就会形成无限渲染模板，结果页面卡死。

我是thinkphp的初学者哈，不知道描述清楚没有？

**Comment by liu21st** [comment]
尽量避免这样调用，如果必须，就在控制的操作方法渲染模板的时候 进行明确指定
