### ISSUE TITLE
关于5.1缓存cache的set里面的serialize问题

### ISSUE THREAD

**Issue by nasireddin** [top-think/framework#1378]
```
/**
 * 缓存基础类
 */
abstract class Driver
 
/**
     * 序列化方法
     * @var array
     */
    protected static $serialize = ['serialize', 'unserialize', 'think_serialize:', 16];

 /**
     * 序列化数据
     * @access protected
     * @param  mixed $data
     * @return string
     */
    protected function serialize($data)
    {
        if (is_scalar($data) || !$this->options['serialize']) {
            return $data;
        }

        //问题：这里self调用是当前类的数组值，配置的serialize没用

        $serialize = self::$serialize[0];
        return self::$serialize[2] . $serialize($data);
    }
```

    protected function serialize($data)
    {
        if (is_scalar($data) || !$this->options['serialize']) {
            return $data;
        }
       //期望：类似这样可以配置去除think_serialize:这个默认的字符串和兼容 json_encode 之类的
        $serialize = isset($this->options['serialize'][0])?$this->options['serialize'][0]:self::$serialize[0];
        return (isset($this->options['serialize'][2])?$this->options['serialize'][2]:self::$serialize[2]) . $serialize($data);
    }

config的cache文件配置
return [
    //缓存配置为复合类型
    'type'  =>  'complex',
    'default'	=>	[
        'type'	     =>	'redis',
        'host'	     =>	'127.0.0.1',
        'port'       => 6379,
        'password'   => '',
        //'serialize' => ['serialize','unserialize', '', 0],
        'serialize'  => ['json_encode','json_decode','',0],
    ],

**Comment by liu21st** [comment]
配置参数serialize只是用于控制是否需要使用序列化，而实际的序列化操作的方法应该用 registerSerialize 方法设置的

**Comment by nasireddin** [comment]
``/**
     * 注册序列化机制
     * @access public
     * @param  callable $serialize      序列化方法
     * @param  callable $unserialize    反序列化方法
     * @param  string   $prefix         序列化前缀标识
     * @return $this
     */
    public static function registerSerialize($serialize, $unserialize, $prefix = 'think_serialize:')
    {
        self::$serialize = [$serialize, $unserialize, $prefix, strlen($prefix)];
    }
``


` //$redis = \think\Cache::registerSerialize('serialize', 'unserialize','')->set(1,[1,2]);

        $redis = \think\facade\Cache::registerSerialize('serialize', 'unserialize','')->set(1,[1,2]);`
这样子？都试过了，报错，还没搞懂怎么用
registerSerialize方法 return $this 是null
致命错误: Call to a member function set() on null

**Comment by liu21st** [comment]
单独注册就行 因为是全局静态方法 和你的缓存操作分开

**Comment by nasireddin** [comment]
了解了，thx
