### ISSUE TITLE
request()->scheme()获取协议出错

### ISSUE THREAD

**Issue by wangshantao** [top-think/framework#1381]
```
var_dump(request()->domain());
var_dump(request()->scheme());
```
![_20180817115852](https://user-images.githubusercontent.com/14883268/44247176-14191080-a215-11e8-894b-849cb71f4349.png)

**Comment by liu21st** [comment]
你可以跟踪下request类的isssl方法 和你的环境有一定关系

**Comment by wangshantao** [comment]
不知道是不是阿里云安全策略问题，里面的参数都是http的
