### ISSUE TITLE
TP5.0版本支持SWOOLE

### ISSUE THREAD

**Issue by xavieryang007** [top-think/framework#1383]
目前参考官方版本写了一个SWOOLE扩展包，需要修改一些核心东西，是否核心更新时可以支持一下。

1.支持删除request类实例
2.CLI模式下请求类型和POST数据接收

public static function deletethis()
    {
        if (!is_null(self::$instance)) {
            self::$instance=null;
        }
    }

public function method($method = false)
        {
            if (true === $method) {
                // 获取原始请求类型
                $this->method = IS_CLI ?(defined('IS_SWOOLE')?((isset($this->server['REQUEST_METHOD'])? $this->server['REQUEST_METHOD'] : isset($_SERVER['REQUEST_METHOD'])?$_SERVER['REQUEST_METHOD']:'GET')):'GET') : (isset($this->server['REQUEST_METHOD']) ? $this->server['REQUEST_METHOD'] : $_SERVER['REQUEST_METHOD']);
            } elseif (!$this->method) {
                if (isset($_POST[Config::get('var_method')])) {
                    $this->method = strtoupper($_POST[Config::get('var_method')]);
                    $this->{$this->method}($_POST);
                } elseif (isset($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE'])) {
                    $this->method = strtoupper($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE']);
                } else {
                    $this->method = IS_CLI ?(defined('IS_SWOOLE')?((isset($this->server['REQUEST_METHOD'])? $this->server['REQUEST_METHOD'] : isset($_SERVER['REQUEST_METHOD'])?$_SERVER['REQUEST_METHOD']:'GET')):'GET') : (isset($this->server['REQUEST_METHOD']) ? $this->server['REQUEST_METHOD'] : $_SERVER['REQUEST_METHOD']);
                }
            }
    
            return $this->method;
        }
暂时通过修改核心版本

现在项目地址https://github.com/xavieryang007/xavier-swoole

**Comment by liu21st** [comment]
5.0的架构没法完美支持的  要改动很多地方 所以还是用5.1版本吧 5.0版本的支持 网上也有很多方法

**Comment by liu21st** [comment]
改进了下 可能你的包需要略微调整下

**Comment by xavieryang007** [comment]
好的 多谢
