### ISSUE TITLE
建议优化多级操制器的写法：将点.改成斜杠/来分隔

### ISSUE THREAD

**Issue by tgl123** [top-think/framework#1396]
1.现在多级控制器是用点 .  来操作，看着很别扭，建议改成  / 来分隔，这样层次也清晰。

因为点是一个特殊的字符连接操作符，尽量让他没有别的含义

**Comment by liu21st** [comment]
你用路由就可以解决这个问题了

**Comment by tgl123** [comment]
嗯，我知道可以，但是你配置的路由的指向的源路径中有 .

**Comment by liu21st** [comment]
只要不是在URL里面输入点号 又有什么影响呢？ 不用斜杠肯定是有原因的 你没法区分是模块还是控制器否则

**Comment by tgl123** [comment]
只是建议优化，不优化又何妨，既然是一门好的框架，尽量完善咯    /index/indx.pay/add/  突然出来一个点，你觉得很顺眼也行呀。我只是建议。没别的意思
