### ISSUE TITLE
TP函数优先加载

### ISSUE THREAD

**Issue by yovei** [top-think/framework#14]
TP5 里面优先加载了   composer的autoload

// 注册composer自动加载
self::registerComposerLoader();

有部分框架也使用了 与TP相冲突的函数

如illuminate\support\helpers.php  中的e() 相冲突

希望有新方案解决

1.composer 加载优先级 由我们自己控制
 // 注册composer自动加载
self::registerComposerLoader();

2.使用 function_exists  避免冲突  在tp中 减少 E 函数的使用

**Comment by liu21st** [comment]
其实 TP核心本身是没有使用任何自定义函数的 封装的都是助手函数 可以自己随便调整的

**Comment by yovei** [comment]
收到  已自行修改
