### ISSUE TITLE
模型自定义数据类型

### ISSUE THREAD

**Issue by i5920** [top-think/framework#1410]
Model 模型能不能自定义数据类型
`protected $type = [];`
希望增加配置

**Comment by liu21st** [comment]
不能定义么？

**Comment by i5920** [comment]
@liu21st 可以定义内置的[timestamp,integer]等;但是内置的类型的不够用。能不能提供一个可以自己定义类型的入口；比如IP地址和整数互转  long2ip  ip2long

读的时候用long2ip;写的时候用ip2long

**Comment by momoca** [comment]
https://www.kancloud.cn/manual/thinkphp5_1/703981
获取器是干这个的.

**Comment by i5920** [comment]
@momoca 好的，谢谢
