### ISSUE TITLE
in查询有问题。麻烦修复一下

### ISSUE THREAD

**Issue by semoons** [top-think/framework#1418]
![image](https://user-images.githubusercontent.com/20333334/45343363-3e22e000-b5d3-11e8-8c59-e6d7d2484115.png)

![image](https://user-images.githubusercontent.com/20333334/45343379-4d099280-b5d3-11e8-8eec-ad47dcf345f4.png)

**Comment by semoons** [comment]
@liu21st

**Comment by liu21st** [comment]
5.1版本不支持你这种数组查询

**Comment by semoons** [comment]
额，那要用in是不是要单独写一个where啊。where('id','in', $ids)  ，只有这样吗？ @liu21st

**Comment by liu21st** [comment]
关于这个问题 你还是仔细看下手册吧

**Comment by semoons** [comment]
5.0的这种方式感觉挺好用的啊。

**Comment by liu21st** [comment]
安全比好用更重要，况且5.1还提供了数组查询对象的
