### ISSUE TITLE
模型删除的问题

### ISSUE THREAD

**Issue by jin123456bat** [top-think/framework#1422]

**Comment by jin123456bat** [comment]
![image](https://user-images.githubusercontent.com/2076638/45533373-0cf01d00-b82a-11e8-8101-914110de2e80.png)

执行save没问题，查看了一下数据 只更新了一条 
执行delete提示没有条件，貌似是主键没有找到的缘故？

DB中的数据
![image](https://user-images.githubusercontent.com/2076638/45533422-2db87280-b82a-11e8-9514-a1045001a93e.png)

已声明主键
![image](https://user-images.githubusercontent.com/2076638/45533453-432d9c80-b82a-11e8-9655-b90a1e1fdb05.png)

**Comment by liu21st** [comment]
更新一条不是很正常么？你直接return了 至于delete的问题 针对复合主键的情况可能需要改进下

**Comment by jin123456bat** [comment]
我说delete有问题，save没问题……看了下源码，getPk方法没有对数组主键的判读

**Comment by jin123456bat** [comment]
上面写的都是测试代码，所以直接return了
