### ISSUE TITLE
namespace think\response;可空类型

### ISSUE THREAD

**Issue by axgle** [top-think/framework#1424]
tp5.2的可空类型:
  public function filter(?callable $filter)
    {
        $this->filter = $filter;
        return $this;
    }

**Comment by axgle** [comment]
我看到 filter有null默认参数,而另外一处filter又要求callable.
php7.1支持 可空类型.

**Comment by axgle** [comment]
function view(string $template = '', $vars = [], $code = 200, $filter = null)
    {
        return Response::create($template, 'view', $code)->assign($vars)->filter($filter);
    }

**Comment by liu21st** [comment]
已经改进
