### ISSUE TITLE
json字段转换时将中文转化为unicode编码,可以设置不编码吗?

### ISSUE THREAD

**Issue by railgun20001** [top-think/framework#1426]
![_20180918161715](https://user-images.githubusercontent.com/22837283/45673906-763f9b00-bb5e-11e8-9def-7058c0929c10.png)
如图所示

**Comment by axgle** [comment]
有选项,可以设置的.
-------
ps:框架本身是否可以考虑默认就是不转,毕竟我们是中文环境居多...

**Comment by railgun20001** [comment]
@axgle 请问是那个选项,或者搜索关键字,找了半天没找到

**Comment by axgle** [comment]
主要是json_encode的JSON_UNESCAPED_UNICODE,
tp5可以用json_encode_param传进去.
下面的是我的业务代码,供参考.
`function api($data=[], $msg='ok', $code=0){

    $params=[
        JSON_PRETTY_PRINT,
        JSON_UNESCAPED_SLASHES,
    ];
    $json_encode_param=JSON_UNESCAPED_UNICODE;

    foreach($params as $p){
        $json_encode_param=$json_encode_param|$p;
    }
    return json(compact('code','msg','data'))
    ->options([
        'json_encode_param'=>$json_encode_param
    ]);
}`

**Comment by liu21st** [comment]
你们说的可能不是一个地方，json字段的编码那块 我改进了
