### ISSUE TITLE
关于5.1版本url_convert配置的问题

### ISSUE THREAD

**Issue by chawuciren** [top-think/framework#1427]
在配置文件 app.php 下的配置项：url_convert，开启URL的控制器操作名自动转换。

开启配置后会将URL中对应的 controller 名称从下划线转为驼峰，对 action 名称却不转换，但是强转为小写。

建议将该行为改为一致，将传入的URL中下划线风格的 action 也转为驼峰，而不是小写。一是对应的方法名本身就应该遵循PSR规范，二是有些场景需要获取原始的 action 名称，一刀切转为小写并不实用。

**Comment by liu21st** [comment]
因为方法名调用不区分大小写，至于获取实际的action方法名称 Request对象的action方法是支持的

**Comment by chawuciren** [comment]
OK,那我这么说吧。

假设我的URL是：http://api.xxxx.com/Api/DocTool/GetActionList.json

由于后续的业务需要，我要拿到原始的、包含大小写的URL信息。

现在最新版本的5.1下，我关闭 url_convert，然后执行下面语句：

        dump($request->path());                                                                                            
        dump($request->url());                                                                                             
        dump($request->module());                                                                                          
        dump($request->controller());                                                                                                                                 
        dump($request->action()); 

得到的结果是：

    string 'Api/DocTool/getactionlist' (length=25)
    string '/Api/DocTool/getactionlist.json' (length=31)
    string 'api' (length=3)
    string 'DocTool' (length=7)
    string 'getactionlist' (length=13)

可以看到，对应的action名依然被转换了，我依然拿不到原始的信息。

**Comment by liu21st** [comment]
request->action(true) 就可以获取实际的操作方法名

**Comment by chawuciren** [comment]
嗯，貌似文档中没有体现，不过试过已经试过可以获取到，谢谢 ！！！^__^
