### ISSUE TITLE
日志 log_write_done 标签位置 有死循环的BUG

### ISSUE THREAD

**Issue by xiasf** [top-think/framework#1433]
```
'log_write_done' => [
        'app\\index\\behavior\\ErrorChecking',
    ],

```

命令行下面执行，会出现死循环记录日志，直至内存消耗完毕崩溃。

### 原因：

think\Log::record()

// 命令行下面日志写入改进
IS_CLI && self::save();

-----

think\Log::save()

Hook::listen('log_write_done', $log);

-----

Hook::exec()

...

Log::record('[ BEHAVIOR ] Run ' . $class . ' @' . $tag . ' [ RunTime:' . Debug::getRangeTime('behavior_start', 'behavior_end') . 's ]', 'info');
...

-----

这样就导致死循环，record > save > Hook::exec > record 死循环了

**Comment by liu21st** [comment]
已经改进

**Comment by xiasf** [comment]
想增加 log_record 标志位 是因为有这样的需求，希望检测到有错误发生时，给管理员发送短信提醒，或者记录单独错误日志等等。

**Comment by liu21st** [comment]
有错误发生给管理员短信提醒 应该是自定义异常处理的 report方法，记录单独的错误日志本身是支持的

**Comment by xiasf** [comment]
不只异常发提醒，我想类似收到某类日志时有提醒，不一定是执行异常了，比如单纯的 trace($errMsg, 'error'); ，比如自定义级别的日志，业务逻辑中可能会有这样的需求。

**Comment by liu21st** [comment]
我增加了一个log_level标签位置

**Comment by xiasf** [comment]
上次那个日志标签位置的死循环问题，我看了你去掉“行为执行的记录日志”的提交，那只是一个临时的解决方案，我想到了一个更好的办法，那就是限制标签位监听的次数，因为这个问题的根源就是监听被执行了多次。切面编程的初衷不就是一个切面一个监听么，监听与切面是一对一的（不可能多个切面用同一个监听，也不可能一个监听被用在多个切面上），所以我们理应这么做，在钩子类里面记录监听方法的执行次数，保证监听方法只被执行一次就可以了。不知道老大觉得怎么样？

**Comment by xiasf** [comment]
否则的话，如果我在行为里面还有日志记录的操作，还是会出现同样的死循环问题，你上次那只是删除了钩子执行时的日志记录。（比如我行为里面还有sql操作，不就会自动记录sql日志吗，也会再次触发日志监听，再次回到死循环问题）

**Comment by liu21st** [comment]
限制监听次数不是一个好的办法 在命令行下面本来就是实时写入日志的，而且次数和死循环并没必然关联

**Comment by xiasf** [comment]
这个例子中，监听被多次执行和死循环问题有必然联系。不然，在log_level标签位置的自定义行为类的run方法中执行了记录日志的操作（如Db操作），会出现死循环的这个问题怎么解决呢。（behavior::run() > Log::record() > 监听 > behavior::run() > ……）
