### ISSUE TITLE
 NOT IN 查询表达式的值为数组的情况SQL 解析错误

### ISSUE THREAD

**Issue by tekintian** [top-think/framework#1434]
NOT IN查询

单个条件直接写正常
Db::name('user')->where('id','in',[1,5,8])->select();

改为数组模式及失效：
值使用数组的
$where['id']=array('not in','1,5,8')
Db::name('user')->where($where)->select();
解析后的where条件为
WHERE  `id` IN (0,1)

NOT IN的条件变成了 IN,后面的值变成了   0,1

**Comment by liu21st** [comment]
根本不支持你这个数组用法的5.1 仔细看手册 数组方式查询

**Comment by tekintian** [comment]
谢谢，5.1的文档的确没有怎么看，还以为和5.0差不多
