### ISSUE TITLE
模型获取的问题

### ISSUE THREAD

**Issue by jin123456bat** [top-think/framework#1435]
通常一个模型添加的时候只会传递一部分字段，其余字段在数据库中已经设置了默认值，在save之后，无法获取到这些默认值，

**Comment by xiasf** [comment]
再次查询一下不就可以了，这个不需要框架来做吧，框架应该做最少的事，做最关键的事。

**Comment by liu21st** [comment]
其实不建议使用数据库的默认值 而是在模型里面设置自动完成

**Comment by jin123456bat** [comment]
当DB繁忙的时候 程序中获取到的时间和实际添加到DB的时间是不一样的

**Comment by liu21st** [comment]
业务数据就应该以业务系统的数据为准 数据库只是一个存储媒介

**Comment by xiasf** [comment]
统一使用 $request->time() 就是一致的啊，不该是有数据库自身的时间函数了吧
