### ISSUE TITLE
Request::file 的多文件上传问题

### ISSUE THREAD

**Issue by hsSam** [top-think/framework#1436]
由于目前有多文件上传各个文件不一样，定义filename为 file1, file2, file3
更新修改了
SHA-1: 61cb45d3e505cb914152e1e0aa8c8faccdd3ec1c
* 修正Request类的file方法

protected function dealUploadFile($files)
添加了 $this->throwUploadFileError($file['error']);

-----
我原有的使用方法是 Reqeust::file() ，获取全部， 但是file1, file2, file3不一定所有文件都要上传。
更新后的 dealUploadFile 函数把 $_FILES的文件都判断一遍， error > 0的直接抛Exception

按理来说，我使用 Request::file('file1') 的话， 你函数就不要管 file2, file3有没有文件上传才对
-----
建议修改：
如果参数有指定的name的，做上传校验
如果name填空的，获取全部上传文件的只获取上传成功的返回File数组就好，上传错误的忽略

**Comment by liu21st** [comment]
已经改进
