### ISSUE TITLE
关联模型中，预加载多个关联表，多个关联表都需要where操作

### ISSUE THREAD

**Issue by 463024796** [top-think/framework#1440]
关联模型中，预加载多个关联表，多个关联表都需要where操作，看了文档和源码发现，如果需要在关联表中使用where，那需要用hasWhere来操作，但是这个操作只能使用一次，并且是一个表，那我有几个关联表都需要使用where应该要怎么写呢？谢谢

**Comment by liu21st** [comment]
自己用join查询
