### ISSUE TITLE
如何扩展日志的驱动类？

### ISSUE THREAD

**Issue by JerryChaox** [top-think/framework#1451]
日志的驱动类现在只有File和Socket。我想额外扩展一个driver将日志打到我的日志管理服务器上，有什么方法可以扩展吗？

目前想到的方案是继承\think\Log, 重写其中的init方法，以加载自己的driver

**Comment by liu21st** [comment]
直接扩展一个自己的驱动，然后改日志类型，不需要改核心

**Comment by JerryChaox** [comment]
是的，一开始以为命名空间写死了。type直接指定全名即可了。/close
