### ISSUE TITLE
在用url函数生成url时 ，如果使用了 Route::any ,则会生成 http://localhost.localhost/xxx 形式的错误url

### ISSUE THREAD

**Issue by liaohongxing** [top-think/framework#1453]
用localhost 访问不正常。
在用url函数生成url时 ，如果使用Route::any,则会出现 http://localhost.localhost/xxx形式的url 

thinkphp5.1.25

**Comment by hongweipeng** [comment]
```
<?php
use think\facade\Route;

// in function
$url = Route::any('blog/:id','index/blog/read');
echo $url->getDomain();   // output:localhost
```
tp5.1
无法复现你说的问题，是我复现的方式有问题吗？

**Comment by momoca** [comment]
@leunggamciu 你一定是配置了主域名为localhost吧。

**Comment by leunggamciu** [comment]
@momoca \@错人了吧

**Comment by liaohongxing** [comment]
@hongweipeng 你的复现确实有问题 ，看我标题 ，一定要用url函数 ,看下面代码:
`Route::any('blog/:id','index/blog/read');
echo url('index/blog/read', ['id' => 1]);   // output:http://localhost.localhost/sync/cms/public/blog/1.html
exit;`

**Comment by liaohongxing** [comment]
@liu21st

**Comment by liu21st** [comment]
改进了下 不过真没有必要用localhost本地测试了

**Comment by hongweipeng** [comment]
哦，确实如此，我也复现了，这是个问题。开发时候确实会做一些虚拟域名到本地。 @liu21st 看了您的改进的 commit，貌似只是对 `localhost` 做了处理，如果我设置虚拟域名是 `localtest` 的话，这个问题还是存在的。

另外，我在想代码判断 $domain 中是否有 `.` 的意图何在。

**Comment by liu21st** [comment]
嗯 换了个方式判断
