### ISSUE TITLE
无法在模型事件中修改模型的值了

### ISSUE THREAD

**Issue by jin123456bat** [top-think/framework#1465]

**Comment by jin123456bat** [comment]
![image](https://user-images.githubusercontent.com/2076638/47601220-eebc3600-d9ff-11e8-9875-c48a57899648.png)
对应的代码如下，，很奇怪，days没了
![image](https://user-images.githubusercontent.com/2076638/47601222-f380ea00-d9ff-11e8-8393-2c71db44891a.png)

**Comment by liu21st** [comment]
最新版本已经修正
