### ISSUE TITLE
单元测试无法运行

### ISSUE THREAD

**Issue by finntenzor** [top-think/framework#1466]
ThinkPHP版本：v5.1.26
think-testing版本：v2.0.2

错误描述：
安装topthink/think-testing后执行单元测试，发现如下报错：
![image](https://user-images.githubusercontent.com/7535112/47262375-a2618980-d519-11e8-8d23-94d2c7861436.png)
根据think-testing的源代码
![image](https://user-images.githubusercontent.com/7535112/47262380-d046ce00-d519-11e8-80b6-95f104037128.png)
猜测原因和PHPUnit为6.x版本有关，根据PHPUnit官方文档，6.x版本中修改了命名空间，使用诸如PHPUnit\Framework\TestCase的形式，很有可能是这个原因造成了单元测试无法运行。
![image](https://user-images.githubusercontent.com/7535112/47262381-fff5d600-d519-11e8-91bd-d0c225cbf497.png)

**Comment by liu21st** [comment]
嗯 回头改进下直接用PHPUnit6起步吧
