### ISSUE TITLE
tp5集成的think-worker运行一段时间后会报错

### ISSUE THREAD

**Issue by ZhJiaYi** [top-think/framework#1472]
刚启动服务后是没问题的，运行一段时候后会显示这些错误信息，一开始以为是长连接导致的数据库断连，后面在database里开启断线重连的配置后运行一段时候后又会不断重连
![_20181019123632](https://user-images.githubusercontent.com/22539402/47420556-516bc280-d7b1-11e8-97da-6d9b27d140e7.png)
![_20181019162652](https://user-images.githubusercontent.com/22539402/47420557-516bc280-d7b1-11e8-96af-7b3176cf4653.png)

**Comment by xavieryang007** [comment]
数据库连接是否存在闲置？MYSQL连接如果长时间闲置就会被中断，所以一般数据库连接池都会发ping

**Comment by ZhJiaYi** [comment]
> 数据库连接是否存在闲置 mysql连接如果长时间闲置就会被中断所以一般数据库连接池都会发ping ， ？

没有长时间闲置，而是cli模式下使用一段时间后无法连接上数据库
