### ISSUE TITLE
5.1.19路由分组注册中间件无法对miss路由生效

### ISSUE THREAD

**Issue by finntenzor** [top-think/framework#1473]
这是我的Route路由写法，将api下两个请求指定到两个方法上
![image](https://user-images.githubusercontent.com/7535112/47475765-a0683500-d84f-11e8-842c-436cdcab9941.png)
方法内容一个返回列表，一个抛出错误
![image](https://user-images.githubusercontent.com/7535112/47475770-abbb6080-d84f-11e8-8ba0-b02d47f764c0.png)
我在api上注册中间件如下：
![image](https://user-images.githubusercontent.com/7535112/47475851-0bb20700-d850-11e8-967a-5cc042bdd563.png)

实际请求结果如下：
请求index时
![image](https://user-images.githubusercontent.com/7535112/47475785-bc6bd680-d84f-11e8-9e02-f8d091c5d159.png)
请求一个不存在的路由时
![image](https://user-images.githubusercontent.com/7535112/47475802-cee61000-d84f-11e8-8e94-1e969138e961.png)

推测get请求经过了中间件但是miss并没有经过中间件。

**Comment by liu21st** [comment]
已经修正
