### ISSUE TITLE
最新版本 正则匹配出现内存溢出

### ISSUE THREAD

**Issue by ksanyu** [top-think/framework#1483]
![_20181031112950](https://user-images.githubusercontent.com/20432069/47764494-5fb16580-dd00-11e8-8ebf-4db82968fb11.png)
![_20181031112954](https://user-images.githubusercontent.com/20432069/47764495-5fb16580-dd00-11e8-84b3-d6a67320bd08.png)

**Comment by jin123456bat** [comment]
感觉这个应该是php的bug，跟框架没什么关系

**Comment by hongweipeng** [comment]
能够提供更详细的信息，您php版本等。如何复现它之类的。
