### ISSUE TITLE
在 swoole 模式下，控制器中的 request 不会变

### ISSUE THREAD

**Issue by browningweb** [top-think/framework#1484]
https://github.com/top-think/framework/blob/bd9c7d3cc469cc3a670d5486c961b6d4f9b2d449/library/think/Controller.php#L99

在 swoole 模式下，控制器中的 request 不会变，使用 
`$this->app->request->action()` 
可行。

**Comment by liu21st** [comment]
不明白你是想表达什么，think-swoole扩展request对象是会更新的
