### ISSUE TITLE
老BUG反馈：生成这样的url路由打不开

### ISSUE THREAD

**Issue by broadteam** [top-think/framework#1487]
以前是好的，自从升级的往前的哪个版本我忘了，之后就再也打不开了。刚升级到最新，结果5.1.25还是一样的。
重新描述下：
对于这样的url地址：
url.cn/products
url.cn/products/women
url.cn/products/women/bags
url.cn/products/women/shoes
其原地址是：
url.cn?path=products
url.cn?path=products/women
url.cn?path=products/women/bags
url.cn?path=products/women/shoes
之前一直是好的，升级后就打不开了，希望解决下，这个问题我自从5.0的时候就提过很多次，后来反反复复修复过很多次，总是在升级版本的时候弄错。最后这一次忘了具体哪个版本开始的，但是也好几个月了。实在是不能用啊

**Comment by broadteam** [comment]
对了，不是跨版本升级出现到问题。都少5.1小版本升级出现到问题

**Comment by hongweipeng** [comment]
能提供下5.1上的复现方式吗以及希望得到的结果？

**Comment by broadteam** [comment]
就是我问题中描述的那样啊，那样的url生成后，不能访问了。原来是可以的。

**Comment by honoryao** [comment]
@broadteam 修改下你的config.php文件中PATHINFO变量 值为path 试一下，兼容模式下是使用这个值作为参数传递给框架路由解析模块的
