### ISSUE TITLE
5.1.28 的json序列化与cache问题

### ISSUE THREAD

**Issue by mlyykk** [top-think/framework#1503]
public function test()
    {
        if (cache('test')) {
            $jsonData = cache('test');
        } else {
            $arr[0]['name']="zhangsan";
            $arr[0]['code']="1";
            $arr[1]['name']="lisi";
            $arr[1]['code']="2";
            $arr[2]['name']="wangwu";
            $arr[3]['code']="3";
            $jsonData = json($arr);
            cache('test', $jsonData, 60);
        }
        return $jsonData;
    }

报错:"Serialization of 'Closure' is not allowed"

**Comment by hongweipeng** [comment]
助手函数 `json` 返回的是一个 `Response` 对象。该对象是不可序列化的。
