### ISSUE TITLE
value为''的时候会跳过，能不能将 && '' !== $value去掉，不然不会运行自定义函数处理自定义逻辑

### ISSUE THREAD

**Issue by lineofsky2017** [top-think/framework#1517]
https://github.com/top-think/framework/blob/51857ae01d8c212e583f3539c76e449d61468113/library/think/Validate.php#L536

情况：
1. 比如根据其他post参数的值对当前值进行校验，当参数传''的时候，直接跳过了，不运行自定义函数
2. 如果在规则里面加入require对于某些情况不需要该参数的时候又过不了

所以去掉该校验，可以将处理权交给自定义函数

**Comment by hongweipeng** [comment]
这里的争议是空字符串`''`算不算满足 `require` 了。
我的看法是''不能通过 `require` 的，理由如下。

前端代码 `<input name="name"  />` 不填而提交表单，后台能得到 name 其值为 `''`。
若 `<input name="name" required="required" />` 不填无法提交表单。从这个的角度看，当有require限定时，不能不填，前端也无法传递空字符串到后台。

所以，在后端上，空字符串也过不了require。既然你的逻辑上允许传''，那就移除掉require规则吧。

**Comment by lineofsky2017** [comment]
> 这里的争议是空字符串`''`算不算满足 `require` 了。
> 我的看法是''不能通过 `require` 的，理由如下。
> 
> 前端代码 `<input name="name" />` 不填而提交表单，后台能得到 name 其值为 `''`。
> 若 `<input name="name" required="required" />` 不填无法提交表单。从这个的角度看，当有require限定时，不能不填，前端也无法传递空字符串到后台。
> 
> 所以，在后端上，空字符串也过不了require。既然你的逻辑上允许传''，那就移除掉require规则吧。

但是对于''，也需要进入自定义函数，比如配置的规则是：
```php
module_type => 'handleModuleType',
```
当传module_type为‘’的时候，并不会进入handleModuleType函数，而是被忽略，导致在必填的时候，可以传空，测试也很难过吧
