### ISSUE TITLE
由input数组指针问题导致的查询错误

### ISSUE THREAD

**Issue by ytlmike** [top-think/framework#1524]
### 1. 现象
在使用数组条件查询数据库时出现报错
![1542455682 1](https://user-images.githubusercontent.com/9930122/48660798-a940d500-eaa2-11e8-8cfb-c70e6d998234.png)
### 2.原因
参数数组是从input()数据拿到的，在[framework/library/think/Request.php](https://github.com/top-think/framework/blob/5.1/library/think/Request.php)#1356只对外层数组重置了指针，而此时内层数组的指针位置为null
![1542456111 1](https://user-images.githubusercontent.com/9930122/48660850-a98da000-eaa3-11e8-8ff6-5ee4bd3b517a.png)

现在我只能在自己的基类中重置指针，希望后续能更新下 多谢

**Comment by liu21st** [comment]
查询代码是什么？

**Comment by ytlmike** [comment]
传输的JSON：
```
{"a":[["di_state","=",2],["di_sercity","=",370126]]}
```
后台代码：
```
$condition = input('post.a');
$data = Db::table('driverinfo')->where($condition)->select();
````
类似这样  有几个接口是这样写的，批量字段查询（虽然这么查的确不安全...）

**Comment by ytlmike** [comment]
> 查询代码是什么？

传输的JSON：
```
{"a":[["di_state","=",2],["di_sercity","=",370126]]}
```
后台代码：
```
$condition = input('post.a');
$data = Db::table('driverinfo')->where($condition)->select();
````
类似这样  有几个接口是这样写的，批量字段查询（虽然这么查的确不安全...）

**Comment by hongweipeng** [comment]
问题确实存在，但我有些疑惑。`$condition = input('post.a');var_dump(key($condition));` 得到是 0，表明指针在初始位置没错。

而当我手动赋值 `$condition = [["di_state","=",2],["di_sercity","=",370126]];` 时却不存在这个异常，程序正常运行。令人费解。

**Comment by hongweipeng** [comment]
![20181119095024](https://user-images.githubusercontent.com/7546325/48681943-a21fe100-ebe0-11e8-91ef-a2edc6e6abaa.png)

似乎从php7.1+开始 `array_walk_recursive` 就不消耗指针了。截图遗漏了5.6，5.6也会消耗指针。

**Comment by liu21st** [comment]
感觉没有必要搞得这么复杂，我换个思路处理了下

**Comment by hongweipeng** [comment]
看了您的改进。似乎是为了解决这个issue而做的修改。在我看来这个问题是`array_walk_recursive` 消耗指针引发的。修改并没有解决这个问题，很容易写出意外代码：
```
$condition = input('post.a');
do {
    $val = current($condition);
    do_somethind();
} while(next($condition));
```
难道提醒用户不要使用从input获取的数据的数组指针？

**Comment by liu21st** [comment]
我会重新审视下这个问题，不过你说的场景应该很少，毕竟要二维数组

**Comment by ytlmike** [comment]
看到了更改。多谢啦

**Comment by hongweipeng** [comment]
后端API让前端传二维数组的情况还是蛮多的吧。我说下我的补丁的理由。
1. 原先的reset也是用来重置数组指针的吧，只是忽略了多维数组，补丁弥补了这个问题。
2. PHP解释器也修复了 `array_walk_recursive` 消耗指针的问题，补丁向后兼容，方便升级。

[7192611](https://github.com/top-think/framework/commit/7192611d4c108dc08ff001158d06d7c2e1bdaebc)  中的 `buildWhere`：
```
reset($value);
if (key($value) !== 0) {
    throw new Exception(...);
}
```
这里的if判断就只有一个结果了，只有空数组才能引发异常。虽然我不知道起初判断数组指针的理由是什么，但这样改打破当时的逻辑了吧。

**Comment by ytlmike** [comment]
的确，本来看到[a2801d0](https://github.com/top-think/framework/commit/a2801d0774b5a9e602c93505cd2754bbf8c3a556)中的更改应该是可以解决的，后来又取消了这个更改可能是感觉性能会有损失？

**Comment by liu21st** [comment]
@hongweipeng Builder类的处理逻辑没有变化，这里是为了避免通过请求产生数组方式注入。至于前面的修复方案，因为在7.1+环境下完全是多余的，加上性能开销问题，所以才有顾虑，当然没有更好的解决办法之前，这个方案尚可接受。我个人更倾向于如果有此场景的升级PHP版本的建议
