### ISSUE TITLE
不兼容七牛的sdk出现问题

### ISSUE THREAD

**Issue by xyz3282836** [top-think/framework#153]
新版（20号后）不兼容七牛的sdk

**Comment by yunwuxin** [comment]
那你要去找七牛啊

**Comment by xyz3282836** [comment]
“改进Composer自动加载的判断机制 增加 vendor目录下面的think_autoload文件判断”
这个更新使得七牛无法用自己定义的命名空间

**Comment by xyz3282836** [comment]
这个和七牛没什么关系吧，主要是tp5这边没做好兼容啊

**Comment by xyz3282836** [comment]
应该是七牛问题！
