### ISSUE TITLE
分页简洁模式无效

### ISSUE THREAD

**Issue by shuliuzhenhua** [top-think/framework#1542]
代码
$result = Db::table('think_user')->paginate(10, true);
return $result;

app.php 文件的配置
// 默认输出类型
 'default_return_type'    => 'json',

**Comment by shuliuzhenhua** [comment]
"total": null,
"per_page": 10,
"current_page": 1,
"last_page": null,
"data": [
]

返回的还是这样的。

**Comment by hongweipeng** [comment]
表里没数据？

**Comment by shuliuzhenhua** [comment]
数据我删了，非要我贴个几百行的代码吗。这个的问题在于"has_more": true, 没有出现，是因为tp51 中的toArray 方法，没有对简洁模式做判断，
