### ISSUE TITLE
5.0.22 aggregate 聚合正则不兼容问题

### ISSUE THREAD

**Issue by ryanho2009** [top-think/framework#1546]
` 

public function aggregate($aggregate, $field, $force = false)
{
        if (!preg_match('/^[\w\.\*]+$/', $field)) {
                throw new Exception('not support data:' . $field);
        } 
        $result = $this->value($aggregate . '(' . $field . ') AS tp_' . strtolower($aggregate), 0, $force );
        return $result;
}
`

5.0.22版本加了正则限制后  原来代码里面的 min('a + b') 这种写法也不支持了，请问官方建议这种代码怎么修改？

**Comment by liu21st** [comment]
已经改进了
