### ISSUE TITLE
请问 5.1.29 LTS 怎么实现乐观锁的功能？

### ISSUE THREAD

**Issue by hectorqin** [top-think/framework#1548]
```php
        $pk    = $this->getPk();
        $array = [];

        foreach ((array) $pk as $key) {
            if (isset($data[$key])) {
                $array[] = [$key, '=', $data[$key]];
                unset($data[$key]);
            }
        }

        if (!empty($array)) {
            $where = $array;
        }
```

我想使用 before_update 的hook来增加条件，但是这个更新条件会被覆盖。。。

**Comment by big-dream** [comment]
利用Trait特性给模型增加乐观锁功能
https://blog.thinkphp.cn/895579

**Comment by hectorqin** [comment]
这个乐观锁是在框架层面实现的？怎么在where条件中增加版本号更新条件来实现呢？

**Comment by hectorqin** [comment]
我是想通过添加where更新条件来实现乐观锁，这样会更加准确吧

**Comment by momoca** [comment]
那如你说的，确实可以全完可以自己实现。^_^。不过用框架的意义呢？不就是为了方便么？

**Comment by NHZEX** [comment]
> 我是想通过添加where更新条件来实现乐观锁，这样会更加准确吧

赞同通过是where实现的乐观锁，官方的锁例子确实是有问题。
重写模型`save`方法，然后把锁版本通过`save`第二个参数追加到更新的`where`里，判断update操作影响行数判断乐观锁执行状态。

**Comment by liu21st** [comment]
@NHZEX 自己实现的话怎么都行，比较建议的方式就是通过模型事件来完成。官方的实现方式是为了更好的嵌入

**Comment by NHZEX** [comment]
> @NHZEX 自己实现的话怎么都行，比较建议的方式就是通过模型事件来完成。官方的实现方式是为了更好的嵌入

主要当前给出的实现的并不能有效保护并发写入，可以转移这里[讨论](https://github.com/top-think/framework/issues/1632#issue-402561378)。

乐观锁的嵌入实现涉及到模型的底层细节，使用事件处理起来会相当麻烦，框架内置有支持会好些（比如软删除，虽然是通过trait动态引入，但模型内部还是存在一些必要支持）。

**Comment by momoca** [comment]
你用了事务还用乐观锁有啥用呢？乐观锁就是为了解决长事务的问题。
你可以先阅读一下百度百科：https://baike.baidu.com/item/%E4%B9%90%E8%A7%82%E9%94%81/7146502

另外如果高并发的话。数据在读写数据时也是有锁的。如果是a和b同时，执行sql也是要有先后顺序的。哪么a或b有一个成功后ver就是3另一个写入的条件ver=2就失败了。

btw你可以阅读一下：https://www.cnblogs.com/sheseido/p/5038562.html
