### ISSUE TITLE
请问 5.1.29 model的save方法返回false,如何知道是因为数据没有发生变化？

### ISSUE THREAD

**Issue by hectorqin** [top-think/framework#1549]
如题，如果请求过来的数据没有发生变化，调用save返回的是false，该怎么分辨是数据没有改变这种情况？

**Comment by liu21st** [comment]
返回false只有两个情况 数据没有变化或者你的前置事件返回了false 表示无需更新 因此这两种其实都是一个性质，数据表没有任何更新。其它情况的错误都是抛出异常的
