### ISSUE TITLE
分页转化成json后, 希望能统一类型, 避免对接app等强类型语言带来的问题

### ISSUE THREAD

**Issue by liaohongxing** [top-think/framework#1550]
分页转化成json后, 希望能统一类型, 避免对接app等强类型语言带来的问题，最好能统一int  ，避免app要处理类型转换问题。tp版本 V5.1.29 LTS

![c1](https://user-images.githubusercontent.com/35255844/49197370-98109600-f3c9-11e8-8bc8-2089e854a059.png)
![c2](https://user-images.githubusercontent.com/35255844/49197372-98a92c80-f3c9-11e8-8bcd-0ce487370653.png)

**Comment by liu21st** [comment]
设置下类型转换 否则在不同的环境下可能会产生差异
