### ISSUE TITLE
在5.1.29中更改log日志path参数不生效，且调试dirver下的File有异常情况

### ISSUE THREAD

**Issue by wx-xw1105** [top-think/framework#1552]
log日志path默认配置为空时，正常的在runtime下生成了log。
但按5.1手册配置为../logs/时，失效。
且在调试过程中，发现在dirver下的File类中的构造方法__construct中打印$config，$this->config等变量会重复出现两次。

**Comment by lineofsky2017** [comment]
没有发现这个问题，你检查一下是不是用户权限不足，没有可写权限，`get_current_user`可以看到当前用户
