### ISSUE TITLE
遇到了一个比较奇葩的问题, 关于 Url::build 的

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#156]
如果 nginx 设置了泛解析, 例如 `*.t.com` 域名
使用 `www.fs.cn_www.t.com` 也能正常访问到 `www.t.com` 域名下的内容

> 最近网站老是被这种URL访问, 不知道怎么屏蔽这种多级的域名访问 : (

这个时候, 如果使用 U 函数生成域名 `article/lists@news`, 则会变为: `http://news.fs.cn_www.t.com/article/lists.html`

我觉得, 如果有设置 `url_domain_root` 配置, 那么 `Url::build` 生成URL的时候, 就不要从 `$_SERVER['HTTP_HOST']` 解析了嘛

**Comment by momoca** [comment]
你是之前的3.x吧.方法变了.看一下文档.
