### ISSUE TITLE
Query类中由于view()函数未指定$filed参数，导致$options['map']报错：“未定义数组索引: map”

### ISSUE THREAD

**Issue by WendeWANG** [top-think/framework#1560]
调用函数为$query_results = Db::view('my_view')->order('id')->limit(0, 0)->where(['f_addtime' => ['between' => '2018-11-30 00:00:00,2018-12-08 00:00:00'])->select();

跟踪调试发现Query->parseExpress()函数中在处理where时会索引$options的map属性，但Query中对$options['map']的初始化只有在Query->view()函数中实现，且只有当view函数中field参数非默认值时才会设置。但通常情况下，我们会选择field为默认值，这样以直接获取全部字段信息。从而导致$options['map']出现未定义数组索引的错误信息。

**Comment by hongweipeng** [comment]
view()函数就是要指定 `$filed` 参数的。

**Comment by hongweipeng** [comment]
是，不传filed时获取全部字段是很好的选择。

**Comment by WendeWANG** [comment]
> 是，不传filed时获取全部字段是很好的选择。

但是，不传$field参数时，$options['map']好像就没有被初始化，造成有些操作出现异常。

**Comment by hongweipeng** [comment]
@WendeWANG 问题已在commit 82e8eb6 修复。

**Comment by WendeWANG** [comment]
> @WendeWANG 问题已在commit [82e8eb6](https://github.com/top-think/framework/commit/82e8eb682cd2a9b5a3a3c63becbd5697691469c0) 修复。

好的，谢谢
