### ISSUE TITLE
聚合查询distinct无效

### ISSUE THREAD

**Issue by 842551256** [top-think/framework#1561]
**问题描述：**
在thinkphpV5.1.28LTS（2018-10-28）的更新日志中，增加了聚合查询方法的字段支持DISTINCT，但是，实际使用中在进行聚合查询时，distinct依然无效。请官方排查一下。
**执行代码：**
![image](https://user-images.githubusercontent.com/13143017/49622495-d11dbb80-fa04-11e8-9c15-45be7aaddd2c.png)
**执行结果：**
![image](https://user-images.githubusercontent.com/13143017/49622449-961b8800-fa04-11e8-806f-46a2e335645d.png)
**thinkphp版本：**
当前版本V5.1.30LTS

**Comment by liu21st** [comment]
是指的count('distinct id') 这种
