### ISSUE TITLE
thinkphp5.0 升级到 5.0.23 数据库查询order 遇到问题

### ISSUE THREAD

**Issue by simapple** [top-think/framework#1571]
$cat_model->order("filed(catid,$str)")->limit(10)->select();

因为模型修改  order中 不能传入小括号()，这样原来的写法进行查询就报错了。

**Comment by simapple** [comment]
count 也是如此 count(distinct(uid)) 就会报错 也是因为小括号，不过这个好解决 去掉就可以 count(distinct uid)

**Comment by liu21st** [comment]
可以使用orderRaw方法
