### ISSUE TITLE
url生成https连接错误。

### ISSUE THREAD

**Issue by momoca** [top-think/framework#1572]
路由绑定域名为何生成的utl不是https的？应该如何设置，真的没找到相关问题。
```php
Route::domain('www.domain.cn', function () {
})->middleware([
    'app\domain\middleware\Session',
])->https()->bind('domain');
```
生成代码：
```php
{:url("domain/user/check@www")}
```

**Comment by lineofsky2017** [comment]
1. 在配置文件里可以全局配置为https：
```php
'is_https' => true,
```
2. 访问的域名是通过https访问的，则自动生成的是https的

见：
https://github.com/top-think/framework/blob/6d1504faeb50192f50ba9ec2784186d9927365e0/library/think/Url.php#L326
https://github.com/top-think/framework/blob/f60da098b64ec747bd21594f21529c5d231e7c1f/library/think/Request.php#L1611
