### ISSUE TITLE
Request 问题

### ISSUE THREAD

**Issue by slmhvip** [top-think/framework#158]
第 1307 行是否应该改成

$this->dispatch = is_array($dispatch)?$dispatch:['type' => $type, $type => $dispatch, 'params' => $params];

原来的

$this->dispatch = ['type' => $type, $type => $dispatch, 'params' => $params];

不能成功解析

**Comment by tbphp** [comment]
我更新到最新版本就是遇到这个问题了，报错。

**Comment by terranc** [comment]
同问

**Comment by liu21st** [comment]
已经修正了
