### ISSUE TITLE
5.1.27关闭日志异常

### ISSUE THREAD

**Issue by LiPengFei1989** [top-think/framework#1588]
使用版本: 5.1.27

为了关闭系统日志,将日志类型设置成test, 然后报了一个"class not exists"的错误

查询后发现日志驱动目录里缺少Test类文件

复制5.0版本的test类文件到驱动目录后解决问题.

望检查修复.

**Comment by liu21st** [comment]
5.1.18的更新日志说的很清楚 取消了test日志驱动
