### ISSUE TITLE
v5.0.22 => v5.0.23 升级驼峰式的控制器不能正常匹配对应的View了

### ISSUE THREAD

**Issue by skiy** [top-think/framework#1589]
```
Updating topthink/framework (v5.0.22 => v5.0.23): Downloading (100%)
```

如题，```composer update``` 升级了框架之后，视图文件无法正常选择了。
比如 ```Admin/findPwd``` 的请求地址，```$this->fetch(); ```时，之前是默认载入 ```admin/findPwd.html``` 的文件的，现在却成了 ```admin/find_pwd.html```。
这样一来，差不多整站 view 里的文件都要修改文件名了。

**Comment by skiy** [comment]
> 我也遇到这个问题，但文档好像还没更新

```
for name in `ls *.html`; 
do 
#echo $name; 
newName=`echo $name | sed 's/[A-Z]/\_\l&/g'`
#echo $newName;
mv $name $newName
done
```
文档没有说明怎么整好，所以我自己写了个批量修改文件名的脚本去处理了。Linux 下可用，MacOS 不可用。

**Comment by skiy** [comment]
> @skiy
> 
> ### 我看了下源码，现在只支持 小写下划线 或者 全部小写了
> Think.php:38
> 
> ```
> // 默认模板渲染规则 1 解析为小写+下划线 2 全部转换小写
> ` 'auto_rule'   => 1,
> ```
> Think.php:132
> 
> ```
> `$template = str_replace('.', DS, $controller) . $depr . (1 == $this->config['auto_rule'] ? Loader::parseName($request->action(true)) : $request->action());`
> Loader.php:611
> `public static function parseName($name, $type = 0, $ucfirst = true)`
> 　` {`
> 　　`if ($type) {`
> 　　　`$name = preg_replace_callback('/_([a-zA-Z])/', function ($match) {`
> 　　　`return strtoupper($match[1]);`
> 　　　` }, $name);`
> 　　　` return $ucfirst ? ucfirst($name) : lcfirst($name);`
> 　　`}`
> 　`return strtolower(trim(preg_replace("/[A-Z]/", "_\\0", $name), "_"));`
> ` }`
> ```
> ### 如果你修改成，不带下划线的小写，应该也行，
> ### 配置参数参考
> convention.php:120
> 
> ```
> 'template'               => [
>     // 默认模板渲染规则 1 解析为小写+下划线 2 全部转换小写
>     'auto_rule'    => 1,
>     ...
> ],
> ```

不用这样改了啊。
我那个脚本可以将文件名批量从
```abcdEfgHijklNm``` 改为 ```abcd_efg_hijkl_nm```形式的了啊。不仅改成小写，还加了下划线。

**Comment by altwei** [comment]
@skiy 
哈哈，也是。如果用全小写，在非windows下，还会有区分大小写问题

**Comment by liu21st** [comment]
TP的模板文件默认都是小写的，最新的调整是改成使用小写+下划线方式 更加直观一些 手册也早就更新过的啊 在模板渲染一章

**Comment by altwei** [comment]
> TP的模板文件默认都是小写的，最新的调整是改成使用小写+下划线方式 更加直观一些 手册也早就更新过的啊 在模板渲染一章

确实有，但没有说清楚：是把驼峰解析成小写加下划线
没升级的人是一脸懵逼呀

**Comment by liu21st** [comment]
@altwei 从来都是小写的 没有驼峰的默认规则
