### ISSUE TITLE
多对多关系异常

### ISSUE THREAD

**Issue by bdlover** [top-think/framework#1596]
直接输出$model->user报错.
追踪进去,$this->relation是空的.

模型中定义关系的函数不会执行.
如果中断调试,则等待几秒钟会执行,
现在必须使用这种方式:  $model->user()->select()
才能查到数据.

git最新版 5.1分支 php7.02 apache2.4

**Comment by liu21st** [comment]
检查是否有user字段和模型关联存在冲突了

**Comment by bdlover** [comment]
一个模型只能和一个模型关联,两个表和user关联就报错,甚至其他和这两个模型不想管的关联全是异常.所有模型的relation属性统统报错......
