### ISSUE TITLE
find函数返回的问题

### ISSUE THREAD

**Issue by QThans** [top-think/framework#1598]
![image](https://user-images.githubusercontent.com/18275400/50494169-9a175480-0a5c-11e9-85c8-0279edebe20c.png)

有的时候数组，有的时候数据集是什么情况？
我的定义的返回数据集

**Comment by liu21st** [comment]
find查询怎么可能返回数据集呢 要么是数组 要么是模型对象实例，你定义的只会影响select查询。默认情况下 Db查询就是返回数组 模型查询返回数据集
