### ISSUE TITLE
app_init钩子是否合理？

### ISSUE THREAD

**Issue by qiqizjl** [top-think/framework#1600]
根据官方文档``app_init``钩子是在应用初始化的时候去执行的。但是命令行场景下不会去执行这个钩子。
我在app_init钩子中注入了一些别名容器，导致在queue下不生效

查看了代码，在``app_init``是在\think\App:run中执行的。
![image](https://user-images.githubusercontent.com/7540584/50539755-7836e280-0bc0-11e9-80f8-491e4961e768.png)

但是queue等命令行并不会执行run,而是执行的initialize。所以``app_init``在initialize中是否更合理呢？

**Comment by qiqizjl** [comment]
@liu21st  hi 关于app_init钩子的问题 是否有更好的方案呢？

**Comment by liu21st** [comment]
命令行对钩子的需求不多 如果需要的话也可以自定义命令行入口
