### ISSUE TITLE
【缓存BUG】文件缓存出现的BUG及解决办法

### ISSUE THREAD

**Issue by LiPengFei1989** [top-think/framework#1601]
@liu21st 大神好,我用的是5.1.27版本

每次新增一个缓存， 都会在缓存目录生成一个新目录，目录下面是缓存文件。

但是在删除该缓存时,  只会删除缓存文件, 而不会删除该文件上层的目录, 这样就会造成每次设置和删除缓存都会留下一个空的目录, 并且这个文件夹不会定时删除.

查看源代码发现, 在think\cache\driver\File.php文件缓存类第300行的unlink方法代码中有如下代码:

    private function unlink($path)
    {
        return is_file($path) && unlink($path);  //这行代码只是删除了缓存文件,并没有处理上层目录
    }

代码修改如下:

    private function unlink($path)
    {
        return is_file($path) && unlink($path) && rmdir(dirname($path));  //删除缓存文件后, 删除上层目录
    }

问题解决,

我是tp5初学者, 不知道这样改的对不对, 不过确实解决了我的问题

**Comment by big-dream** [comment]
缓存文件是多个缓存文件一个目录的，不是一个缓存文件一个目录。
如果需要删除空目录，参考手册：https://www.kancloud.cn/manual/thinkphp5_1/354143

**Comment by LiPengFei1989** [comment]
> 缓存文件是多个缓存文件一个目录的，不是一个缓存文件一个目录。
> 如果需要删除空目录，参考手册：https://www.kancloud.cn/manual/thinkphp5_1/354143

这里面不都是在命令行里使用的吗? 请问该如何使用?
