### ISSUE TITLE
$model = Model::create($data) 时 $data 中未定义某数据库字段fieldX，$model->fieldX 无法拿到

### ISSUE THREAD

**Issue by liuruidong1994** [top-think/framework#1604]
$model = Model::create($data) 时 
$data 中未定义某数据库字段fieldX，
create 成功后，直接使用$model,
$model->fieldX 无法拿到，即使定义了 getFieldXAttr 方法。
应该是create 方法时未读取数据库所有字段，$model->data 中没有fieldX。
大部分情况下是没关系的，但是这个findX一旦拿不到就不好找到这个原因。
我目前的解决办法是，在create成功后再重新get一次。
希望可以改进一下。

**Comment by liu21st** [comment]
数据应该都在模型中设置传入 （包括修改器） 而不要依赖数据库的默认值
