### ISSUE TITLE
路由解析问题

### ISSUE THREAD

**Issue by QThans** [top-think/framework#1607]
Route::resource('menu', 'admin.menu');
Route::get('menu/create/[:pid]', 'admin.menu/create');
如果先定义资源路由，再定义一个路由。会导致资源路由的url生成出问题

**Comment by QThans** [comment]
Route::group('menu',function (){
        Route::get('create/[:pid]', 'admin.menu/create');
    });
增加一个分组就正常。分组冲突？

**Comment by liu21st** [comment]
你单独定义的路由设置下路由标识 否则路由标识就冲突了
