### ISSUE TITLE
composer加载缺陷

### ISSUE THREAD

**Issue by JerryChaox** [top-think/framework#1611]
删除根目录的think文件夹后会导致composer到项目的上层目录寻找vendor文件夹，从而导致无法正常加载类库，建议修改确定根目录的方法

**Comment by JerryChaox** [comment]
删除根目录的think文件夹后会导致composer到项目的上层目录寻找vendor文件夹，从而导致无法正常加载类库，建议修改确定根目录的方法

**Comment by masterZSH** [comment]
在public/index.php加个
`
defined('VENDOR_PATH','你的vendor目录路径');
`
试试
