### ISSUE TITLE
 thinkphp5.1.32 cli 模式下 mysql has gone away 

### ISSUE THREAD

**Issue by qihuantian1** [top-think/framework#1612]
问题： thinkphp5.1.32 cli 模式下 mysql has gone away ， 数据库开启 自动重连，无效

场景： think-queue 配合 supervisor 使用下， 一段时间（3600S） 后，提示mysql has gone away， 一直重复执行。

伤害： think-queue用来做短信队列， 是先发送短信后记录结果， 结果在数据库连接失败后，一直重复执行redis队列， 导致几个小时发送了几万条短信

希望： 希望官方重视这个bug，尽快修复。

版本： thinkphp 5.1.32 think-queue 2.0.4

详细代码说明： 
    public function fire( Job $job, $data )
    {
        $isJobDone = $this->doSendSms($data);
        if ( $isJobDone['code'] == 1 ) {
            $job->delete();
              .........

     private function doSendSms( $data = [] )
    {
        try {
            $res = $sms->send(.......);
            if ( $res ) {
                $this->saveLog($data['orgData']);
                return [ 'code' => 1, 'message' => '' ];
            }

在 $sms->send 后 由于$this->saveLog 需要链接数据库，提示数据库 has gone away， 又不能重新连接上, 所以 supervisor 一直不停的执行上面的 fire 方法 导致不停发送短信

**Comment by lw78665806** [comment]
你需要在database配置文件中增加
// 是否需要断线重连
'break_reconnect' => true,
// 断线标识字符串
 'break_match_str' => [
        '2006'
]

**Comment by qihuantian1** [comment]
断线配置已经增加过了， 标识也增加了， 但是还是不行

**Comment by pxc1993** [comment]
是的，这个问题如果开启日志记录，会增加日志空间

**Comment by HubQin** [comment]
这个问题解决了吗？我今天也遇到：SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**Comment by Funny-dot** [comment]
2020-08-27 这个问题还是没解决。

**Comment by codekissyoung** [comment]
2020-09-25 这个问题还是没有解决！

**Comment by HubQin** [comment]
按lower21的方法可以，记录下解决方法：https://learnku.com/articles/47507
