### ISSUE TITLE
上传文件时临时生成的tmp文件不会自动删除

### ISSUE THREAD

**Issue by zhang4034** [top-think/framework#1613]
上传文件时临时生成的tmp文件不会自动删除，如果没有设置upload_tmp_dir，windows服务器会自动将tmp临时文件存储到C盘的C:\Users\Administrator\AppData\Local\Temp目录下，导致占用C盘空间

**Comment by orchie** [comment]
我记得这是windows负责清除的，与windows的设置有关系

**Comment by jin123456bat** [comment]
系统负责清理，清理时间为系统重启的时候

**Comment by kinosang** [comment]
@zhang4034 所以系统提供了自行调整清理策略的选项

另外 upload tmp 是 PHP 控制的，框架干涉不到的

**Comment by jin123456bat** [comment]
> > 系统负责清理，清理时间为系统重启的时候
> 
> 服务器怎么可能每天都重启呢？那假如说服务器不重启，这些文件就删除不掉了？
@zhang4034 临时文件框架不好删除，因为你不知道人家的代码是怎样的，什么时候代表利用完毕？所以需要手动来删除，代码中利用完毕后手动删除
