### ISSUE TITLE
[bug]按文档走配置多语言不生效

### ISSUE THREAD

**Issue by orchie** [top-think/framework#1614]
### 文档
https://www.kancloud.cn/manual/thinkphp5_1/354119
### 流程
> 如果不希望浏览器自动侦测语言，请关闭lang_switch_on后设置默认语言。

根据数据库配置设定语言  所以不需要 自动检测 
'lang_switch_on' => false,   
然后 在控制器中设置 
```
config('default_lang','zh-tw');
trace(config('default_lang'));//此时是 zh-tw 
```

> 系统会默认加载下面三个语言包：
框架语言包: thinkphp\lang\当前语言.php
应用语言包: application\lang\当前语言.php
模块语言包: application\模块\lang\当前语言.php 

为方便复用 自定义语言包 我放到 
```
application\lang\zh-cn.php
application\lang\zh-tw.php
```
调用 lang('password wrong');

#### 错误的结果
返回 密码错误 而不是 密碼錯誤
### 参考其他用户
> 如果你还需要加载其他的语言包，可以在设置或者自动检测语言之后，用load方法进行加载

文档中有用户评论  
![image](https://user-images.githubusercontent.com/29848298/51222484-e9c0b000-1978-11e9-96f6-60e973e91bc7.png)
于是我尝试 
```
        Lang::load( '../application/lang/zh-tw.php', 'zh-tw');
        Lang::range('zh-tw');
        //config('default_lang','zh-tw');
        trace(config('default_lang'));//此时是 zh-cn
```
在 手动加载后生效了  
根据 上面用户的说法是
> 在$_GET没有lang参数情况下，框架某些地方还有检测，导致Lang类中的range还是zh-cn

所以怀疑是一个bug 
### 希望tp越来越好

**Comment by liu21st** [comment]
你在控制器里面设置的时候 语言包已经不会自动加载了的 需要设置就要在公共文件里面或者行为里面设置

**Comment by orchie** [comment]
> 你在控制器里面设置的时候 语言包已经不会自动加载了的 需要设置就要在公共文件里面或者行为里面设置

公共文件肯定不行因为要判断  
这样的话就只能走中间件或者钩子了对吧
谢刘总~ ：）
