### ISSUE TITLE
unique验证问题, 而且似乎存在很久了

### ISSUE THREAD

**Issue by t9044** [top-think/framework#1620]
验证器unique是支持复杂验证条件的, 例如
`'name'   => 'unique:user,status=1'`
那么理想情况下生成的查询条件应该是这样
`"name={$data['name']}&status=1"`
但是实际上生成的查询条件变成这样
`['status=1', '=', $data['name']]`, 这样就被模型类表达式错误了

所以验证器的unique的复杂验证条件其实是根本用不了的, 而且这个问题我在文档上看到一年前就有人提出了, 但是一直没人解决?
代码上也定位到了, 是由于在判断是否为负责验证条件时, 把其他条件当成了需要判断的字段, 具体代码是
`$key = isset($rule[1]) ? $rule[1] : $field;`

**Comment by liu21st** [comment]
我看了下代码 似乎5.1把这个功能废弃了 然后文档可能是旧的，刚恢复了下
