### ISSUE TITLE
Thinphp5.1版本，事务有一个bug

### ISSUE THREAD

**Issue by wangdasheng** [top-think/framework#1622]
在事务中有查询语句会导致整个事务失败，没有任何异常，且执行了事务提交代码。但事务并未生效，数据库没有写入任何数据。
类似伪代码：
// 启动事务
Db::startTrans();
try {
    Db::table('think_user')->find(1);
   $ex=db('think_ex')->select(3);
    Db::table('think_user')->delete(1);
    // 提交事务
    Db::commit();
} catch (\Exception $e) {
    // 回滚事务
    Db::rollback();
}

不知道是不是db这个助手函数导致产生了新的数据库连接影响的。
我原来使用的5.0版本，同样的代码没有任何问题。
由于上次模块代码漏洞导致服务器被注入攻击才选择升级了5.1为了以后方便升级打补丁。
最后建议大家不到万不得已千万别从5.0升级到5.1，当初这个错误的选择我改了半个月代码，都是白费的功夫，现在还有各种坑。切记！切记！切记！

**Comment by liu21st** [comment]
这不是BUG db助手函数每次都会重新连接 所以不是同一个数据库连接 事务是无效的

**Comment by wangdasheng** [comment]
> 这不是BUG db助手函数每次都会重新连接 所以不是同一个数据库连接 事务是无效的
@liu21st 
不能这样说，虽然db函数是产生了一个新连接，问题是它并没有做增删改操作，只是用于查询数据。这种业务场景很多，操作了某些数据后，需要在查询某些数据进一步进行操作，实际场景会封装成很多方法复用，不会像上面的代码这么简单明了。退一步说就算是也要抛个异常吧，不然看打印日志都是OK的，但就是没有在数据库中写入数据。不瞒你说，这个问题我找了一天。5.0的版本是没有任何问题
