### ISSUE TITLE
路由和url生成的一个bug

### ISSUE THREAD

**Issue by molong** [top-think/framework#163]
>$route['home/article/index'] = 'home/content/index?model_id=2';
>\think\Route::rule($route);
>echo url('home/content/index?model_id=2&id=12');

输出结果：

> 打印出的是：/home/content/index/model_id/2/id/12.html
> 真正的应该是：/home/article/index/id/12.html

**Comment by molong** [comment]
@liu21st

**Comment by liu21st** [comment]
感谢反馈 已经修正！

**Comment by molong** [comment]
@liu21st 这个这样修正之后还会存在一个问题

> $route['home/article/index'] = 'home/content/index?model_id=2';
> $route['home/photo/index'] = 'home/content/index?model_id=3';
> \think\Route::rule($route);
> echo url('home/content/index?model_id=3&id=12');

输出结果

> 打印出的是：/home/article/index/id/12.html
> 真正的应该是：/home/photo/index/id/12.html

**Comment by liu21st** [comment]
现在可以了

**Comment by molong** [comment]
>             if (!empty($param) && array_intersect_assoc($param, $array) === $param) {
                $match = false;
                $vars = array_diff_key($array, $param);
                return $url;
            }
            if ($match) {
                $vars = array_diff_key($array, $param);
                return $url;
            }


这样改是对的，应该
