### ISSUE TITLE
5.2版本的乐观锁实现不正确

### ISSUE THREAD

**Issue by NHZEX** [top-think/framework#1632]
https://github.com/top-think/framework/blob/a2f50402bea428bab834d05e7047612f15ea7623/src/think/model/concern/OptimLock.php#L112-L122

乐观锁的版本比对应该在数据引擎层面处理（比如通过Where参数判断），而不应该在代码层处理（比如在语句执行前去查询版本），增加了不必要的数据库开销到头还没能起到保护作用。
@liu21st 

示例：```UPDATE admin_user  SET status = 0 , lock_version = 3 , update_time = 1548314281  WHERE (  id = 109  AND lock_version = 2 ) AND admin_user.delete_time = '0'```

当前版本只能保护“ ORM读 -> 业务处理 -> ORM编译语句前”，对 “ ORM编译语句 -> SQL 执行 ”时间内并没有起到保护作用。
如果与事务一起执行也是无效([详情](https://github.com/top-think/framework/issues/1632#issuecomment-457263985))，最终结果只会互相覆盖。

**Comment by momoca** [comment]
你用了事务还用乐观锁有啥用呢？乐观锁就是为了解决长事务的问题。
你可以先阅读一下百度百科：https://baike.baidu.com/item/%E4%B9%90%E8%A7%82%E9%94%81/7146502

另外如果高并发的话。数据在读写数据时也是有锁的。如果是a和b同时，执行sql也是要有先后顺序的。哪么a或b有一个成功后ver就是3另一个写入的条件ver=2就失败了。

btw你可以阅读一下：https://www.cnblogs.com/sheseido/p/5038562.html

**Comment by NHZEX** [comment]
> 你用了事务还用乐观锁有啥用呢？乐观锁就是为了解决长事务的问题。
> 你可以先阅读一下百度百科：https://baike.baidu.com/item/%E4%B9%90%E8%A7%82%E9%94%81/7146502
> 
> 另外如果高并发的话。数据在读写数据时也是有锁的。如果是a和b同时，执行sql也是要有先后顺序的。哪么a或b有一个成功后ver就是3另一个写入的条件ver=2就失败了。
> 
> btw你可以阅读一下：https://www.cnblogs.com/sheseido/p/5038562.html

事务只是一个举例（也为不太正确），但不能否认官方当前提供的乐观锁实现有问题。并不是太高where实现的，而是在写入前去查询版本是否发生变化。

**Comment by NHZEX** [comment]
> > 你用了事务还用乐观锁有啥用呢？乐观锁就是为了解决长事务的问题。
> > 你可以先阅读一下百度百科：https://baike.baidu.com/item/%E4%B9%90%E8%A7%82%E9%94%81/7146502
> > 另外如果高并发的话。数据在读写数据时也是有锁的。如果是a和b同时，执行sql也是要有先后顺序的。哪么a或b有一个成功后ver就是3另一个写入的条件ver=2就失败了。
> > btw你可以阅读一下：https://www.cnblogs.com/sheseido/p/5038562.html
> 
> 事务只是一个举例（也为不太正确），但不能否认官方当前提供的乐观锁实现有问题。并不是通过where实现的，而是在写入前去查询版本是否发生变化。


> 你用了事务还用乐观锁有啥用呢？乐观锁就是为了解决长事务的问题。
> 你可以先阅读一下百度百科：https://baike.baidu.com/item/%E4%B9%90%E8%A7%82%E9%94%81/7146502
> 
> 另外如果高并发的话。数据在读写数据时也是有锁的。如果是a和b同时，执行sql也是要有先后顺序的。哪么a或b有一个成功后ver就是3另一个写入的条件ver=2就失败了。
> 
> btw你可以阅读一下：https://www.cnblogs.com/sheseido/p/5038562.html

我描述的事务例子具体是这样的：
***其实有没有事务不是关键，核心是更新条件没有包含`id=1 AND ver=x`，这个就是当前版本实现的问题，版本检查在代码中完成！！***

| * | 会话S1 | 会话S2 | * |
| - | - | - | - |
| T0 | SELECT * FROM test WHERE id = 1; | SELECT * FROM test WHERE id = 1; | name = 0，ver = 10, ThinkORM 保存版本 |
| T0 | 业务处理。。。 | 业务处理。。。 |  |
| T0 | 发起更新 set name = 123 | 发起更新 set name = 789 | 两者的版本都为 10 |
|  | 模型查询id=1的ver是否发生变化 | 模型查询id=1的ver是否发生变化 | 两种都通过模型的乐观锁验证 |
| T1 | BEGIN | \ |  |
| T2 | UPDATE test SET `name` = '123', `ver` = 11 WHERE id = 1; | \ |  |
| T3 | \ | UPDATE test SET `name` = '789', `ver` = 11 WHERE id = 1; | 会话S2会被S1的事务阻塞，但最终都能成功执行 |
| T4 | COMMIT | \ |  |
| T5 | SELECT * FROM test; | \ | name = 789，按照时间轴来说并不是123，而且并不会抛出如何异常 |

**Comment by momoca** [comment]
我仔细想了一下。虽说你说的是有道理。
但我又仔细阅读了model.php它在插入或更新时的checkData都会startTrans/commit。知道吧。所有以不写在where里也是没问题的。

但我必须吐槽一下。这里竟然直接写$_SESSION了？不是应该Container::pull('session')么？
就算取消了session前缀是不是应该也要统一一下好吧。

**Comment by NHZEX** [comment]
> 我仔细想了一下。虽说你说的是有道理。
> 但我又仔细阅读了model.php它在插入或更新时的checkData都会startTrans/commit。所有以不写在where里也是没问题的。如果你真的担心可以在save的where添加ver的条件呀。
> 
> 但我必须吐槽一下。这里竟然直接写$_SESSION了？不是应该Container::pull('session')么？
> 就算取消了session前缀是不是应该也要统一一下好吧。

具体哪行？
我又确认了下比对锁版本并没有包含在事务中。

checkData在事务执行前
https://github.com/top-think/framework/blob/a2f50402bea428bab834d05e7047612f15ea7623/src/think/Model.php#L485-L495
事务执行在
https://github.com/top-think/framework/blob/a2f50402bea428bab834d05e7047612f15ea7623/src/think/Model.php#L555-L562

**Comment by momoca** [comment]
恩，我理解你的意思。等官方解答吧。

**Comment by liu21st** [comment]
@NHZEX 改进了一个版本
