### ISSUE TITLE
Request->path() url参数问题

### ISSUE THREAD

**Issue by essaying** [top-think/framework#1636]
`public function path()
    {
        if (is_null($this->path)) {
            $suffix   = $this->config['url_html_suffix'];
            $pathinfo = $this->pathinfo();
            if (false === $suffix) {
                // 禁止伪静态访问
                $this->path = $pathinfo;
            } elseif ($suffix) {
                // 去除正常的URL后缀
                $this->path = preg_replace('/\.(' . ltrim($suffix, '.') . ')$/i', '', $pathinfo);
            } else {
                // 允许任何后缀访问
                $this->path = preg_replace('/\.' . $this->ext() . '$/i', '', $pathinfo);
            }
        }
        return $this->path;
    }`

` $this->path = preg_replace('/\.(' . ltrim($suffix, '.') . ')$/i', '', $pathinfo);`

这段是不是有问题?
当url地址为admin/index.html?name=abc时会导致action名称取到index.html, 没有去掉.html后缀

**Comment by essaying** [comment]
@liu21st

**Comment by liu21st** [comment]
检查你是否设置了伪静态后缀

**Comment by essaying** [comment]
设置了, 但是走到上面那个正则是不会去掉.html后缀的, 如果没有接问号的话就可以正常访问
