### ISSUE TITLE
域名路由使用IP+端口或域名+端口时不能绑定到对应模块

### ISSUE THREAD

**Issue by sscsdl** [top-think/framework#1644]
路由：
Route::domain('192.168.1.123:8001', 'module1')->append(['site' => 'ip+8001']);
Route::domain('xxx.com:8002', 'module2')->append(['site' => 'domain+8002']);

使用 192.168.1.123:8001 或 xxx.com:8002 都只会访问到index模块

**Comment by gitee1** [comment]
@sscsdl 请问解决了吗？
