### ISSUE TITLE
getLastSql存在异常

### ISSUE THREAD

**Issue by viphackl** [top-think/framework#1656]
https://github.com/top-think/framework/blob/98af9cd4f6da08168fd83045f52111f15ef85b20/library/think/db/Connection.php#L1476

此处strops在查找SQL是如果不存在?，返回false,substr_replace强制转换为0导致获取SQL异常。
如：
$result     =   $this->db->execute("delete from log_notice where id=12", []);
$this->db->getLastSql();

返回值为：
'3'elete from log_notice where id=12

'3'不知道这个'3'怎么来的

**Comment by viphackl** [comment]
这样？
$sql = is_numeric($key) **&& strpos($sql, '?') !== false** ?
            substr_replace($sql, $value, strpos($sql, '?'), 1) :
            str_replace(
                [':' . $key . ')', ':' . $key . ',', ':' . $key . ' '],
                [$value . ')', $value . ',', $value . ' '],
                $sql . ' ');

**Comment by liu21st** [comment]
什么版本？

**Comment by liu21st** [comment]
这种写法的前提就是前面的is_numeric($key)判断 如果你出错了 说明你的参数绑定是不合法的 参数绑定如果为空是不会进入循环执行的，你的问题估计是因为把Query对象赋值了 然后重复操作 导致参数绑定数据没有清空
