### ISSUE TITLE
异常类 think\exception\TemplateNotFoundException 冲突

### ISSUE THREAD

**Issue by bestways** [top-think/framework#1657]
Warning: Ambiguous class resolution, "think\exception\TemplateNotFoundException" was found in both "/vendor/topthink/think-template/src/exception/TemplateNotFoundException.php" and "/vendor/topthink/think-view/src\exception\TemplateNotFoundException.php", the first wi ll be used.

**Comment by bestways** [comment]
其他composer包存在类似问题，命名空间建议采用：
think\template\exception\TemplateNotFoundException
think\view\exception\TemplateNotFoundException

**Comment by liu21st** [comment]
已经改进
