### ISSUE TITLE
think\db\Query bug

### ISSUE THREAD

**Issue by uuling** [top-think/framework#166]
Query.php 类中的 query ，execute方法中 的$fetch参数多余，应该去掉

Query.php `public function query($sql, $bind = [], $fetch = false, $master = false, $class = false)`
`public function execute($sql, $bind = [], $fetch = false, $getLastInsID = false, $sequence = null)`
Connection.php `public function execute($sql, $bind = [], $getLastInsID = false, $sequence = null)`

@liu21st

**Comment by uuling** [comment]
Connection.php. 中的query  execute 中没有$fetch 参数

**Comment by liu21st** [comment]
感谢反馈 已经修正
