### ISSUE TITLE
分页各种报错

### ISSUE THREAD

**Issue by wolf-leo** [top-think/framework#1660]
有的方法要不是本该传int的 结果传了string ，要不是本该传string的 结果传了int
涉及到的文件有  
Bootstrap.php、Paginator.php、Url.php

**Comment by wolf-leo** [comment]
版本5.2最新

**Comment by liu21st** [comment]
你给出一个实例代码吧

**Comment by wolf-leo** [comment]
$page = input('page', 1);
$pageSize = 5; //每页显示的数量
$pageparam 打印值
array(2) {
  ["query"] => array(0) {
  }
  ["path"] => string(20) "/admin/article/index"
}
$list 文章列表
$count 7 足以分页
传入Bootstrap
$Page = new \think\paginator\driver\Bootstrap($list, $pageSize, $page, $count, FALSE, $pageparam);
提示：
[0] TypeError in Bootstrap.php line 198
Argument 2 passed to think\paginator\driver\Bootstrap::getPageLinkWrapper() must be of the type integer, string given, called in D:\phpStudy2018\PHPTutorial\WWW\blogtp52\vendor\topthink\framework\src\think\paginator\driver\Bootstrap.php on line 51

**Comment by liu21st** [comment]
为啥要这样使用分页， 直接用数据库的分页方法查询啊

**Comment by wolf-leo** [comment]
查询分页数据没问题 - -  主要是要用到分页样式

**Comment by liu21st** [comment]
分页样式是通过配置参数 自动处理的 不需要手动实例化 而且默认就是bootstrap驱动

**Comment by wolf-leo** [comment]
Db::name('article')->where(‘status’,1)->paginate(5);
[2] ErrorException in Paginator.php line 147
count(): Parameter must be an array or an object that implements Countable

**Comment by wolf-leo** [comment]
之前5.1都是继承Bootstrap自己写样式了 - - 忘了框架有集成分页功能了 也就没用了  5.2用到Bootstrap发现错误...
