### ISSUE TITLE
注解路由无效

### ISSUE THREAD

**Issue by RuizhaoLee** [top-think/framework#1663]
### 环境：
- PHP7.2
- THINKPHP 5.1

#### 问题描述：
在controller目录下创建的控制器，通过注解路由可以正常访问，但是如果控制器是在controller下的** 其他 ** 目录下，就不能访问了。

![image](https://user-images.githubusercontent.com/35215628/53297228-1b6d4680-3856-11e9-97ae-a3833ed2b195.png)

如图所示：
- wechat-side-access 路由是在index/WeChat/wechatAccess下，可以正常访问；
- wechat-side-access-1  路由是在index/wechat\access.Access/wechatAccess 下，就不能访问了；

### 报错截图
![tim 20190224170759](https://user-images.githubusercontent.com/35215628/53307856-7c892e80-38d7-11e9-99a8-7dde15c89968.png)

似乎是没把这个控制器当控制器载入，当成普通类库加载了

**Comment by liu21st** [comment]
路由定义明显有问题的 怎么会有 \ 呢
