### ISSUE TITLE
ThrowableError无法捕获异常

### ISSUE THREAD

**Issue by jadechenlei** [top-think/framework#1671]
用原生的\Exception也无法铺获
`      //exception('异常消息', 10006);  #手动抛出的，可以正常铺获`
`$user = SysVersion::get(20); #主键不存在，所以下面的delete抛出ThrowableError。但调用处却无法铺获`
`$user->delete();`

**Comment by liuwave** [comment]
是哪个版本呢？

**Comment by jadechenlei** [comment]
版本号：V5.1.35 LTS
调用处代码如下
`try {`
`app('logic命名空间路径')->add(input());#正常情况下可成功调用，所以排除路径错误的可能`
`} catch (\Exception $e) {`
`$this->error($e->getMessage());`
`}`
