### ISSUE TITLE
tp5.1 - db() 强制重新连接=true 导致事务无法使用

### ISSUE THREAD

**Issue by RelicOfTesla** [top-think/framework#1672]
如题。
db() tp5.1强制开新链接$force=true。 git版本修改于2016年8月9日.
db() tp5.0强制开新链接$force=false。git版本修改于2016年8月9日.
5.2干脆就没有db()函数了。。。
表示一脸懵逼。。同一天上传的版本，为什么要打架。。到底要用哪一个。
链接复用有什么不好，表示大量代码全是db(xxxx)而不是new XXXXModel的，这样情何以堪。。

**Comment by RelicOfTesla** [comment]
db()->startTrans()
...
db()->commit()
无效。
tp5.1会导致事务功能无法正常使用。

**Comment by liu21st** [comment]
db助手函数有参数可以控制是否重连的 你可以在项目里面重新定义db助手，没必要抱怨 之所以这么做 因为有很多新手奇葩的用法 所以建议还是用Db类静态方法吧
