### ISSUE TITLE
控制器中使用__call()魔术方法不生效

### ISSUE THREAD

**Issue by jadechenlei** [top-think/framework#1674]
版本：V5.1.35 LTS
访问路径是 “xxx.com/system/Test/add”
Test控制器中add方法不存在，但是代码走不到__call()中；页面依然抛出异常
`Method app\system\controller\SysVersion::add() does not exist`

**Comment by lw78665806** [comment]
底层用的反射机制，还没执行到你的controller里__call()当然不会执行
想实现__call()，可以使用_empty()空操作

**Comment by liu21st** [comment]
不建议使用 用分组的MISS路由控制
