### ISSUE TITLE
5.0 between time 兼容

### ISSUE THREAD

**Issue by callmez** [top-think/framework#1679]
在5.0都能解析该语法, 5.1之后 between time 就解析不了了 
```php
$where = [
    'user' => 1001,
    'create_time' => ['between time', ['1551369600', '1554047999']]
]
$query->where($where)->find();
```

**Comment by liu21st** [comment]
仔细看5.1的升级指导 5.1的查询语法和5.0是不兼容的

**Comment by callmez** [comment]
先别急着关, 升级指导没有给出这块的指导. 只能去看语法文档找方法.
 在使用`Where`类之后可以正确装换.
我觉得还是框架对语法支持的深度问题. 如果这两个语法一致那是最好的.

如果还是确定不支持此兼容的话. 那我就贴出解决方案吧.  

```php
// 5.0 可用
$where = [
    'user' => 1001,
    'create_time' => ['between time', ['1551369600', '1554047999']]
]
// 5.1 可用
$where = new Where();
$where['uid'] =1001;
$where['create_time'] = ['between time', ['1551369600', '1554047999']];
$query->where($where)->find();
```

**Comment by callmez** [comment]
在说明下 Where对升级兼容性的问题不足之处.

很多5.0的项目 都是 直接定义了数组  `function getXXBy($where = [])`, 所以这块的代码要升级
成本是很大的.  

虽然`Where`都已经是`ArrayAccess`了, 在代码可理解性上是不如原生数组的.  

还是肯定官方在这里做下兼容考虑.

**Comment by momoca** [comment]
升级文档写的很清楚了。如果要升级有些痛苦是必须要承担的。
更何况除了数据库。5.0和5.1其它地方也有不少差距呢。
