### ISSUE TITLE
路由不存在时,全局中间件不执行

### ISSUE THREAD

**Issue by hellolxc** [top-think/framework#1681]
## 问题描述
路由不存在时，全局中间件不执行，直接抛出错误“模块不存在”

## 版本
- Thinkphp:V5.1.35
- PHP:PHP7.1

## 代码示例

```php
//路由注册
Route::get('oss', function () {
    return 'oss';
});
```
### 生成中间件
```bash
php think make:middleware Auth
```
### 应用目录下全局中间件
在应用目录的middleware.php文件注册全局中间件
```php
return [
	\app\http\middleware\Auth::class,
];
```

## PostMan中用POST/OPTIONS等方式访问http://test.com/oss
报错： 模块不存在:oss

### 全局异常处理
- 未开强制路由的情况下:在全局异常拦截的地方(此处需要自己定义)，检测HttpException异常，如果是HttpException并且method是OPTIONS,则返回200,
- 开启强制路由还需要拦截RouteNotFoundException异常

**Comment by jin123456bat** [comment]
miss路由了解一下
