### ISSUE TITLE
url生成参数不支持url地址 

### ISSUE THREAD

**Issue by RelicOfTesla** [top-think/framework#1702]
echo url('/index/user/login', [
			'callback'=>'http://www.baidu.com'
		]);
生成网址为
/index/user/login/callback/http%3A%2F%2Fwww.baidu.com.html

这种网址是无意义的，%2F%2F会重新转义成/参数
也就是，重新会被路由解析器，解析成参数http://xxxx/key1/value1/key2/value2
```
public function login($callback){
		echo $callback;
	}
```
实际打印出的是http:
而不是http://www.baidu.com

**Comment by liu21st** [comment]
原因你仔细想想就明白了 你可以改成普通参数传参

**Comment by RelicOfTesla** [comment]
原因问题中已说明了，你不要回复没意义的回复！
问题不在于传参，而在于url()生成的网址是不可用的！！
用个url参数生成都这么闹心，关键在于url()生成是没有选项选择是否禁用路由模式的，必须url()执行前，强制改禁用全局配置

**Comment by liu21st** [comment]
url_common_param配置本来就是全局的 非路由变量根本不需要使用pathinfo地址

**Comment by RelicOfTesla** [comment]
我就想问，怎么传网址参

**Comment by tekintian** [comment]
> 我就想问，怎么传网址参，怎么生成。你不能拒绝这种基础需求。

人家没有义务非要告诉你的! 能自己解决就自己解决吧.

**Comment by momoca** [comment]
base64

**Comment by RelicOfTesla** [comment]
> base64

base64会导致安全验证函数被跳过的哦，这不是好方案

**Comment by tekintian** [comment]
> > base64
> 
> base64会导致安全验证函数被跳过的哦，这不是好方案

先BASE64， 然后在接收的时候使用正则检查一下就OK了
