### ISSUE TITLE
v5.1.35 模型中使用$model->isUpdate(false)->save($data)一次循环插入多条数据的时候引起主键冲突的问题

### ISSUE THREAD

**Issue by vongele** [top-think/framework#1708]
这种写法会报错
`
foreach($datas as $data){
$model->isUpdate(false)->save($data)
}
`
这种写法可以
`
foreach($datas as $data){
$model->isUpdate(false)->data($data)->save()
}
`
查看源码发现
![image](https://user-images.githubusercontent.com/22783626/54739277-7e05f800-4bf2-11e9-97ba-41e322f237e5.png)
使用checkbeforesave方法给this->data赋值的时候没有清空this->data，所以上一次插入的所以字段值都存在，引起错误的lastinsertid的值也在，同时下一次插入会保留上一次插入的所有字段值，除非你覆盖他，这是坑啊
加上这个就没问题了
```
//model.php
protected function checkBeforeSave($data, $where)
    {
        $this->exists or $this-data = []; //加上这个判断
        if (!empty($data)) {
            // 数据对象赋值
            foreach ($data as $key => $value) {
                $this->setAttr($key, $value, $data);
            }

            if (!empty($where)) {
                $this->exists      = true;
                $this->updateWhere = $where;
            }
        }

        // 数据自动完成
        $this->autoCompleteData($this->auto);

        // 事件回调
        if (false === $this->trigger('before_write')) {
            return false;
        }

        return true;
    }
```

**Comment by liu21st** [comment]
本来就不建议你这种写法

**Comment by vongele** [comment]
> 本来就不建议你这种写法
$model->isUpdate(false)->data($data)->save() 这种写发又可以，感觉很多人会踩坑，不修复下么

**Comment by liu21st** [comment]
问题是你这种方式修正 影响了原有的数据 岂不是又有新的坑，要清空数据也是让用户自己在循环中清理，或者使用insertall方法

**Comment by momoca** [comment]
我感觉也是。原来model设计并没有问题。可能是 @vongele 还不太适应吧。
但看云上的thinkphp文档我必须吐槽一下，5.1的文档有部分交代的不清楚。如果从3.0、5.0一路看过来是没有问题的。但如果只看5.1可能就不好理解拉。 @liu21st 希望在5.2时的文档做的好些呀。

**Comment by liu21st** [comment]
@momoca 感谢建议，我们会在写新手册的时候尽量注意

**Comment by momoca** [comment]
举个例子：
5.0的https://www.kancloud.cn/manual/thinkphp5/158834
5.1的https://www.kancloud.cn/manual/thinkphp5_1/518749
···
$request = Request::instance();
echo "当前模块名称是" . $request->module();
echo "当前控制器名称是" . $request->controller();
echo "当前操作名称是" . $request->action();
···
这些在5.1文档就完全找不到。但实际是有的。
