### ISSUE TITLE
关于请求参数的问题请教

### ISSUE THREAD

**Issue by slmhvip** [top-think/framework#171]
如果URL为 www.abc.com/vara/a.html 时，

默认get请求下 $this->request->get('vara') 为空

但 $this->request->param('vara') 为 a;

但如果URL为 www.abc.com/?vara=a 时

以上都为 a 

如果使用 url 函数生成的话都会是第一种形式，在这种情形下，我是否都需要使用 $this->request->param('vara') 去获取参数？

**Comment by slmhvip** [comment]
// 设置当前请求的参数
        Request::instance()->param(array_merge($var, $_GET));

**Comment by liu21st** [comment]
建议统一使用param方法获取当前请求的参数 而 get只会获取$_GET数组的参数 而不会包含pathinfo的参数

**Comment by terranc** [comment]
@liu21st 这个逻辑貌似和以前3.2的不同
