### ISSUE TITLE
5.2-rc1 自动多应用模式下部分对象(cookie)无法正常读取应用配置问题.

### ISSUE THREAD

**Issue by watermelon322** [top-think/framework#1711]
在自动多应用模式下cookie对象在执行Http::parseMultiApp之前就已经由Request对象初始化注入。
使用系统注入Cookie对象无法应用正确的配置，只有新创建Cookie对象的配置是读取正确。
同理在所有Http::parseMultiApp之前初始化注入的对象都无法应用正确的配置。

不动framework代码的解决方案：
1. 创建父控制器，所有应用控制器继承它。
2. 在此控制器 initialize 方法中增加 $this->app->delete('cookie');, 如有其他对象一起删除

目前发现以下5个配置在Http::parseMultiApp之前读取
app,default_lang
app.lang_switch_on
app.default_timezone
route
cookie
log

**Comment by liu21st** [comment]
Cookie、Log对象都调整过了
