### ISSUE TITLE
'\r\n'替换成PHP_EOL

### ISSUE THREAD

**Issue by SeasClouds** [top-think/framework#1713]
日志文件写入使用 '\r\n' 在linux下日志有 ^M 标记，是不是可以使用 PHP_EOL

**Comment by hainuo** [comment]
感觉可以，但是多平台又会引申出同样的问题。 比如： windows 的日志拿到 mac 或 linux 上分析    mac 或linux 的日志拿到 windows 下 分析 感觉这块还得另行处理才可以   。这块的工作不应该是框架来做 应该由 数据分析系统来做
