### ISSUE TITLE
withJoin的关联函数不支持附加条件

### ISSUE THREAD

**Issue by RelicOfTesla** [top-think/framework#1718]
```
class xxmodel extend Model {
  function someStatus(){
      return $this->hasOne('xxx')->where('status', 1111)->where('xxx',2222)
  }
}
/////////////
echo xxmodel::withJoin('someStatus')->fetchSql()->select();
```
where等附加条件在withJoin()中被过滤了。
而使用with()表示结果正常，where有正常触发。

这样表示，不少withJoin语句，需要外层重写where，（withJoin(['xx'=>function($q){$q->where()->where()}, 'bb'=>function($q){}]）
如果我withJoin表多的情况下，极其难以使用。

**Comment by RelicOfTesla** [comment]
## p2
withJoin生成的jon xx on xx=xx 后面也无法附加其他left join xxx on xxx and xxx and ...仅支持单条件.
哪怕后面附加where，也是默认会把条件扔到where语句中。
会产生一定的局限性，因为inner join扔到where没问题 ，但left/right join还把条件扔到where中，会导致结果集不对。
如left join xxx on xxx.xxx_id = main.id and xxx.a = 'aaa' and xxx.b = 'bbb'
与left join xxx on xxx.xxx_id = main.id     where xxx.a = 'aaa' and xxx.b = 'bbb'
两个结果集是不一样的

**Comment by liu21st** [comment]
所以最好还是不要使用withJoin为好

**Comment by RelicOfTesla** [comment]
> 所以最好还是不要使用withJoin为好

你真棒！所以我是要with与withJoin功能直接干掉了不用咯。

**Comment by wxkxklmyt** [comment]
一对一关联with方法会导致如果A表关联条件为null，显示的时候会自动取B表的第一条数据，这样不符合业务规则

**Comment by lascyb** [comment]
> 所以最好还是不要使用withJoin为好

？？？？？？？？
