### ISSUE TITLE
6.0 composer 会出现一大堆错误提示

### ISSUE THREAD

**Issue by linjialiang** [top-think/framework#1720]
> 6.0 composer 会出现一大堆错误提示

![图片](https://user-images.githubusercontent.com/8848263/55043241-48d52c00-5070-11e9-84dc-79941f111a8f.png)
![图片](https://user-images.githubusercontent.com/8848263/55043253-57234800-5070-11e9-8f32-bc87fea8b743.png)
![图片](https://user-images.githubusercontent.com/8848263/55043265-62767380-5070-11e9-9585-36fb4041ce39.png)

**Comment by linjialiang** [comment]
> 我的php版本是：

![图片](https://user-images.githubusercontent.com/8848263/55043287-8043d880-5070-11e9-8cba-8eb8f9c0b766.png)

**Comment by liu21st** [comment]
已经修正过了，最近一段时间更新频繁，所以会有一些不稳定的情况出现

**Comment by linjialiang** [comment]
好的,老大辛苦了
