### ISSUE TITLE
count('DISTINCT user_id,time') 报"不支持的数据表达式"

### ISSUE THREAD

**Issue by SifuLi** [top-think/framework#1728]
[0] Exception in Mysql.php line 149

![TIM截图20190401171034](https://user-images.githubusercontent.com/10288368/55316478-12007b00-54a1-11e9-8e75-12d68c6264f0.png)

**Comment by liu21st** [comment]
聚合查询只支持一个字段，除非你使用Raw方式

**Comment by SifuLi** [comment]
好的
