### ISSUE TITLE
高精度定点数参数绑定底层直接float化,造成精度损失

### ISSUE THREAD

**Issue by jaya1992** [top-think/framework#1743]
![微信截图_20190403185017](https://user-images.githubusercontent.com/13504408/55522995-dab8e680-56b9-11e9-93f1-3ed69081c4ad.png)

我们程序中有小数点后16位的数据,但是框架底层做了处理,后面几位损失掉了,请问这种情况如何处理?是否只能写原生SQL,原生SQL支持TP事务吗?

**Comment by jaya1992** [comment]
@liu21st 请问 后期这个问题会做处理吗?

**Comment by liu21st** [comment]
这个不太好处理，PHP处理高精度数本来就不足，采用字符串方式是折中解决方案
