### ISSUE TITLE
tp6开启注解路由后， 程序报错

### ISSUE THREAD

**Issue by shulinqian** [top-think/framework#1752]
开启注解路由后， 程序报错
`
  [Error]                                     
  Call to a member function import() on null 
at /data/www/tp/tp/vendor/topthink/framework/src/think/Route.php:452
`
经查原因
think\Route.php
第179行 import里面调用了$this->ruleName,而 $this->ruleName在184行才赋值。。。

**Comment by liu21st** [comment]
已经修正，和注解路由无关，是路由缓存的问题
