### ISSUE TITLE
5.1 php think  报错

### ISSUE THREAD

**Issue by kwokzc** [top-think/framework#1758]
5.1核心下，在应用根目录执行 php think，按照手册会出现
>php think
Think Console version 0.1

实际报错
php think

Parse error: parse error, expecting `'&'' or `"variable (T_VARIABLE)"' in /Users/Kwok/git/kwok/thinkphp/library/think/Loader.php on line 391
---
执行其他命令也会报错，修改391行会报其他文件的错

**Comment by liu21st** [comment]
检查你的命令行php版本吧

**Comment by kwokzc** [comment]
> 检查你的命令行的PHP版本吧

感谢。添麻烦了。
