### ISSUE TITLE
cache 缓存获取反序列化问题

### ISSUE THREAD

**Issue by cys138138** [top-think/framework#1761]
测试环境 window php5.6 和centos php 7.3  调用缓存数组，自动使用序列化存储数据，获取缓存使用cache::get() 方式，返回结果是字符串（反序化失败），追踪源码，发现在 think/cache/driver/File.php 145 行 $content      = substr($content, 32); 这里截取 时候出问题，这里的长度算上换行符应该是34 修改源码如下 $content      = substr($content, 34);  才对，自身项目修复，建议官方测试一下改bug

**Comment by liu21st** [comment]
你确定？

**Comment by cys138138** [comment]
在centos +php7.3环境下问题问题很明显，另外获取缓存失效时间也是同样的问题

**Comment by momoca** [comment]
会不会是文件格式的问题.加了bom?所以差了2字节?

**Comment by cys138138** [comment]
这个应该不太可能，缓存文件本来就是框架自动生成的

**Comment by cys138138** [comment]
> 会不会是文件格式的问题.加了bom?所以差了2字节?

这个应该不太可能，缓存文件本来就是框架自动生成的

**Comment by momoca** [comment]
我建议你查一下.

**Comment by cys138138** [comment]
> 我建议你查一下.

这个建议可以试试，我直接改了官方这种截取方式了，不用数字节数，直接用字符串截取用了好久了
