### ISSUE TITLE
v6版本无法进行跨应用路由定义

### ISSUE THREAD

**Issue by citisoft** [top-think/framework#1770]
thinkphp6 路由无法进行跨应用路由定义

app目录下两个应用
```
index
  IndexController   /index/index/index
user
  IndexController   /user/index/index
  LoginController   /user/login/index
```
index 应用访问 user 应用的login控制器。
`
url('user/login/index')
`
无法将登录的路由 简化为  /login

类似这样的定义不生效
`
Route::get('login', 'user/login/index');
`
domain.com/login 直接 访问 user/login/index

**Comment by momoca** [comment]
没写全。https://www.kancloud.cn/manual/thinkphp6_0/1037497 请阅读:路由到类的方法
而且从5.0一直是这么规定的呀。

**Comment by citisoft** [comment]
楼上说法不准确。

采用的是多应用模式，每个应用的路由都是完全独立的，并且路由地址不能跨应用（除非采用重定向路由）。

https://www.kancloud.cn/manual/thinkphp6_0/1037494
