### ISSUE TITLE
> setJsonFieldType方法是用setFieldType方法替代了，文档已经修正

### ISSUE THREAD

**Issue by php4world** [top-think/framework#1775]
> setJsonFieldType方法是用setFieldType方法替代了，文档已经修正

update方法还是没有更正类型
```php
Db::name('sign_log')
    ->where('openid', $this->request->put('openid'))
    ->where('week_start', '>=', week()[0])
    ->where('week_start', '<=', week()[1])
    ->json(['signs'])
    ->setFieldType(['signs->d'.$w => 'int'])
    ->update(['signs->d'.$w => 1]);
```
//  结果，d6数据还是字符串"1"
{"d1": 0, "d2": 0, "d3": 0, "d4": 0, "d5": 0, "d6": "1", "d7": 0}

_Originally posted by @php4world in https://github.com/top-think/framework/issues/1774#issuecomment-487257653_

**Comment by liu21st** [comment]
已经修正
