### ISSUE TITLE
关联模型查询不支持model多级命名空间

### ISSUE THREAD

**Issue by hefy8655** [top-think/framework#1776]
![image](https://user-images.githubusercontent.com/39359122/56857245-ad501780-699d-11e9-9bfc-d0f8af7c126d.png)
model内分组后，用关联查询会报模型找不到

**Comment by hefy8655** [comment]
model内分组后，用关联查询会报模型找不到

**Comment by liu21st** [comment]
你这用法真搞笑，手册不看的？
