### ISSUE TITLE
tp5还能不用建立模型文件而直接使用模型吗？

### ISSUE THREAD

**Issue by caiweiming** [top-think/framework#178]
tp3可以直接M('User')来实例化没有创建模型文件的模型，并且自动对应think_user表，请问tp5有类似的方法吗？
我用model('user')来实例模型，但是没有建立模型文件，系统会报错。
是不是只能用Db::table('think_user') 方式来读取？

**Comment by momoca** [comment]
你试试不就知道了.(^+^)

**Comment by caiweiming** [comment]
试过了，在没有建立user模型文件的情况下，直接model('user')不可以，Db::table('think_user')这种方式就可以。

**Comment by lilwil** [comment]
你可以理解为Db::table('think_user')=M('think_user')

**Comment by caiweiming** [comment]
tp5已经没有M()函数了，而tp5里面，Db::table('think_user')和model('think_user')也是不一样的，Db::table('think_user')可以查询到数据，而model('think_user')会提示类不存在。

**Comment by liu21st** [comment]
当你真正了解TP5的模型之后 就不会这么想了，你要的也许只是 Db::name('User');

**Comment by kinosang** [comment]
TP5 的 Model 依赖于类文件，Db 不需要。另，Model 对数据库和表的操作做了很多增强，如果只是需要基础的查询功能，建议使用Db

**Comment by caiweiming** [comment]
非常感谢各位的解答，现在比较明白两者的区别了。
