### ISSUE TITLE
[v5.1.36]隐藏关联查询结果时发生奔溃

### ISSUE THREAD

**Issue by NHZEX** [top-think/framework#1798]
// 定义
public function latestVersion() {
    return $this->hasOne(Version::class, 'id', 'latest_version_id');
}
// 调用
$list = Resources::with(['latest_version'])
            ->field(['id', 'name', 'latest_version_id'])
            ->where('status', ApkResources::STATUS_PUBLISH)
            ->hidden(['latest_version'])
            ->select();
$list->toArray() // 发生奔溃

// 异常信息
```
Stack Trace: [0] Type error: Argument 1 passed to think\Model::hidden() must be of the type array, boolean given, called in /www/wwwroot/launcher_cms/thinkphp/library/think/model/concern/Conversion.php on line 170
#0 /www/wwwroot/launcher_cms/thinkphp/library/think/model/concern/Conversion.php(170): think\Model->hidden(true)
#1 /www/wwwroot/launcher_cms/thinkphp/library/think/Collection.php(51): think\Model->toArray()
#2 [internal function]: think\Collection->think\{closure}(Object(app\Model\ApkResources))
#3 /www/wwwroot/launcher_cms/thinkphp/library/think/Collection.php(52): array_map(Object(Closure), Array)
#4 /www/wwwroot/launcher_cms/thinkphp/library/think/Collection.php(518): think\Collection->toArray()
```

// 临时解决方法
`$list->toArray()` 前吧 unset掉 latest_version，不能使用 hidden 进行隐藏。

通过源码发现这样调用是正常得，但我想干掉整个属性，只能unset掉了。
->hidden(['latest_version'=>[...]])

@liu21st 这是bug还是特性

**Comment by liu21st** [comment]
已经修正 感谢反馈
