### ISSUE TITLE
缓存检测异常

### ISSUE THREAD

**Issue by dream2023** [top-think/framework#1801]
![WX20190517-155128](https://user-images.githubusercontent.com/19297757/57912119-1d2a3180-78bc-11e9-910b-d5f5407cc9b8.png)

服务器环境的是：
服务器: Linux Ubuntu 12.04.5 LTS
php: PHP 5.6.31

如图所示，129行命名判断了文件是否存在，但是走到133行还是出现了文件不存在的异常，请问是怎回事？

**Comment by jin123456bat** [comment]
有可能没有读取权限，用is_readable函数判断以下

**Comment by yunwuxin** [comment]
好像是是php7的一个bug  要用file_exists判断

**Comment by dream2023** [comment]
> 有可能没有读取权限，用is_readable函数判断以下

runtime目录设置的是777
![image](https://user-images.githubusercontent.com/19297757/58306834-71d72a80-7e2f-11e9-88a0-2db7e2b19c58.png)

**Comment by dream2023** [comment]
> 好像是是php7的一个bug 要用file_exists判断

不好意思忘记说环境了，我们服务器的是：
服务器: Linux Ubuntu 12.04.5 LTS
php: PHP 5.6.31

**Comment by jin123456bat** [comment]
> > 有可能没有读取权限，用is_readable函数判断以下
> 
> runtime目录设置的是777
> ![image](https://user-images.githubusercontent.com/19297757/58306834-71d72a80-7e2f-11e9-88a0-2db7e2b19c58.png)

目录权限和文件权限是两码事
