### ISSUE TITLE
input('/s')方法参数获取数据异常

### ISSUE THREAD

**Issue by wolf-leo** [top-think/framework#1802]
假设地址为 www.xxx.com
获取地址中的a参数
代码中写法，当a参数为空则自动设置a=123
```
$a = input('get.a/s', '123');
dump($a);
```
问题：
当直接访问www.xxx.com
打印$a：输出 "123"
当直接访问www.xxx.com?a=
打印$a：输出 ""
所以  input($key = '', $default = null, $filter = '')  中的default判断？

**Comment by liu21st** [comment]
从来没有说过参数为空 才使用默认值 是参数不存在才会使用默认值

**Comment by jin123456bat** [comment]
这个问题关了吧，可能不知道isset和empty的区别
