### ISSUE TITLE
开启 route_check_cache(路由缓存) 代码报错

### ISSUE THREAD

**Issue by novnan** [top-think/framework#1807]
## version

> 6.0.0RC2

## 重现步骤

1. `composer create-project topthink/think tp 6.0.*-dev` 全新安装的框架，设置 `app_debug` 为 `true`，其他全部未动。
2.  设置 `config/route.php` 中 `route_check_cache` 为 `true`，访问任意一个路由，页面报错。

## 错误信息

![20190521164233.png](https://i.loli.net/2019/05/21/5ce3ba1f114af74721.png)

是否是因为 `think\Cache` 中的 `init` 方法被设置为 `protected` 导致的 🤔

**Comment by liu21st** [comment]
已经修正，感谢反馈
