### ISSUE TITLE
tp5.1, tagLoad是否可以在js,css链接后面加入日期或版本号

### ISSUE THREAD

**Issue by yangqinjiang** [top-think/framework#1808]
https://github.com/top-think/framework/blob/5.1/library/think/template/taglib/Cx.php

**Comment by jin123456bat** [comment]
对于静态资源分离的项目版本号或者日期不太好决定

**Comment by liu21st** [comment]
这个完全可以自己加的

**Comment by yangqinjiang** [comment]
> 这个完全可以自己加的

我在template.php的tpl_replace_string,加入一个日期时间的, 不使用load函数,
例如 `<link href="/cp/css/layout.css?__ASSET_VERSION__" rel="stylesheet"/>`
`    'tpl_replace_string'  => [
        '__ASSET_VERSION__'  => date('Y-m-d-H-i'),
    ],`
