### ISSUE TITLE
5.1.36和5.137调度信息获取不一致导致跨域失败

### ISSUE THREAD

**Issue by ChenJinchuang** [top-think/framework#1817]
![TIM截图20190525232737](https://user-images.githubusercontent.com/49727104/58371546-b7394c00-7f44-11e9-96e9-4cc9e694bee3.png)

同样的代码，5.1.36获取到的调度信息如下：
![TIM截图20190525231342](https://user-images.githubusercontent.com/49727104/58371510-590c6900-7f44-11e9-84b6-c809e7ec52c3.png)
这个是正确的，升级了5.1.37后，获取到的调度信息如下：
![TIM截图20190525231755](https://user-images.githubusercontent.com/49727104/58371519-6d506600-7f44-11e9-8f41-4d241ffdb78c.png)
然后会404提示找不到cms模块

**Comment by liu21st** [comment]
调度没有改动过的

**Comment by ChenJinchuang** [comment]
> 调度没有改动过的

发现一个问题，在不跨域的情况下，调度信息没问题，但是跨域情况下，得到的调度信息又不一样。5.1.36没有这个问题。我还在继续debug，刘大有空的话留意下。

**Comment by lupuxyz** [comment]
5.1.35升级到5.1.37确实导致跨域失败了，退回去正常了

**Comment by ChenJinchuang** [comment]
> 5.1.35升级到5.1.37确实导致跨域失败了，退回去正常了

提了个pr了，把之前删掉的一段代码加回去就可以了，看合不合并，不合并就回退吧。
