### ISSUE TITLE
从5.1.35升级到5.1.37 visible方法报错

### ISSUE THREAD

**Issue by liuwave** [top-think/framework#1820]
从5.1.35升级到5.1.37 visible方法报错
[：(https://github.com/top-think/framework/commit/f30e00d0cf0dcfab32a193186c83577e9f1192b0#r33697756](https://github.com/top-think/framework/commit/f30e00d0cf0dcfab32a193186c83577e9f1192b0#r33697756)

**Comment by liu21st** [comment]
已经修正过 最新git版本
