### ISSUE TITLE
tp6.0多应用模式中增加应用内的服务配置

### ISSUE THREAD

**Issue by xiaoqingping** [top-think/framework#1821]
多应用模式下，service.php也只能在app目录下才有效。希望能在具体的应用目录内配置也能生效。

**Comment by xiaoqingping** [comment]
已经提了[Pull Request](https://github.com/top-think/framework/pull/1822)

**Comment by liu21st** [comment]
应用内不需要注册服务 注册了也无效，可以通过provider来绑定提供者
