### ISSUE TITLE
postgresql 更新数据问题

### ISSUE THREAD

**Issue by shuangfeilee** [top-think/framework#1824]
打印出的sql语句无法更新.
`UPDATE auth SET title = '测试角色' , desc = '测试角色' , id = 4 WHERE  id = 4`

有的字段需要加引号才行.
`UPDATE auth SET title = '测试角色' , "desc" = '测试角色' , id = 4 WHERE  id = 4`

**Comment by gitee1** [comment]
desc是pgsql关键字
