### ISSUE TITLE
5.0.23后断线重连问题并没有得到解决

### ISSUE THREAD

**Issue by malu040** [top-think/framework#1840]
我用swoole做了一个队列服务，其中逻辑需要去查数据库。
但是现在如果超过mysql的等待时间wait_timeout的限制后，tp5.0.22的释放前次的查询结果会出错。

`// 释放前次的查询结果`
`if (!empty($this->PDOStatement)) {`
`$this->free();`
`}`
`// 预处理`
`if (empty($this->PDOStatement)) {`
`$this->PDOStatement = $this->linkID->prepare($sql);`
`}`

日志会记录这条
[ error ] [8]think\db\Connection::free(): send of 9 bytes failed with errno=32 Broken pipe
但是重连是没问题的。报错之后依旧会去重连。
按我的逻辑去看的话tp5.0.22的代码是没问题的。
看源代码：

![image](https://user-images.githubusercontent.com/51440070/59022839-2423de80-8881-11e9-8246-8074b7598bec.png)

图片中的代码
`$this->free();`
按我个人认为不应该会被直接捕获然后去重连吗，事实它的确是去重连了，我的疑惑是为什么在的时候又记录了一条超时限制的日志，这条日志是哪里捕获到之后存的。

而tp5.0.23说改进了断线重连（代码我就不贴了），上述错误是不会记录了，但出现了另一个错误：
[ error ] [8]PDO::prepare(): send of 67 bytes failed with errno=32 Broken pipe
我个人认为因为5.0.23不再去先释放前次的查询结果，而是去直接执行覆盖前一次的查询结果。但这是连接依旧是断开的，我并没有看到任何改进的地方。是我遗漏了什么吗？？？

ps 我并没有进行升级，只是把Connection.php里的改动给手动修改了。

**Comment by jiuwuxiaohun** [comment]
你开启断线重连没有??在app config里面

**Comment by malu040** [comment]
> 你开启断线重连没有??在app配置里面

开启了，像我上边说的，断线重连我已经证实了是可以重连的，只是会报一个错误，但我不知道是被tp从哪里捕获的。这样会导致日志文件里会记录这些错误，但我不清楚并且也没有证明此错误还会不会有其他影响。

**Comment by liu21st** [comment]
断线重连之前是会记录下错误信息，因为确实是有错误发生了
