### ISSUE TITLE
tp5.0 tp5.1 追加一对一、一对多关联模型属性问题

### ISSUE THREAD

**Issue by MrCJJW** [top-think/framework#1843]
tp5.0.24
tp5.1.36
# 追加一对一关联模型属性
调用代码示例：

![image](https://user-images.githubusercontent.com/15009827/59239423-06b19480-8c34-11e9-807f-14eae09b10b8.png)

当不存在detail数据时会报错。

tp5.0相关源码位置thinkphp/library/think/Model.php
![image](https://user-images.githubusercontent.com/15009827/59239666-dcaca200-8c34-11e9-8cf4-598abb2e99b3.png)

tp5.1相关源码位置thinkphp/library/think/model/concern/Conversion.php
![image](https://user-images.githubusercontent.com/15009827/59239907-c2bf8f00-8c35-11e9-88b6-9ecafda30b1e.png)

框架是否应该先判断一下是否为null再调用？还是交由使用者自行判断关联的属性是否为null再追加关联模型属性？

# 追加一对多关联模型属性
当不存在books数据时，对于tp5.0来说，若查询结果为数组时，会报错，若为数据集则正常。tp5.1模型查询默认为数据集所以正常。

tp5.0相关源码位置thinkphp/library/think/Model.php
![image](https://user-images.githubusercontent.com/15009827/59239666-dcaca200-8c34-11e9-8cf4-598abb2e99b3.png)

框架是否应该先判断一下是否为array,先转换为collection再调用？还是交由使用者自行判断关联的属性是否为空再追加关联模型属性？

**Comment by liu21st** [comment]
5.1.37版本你测试下

**Comment by MrCJJW** [comment]
一样，5.1.37

![image](https://user-images.githubusercontent.com/15009827/59241296-a887b000-8c39-11e9-8783-c9cf251d0c64.png)

**Comment by liu21st** [comment]
5.1已经改进了

**Comment by MrCJJW** [comment]
看了下修改

![image](https://user-images.githubusercontent.com/15009827/59436277-e6472d00-8e21-11e9-9879-19a60c66e014.png)

默认为null会不会合理些。
$item[$key] = $relation ? $relation->append([$attr])->toArray() : null;
因为对于一对一关联来说，存在时返回对象，不存在返回null合理些。
