### ISSUE TITLE
建议还原 fetchArray函数

### ISSUE THREAD

**Issue by gjianbo** [top-think/framework#1844]
建议还原query.php中的fetchArray 函数,返回数组,而不是返回一个模型对象集.
经常在控制器使用模型的静态方法进行数据的简单查询,结果只需要一个数组, 前几个版本用了fetcharray 函数感觉太方便了,现在感觉又回来了5.1的方式太不方便.查询先要判断是否为空,然后再toarray.

**Comment by liu21st** [comment]
查询之后统一使用toArray就行 去掉的原因主要是两种操作方式不统一

**Comment by gjianbo** [comment]
虽然造成了返回的不统一，但极大的方便了，在模型和控制器中只需要获取数组的操作。建议恢复该函数。

**Comment by liu21st** [comment]
既然toArray已经可以达到目的 为何还要fetchArray呢
