### ISSUE TITLE
5.1.x版本whereNotIn函数bug

### ISSUE THREAD

**Issue by jin123456bat** [top-think/framework#1845]
`Db::name('room_calendar')->whereNotIn('room_id',[1072])->buildSql(true)`
生成sql为:
`( SELECT * FROM `room_calendar` WHERE  `room_id` = 1072 )`

**Comment by liuwave** [comment]
我这边测试正常呢。
版本是 v5.1.37.1。
`var_dump( Db::name('article')->whereNotIn('article_id',[10010])
         ->buildSql());`

`string(64) "( SELECT * FROM `c_article` WHERE `article_id` NOT IN (10010) )" `

**Comment by jin123456bat** [comment]
> 我这边测试正常呢。
> 版本是 v5.1.37.1。
> `var_dump( Db::name('article')->whereNotIn('article_id',[10010]) ->buildSql());`
> 
> `string(64) "( SELECT * FROM `c_article`WHERE`article_id`NOT IN (10010) )"`

也是5.1.37，已经更新到最新了

**Comment by liu21st** [comment]
修正了
