### ISSUE TITLE
验证上传文件大小的方法是否有错误，是否应该调整为这样？

### ISSUE THREAD

**Issue by MiloZheng** [top-think/framework#1869]
`public function fileSize($file, $rule): bool
    {
        if (is_array($file)) {
            foreach ($file as $item) {
                if (!($item instanceof File) || !$this->checkSize($item, $rule)) {
                    return false;
                }
            }
            return true;
        } elseif ($file instanceof File) {
            return !$this->checkSize($file, $rule);
        }

        return false;
    }`

**Comment by yunwuxin** [comment]
已修正
