### ISSUE TITLE
6.0的hasOne hasMany中的第三个参数localKey可以加上吗?

### ISSUE THREAD

**Issue by cnzaicom** [top-think/framework#1877]
6.0的hasOne hasMany中的第三个参数localKey可以加上吗?
像以前一样  觉得更灵活

**Comment by liu21st** [comment]
完全可以自动获取的吧

**Comment by cnzaicom** [comment]
多对多模型的with方法,是不是不支持使用闭包的方式进行约束??
比如:Tags::with(['articles'])->findOrFail($data)  是没有问题的,
tp6只要使用闭包就出错.查看错误应该是有一部分语句没有组装进去.
现在想知道是bug还是?????

**Comment by liu21st** [comment]
支持闭包的 参考手册，你是出什么错误？

**Comment by cnzaicom** [comment]
提示:SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pivot.c_id' in 'field list'
Tags模型定义articles方法 使用belongsToMany关联.tp5是正常的,tp6报错.
下面这种什么也不干也会报错.
Tags::with(['articles'=>function($query){
    return $query;
}])->findOrFail($data) 
如果把闭包去掉不出错

**Comment by liu21st** [comment]
多对多的有问题修正了

**Comment by cnzaicom** [comment]
但是还是有一个问题如果是传入一个数组 返回的是不正确的.
比如下面这条:
Tags::with(['articles'=>function($query){
return $query->limit(10);
}])->whereIn('in',[1,2,3])->select()
pivot只用到了3    1跟2丢失了.
显示SQL:  WHERE `pivot`.`XXXX_id` = 3 LIMIT 10
正确应该是 WHERE `pivot`.`XXXX_id` in (1,2,3) LIMIT 10
