### ISSUE TITLE
6.0 think/db/concern/WhereQuery.php 469行能否修改一下，支持关联数组

### ISSUE THREAD

**Issue by qqlcbb** [top-think/framework#1878]
$where[] = is_null($val) ? [$key, 'NULL', ''] : [$key, is_array($val) ? 'IN' : '=', $val];
修改成
if (is_null($val)) {
    $where[] = [$key, 'NULL', ''];
} elseif (is_array($val)) {
    $where[] = [$key, $val[0], $val[1]];
} else {
    $where[] = [$key, '=', $val];
}
可以支持这种查询：
$where['name'] = ['like', "%{$keywords}%"];

为什么不呢？

**Comment by liu21st** [comment]
不是不能支持 是故意不支持 数组的用法只有一种，多了不乱么？

**Comment by liu21st** [comment]
其中一个重要原因是关联数组存在安全隐患
