### ISSUE TITLE
composer update error

### ISSUE THREAD

**Issue by anydson** [top-think/framework#1896]
6.0.x-dev 1aff42e
6.0.x-dev a414740
6.0.x-dev c13f162
composer update
Script @php think service:discover handling the post-autoload-dump event returned with error code 1

**Comment by 4352570** [comment]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> @php think service:discover


                                    
  [think\exception\ErrorException]  
  mkdir(): Permission denied        
                                    


Script @php think service:discover handling the post-autoload-dump event returned with error code 1

**Comment by liu21st** [comment]
看报错应该是权限问题

**Comment by 4352570** [comment]
`composer update topthink/framework` 时报的错误，已经修复了
