### ISSUE TITLE
建议仍然加上URL模式配置选项

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#190]
RT. 

应用场景:
很多情况下, 可能需要将一个列表的数据进行缓存, 其中使用了 `Url::build` 方法来生成url
在开启Rewrite后, 如果是正常访问下能正确生成URL
但是并不是所有的访问者都按规矩来访问, 正好有人以
`http://www.xxx.com/index.php/index/index` 的方式访问时, 缓存刷新
此时使用 `Url::build` 生成的 URL 地址将会以 `http://www.xxx.com/index.php/` 开头
而不是预期的 `http://www.xxx.com/` 开头

建议增加 `URL模式` 配置, 强制 `Url::build` 生成的链接为 Rewrite 模式链接, 而不会根据外部的访问方式来生成 url 地址

**Comment by liu21st** [comment]
可以使用request类的root方法设置即可
