### ISSUE TITLE
ThinkPHP 5.1路由BUG

### ISSUE THREAD

**Issue by WangBaoJing** [top-think/framework#1901]
5.1路由开启完全匹配时，url若以斜杠结尾则报“当前访问路由未定义或不匹配”的错误。

BUG复现：
路由为“Route::get('admin/verify', 'admin/Account/verify');”，
域名为“http://test.cn”，
访问“http://test.cn/admin/verify”正常，
但访问“http://test.cn/admin/verify/”时报错。

经测试，5.0和6.0dev均无此BUG，望尽快解决。

**Comment by liu21st** [comment]
本来这就是两个不同的路由，定义路由的时候使用removeSlash方法即可

**Comment by WangBaoJing** [comment]
@liu21st 辛苦了，感谢回复，谢谢！
