### ISSUE TITLE
路由首字母转自动大写问题

### ISSUE THREAD

**Issue by xaboy** [top-think/framework#1902]
项目刚从 tp5.0升上来,在服务器上测试发现找不到控制器,系统是centos,在 mac 和 windows 上正常

error:
```
[0] HttpException in Controller.php line 71
控制器不存在::app\admin\controller\Store\StoreProduct
```
url:
```
/admin/store.store_product/index.html?type=1
```

目录解构:
├─admin 
│  ├─contoller     
│    │  ├─store         
│    │   │  ├─StoreProduct.php 

在[Controller#158行](https://github.com/top-think/framework/blob/6.0/src/think/route/dispatch/Controller.php#L156)调试发现解析后的命名空间`store`首字母变成了大写

在 mac 和 windows 环境下`class_exists`返回的是`true`,linux 下返回的是`false`.

**Comment by xaboy** [comment]
StoreProduct.php 文件的命名空间是 
```
app\admin\controller\store\StoreProduct
```

**Comment by liu21st** [comment]
已经修正
