### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by xaboy** [top-think/framework#1905]
日志的路径错误

打开页面时
![image](https://user-images.githubusercontent.com/21242408/60944597-dd138800-a31b-11e9-937a-662dc77c0db8.png)
更新框架时
![image](https://user-images.githubusercontent.com/21242408/60944646-f61c3900-a31b-11e9-8a8d-ae663ca420eb.png)

**Comment by xaboy** [comment]
版本: 6.0.x-dev 35fa0f4c2

**Comment by liu21st** [comment]
日志的path参数需要自己设置

**Comment by xaboy** [comment]
谢谢,我从 c13f16240 版本更新过来忽然就报错了
是不是有个默认值好一些

**Comment by liu21st** [comment]
等后面改进
