### ISSUE TITLE
5.1时间查询

### ISSUE THREAD

**Issue by codesboy** [top-think/framework#1920]
5.1时间表达式查询有点bug. whereTime('followup_time', 'today')这个解析出来的是BETWEEN 1563120000 AND 1563206400 （就是从2019-07-15 00:00:00-2019-07-16 00:00:00），
我数据库followup_time字段存的时间戳格式是Y-m-d格式 只有年月日，我只想查2019-07-15这个日期的，结果用whereTime('followup_time', 'today')查出来包含了15号和16号两天的日期。所以感觉today的取值范围多了1s，2019-07-16 00:00:00这个时间应该是属于明天的，不是今天的

**Comment by hbh112233abc** [comment]
> 5.1时间表达式查询有点bug. whereTime('followup_time', 'today')这个解析出来的是BETWEEN 1563120000 AND 1563206400 （就是从2019-07-15 00:00:00-2019-07-16 00:00:00），
> 我数据库followup_time字段存的时间戳格式是Y-m-d格式 只有年月日，我只想查2019-07-15这个日期的，结果用whereTime('followup_time', 'today')查出来包含了15号和16号两天的日期。所以感觉today的取值范围多了1s，2019-07-16 00:00:00这个时间应该是属于明天的，不是今天的

sql的between a and b 是不包含b的啊

**Comment by liu21st** [comment]
修正了的

**Comment by codesboy** [comment]
拉取了最新代码，测试已经修正了，感谢！
