### ISSUE TITLE
字段_问题，database.php配置是默认的

### ISSUE THREAD

**Issue by hulang** [top-think/framework#1927]
我的表
![q1](https://user-images.githubusercontent.com/4961831/61526039-367e6400-aa4c-11e9-9d07-a1a36e2a90f4.png)
生成json：
`{"sql":"SELECT * FROM `xxx_crontab` ORDER BY `px` ASC,`id` DESC LIMIT 0,5","code":0,"count":22,"data":[{"id":22,"type":"url","title":"xxx","content":"https:\/\/www\/api\/xxx\/txt.html?id=61","schedule":"*\/5 * * * *","sleep":0,"maximums":0,"executes":124,"executetime":1562296201,"executetime_status":"1","px":0,"status":"normal","state":1,"nexttime":1563529200},{"id":21,"type":"url","title":"xxx","content":"https:\/\/www\/api\/xxx\/sync","schedule":"*\/15 * * * *","sleep":0,"maximums":0,"executes":41,"executetime":1562295601,"executetime_status":"1","px":0,"status":"normal","state":1,"nexttime":1563529500},{"id":20,"type":"url","title":"xxx","content":"https:\/\/www\/api\/xxx\/xxx","schedule":"*\/40 * * * *","sleep":0,"maximums":0,"executes":21,"executetime":1562295601,"executetime_status":"1","px":0,"status":"normal","state":1,"nexttime":1563529200},{"id":19,"type":"url","title":"xxx","content":"https:\/\/www\/api\/xxx\/xxx","schedule":"*\/20 * * * *","sleep":0,"maximums":0,"executes":31,"executetime":1562295601,"executetime_status":"1","px":0,"status":"normal","state":1,"nexttime":1563529200},{"id":18,"type":"url","title":"xxx","content":"https:\/\/www\/api\/content\/xxx","schedule":"*\/30 * * * *","sleep":0,"maximums":0,"executes":21,"executetime":1562295601,"executetime_status":"1","px":0,"status":"normal","state":1,"nexttime":1563530400}]}`

把_去掉了。。
如果使用：withoutField排除execute_result
`{"sql":"SELECT `id`,`type`,`title`,`content`,`schedule`,`sleep`,`maximums`,`executes`,`executetime`,`executetime_status`,`px`,`status`,`state` FROM `xxx_crontab` ORDER BY `px` ASC,`id` DESC LIMIT 0,5","code":0,"count":22,"data":[{"id":22,"type":"url","title":"xxx","content":"https:\/\/www\/api\/xxx\/txt.html?id=61","schedule":"*\/5 * * * *","sleep":0,"maximums":0,"executes":124,"executetime":1562296201,"executetime_status":"1","px":0,"status":"normal","state":1,"nexttime":1563529500},{"id":21,"type":"url","title":"xxx","content":"https:\/\/www\/api\/xxx\/sync","schedule":"*\/15 * * * *","sleep":0,"maximums":0,"executes":41,"executetime":1562295601,"executetime_status":"1","px":0,"status":"normal","state":1,"nexttime":1563529500},{"id":20,"type":"url","title":"xxx","content":"https:\/\/www\/api\/xxx\/xxx","schedule":"*\/40 * * * *","sleep":0,"maximums":0,"executes":21,"executetime":1562295601,"executetime_status":"1","px":0,"status":"normal","state":1,"nexttime":1563530400},{"id":19,"type":"url","title":"xxx","content":"https:\/\/www\/api\/xxx\/xxx","schedule":"*\/20 * * * *","sleep":0,"maximums":0,"executes":31,"executetime":1562295601,"executetime_status":"1","px":0,"status":"normal","state":1,"nexttime":1563530400},{"id":18,"type":"url","title":"xxx","content":"https:\/\/www\/api\/content\/xxx","schedule":"*\/30 * * * *","sleep":0,"maximums":0,"executes":21,"executetime":1562295601,"executetime_status":"1","px":0,"status":"normal","state":1,"nexttime":1563530400}]}`

SQL语句居然是：
SELECT `id`,`type`,`title`,`content`,`schedule`,`sleep`,`maximums`,`executes`,`executetime`,`executetime_status`,`px`,`status`,`state` FROM `xxx_crontab` ORDER BY `px` ASC,`id` DESC LIMIT 0,5

是不是需要database.php配置，我没有看到相关的！！

**Comment by hulang** [comment]
把：max_num 生成：maximums，这也太扯淡了吧
还有：start_time,end_time居然去掉了。。executes哪里来的啊，我根本没有
总之，各种生成错误。。是我配置了什么？我都是默认的。。今天是第一次试用6.0 RC3
一直用tp5.1.37.1最新版本。。。

**Comment by liu21st** [comment]
给出你的测试代码和报错信息

**Comment by hulang** [comment]
@liu21st 没有报错，就是查询出的结果错误了。。

**Comment by hulang** [comment]
model
`<?php

namespace app\common\model;

use think\Model;

/**
 * @mixin think\Model
 */
class Crontab extends Model
{
    protected $pk = 'id';
}`

controller
namespace app\e\controller;

use think\facade\Request;
use think\facade\View;
use service\CronParser;
use app\common\model\Crontab as CrontabModel;

class Crontab extends Base
{
    protected $validate = 'Crontab';
    protected $crontab_model;
    protected function initialize()
    {
        parent::initialize();
        $this->crontab_model = new CrontabModel();
    }
    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        return View::fetch();
    }

    /**
     * 显示AJAX列表
     *
     * @return json
     */
    public function ajax()
    {
        // 获取GET数据
        $g = input('get.');
        $keyword = isset($g['keyword']) ? $g['keyword'] : '';
        $limit = isset($g['limit']) ? $g['limit'] : 5;
        $page = isset($g['page']) ? $g['page'] : 1;
        //
        $pageNum = $limit < 5 ? 5 : $limit;
        $map = [];
        if (!empty($keyword)) {
            $keyword = trim($keyword);
            $map[] = ['title|content', 'like', "%{$keyword}%"];
        }
        $px = ['px' => 'asc', 'id' => 'desc'];
        $list = $this->crontab_model->withoutField(['execute_result'])->where($map)->order($px)->paginate($pageNum, false, ['page' => $page, 'query' => ['keyword' => $keyword]]);
        $sql = $this->crontab_model->getLastSql();
        //
        if (!empty($list)) {
            foreach ($list as $key => $value) {
                $nexttime = CronParser::formatToDate($value['schedule'], 1)[0];
                $list[$key]['nexttime'] = strtotime($nexttime);
                unset($nexttime);
            }
        }
        // json
        $json['sql'] = $sql;
        $json['code'] = 0;
        $json['count'] = $list->total();
        $json['data'] = $list->items();
        return json($json);
    }
}

数据表
`DROP TABLE IF EXISTS `zjjcms_crontab`;
CREATE TABLE `zjjcms_crontab` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `type` varchar(10) NOT NULL DEFAULT '' COMMENT '任务类型',
  `title` varchar(100) NOT NULL DEFAULT '' COMMENT '任务名称',
  `content` text NOT NULL COMMENT '任务内容',
  `schedule` varchar(100) NOT NULL DEFAULT '' COMMENT '任务周期',
  `sleep` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '延迟秒数执行',
  `max_num` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '最大执行次数 0为不限',
  `start_time` int(11) DEFAULT '0' COMMENT '开始时间',
  `end_time` int(11) DEFAULT '0' COMMENT '结束时间',
  `execute_num` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '已经执行的次数',
  `execute_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '最后执行时间',
  `execute_status` varchar(30) NOT NULL DEFAULT '' COMMENT '执行状态',
  `execute_result` text COMMENT '最后执行结果',
  `px` int(11) NOT NULL DEFAULT '0' COMMENT '排序',
  `status` int(1) DEFAULT '0' COMMENT '状态',
  `uptime` int(11) DEFAULT '0' COMMENT '更新时间',
  `addtime` int(11) DEFAULT '0' COMMENT '添加时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8 COMMENT='定时任务表';`

**Comment by liu21st** [comment]
没法重现你的问题 建议你重新安装 用一个最简单的例子测试

**Comment by hulang** [comment]
@liu21st 作者老大，我就做了这一个示例，根本没有做其它示例
我上面的model你复制，控制器你也复制下，表也复制创建，随便添加一条数据，你就知道了。

**Comment by hulang** [comment]
@liu21st 我就今天刚下载的最新6.0 RC3，用的：composer安装的。。

**Comment by hulang** [comment]
@liu21st 作者老大，用不了你多长时间进行测试！！

**Comment by liu21st** [comment]
抱歉 今天没时间

**Comment by hulang** [comment]
use service\CronParser;
和，这个去掉。。
if (!empty($list)) {
foreach ($list as $key => $value) {
$nexttime = CronParser::formatToDate($value['schedule'], 1)[0];
$list[$key]['nexttime'] = strtotime($nexttime);
unset($nexttime);
}
}

**Comment by hulang** [comment]
@liu21st 哎。。。

**Comment by hulang** [comment]
@liu21st 不好意思，链接错了库！！！
