### ISSUE TITLE
更新框架后报错了

### ISSUE THREAD

**Issue by dafa168** [top-think/framework#1933]
[23-Jul-2019 11:44:26 Asia/Shanghai] PHP Fatal error:  Uncaught TypeError: Return value of think\Log::getDefaultDriver() must be of the type string, null returned in E:\www\tp6\vendor\topthink\framework\src\think\Log.php:46

composer 1.8.2  
php 7.2.10 
apache 2.3.0

是否因为框架没更新好呢？

**Comment by dafa168** [comment]
think service:discover
Script @php think service:discover handling the post-autoload-dump event returned with error code 255

补充说明  
thinkphp 6.0 - dev

**Comment by liu21st** [comment]
你的log配置存在问题

**Comment by JackZhangfromChina** [comment]
> [23-Jul-2019 11:44:26 Asia/Shanghai] PHP Fatal error: Uncaught TypeError: Return value of think\Log::getDefaultDriver() must be of the type string, null returned in E:\www\tp6\vendor\topthink\framework\src\think\Log.php:46
> 
> composer 1.8.2
> php 7.2.10
> apache 2.3.0
> 
> 是否因为框架没更新好呢？

换nginx，apache太慢了

**Comment by dafa168** [comment]
收到 。谢谢
