### ISSUE TITLE
ThinkPHP 6.0 设置cookie 无效

### ISSUE THREAD

**Issue by HelplessMan** [top-think/framework#1948]
> 设置cookie
![image](https://user-images.githubusercontent.com/9101275/62478729-62d10900-b7de-11e9-93ef-732e1643d774.png)

> 获取cookie
![image](https://user-images.githubusercontent.com/9101275/62478767-7a0ff680-b7de-11e9-9250-fbdab6c1d171.png)

> 获取结果

![image](https://user-images.githubusercontent.com/9101275/62478813-94e26b00-b7de-11e9-94a1-062f703e7d80.png)

>cookie 配置文件

![image](https://user-images.githubusercontent.com/9101275/62478860-b93e4780-b7de-11e9-91df-04b400eb9faf.png)

ps: 我当前设置的值例如是：baidu ，然后在获取的时候。永远都是 images？

**Comment by HelplessMan** [comment]
感觉这个issue 没人维护么。。 看好多人提都是0 回答～～～

**Comment by 4352570** [comment]
你自己设置的问题，我试了可以的

**Comment by 4352570** [comment]
应该看响应里是否有返回cookie信息，如果客户端不支持你就读不到

**Comment by HelplessMan** [comment]
> 应该看响应里是否有返回cookie信息，如果客户端不支持你就读不到

想了下。昨天看cookie的时候，在response里面是有 我设置cookie的key 和value 而且都是对的。。request里面也有。不过刚才在公司的电脑上测试了下。的确没有问题。那估计就是我本地的问题了~  谢谢老哥解答。
