### ISSUE TITLE
tp6.0RC3 关联查询为何不能使用where和field方法了

### ISSUE THREAD

**Issue by static7** [top-think/framework#1951]
![image](https://user-images.githubusercontent.com/11241063/62590288-6491ee00-b8fe-11e9-8738-fbd92125b907.png)
如果不能在关联查询使用where方法 会导致被禁用的数据也能查出来,field方法是限制无用字段被查询出来,然而官方为何要取消这个两个方法,
不知道是bug还是官方故意取消

**Comment by liu21st** [comment]
你的问题在于field方法使用不当 关联数据没法关联查询 用模型就不要在乎这点性能了 除非你自己能驾驭
