### ISSUE TITLE
更新v5.1.38不支持PHP5.6需要7.0以上版本

### ISSUE THREAD

**Issue by cinaofdai** [top-think/framework#1952]
在2019-8-8号创建，更新一个项目，本人自己写的composer包时候，把v5.1.*升级了最新版本v5.1.38发现不支持PHP5.6，查了一下thinkphp的composer.json是支持php5.6的

域名直接访问项目直接报如下错误
![1565319721(1)](https://user-images.githubusercontent.com/20353921/62751749-7064e800-ba97-11e9-8c29-72c714ee3605.jpg)

事故解决方案：
1、更改PHP最低版本：为7.0正常访问。
1、将composer.json内的thinkphp版本改为v5.1.37.*可正常访问。

**Comment by liu21st** [comment]
已经修正了
