### ISSUE TITLE
远程一对多的预载入查询及关联统计报错

### ISSUE THREAD

**Issue by 123shang60** [top-think/framework#1962]
thinkPHP版本 5.1.38.1
模型定义如下：
Order.php：
public function ss(){
    return $this->hasManyThrough('Drug','OrderDetail','order_id','id','id');
}
存在OrderDetail模型及Drug模型，OrderDetail模型主键设置为drug_id

当使用：
$order = OrderMasterModel::where(['id' => $order_id])->find();
$order->ss;
return ReturnUtils::TrueResult($order);
可以得到正确结果
当使用：
$order = OrderMasterModel::where(['id' => $order_id])->with('ss')->find();
或者
$order = OrderMasterModel::where(['id' => $order_id])->withCount('ss')->find();
会出现异常如下：
[0] ThrowableError in HasManyThrough.php line 199
类型错误: Argument 3 passed to think\model\relation\HasManyThrough::eagerlyResult() must be of the type array, string given, called in D:\xampp\htdocs\yaodian\thinkphp\library\think\model\concern\RelationShip.php on line 296

**Comment by liu21st** [comment]
已经修正
