### ISSUE TITLE
TP 5.1 模型如何关闭自动完成？

### ISSUE THREAD

**Issue by richex-cn** [top-think/framework#1969]
ThinkPHP 5.1.37 LTS

```php
<?php
namespace app\common\model;

use \think\Model;

class Product extends Model
{
    protected $update = ['updatetime'];

    public function setUpdatetimeAttr()
    {
        return date('Y-m-d H:i:s');
    }
}
```

如上模型定义，如果我希望在部分特殊情况下希望关闭自动完成，例如提供相关函数：

```php
$model = new Product();
// ->closeAuto(array $fields)
// ->closeAutoInsert(array $fields)
// ->closeAutoUpdate(array $fields)
$model->closeAutoUpdate(['updatetime'])->saveAll([
    ['id' => 1, 'name' => 'new name1' ],
    ['id' => 2, 'name' => 'new name2' ],
]);
```

我考虑过通过 `Db::update()` 直接实现，但是这样可能会随着业务逻辑增加导致混乱，例如一规定了数据库操作必须通过模型，如果部分通过 Db 解决了，日后如果通过模型事件 `before_update` 等注册了其他业务逻辑，那么使用 Db 操作将不会触发模型事件注册的业务逻辑了。

**Comment by liu21st** [comment]
最好是使用模型事件来替代自动完成

**Comment by richex-cn** [comment]
> 最好是使用模型事件来替代自动完成

使用模型事件也是全局注册，我想要单独控制部分情况不触发自动完成应该怎么做？

需求是更新特定的字段时不触发事件或者数据完成。

**Comment by pifeifei** [comment]
> > 最好是使用模型事件来替代自动完成
> 
> 使用模型事件也是全局注册，我想要单独控制部分情况不触发自动完成应该怎么做？
> 
> 需求是更新特定的字段时不触发事件或者数据完成。

用 db()  是否可以, 不用模型?

**Comment by richex-cn** [comment]
> > > 最好是使用模型事件来替代自动完成
> > 
> > 
> > 使用模型事件也是全局注册，我想要单独控制部分情况不触发自动完成应该怎么做？
> > 需求是更新特定的字段时不触发事件或者数据完成。
> 
> 用 db() 是否可以, 不用模型?

如果部分通过 Db 解决了，日后如果通过模型事件 `before_update` 等注册了其他业务逻辑，那么使用 Db 操作将不会触发这部分新注册的模型事件业务逻辑了，是个麻烦的问题。

**Comment by pifeifei** [comment]
> > > > 最好是使用模型事件来替代自动完成
> > > 
> > > 
> > > 使用模型事件也是全局注册，我想要单独控制部分情况不触发自动完成应该怎么做？
> > > 需求是更新特定的字段时不触发事件或者数据完成。
> > 
> > 
> > 用 db() 是否可以, 不用模型?
> 
> 如果部分通过 Db 解决了，日后如果通过模型事件 `before_update` 等注册了其他业务逻辑，那么使用 Db 操作将不会触发这部分新注册的模型事件业务逻辑了，是个麻烦的问题。 @pifeifei

想到简单方法了, 
你知道 trait 吧?

```php

trait AutoModel
{
     public function closeAuto(){$this->auto = []; return $this;}
     public function closeAutoInsert(){$this->update = []; return $this;}
     public function closeAutoUpdate(){$this->update = []; return $this;}
}

// model 直接㱇autoModel (名字自己改下就行)
```

那里需要 那里 use

**Comment by richex-cn** [comment]
@pifeifei 感谢，完美解决问题又不影响框架本身代码 (๑•̀ㅂ•́)و✧
