### ISSUE TITLE
ThinkPHP6.0的日志记录，不再记录请求的路径，运行的时间了吗？

### ISSUE THREAD

**Issue by xnny** [top-think/framework#1975]
像 5.1 版本的这种日志，看起来更加直观啊
---------------------------------------------------------------
[2019-08-07T17:08:01+08:00] 127.0.0.1 GET 127.0.0.1:8000/
[运行时间：0.217541s] [吞吐率：4.60req/s] [内存消耗：1,998.23kb] [文件加载：73]
[ info ] [ LANG ] d:\web\www\thinkphp\lang\zh-cn.php
[ info ] [ ROUTE ] array (
)
知道是哪些请求产生的日志

**Comment by liu21st** [comment]
可以自己加 这种日志实际上没有意义 浪费日志空间

**Comment by nsnake** [comment]
这些日志在调试模式下还是应该记录下，方便调试。
最坑的是文档中没有任何说明此处的改动，害的我还以为是哪里配置错误了

**Comment by wikimo** [comment]
【可以自己加 这种日志实际上没有意义 浪费日志空间】
具体如何加，可否提供示例，谢谢。 @liu21st
