### ISSUE TITLE
model有那个函数可以指定offset的同时返回一行数据

### ISSUE THREAD

**Issue by Ulyssesyi** [top-think/framework#1980]
当使用find函数时会自动添加limit 1到sql中，导致了使用limit函数或者page函数无效。这样我就没法获取到指定offset位置的一条数据了。只能时limit配合select返回二维数组才行

**Comment by momoca** [comment]
find()本来就是查询一条的.

**Comment by Ulyssesyi** [comment]
我的意思是想查找第100条数据，用page或者limit就只能用all返回二维数组。用find没法定位到100
