### ISSUE TITLE
v6.0.0RC4 版本下，调试输出接口Bug

### ISSUE THREAD

**Issue by Liangkk** [top-think/framework#1981]
出错在于
\vendor\topthink\framework\src\think\debug\Console.php line 44
或者
\vendor\topthink\framework\src\think\debug\Html.php line 46

`

/**
     * 调试输出接口
     * @access public
     * @param  Response  $response Response对象
     * @param  array     $log 日志信息
     * @return string|bool
     */
    public function output(App $app, Response $response, array $log = [])
    {
        $request     = $app->request;
        $contentType = $response->getHeader('Content-Type');
        $accept      = $request->header('accept');
        if (strpos($accept, 'application/json') === 0 || $request->isAjax()) {
            return false;
        } elseif (!empty($contentType) && strpos($contentType, 'html') === false) {
            return false;
        }

`

假如请求头没有accept的时候，$accept 取值为null，strpos 方法则会报错

strpos() expects parameter 1 to be string, null given

**Comment by liu21st** [comment]
已经改进 感谢反馈
