### ISSUE TITLE
whereRaw在闭包中使用，会出现参数绑定丢失问题

### ISSUE THREAD

**Issue by liaohongxing** [top-think/framework#1999]
# 版本：5.1.38 LTS
# 下面是重现代码

### 不在闭包中正常
```
$list = Db::name('user')->whereRaw('id = :id', ['id' => 1])->where('status', '=', 0)->select();
dump($list)
```

### 在闭包中会报错
```
$list = Db::name('user')->where(function ($query) {
	$query->whereRaw('id = :id', ['id' => 1]);
	$query->where('status', '=', 0);
})->select();
dump($list);
```

**Comment by liu21st** [comment]
修正了

**Comment by xiaobudie** [comment]
@liu21st 
使用修正后代码，闭包执行报错，SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''
调试发现，将 316 行 buildWhere 参数1 还原为 $query 便可正常执行。
请确认是否为BUG。

**Comment by liu21st** [comment]
> @liu21st
> 使用修正后代码，闭包执行报错，SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''
> 调试发现，将 316 行 buildWhere 参数1 还原为 $query 便可正常执行。
> 请确认是否为BUG。

已修正

**Comment by xiaobudie** [comment]
@liu21st 
发现新的报错：SQLSTATE[HY093]: Invalid parameter number

假设查询为：
Model::where('a', 1)
->where(function ($subQuery) {
	$subQuery->where('b', 2);
})
->fetchSql(true)
->select();

生成的SQL语句是：
SELECT * FROM `prefix_model` WHERE  `a` = 2  AND (  `b` = :ThinkBind_1_ )

参数值位置错误、丢失。
请确认。

**Comment by liu21st** [comment]
@xiaobudie 可以再试下

**Comment by xiaobudie** [comment]
@liu21st 
fetchSql 打印出的SQL、runtime中log记录的SQL、phpMyAdmin 中执行的结果都正常且有数据；
但执行模型select查询，却取不到数据，显示为空数组；
同样的，316 行 buildWhere 参数1 还原为 $query 便可正常获取到数据。
对框架源码不熟悉，无从下手。请确认。

**Comment by liu21st** [comment]
我测试正常的

**Comment by xiaobudie** [comment]
@liu21st 
接上一条
试了一下，应该与闭包查询中包含 JSON 字段有关系。
假定Model中定义：b 是JSON类型，其中包含的 c 为int类型；

Model::where('a', 1)
->where(function ($subQuery) {
$subQuery->where('b->c', 2);
})
->select();
==> 返回为空

Model::where('a', 1)
->where(function ($subQuery) {
$subQuery->where('d', 3);
})
->select();
==> 返回正常

**Comment by xiaobudie** [comment]
@liu21st
请确认，是否与json配置未设置到newQuery有关。
