### ISSUE TITLE
tp6.0 cache不会自动更新

### ISSUE THREAD

**Issue by qq475281441** [top-think/framework#2014]
如下代码
`$cate = GoodsCateModel::cache(true)->where('level', 3)->where('goods_cate_id',54)->find();`

goods_cate_id为主键
level为普通字段

我将level的值从3改为2，发现cache的key固定为：think:guangguang.goods_cate|54
如果我去掉主键的查询条件则不会有这种情况

在db/connection类中看到下获取cacheKey的如下实现，发现在查询条件中只要有主键，就会将缓存的key固定设置，而不会再根据其他条件去设置缓存key。
```
protected function getCacheKey(BaseQuery $query): string
    {
        if (!empty($query->getOptions('key'))) {
            $key = 'think:' . $this->getConfig('database') . '.' . $query->getTable() . '|' . $query->getOptions('key');
        } else {
            $key = $query->getQueryGuid();
        }

        return $key;
    }
```

我不明白为什么只要查询条件包含了主键要做这样的限制，是有意为之还是我的用法错误？

**Comment by liu21st** [comment]
因为如果带主键值的话 就是唯一的标识，你是复合主键？

**Comment by qq475281441** [comment]
> 因为如果带主键值的话 就是唯一的标识，你是复合主键？

不是复合主键，我的主键只有一个就是goods_cate_id

**Comment by liu21st** [comment]
你唯一主键的话 其它的查询条件还有啥意义？

**Comment by qq475281441** [comment]
> 你唯一主键的话 其它的查询条件还有啥意义？

我的业务需要限制查询这个主键对应的分类信息，然后限制他只能是三级分类，如果不支持的话我只能先查出这条记录然后从代码中做判断

**Comment by liu21st** [comment]
如果你更新的时候也是根据主键来的话 缓存应该是自动更新的

**Comment by qq475281441** [comment]
好的

**Comment by qq475281441** [comment]
好的，明白了
