### ISSUE TITLE
微信授权跳转callback时session读取为空（在跳转之前写的session）

### ISSUE THREAD

**Issue by terry8650** [top-think/framework#2018]
微信登录网页授权时，登录之前的session，在微信服务器跳转我的callback地址时，读取session为空，确认之前已写session,目录中有值，本地控制器和不同应该之间跳转时可以读到，不存在跨域问题，就是微信服务器跳转时读不到了
` public function login()
    {

         session('tt','sssdfsa');
        //省略微信登录代码........
 }
   public function callback(){
    	dump(session());
//微信跳转到这里读不到任何session了，目录中存在session缓存
}

`

**Comment by terry8650** [comment]
经测试，session read的sessionid和session缓存文件夹中的值不一样，导致读取为空，没有人确认下这个bug吗？微信网页授权微信服务器跳转本地callback时读取session为空

**Comment by momoca** [comment]
callback当然无法使用session了.微信授权跳转的连接上加参数.

**Comment by terry8650** [comment]
> callback当然无法使用session了.微信授权跳转的连接上加参数.
给个callback不能用session的理由，为啥原来的可以？

**Comment by terry8650** [comment]
> callback当然无法使用session了.微信授权跳转的连接上加参数.

写session和读session的是同一个域名下的，为毛不可以？只是跳转到微信api再跳转回来就不可以了？这明显解释不通啊

**Comment by terry8650** [comment]
测试是easywechat的send方法和tp有冲突的地方，手动获取url直接重定向解决了
