### ISSUE TITLE
Model类可能存在的bigint溢出问题

### ISSUE THREAD

**Issue by CantonBolo** [top-think/framework#202]
thinkphp/library/think/Model.php，`writeTransform`和`readTransform`方法，当类型为integer的时候，值可能大于PHP_INT_MAX，导致溢出。
文档：http://php.net/manual/zh/language.types.integer.php
修复方案：http://www.ganzhishi.com/view.asp?id=604

**Comment by liu21st** [comment]
这种情况 自己定义一个修改器和获取器就行了

**Comment by CantonBolo** [comment]
@liu21st 
有一个解决方案：
```php
                if(function_exists('bcadd')) {
                    $value = bcadd($value, 0);
                } elseif (function_exists('gmp_add ')) {
                    $value = gmp_add($value, 0);
                } else {
                    $value = (int) $value;
                }
```
至少保数据写入无错?
