### ISSUE TITLE
TP6.0.0RC4 多应用模式下，路由地址使用完整类名时 Request 使用 controller 和 action 方法返回为空

### ISSUE THREAD

**Issue by unrealsmart** [top-think/framework#2021]
在 `route/main/route.php` 文件中设置如下：
```
Route::any('avatar/store', '\app\common\controller\AvatarStore@store');
```
在对应操作中：
```
dump(request()->controller()); // return is ""
dump(request()->action()); // return is ""
```

打印请求 `dump(request());` ，部分结果如下：

![image](https://user-images.githubusercontent.com/11688458/65813605-3e0b7780-e20a-11e9-82a1-91251c47224d.png)

没有 `controller` 和 `action` 值

补充1：
我以为是`common`应用名称的问题，添加路由：
```
Route::any('demo', 'app\demo\controller\Index@index');
```
输出结果类似于上图，不是名称的问题。

补充2：
使用下面这样的路由没有问题
```
Route::any('adp', 'main/AllConfig/adp');
```
![image](https://user-images.githubusercontent.com/11688458/65813745-d0604b00-e20b-11e9-9612-a80217da2d31.png)

`app`、`controller`、`action`都有正确的值

**Comment by liu21st** [comment]
路由到类的方法是不会解析控制器和操作名的

**Comment by chuoke** [comment]
整了半天，明明看到有 setController，却没有值，这行为太不一致了
