### ISSUE TITLE
tp6注册为全局中间件时，中间件的参数$request对象里控制器和方法名为null (20191007) 

### ISSUE THREAD

**Issue by qiangvei** [top-think/framework#2026]
如题。
注册为路由中间件时控制器和方法名正常
补充：所述问题为多应用模式，单应用下未测试

**Comment by liu21st** [comment]
因为全局中间件的执行顺序在路由之前 所以。。。你可以注册为应用中间件

**Comment by qiangvei** [comment]
> 因为全局中间件的执行顺序在路由之前 所以。。。你可以注册为应用中间件

@liu21st 我是先在应用中间件发现没获取到的，然后再改成全局中间件，也是null，最后改成路由中间件才有值。

**Comment by zfjhui** [comment]
问题是全局中间件 怎么获取request全部信息(习惯在这里做权限认证)   前些天正常,,,昨天更新了一下,,才不能获取的http://www.thinkphp.cn/topic/65932.html

**Comment by liu21st** [comment]
最新的调整对中间件的执行顺序进行了规范，其实验证权限应该按照pathinfo就行了 没必要按照控制器操作，或者你就要往后移动

**Comment by qiangvei** [comment]
我也是在中间件验证权限做跳转，既然框架这样调整，那只能通过$request->server()里的参数自己写方法获取了。

**Comment by mrtwenty** [comment]
这问题我也遇到了，中间件 获取 也是null，后台统一权限 ，在中间件里面做处理，挺好的啊，现在却用不了，只能自己扩展了。

**Comment by zfjhui** [comment]
中间注册到BaseController中,就可以了

**Comment by liu21st** [comment]
最新版本支持在路由配置文件中定义中间件 参考手册中间件章节
