### ISSUE TITLE
ThinkPHP 5.0 RC4 第一次打开就报错

### ISSUE THREAD

**Issue by wangjiaqi** [top-think/framework#203]
打开默认首页，快速F5刷新就会报错
![qq 20160707170342](https://cloud.githubusercontent.com/assets/1821532/16648273/cadd4026-4465-11e6-9ca0-d541fc1e6799.png)

\thinkphp\library\think\log\driver\File.php 58行

快速刷新的时候 $runtime 会是 0，

环境是win7_64 httpd-2.4.23 httpd-2.4.23-64 php-7.0.8-x64

**Comment by CantonBolo** [comment]
不知道官方为什么不把debug注入放到最后：在Response->send()里加入Debug::inject($this);

**Comment by liu21st** [comment]
只能说明 TP5太快了 你的机器性能太高 ^_^ @CantonBolo 这个错误和debug注入无关 是日志里面报的 而日志已经是最后执行的

**Comment by wangjiaqi** [comment]
@liu21st 确实，新买的这电脑配置有点高 :smile:

**Comment by wangjiaqi** [comment]
@liu21st 既然遇到错误了，亲还是处理一下吧，哈哈

**Comment by hetangyuese** [comment]
我之前也是这个情况，后来没有了，难道是我电脑老化了？

**Comment by hainuo** [comment]
@hetangyuese  你装了太多的后台程序了吧。
@liu21st   还是建议做个判断，如果cpu处理真的太快的话，也应该有一个友好的提示而不是 throw error

**Comment by liu21st** [comment]
@hainuo 早就改过了啊
