### ISSUE TITLE
Request获取变量会被覆盖

### ISSUE THREAD

**Issue by caiweiming** [top-think/framework#204]
比如post页面请求地址是：
`http://localhost/public/index.php/admin/config/add/name/test.html`

假如表单中也有一个名为“name”变量，值为“123”，这时候post到上面那个地址时，
`input('param.name')`的结果是123，但是想获得url地址上的name值就没办法了。
不管是`input('get.name')`还是`input('request.name')`都没办法获得url上的name值。

或者有什么办法可以获得url上的name值？

**Comment by caiweiming** [comment]
测试了一下，发现是因为我今天把tp核心框架更新到最新版本，所以input('param.title')获取到的是post里面的数据，而不是url上面的。
我把tp版本换成7月4号发布的就没事。

**Comment by liu21st** [comment]
pathinfo url和路由里面的变量都可以通过 $request->route() 获取

**Comment by caiweiming** [comment]
但是我没更新到昨天的版本之前，`input('param.name')`是可以获取到url上的参数的。
还是上面的例子
`http://localhost/public/index.php/admin/config/add/name/test.html`
表单中有个name变量，值为123
比如方法如下：
`public function add(name = '')
{
    if($this->request->isPost()){
        dump($name); //结果是123
        dump(input('param.name')); //结果是123
        die;
    }
    $this->fetch();
}
`

以上情况是我将tp核心更新到昨天那个版本之后才会的，正常情况下，dump($name)时，应该还是“test”才对，而真实的情况确是post中的name值把add()方法中的name参数值给覆盖了。

在7月4号那个版本就没问题。
是不是以后都要用$request->route()来获取？
@liu21st

**Comment by liu21st** [comment]
param 是获取当前请求的变量 并且当前请求的原始变量会覆盖路由和pathinfo变量，以post请求为例优先顺序是： post变量 > get变量 > 路由变量

**Comment by caiweiming** [comment]
好吧，也就是说，post请求时，function add($name = '')方法中的name参数值会被post变量覆盖是吗？如果要获取pathinfo变量，就要用路由变量来获取，是这个意思对吧。

**Comment by liu21st** [comment]
当然啦 你没事搞两个相同的变量干嘛

**Comment by caiweiming** [comment]
因为这种情况是特殊情况，比如表单中的变量是用户自己创建，用户要创建什么变量名是无法预计的，但pathinfo上又必须要有name这个变量，所以就导致有可能有相同变量的情况了。现在的解决办法要么只能用路由变量来获取，要么只能将pathinfo上的变量取个特殊点的名字了。
