### ISSUE TITLE
ThinkPHP6 Swoole Trace 运行时间 统计异常

### ISSUE THREAD

**Issue by xiaodit** [top-think/framework#2075]
使用 `topthink/think-swoole` 启动服务后 Trace的时间是累计

请求信息 : 2019-10-24 14:55:45 HTTP/1.1 GET : http://localhost:9003/
运行时间 : 79.125552s [ 吞吐率：0.01req/s ] 内存消耗：1,650.65kb 文件加载：176
查询信息 : 0 queries
缓存信息 : 0 reads,0 writes

**Comment by yunwuxin** [comment]
这是think-trace的问题  

可以使用think-debugbar

**Comment by xiaodit** [comment]
好的
