### ISSUE TITLE
tp6 redis缓存BUG 当取出的值为null时，反序列化报错

### ISSUE THREAD

**Issue by pike12138** [top-think/framework#2083]
当使用Cache::get($key)时，取出的值为null
根据\think\cache\driver\Redis.php代码中的get方法
$value = $this->handler->get($this->getCacheKey($name));
        if (false === $value) {
            return $default;
        }
        return $this->unserialize($value);
$value的值为null 它不和false等值。
进行反序列化时报错：不是字符串。

**Comment by liu21st** [comment]
你的null是怎么写入的？

**Comment by pike12138** [comment]
没有写入，在写入之前我需要用用get取值，判断是否存在。
所以相当于我取一个没有写入过的值。

**Comment by hongweipeng** [comment]
@pike12138 你使用的是不是 `\Predis\Client` 的。`composer require predis/predis` 。

tp的redis有两种句柄。我开启php_redis没复现出来。但用`\Predis\Client`就复现出来了。

**Comment by liu21st** [comment]
修正了

**Comment by pike12138** [comment]
> @pike12138 你使用的是不是 `\Predis\Client` 的。`composer require predis/predis` 。
> 
> tp的redis有两种句柄。我开启php_redis没复现出来。但用`\Predis\Client`就复现出来了。

是，我用的是predis
