### ISSUE TITLE
tp6 redis驱动参数类型不符

### ISSUE THREAD

**Issue by lowe21** [top-think/framework#2084]
通过环境变量配置cache
![image](https://user-images.githubusercontent.com/3894346/67661218-9796cb80-f99b-11e9-8eb5-b1728af5a370.png)
![image](https://user-images.githubusercontent.com/3894346/67661253-ada48c00-f99b-11e9-9d79-81b95181f54d.png)
vendor\topthink\framework\src\think\cache\driver\Redis.php 63 : Redis::connect() expects parameter 3 to be float, string given

**Comment by liu21st** [comment]
修正了

**Comment by hongweipeng** [comment]
修正的相关提交：https://github.com/top-think/framework/commit/d9c211f2f8408517453bdead6d4318f715d398e6

因此我关闭这个issue。@lowe21 感谢反馈。
