### ISSUE TITLE
TP6 Log日志写入时,门面类的常量问题

### ISSUE THREAD

**Issue by Liangkk** [top-think/framework#2090]
当时用Log::write 写入日志的时候,Log是一个门面类
此时,如果使用 `Log::write('测试日志',Log::CRITICAL);`记录记录日志的话,IDE可以找到Log::CRITICAL对应的字符串,但是代码执行的时候就会报出 **Undefined class constant 'CRITICAL'** 的错误,因为Log门面类里面没有这个定义,需要使用        ` Log::write('test',\think\Log::CRITICAL);` 才可以正常执行

**Comment by liu21st** [comment]
建议直接使用
Log::critical('测试日志');

**Comment by Liangkk** [comment]
好的,谢谢回复
