### ISSUE TITLE
模型在设置$schema属性时，无法获取自增ID

### ISSUE THREAD

**Issue by rscms** [top-think/framework#2098]
模型在未定义 $schema 属性情况下，是能正常获取到自增ID，
但在设置了$schema后获取不到，返回数据为NULL

tp6.0正式版

$user           = new User;
$user->name     = 'thinkphp';
$user->email    = 'thinkphp@qq.com';
$user->save();
// 获取自增ID
echo $user->id;

**Comment by rscms** [comment]
同：https://github.com/top-think/think-orm/issues/89

**Comment by liu21st** [comment]
改进了下
