### ISSUE TITLE
建议：错误页面在关闭调试时能不能隐藏TP版本信息

### ISSUE THREAD

**Issue by hongweipeng** [top-think/framework#2100]
![image](https://user-images.githubusercontent.com/7546325/68282097-f94de880-00b3-11ea-937d-6c80d86df188.png)

版本信息，在关闭调试时应该隐藏吧。

**Comment by liu21st** [comment]
虽然说可以，但其实后面的官方手册已经暴露了是6.0版本，应该要求项目必须自定义异常页面

**Comment by hongweipeng** [comment]
有道理，感谢回复。
