### ISSUE TITLE
TP6 Collection 的 column 方法参数类型与 array_column 参数类型不一致

### ISSUE THREAD

**Issue by hectorqin** [top-think/framework#2103]
array_column ( array $input , mixed $column_key [, mixed $index_key = NULL ] ) : array

column(string $columnKey, string $indexKey = null)

**Comment by hectorqin** [comment]
在重新索引数组的时候传入$columnKey为null, 调用会报错

**Comment by liu21st** [comment]
已经改进过了的吧

**Comment by liu21st** [comment]
不可能每个修正都马上就发新版的 又不是严重的BUG
