### ISSUE TITLE
6.0 文件下载（download 函数）无法正常下载的问题

### ISSUE THREAD

**Issue by chuanshuo-yongyuan** [top-think/framework#2114]
文件下载的代码：
```
// 需要下载的文件所在目录
$filePath = $this->app->getRootPath() . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR . 'temp';

// 需要下载的文件名
$tmpFile = $filePath . DIRECTORY_SEPARATOR . 'xjG5dK.zip';

// 下载输出的文件名
$download_name = time_format() . '.zip';
```

框架版本：

> v6.0.0,最新安装

PHP 版本：

> PHP 7.2.9

问题：

> 当按照官方文档的写法的时候，文件下载功能无法正常运行（5.1 中正常），服务器报错。作为小白的我，简单的追踪了一下，初步判断可能是保存 cookie 的时候引起的异常，因为当我注释掉：think/Response.php 文件中第 142 行代码：`$this->cookie->save();` 的时候，下载功能就能正常使用了。

日志中报错为：

> [error] [0]Call to a member function save() on null[xxxx/vendor/topthink/framework/src/think/Response.php:142]

**Comment by liu21st** [comment]
这个问题已经修正过的 可以用开发版测试下

**Comment by hongweipeng** [comment]
v6.0.1 发布中已修复此问题，issue可关闭。
