### ISSUE TITLE
模型的静态方法更新问题

### ISSUE THREAD

**Issue by leruge** [top-think/framework#2124]
比如我数据库只有id为1和2的俩条数据，我使用静态方法更新id为3的数据也提示更新成功，这个能解决一下吗、

**Comment by liu21st** [comment]
更新只要没有异常就是成功的 更新id为3的数据 只要你的SQL执行没有错误 就是成功的 是否存在数据需要你自己检查的

**Comment by leruge** [comment]
好吧，我以为更新、插入、删除都是只要影响条数是0，就会抛出异常或者在事务中可以回滚的。
