### ISSUE TITLE
关于SESSION在Redis下的时间问题

### ISSUE THREAD

**Issue by jyxjjj** [top-think/framework#2126]
PHP自带的默认为/tmp目录文件形式的SESSION会在触发GC时清空，几率可以很低，且允许没有过期时间。默认是在cookie中设置过期时间，文件还在。
而Redis本身只会在内存上限等情况下清空数据，设置过期时间后也会在过期时删除数据。
假设当我设置timeout为0，expire为3600，
那TP是否会给session每次访问做续期？
还是说一旦到3600，所有3600前的用户都会掉线一次？
另外这个timeout到底是Redis的过期时间还是连接Redis的超时时间？

**Comment by liu21st** [comment]
每次请求结束的时候都会续期 如果你使用的是file类型 也支持自动GC的
