### ISSUE TITLE
建议单独定义个build_path来指认build 文件的位置 或者默认根目录

### ISSUE THREAD

**Issue by mcmf** [top-think/framework#213]
而不是使用APP_PATH.  /library\think\console\command\build.php 45行, 如果框架改版默认位置 使用php think build 生成的 app_path 和 build.php的文件就会冲突, 如果使用  define('APP_PATH', __DIR__.'/app/'); 则找不到build.php文件  如果使用define('APP_PATH', __DIR__.'/');  则生成的模块文件直接回出现在根目录下  define('BUILD_PATH', __DIR__.'/');

**Comment by liu21st** [comment]
命令行执行指令的时候 build.php 文件的位置是可以指定的
