### ISSUE TITLE
TP6下 验证码扩展库用不了（Session问题）

### ISSUE THREAD

**Issue by liuxiaojinla** [top-think/framework#2130]
TP6下 验证码扩展库用不了（Session问题） ：
主要原因：
因为扩展库里面直接输出图片并终止后续程序执行，造成了中间件end方法没有回调
，从而导致SessionInit中间件 end 回调方法里面 $this->session->save(); 没有调用。所以session一直存储不上，captcha_check也一直返回false.

**Comment by liu21st** [comment]
验证码扩展什么时候中断执行了

**Comment by Lightopus** [comment]
laji，是交钱了会提供好的版本。。。

**Comment by Lightopus** [comment]
都没人回复，没人维护的。。。。

**Comment by liu21st** [comment]
> laji，是交钱了会提供好的版本。。。

说话要负责，框架一直是提供的免费开源版本 没有第二个版本，凭啥一定要回复你呢？服务是免费的？

**Comment by liuxiaojinla** [comment]
> 都没人回复，没人维护的。。。。

不要乱发表，ThinkPHP作为国产开源框加，已经帮助多少程序员就业问题，而且一直免费开源，能做到这一步已经很不容易了，毕竟ThinkPHP官方也有自己的事情要处理，不能实时回复很正常。

**Comment by liuwave** [comment]
@liuxiaojinla  没有出现您所说的情况。 
有可能是您没开启Session功能：https://www.kancloud.cn/manual/thinkphp6_0/1037635
> Session功能默认是没有开启的（API应用通常不需要使用Session），如果你需要使用Seesion，需要在全局的中间件定义文件中加上下面的中间件定义：
> 'think\middleware\SessionInit'

**Comment by liuxiaojinla** [comment]
// Session初始化
	\think\middleware\SessionInit::class
有开启的，我的是多应用模式

**Comment by liuwave** [comment]
我这边也是多应用模式，但是在app/middleware.php内设置的。



---原始邮件---
发件人: "刘小晋啦"<notifications@github.com&gt;
发送时间: 2019年12月10日(周二) 上午10:06
收件人: "top-think/framework"<framework@noreply.github.com&gt;;
抄送: "葡萄架"<liuwave@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [top-think/framework] TP6下 验证码扩展库用不了（Session问题） (#2130)


// Session初始化 \think\middleware\SessionInit::class  
有开启的，我的是多应用模式

**Comment by liuxiaojinla** [comment]
你可以试试放在app/index/middleware.php下面试试

**Comment by liuxiaojinla** [comment]
TP6是不是不推荐使用多应用模式，但是不使用多应用模式的话如何更好的划分各个模块呢？用路由+中间件吗？

**Comment by liuwave** [comment]
简单做了个测试，确实是没有问题。









我想你应该自己先想办法找原因，然后求助的话，把你遇到的问题描述详细一点，不要没头没脑的就说不行。











------------------&nbsp;原始邮件&nbsp;------------------
发件人: "刘小晋啦"<notifications@github.com&gt;; 
发送时间: 2019年12月10日(星期二) 上午10:12
收件人: "top-think/framework"<framework@noreply.github.com&gt;; 
抄送: "刘强"<liuwave@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [top-think/framework] TP6下 验证码扩展库用不了（Session问题） (#2130)




TP6是不是不推荐使用多应用模式，但是不使用多应用模式的话如何更好的划分各个模块呢？用路由+中间件吗？
 
&mdash;

**Comment by liuwave** [comment]
邮件发图片没成功，补一下：
![image](https://user-images.githubusercontent.com/6533126/70489772-a1355680-1b37-11ea-98cc-f5cab58bfd7d.png)
![image](https://user-images.githubusercontent.com/6533126/70489778-a5617400-1b37-11ea-91a4-5cfa3c97acec.png)
![image](https://user-images.githubusercontent.com/6533126/70489785-a7c3ce00-1b37-11ea-84ca-8ab39a4e1a7c.png)
