### ISSUE TITLE
move_uploaded_file() expects parameter 2 to be a valid path, object given

### ISSUE THREAD

**Issue by Git-So** [top-think/framework#2136]
### 错误信息：

move_uploaded_file() expects parameter 2 to be a valid path, object given

### 截图：
![2019-12-09_14-24.png](https://i.loli.net/2019/12/09/Shu6yWOzC1NkPdB.png)

### 如何发生的：

```php
 $test = new \think\File("/var/www/src/public/public/phph4EbdD");
 $test->move('public/uploads/images/20191209/');
```

### 环境信息：

环境： 
+ docker

镜像：
+ php:7.1.33-fpm 
+ nginx:mainline-alpine

thinkphp:
```
$ php think version
v6.0.0
```
### 临时解决方案
```php
(string) $target
```

**Comment by liu21st** [comment]
这个问题已经修正过的 参考 https://github.com/top-think/framework/commit/6bb9cc42288b270e2cc54a2e6ddf35680405eaa5
