### ISSUE TITLE
tp6.0.0的miss路由，不支持多模块设定了么？

### ISSUE THREAD

**Issue by jiuwuxiaohun** [top-think/framework#2138]
tp6.0.0的miss路由，不支持多模块设定了么？
---
Route::miss('index/Index/miss');
方法不存在:app\controller\Index->miss()
---
在5.1的时候，上方代码正常。会路由到index模块的Index控制器的miss方法。

**Comment by liu21st** [comment]
6没有模块的概念 路由也不支持跨应用
