### ISSUE TITLE
关于TP6多应用调试问题

### ISSUE THREAD

**Issue by jasonfanjun** [top-think/framework#2139]
TP6多应用模式下，能否将某个应用设置为调试模式，其他应用非调试模式？
看到文档指引是在根目录一个配置文件，但这样会是全局调试。

**Comment by liu21st** [comment]
每个应用可以单独一个入口 然后在入口文件开启调试模式 手册有提及的

**Comment by jasonfanjun** [comment]
入口文件我有看，每个入口文件单独开启调试模式具体该怎么操作请指点下。谢谢

**Comment by liu21st** [comment]
入口文件调用App类的debug方法即可

**Comment by jasonfanjun** [comment]
debug问题解决感谢，另问：tp6取消别名路由，原定的别名路由有什么办法能够平移过来。例如Route::alias('invoicev1','baibaoyun/Invoicev1');   实际应该路由到baibaoyun这个应用的Invoicev1控制器。多应用模式 在route/route.php中写这句貌似没用了。
