### ISSUE TITLE
增加了“改进Model类的getData和getAttr方法 不存在的属性抛出异常” 反而不合理了

### ISSUE THREAD

**Issue by benaheng** [top-think/framework#215]
项目中所有的数据都是通过模型来获取的，获取后的会增加修改一数据库中不存在的字段
比如： $data['right_button'].='<a '.$right_button['attribute'].'>'.$right_button['title'].'</a> ';
那这个时候就直接报错了：类的属性不存在 :app\common\model\CommonMenu->right_button

虽然可以在模型中定义一下 但每个模型都定义反而麻烦了

**Comment by benaheng** [comment]
我觉得应该加个配置 是否抛出异常，现在这种情况繁琐了好多。

**Comment by liu21st** [comment]
你要获取一个不存在的属性 和 定义了一个未定义变量有什么区别？
