### ISSUE TITLE
tp5.1.38 mysql json类型字段查询sql语句构造问题

### ISSUE THREAD

**Issue by MrCJJW** [top-think/framework#2151]
版本5.1.38
现在版本构造出来的sql json字段是用json_extract函数来查询，但是此函数查询出来的数据是带有""的，如图，是否改为使用->>较为合适？就是因为“”导致in查询不匹配，除非in里面的数据本身也加上""
![image](https://user-images.githubusercontent.com/15009827/71364093-16903500-25d6-11ea-9e5b-59d70bb81241.png)
![image](https://user-images.githubusercontent.com/15009827/71364103-1db74300-25d6-11ea-89b3-9a7d4cbf82ea.png)

**Comment by liu21st** [comment]
可以定义json字段属性的类型

**Comment by MrCJJW** [comment]
类型默认不是字符串吗？我存入数据库的也是数字字符串，而非数字。
```
方式一
改变json字段获取方式，查询结果符合预期
SELECT
	`id`,
	`info_json` ->> '$.bent_cap_specification',
	json_extract(`info_json`,'$.bent_cap_specification'),
	info_json
FROM
	`component_bridge` 
WHERE
	( `belong` = 1348 AND `is_delete` = 0 ) 
	AND `cpt_id` = 1 
	AND `info_json` ->> '$.bent_cap_specification' in ('cs1','1') 
```
![image](https://user-images.githubusercontent.com/15009827/71398229-b98a9280-265a-11ea-985a-3369ec6d8693.png)
```
方式二（同tp构造出来的sql）
查询结果不符合预期
SELECT
	`id`,
	`info_json` ->> '$.bent_cap_specification',
	json_extract(`info_json`,'$.bent_cap_specification'),
	info_json
FROM
	`component_bridge` 
WHERE
	( `belong` = 1348 AND `is_delete` = 0 ) 
	AND `cpt_id` = 1 
	AND json_extract(`info_json`,'$.bent_cap_specification') in ('cs1','1') 
```
![image](https://user-images.githubusercontent.com/15009827/71398264-d4f59d80-265a-11ea-8d04-51ef7e57aa6e.png)
```
方式三
改变in的条件值加上双引号，查询结果符合预期
SELECT
	`id`,
	`info_json` ->> '$.bent_cap_specification',
	json_extract(`info_json`,'$.bent_cap_specification'),
	info_json
FROM
	`component_bridge` 
WHERE
	( `belong` = 1348 AND `is_delete` = 0 ) 
	AND `cpt_id` = 1 
	AND json_extract(`info_json`,'$.bent_cap_specification') in ('"cs1"','"1"') 
```
![image](https://user-images.githubusercontent.com/15009827/71398309-f6ef2000-265a-11ea-8d9c-657811f6dd6a.png)
