### ISSUE TITLE
多次延迟预载入 php5.6 报错

### ISSUE THREAD

**Issue by 745162202** [top-think/framework#2174]
https://github.com/top-think/framework/blob/e61b34ceca2fb46f2d1319d5b1a956ef6907e8f3/library/think/model/Collection.php#L28

多次调用会有指针问题，第二次调用 current 会返回 false，第二次调用前需要 reset 重置指针。

**Comment by liu21st** [comment]
也没必要多次调用啊 本来relation参数就支持传入数组

**Comment by 745162202** [comment]
传入数组是没问题，只是钻了下牛角尖
