### ISSUE TITLE
建议可更改env的名称和路径

### ISSUE THREAD

**Issue by sorshion** [top-think/framework#2176]

**Comment by liu21st** [comment]
可以在公共文件里面自己加载的

**Comment by sorshion** [comment]
感谢回复，但是我在src/think/App.php 里面看到是：
// 加载环境
if (is_file($this->rootPath . '.env)) {
    $this->env->load($this->rootPath . '.env');
}

所以，我想请问如何加载自定义的env名称和路径？

**Comment by liu21st** [comment]
你在全局common文件自己加这行代码就行了 随便你放什么位置env文件
