### ISSUE TITLE
使用inc和dec进行数字加减的问题

### ISSUE THREAD

**Issue by Ulyssesyi** [top-think/framework#2179]
在模型中如果使用$model->a +=5得方法将a+5，假设a这时等于10，生成得sql语句update xx set a = 15。如果获取数据和更新数据中间有较多流程得话，很容易出现更新前，a的值已经被其他的地方更新成5了，实际结果就出错了。所以tp提供了$model->a = ['inc', 5]得方法使得生成sql语句为update xx set a = a+5。

**但是这时如果你在model中定义了$type=['a'=>'integer']的话，再setAttr时会将['inc', 5]数组强转为数字1。希望新版本能修复这个bug**

**Comment by big-dream** [comment]
可以试试用`Db::exp()`或`Db::raw()`，参考手册：https://www.kancloud.cn/manual/thinkphp6_0/1037535

**Comment by Ulyssesyi** [comment]
Db::raw可以
