### ISSUE TITLE
move_uploaded_file() expects parameter 2 to be a valid path, object given

### ISSUE THREAD

**Issue by lazzzy18** [top-think/framework#2185]
#2136 并未完全修复。

https://github.com/top-think/framework/commit/6bb9cc42288b270e2cc54a2e6ddf35680405eaa5 中修复的是 src/think/File.php

而[src/think/file/UploadedFile.php](https://github.com/top-think/framework/blob/6.0/src/think/file/UploadedFile.php)
https://github.com/top-think/framework/blob/7908de7e6a0a2207c14c6c7b431ec7f781e45511/src/think/file/UploadedFile.php#L63
https://github.com/top-think/framework/blob/7908de7e6a0a2207c14c6c7b431ec7f781e45511/src/think/file/UploadedFile.php#L69
 中的 move函数也存在类似问题

**Comment by liu21st** [comment]
已修复
