### ISSUE TITLE
国内composer安装非常波折，最后git超时，请问还有其他安装方法吗？

### ISSUE THREAD

**Issue by zimri-j** [top-think/framework#2204]
本地服务器、本级开发环境
网络：无梯国内电信
系统：CentOS7.7 CentOS8
环境1:
WebServer:OpenLiteSpeed
lsPHP:php PHP 7.4.3 (cli) (built: Feb 28 2020 16:08:06) ( NTS )
Composer version 1.10.1 2020-03-13 20:34:27

环境2:
WebServer:宝塔Apache2.4
php PHP 73
Composer version 1.10.1 2020-03-13 20:34:27

问题1:
Composer大概花了3个小时 才下载成功。 

问题2:
CentOS root下：
Do not run Composer as root/super user! See https://getcomposer.org/root for detail

问题3:
执行`composer create-project topthink/think tp`后 红色报错
 git remote set-url composer 'https://github.com/top-think/think.git'" exceeded the timeout of 300 s  

源尝试过 
composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
和
composer config repo.packagist composer https://mirrors.aliyun.com/composer/

很多人说   Composer 很好配置，我相信 是的，但我没有机会体验。 
请问除了Composer安装thinkphp6 还有其他办法吗？ 真的无解

**Comment by momoca** [comment]
你的写法错误了吧.亲.官方文档安装步骤里有.

**Comment by hongweipeng** [comment]
用国内的源讲道理不会这么慢啊

**Comment by zimri-j** [comment]
> 你的写法错误了吧.亲.官方文档安装步骤里有.

感谢提醒，检查了 语法问题不大。 经过几天的研究，我当地DNS可能已经封锁了git 所以一直超时。封锁也说不上，因为能通但速度只有70B/s 对没错 就是70B/s 连1Kb/s都到不了

**Comment by zimri-j** [comment]
> 用国内的源讲道理不会这么慢啊

嗯嗯  我这里git 被限速了， 是git拉取超时  最后还是忍不住挂梯子了

**Comment by momoca** [comment]
你用国内的源也是被限制?比如ali的?

**Comment by benhuang1024** [comment]
更换 composer 源后，尝试 composer clear 清理，同时移除 composer.lock 文件试下
