### ISSUE TITLE
大佬，您好，请问下路由加载能否改成 ：可以加载route目录下子目录中的路由配置。这样的话，能否使得路由配置目录更加清晰。

### ISSUE THREAD

**Issue by Guo-Hongfu** [top-think/framework#2208]
https://github.com/top-think/framework/blob/d34a695466611cb167505fa2bf991d9b8a65a9b8/src/think/Http.php#L231

**Comment by momoca** [comment]
早就有人提过了.官方是不认可这种做法的.

**Comment by momoca** [comment]
其实还有好多方法呀.比如注释路由.
