### ISSUE TITLE
HasMany中的 hasWhere 中无法指定 join连接方式

### ISSUE THREAD

**Issue by zsboss** [top-think/framework#2210]
HasMany中的 hasWhere 中无法指定 join方式，
public function hasWhere($where = [], $fields = null, string $joinType = '', Query $query = null)
参数中有joinType 但是在方法中并没有使用
return $query->group($model . '.' . $this->localKey)
            ->field($fields)
            ->join([$table => $relation], $model . '.' . $this->localKey . '=' . $relation . '.' . $this->foreignKey)
            ->when($softDelete, function ($query) use ($softDelete, $relation) {
                $query->where($relation . strstr($softDelete[0], '.'), '=' == $softDelete[1][0] ? $softDelete[1][1] : null);
            })
            ->where($where);

**Comment by liu21st** [comment]
已经改进的
