### ISSUE TITLE
TP6.0.2 中间件使用$request->param(),$request->input(),会导致路由传的参数变成空数组

### ISSUE THREAD

**Issue by WongYueKeung** [top-think/framework#2220]
如果定义了路由参数，使用中间件时用了request助手的param()或者input()方法查看参数，会导致控制器的request()->param()结果为一个空白数组，路由传来的值全没了
在全新的最新的tp6.0.2 win64 php7.4
步骤1 键个新的tp6
在app\controller\index 随便建个方法比如
```
public function subject($subject_code = null){
        dump(request()->param());
    }
```
在路由route/app.php
加上传参
Route::get('subject/:subject_code', 'index/subject');
这时候访问http://tp6.com/subject/9006
结果：
```
^ array:1 [▼
  "subject_code" => "9006"
]
```
创建个中间件
app/middleware/CheckUserParam.php
内容为
```
namespace app\middleware;
class CheckUserParam
{
    public function handle($request, \Closure $next)
    {

        $request->param();

        return $next($request);
    }
}
```
注册下中间件
app/middleware.php
```
<?php
// 全局中间件定义文件
return [
    // 全局请求缓存
    // \think\middleware\CheckRequestCache::class,
    // 多语言加载
    // \think\middleware\LoadLangPack::class,
    // Session初始化
    // \think\middleware\SessionInit::class

    '\app\middleware\CheckUserParam',

];

```

这时候访问http://tp6.com/subject/9006
结果：
`^ []`
变成了空数组
控制器从路由接收的参数变成了空数组，而我只是在中间件用$request()->param()查看了下参数
。。。
也顺便看看会不会有其他的隐藏问题

**Comment by liu21st** [comment]
这个问题 最新的开发版有改进过 可以重新测试下
