### ISSUE TITLE
关于路由配置的一点疑问

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#223]
经过测试, 发现目前框架暂不支持模块路由配置.
但是在 `config.php` 的 `extra_config_list` 参数中指定了路由配置, 模块下也同样会去加载 模块下的 `route` 配置文件
此时的 `route` 配置并不会生效

**Comment by liu21st** [comment]
加载模块配置的时候路由检测已经完成了 当然不会生效了

**Comment by cbwfree** [comment]
@liu21st
那该如何设置分组的路由呢?

我在路由中配置了如下规则:
```
    '[admin]'     => [
        'index' => 'admin/index/index',     // 后台首页
        'login' => 'admin/login/index',     // 登录页面
    ]
```
上面的规则能够正常的生成对应的URL, 也能正常访问.
但是在访问后台首页时, 用 `http://www.xxx.com/admin/` 访问的页面却是 `/index/index/index.html` 的内容, 而不是后台首页

**Comment by liu21st** [comment]
@cbwfree 路由分组和模块没有直接关系

**Comment by momoca** [comment]
route.php是要统一配置的.如果在模块中可以使用动态注册路由呀.
