### ISSUE TITLE
常驻内存下 Str 类会导致内存不断上涨

### ISSUE THREAD

**Issue by hongweipeng** [top-think/framework#2231]
这主要是针对结合 workerman 这种常驻内存运行方式。`think\helper\Str` 用静态变量做缓存，没有及时释放，导致内存泄露。

可以结合 LRU 的机制控制缓存大小。

**Comment by hongweipeng** [comment]
或者不要那些充当缓存的静态变量了。

**Comment by yunwuxin** [comment]
Str只有转驼峰那里使用了静态变量缓存了   
除非你每次请求的时候 都有一个新的字符串需要 驼峰转换的操作  内存才会持续上涨

**Comment by hongweipeng** [comment]
所以这个问题就不处理了？

**Comment by yunwuxin** [comment]
不需要处理    这里在框架本身并不会造成内存持续上涨

如果你业务上需要对无限量的字符串进行驼峰转换的话，可以自行转换(这种情况也是极少)

**Comment by hongweipeng** [comment]
好的，了解。
