### ISSUE TITLE
tp6 向控制器中间件传参报错

### ISSUE THREAD

**Issue by s825799354** [top-think/framework#2234]
### 报错如下

![11](https://user-images.githubusercontent.com/60286005/79770618-3d7e2e00-8360-11ea-966f-0a68705141c3.png)
vendor\topthink\framework\src\think\Middleware.php 142行
### 按照如下写法传参，

```php
//route.php
use think\facade\Route;
Route::get('index',"index/index");

//控制器
class Index extends BaseController {

    protected $middleware = [
        'app\middleware\RegCheck:test_value'=>['only' 		=> ['index'] ],
    ];
    public function index(Request $request,User $user){
        var_dump($user);
    }
   
}
//中间件
namespace app\middleware;

class RegCheck
{
    /**
     * 处理请求
     *
     * @param \think\Request $request
     * @param \Closure $next
     * @return mixed
     */
    public function handle($request, \Closure $next, $test_key = '')
    {
        file_put_contents('1.txt',$test_key);
        return $next($request);

    }
}
## 错误是在 注册控制器中间件，调度管道时发生的，因为可变参数的写法不支持传入字符串
## 请问如何使用protected $middleware的写法向控制器中间件传参

**Comment by hongweipeng** [comment]
6.0.2也复现

**Comment by ouyanglingyun** [comment]
是否应该这样？   
 public function pipeline(string $type = 'global')
    {

        return (new Pipeline())
            ->through(array_map(function ($middleware) {
                return function ($request, $next) use ($middleware) {
                    [$call, $params] = $middleware;
                    if (is_array($call) && is_string($call[0])) {
                        $call = [$this->app->make($call[0]), $call[1]];
                    }
                    $params   = (array) $params;
                    $response = call_user_func($call, $request, $next, ...$params);
                    // $response = call_user_func($call, $request, $next, $params);

                    if (!$response instanceof Response) {
                        throw new LogicException('The middleware must return Response instance');
                    }
                    return $response;
                };
            }, $this->sortMiddleware($this->queue[$type] ?? [])))
            ->whenException([$this, 'handleException']);
    }

**Comment by s825799354** [comment]
> ## 问题描述：使用tp6，向控制器中间件传参数时，按照tp6手册demo使用出错，
> ### 环境
> #### php:7.2
> #### thinkphp 6.0.0
> ### 报错如下
> ![11](https://user-images.githubusercontent.com/60286005/79770618-3d7e2e00-8360-11ea-966f-0a68705141c3.png)
> vendor\topthink\framework\src\think\Middleware.php 142行
> 
> ### 按照如下写法传参，
> ```
> //route.php
> use think\facade\Route;
> Route::get('index',"index/index");
> 
> //控制器
> class Index extends BaseController {
> 
>     protected $middleware = [
>         'app\middleware\RegCheck:test_value'=>['only' 		=> ['index'] ],
>     ];
>     public function index(Request $request,User $user){
>         var_dump($user);
>     }
>    
> }
> //中间件
> namespace app\middleware;
> 
> class RegCheck
> {
>     /**
>      * 处理请求
>      *
>      * @param \think\Request $request
>      * @param \Closure $next
>      * @return mixed
>      */
>     public function handle($request, \Closure $next, $test_key = '')
>     {
>         file_put_contents('1.txt',$test_key);
>         return $next($request);
> 
>     }
> }
> ## 错误是在 注册控制器中间件，调度管道时发生的，因为可变参数的写法不支持传入字符串
> ## 请问如何使用protected $middleware的写法向控制器中间件传参
> ```

测试

**Comment by s825799354** [comment]
嗯 是的，而且注册控制器中间件那块也需要修改，具体修改有人完成了，https://github.com/top-think/framework/pull/2235/commits/190754af1af70c62e758e1f3a7683b29a9383485
