### ISSUE TITLE
5.0.24 缓存报unserialize的offset错误

### ISSUE THREAD

**Issue by csensix** [top-think/framework#2237]
```
115        if (false !== $content) {
116             $expire = (int) substr($content, 8, 12);
117             if (0 != $expire && time() > filemtime($filename) + $expire) {
118                 return $default;
119             }
120             $this->expire = $expire;
121             $content      = substr($content, 32);
122             if ($this->options['data_compress'] && function_exists('gzcompress')) {
123                 //启用数据压缩
124                 $content = gzuncompress($content);
125             }
126             $content = unserialize($content);
127             return $content;
128         } else {
129             return $default;
130         }
````
运行一段时间之后，就会报错：`unserialize()：Error at offset 16352 of 65807 bytes`，`ErrorException in File.php line 126`。

清除缓存后可以恢复正常访问，但过段时间还是会出现。请问是什么原因呢？

**Comment by hongweipeng** [comment]
5.0不在维护期了，不过我挺感兴趣的，我有的项目依然跑着5.0，你能提供下复现的方式吗？

**Comment by csensix** [comment]
> 5.0不在维护期了，不过我挺感兴趣的，我有的项目依然跑着5.0，你能提供下复现的方式吗？

由于这个问题是偶尔出现，通过对出错的缓存文件分析之后，找到了出错的片段：

`a:12:{s:5:"gc_id";i:_parent_id";i:8;s:11:"commis_rate";d:1;s:7:"gc_sort";i:255;s:10:"gc_virtual";i:0;s:8:"gc_title";N;s:11:"gc_keywords";s:0:"";s:14:"gc_description";s:0:"";s:7:"gc_show";i:1;};`

`a:12:{s:5:"gc_id";i:1403;s:7:"gc_name";s:27:"门禁考勤器材及系统";s:7:"type_id";i:1;s:9:"type_name";s:6:"联动";s:12:"gc_parent_id";i:8;s:11:"commis_rate";d:1;s:7:"gc_sort";i:255;s:10:"gc_virtual";i:0;s:8:"gc_title";N;s:11:"gc_keywords";s:0:"";s:14:"gc_description";s:0:"";s:7:"gc_show";i:1;};`
下面一段是正常的，上面第一段从gc_id到parent_id 这段中间有内容缺失了，所以导致反序列化错误。

希望能帮忙看下是什么问题，谢谢。

**Comment by hongweipeng** [comment]
那可能是并发下的文件写入冲突了。你试下在 `file_put_contents` 中加锁看看还会不会：

细节见：https://github.com/hongweipeng/framework/pull/1/files

**Comment by csensix** [comment]
> 那可能是并发下的文件写入冲突了。你试下在 `file_put_contents` 中加锁看看还会不会：
> 
> 细节见：https://github.com/hongweipeng/framework/pull/1/files

按照你的建议修改了，最近两天没有再出现之前的问题。后面我们还会继续观察几天。非常感谢！

**Comment by hongweipeng** [comment]
@csensix 有结果还请麻烦告知下。我这边用ab测试并发，没加锁的情况下也没能复现出这个问题。我这边无法验证修复办法是否有效。

**Comment by csensix** [comment]
@hongweipeng 目前为止没有再出现之前的问题，感觉应该是解决了。后续如果还有类似问题出现，我会第一时间告知你。十分感谢！
ps：将缓存换成redis的话也不会出问题。

**Comment by hongweipeng** [comment]
收到，感谢反馈。

**Comment by csensix** [comment]
@hongweipeng 过了差不多一个月，没再出现问题，应该是解决了。再次表示感谢！

**Comment by hongweipeng** [comment]
good!
