### ISSUE TITLE
【5.1.39】Collection::column 方法返回空数组

### ISSUE THREAD

**Issue by marx88** [top-think/framework#2241]
TP版本：`5.1.39`

问题描述：使用`Model::select()->column('字段名')`返回空数组

产生原因：看官方函数说明[array_column](https://www.php.net/manual/zh/function.array-column.php)，`array_column`方法在`php7`下，第一个参数可以是包含对象的数组，而`php5.6`无法处理包含对象的数组，所以返回空

不同版本下返回结果验证：
![20D65E97-06CB-4e24-B64A-CF80DFA057F5](https://user-images.githubusercontent.com/11767707/80077682-6a109080-8580-11ea-89ee-7ad93a1782ae.png)

**Comment by liu21st** [comment]
修正了
