### ISSUE TITLE
验证器 字段描述不支持多语言

### ISSUE THREAD

**Issue by ouyanglingyun** [top-think/framework#2256]

**Comment by 18y** [comment]
支持的
![image](https://user-images.githubusercontent.com/22790765/87772327-2ada9e80-c854-11ea-9b89-5cd42fbfe79f.png)

**Comment by ouyanglingyun** [comment]
> 
> 
> 支持的
> ![image](https://user-images.githubusercontent.com/22790765/87772327-2ada9e80-c854-11ea-9b89-5cd42fbfe79f.png)

我说的是验证器中的 字段描述 不是你说的这个 错误提示信息

当前我是在 vendor\topthink\framework\src\think\Validate.php 第 494 行加入 $title = $this->lang->get($title);

**Comment by ouyanglingyun** [comment]
> 
> 
> 支持的
> ![image](https://user-images.githubusercontent.com/22790765/87772327-2ada9e80-c854-11ea-9b89-5cd42fbfe79f.png)

我说的是验证器中的字段描述

**Comment by liu21st** [comment]
字段描述本来就是一个可选项 验证信息多语言后 就不需要了
