### ISSUE TITLE
Container 中的make方法,已经存在则不会直接获取，还是会创建对象

### ISSUE THREAD

**Issue by huan-xi** [top-think/framework#2259]
swoole模式启动在Container getObjectParam方法中绑定参数,还是会重新实例化对象，改成下面这种方式就不会。希望能解决一下这个问题
![image](https://user-images.githubusercontent.com/38528425/81670416-28398280-947a-11ea-8f39-5614e8b46d5e.png)

service中有绑定ab
![image](https://user-images.githubusercontent.com/38528425/81670787-b281e680-947a-11ea-9f98-f69fed636b6a.png)
在控制器方法中注入的时候，还是会重新实例化对象
![image](https://user-images.githubusercontent.com/38528425/81670828-c3caf300-947a-11ea-89ae-129d70ab6171.png)

**Comment by yunwuxin** [comment]
meke方法对已存在的对象是不会重新实例化的
![image](https://user-images.githubusercontent.com/2168125/81672000-1fe24700-947c-11ea-9bd7-5febe62c091b.png)

**Comment by yunwuxin** [comment]
你的bind用法不对

你只是把TopComment这个对象绑定在了ab这个字符串标记上  

而下面依赖的是TopComment这个类  容器里并没有他的实例   当然会实例化

你可以看一下bind方法

**Comment by huan-xi** [comment]
这个是只能通过类名绑定到容器吗

**Comment by huan-xi** [comment]
这样绑定确实可以取到，要是可以直接绑定对象就好了
![image](https://user-images.githubusercontent.com/38528425/81757618-0c71c300-94f2-11ea-84d7-b04e4cb57edd.png)

**Comment by yunwuxin** [comment]
不就是直接绑定的对象么  

至于对象绑定到哪里 是你第一个参数决定的

你最上面是绑定到了ab这个字符串上  你照样可以通过$app->get('ab');来获取 

可是依赖注入是通过你依赖的类名来获取的  所以你要绑定到你依赖的类名上(这个类名是可以和对象的类名不一样的，比如可以是一个接口)

**Comment by huan-xi** [comment]
好的，感谢
