### ISSUE TITLE
全局过滤需要先实例化这样不好

### ISSUE THREAD

**Issue by wapele** [top-think/framework#226]
如果需要'default_filter'         => 'htmlspecialchars', 定义生效就必须使用先进行实例化
$request=new \think\Request();
$request->param('test');
但是文档的
\think\Request::instance()->param('test');
就无法使用 
改进方案
instance()方法的时候就需要先载入default_fiter

**Comment by liu21st** [comment]
不是有么 实例化方法里面有读取default_filter

**Comment by liu21st** [comment]
哦 这里有个问题 我修正下

**Comment by liu21st** [comment]
已经修正
