### ISSUE TITLE
多了个括号

### ISSUE THREAD

**Issue by fansUI** [top-think/framework#2265]
https://github.com/top-think/framework/blob/5.1/library/think/db/connector/Mysql.php
第一百行

**Comment by fansUI** [comment]
5.1版

**Comment by fansUI** [comment]
https://github.com/top-think/framework/blob/5.1/library/think/db/connector/Mysql.php
第一百行

**Comment by phpyii** [comment]
@fansUI  什么括号 没发现

**Comment by fansUI** [comment]
@phpyii 改了吧应该
