### ISSUE TITLE
需要能清理过期缓存文件的指令

### ISSUE THREAD

**Issue by hongweipeng** [top-think/framework#2283]
文件缓存缺少过期清理机制，虽然有 `php think clear --cache` 但它会将所有缓存文件都删掉，影响线上使用。

能不能提供个新的参数只删除过期缓存，比如 `php think clear --cache --expire` ？

**Comment by wolf-leo** [comment]
都过期了 何不自动清理？

**Comment by hongweipeng** [comment]
@wolf-leo 有什么好办法？
