### ISSUE TITLE
识别多语言切换问题，希望完善一下

### ISSUE THREAD

**Issue by diankemao** [top-think/framework#2287]
目前国际化只支持：GET变量获取、Cookie变量获取，唯一不支持header变量获取，目前API时代，很少使用Cookie，而且GET不怎么方便呢，希望在头部header 增加lang变量识别多语言切换；
@liu21st  @yunwuxin 5.1版本， 6.0版本希望完善一下，谢谢

**Comment by kuaitukeji** [comment]
5.1版本， 6.0版本希望完善一下

**Comment by hongfs** [comment]
#2293

**Comment by diankemao** [comment]
希望在头部header 增加lang变量识别多语言切换,
 或者
在头部增加一个可以自定义的字段 例如 lang 去识别多语言切换,

**Comment by liu21st** [comment]
改进了
