### ISSUE TITLE
tp6 火绒误报病毒

### ISSUE THREAD

**Issue by hbh112233abc** [top-think/framework#2289]
![TIM图片20200617153418](https://user-images.githubusercontent.com/7788164/84868975-0900c700-b0b0-11ea-811c-7e434d0d1fb3.png)
误报原因是检测到`exec()`
不懂php的领导会因为误报来说事.

建议方法名改为:`execute`

**Comment by yunwuxin** [comment]
这个问题我觉得应该是去火绒那边反馈
