### ISSUE TITLE
版本 6.0.3 路由错误

### ISSUE THREAD

**Issue by yanwenwu** [top-think/framework#2298]
版本 6.0.3 路由错误:

原因：设置 `resource` 路由导致路由解析错误。

框架默认使用 `@` 作为分隔符解析。

问题出现在 resource 路由解析部分。修改其 分隔符即可！

**Comment by liu21st** [comment]
框架什么时候默认使用 @ 作为分隔符了 那是不同的用法 一个是调用类的方法 一个是执行控制器/操作。最好能给出重现的代码示例

**Comment by yanwenwu** [comment]
路由到类的方法这里的判断是使用 @ 作为判断符号的吧
<img src="https://cdn.learnku.com/uploads/images/202006/26/18206/H0qB1wuaP7.jpg!large">
但是到了 reource 路由这里 就变成了  `/` 了, **这里的 @ 是我自己修改的，不用在意，实际 / **
<img src="https://cdn.learnku.com/uploads/images/202006/26/18206/hOOppI5GxE.jpg!large">
所以导致 resource 路由解析错误，例如这样的
```
 $router->resource('config', '\catchAdmin\system\controller\Config');
```

个人使用的，例如下面使用 @ 符号的就是正常可访问
```
 $router->get('', '\catchAdmin\wechat\controller\Users@index');
```

**Comment by liu21st** [comment]
这根本就是两个不同的路由地址 你仔细看下手册的用法
