### ISSUE TITLE
升级至6.0.3后OPTIONS请求出现异常

### ISSUE THREAD

**Issue by kainonly** [top-think/framework#2299]
升级至6.0.3后

当开启DEBUG时，以 OPTIONS 请求访问控制器定义的 URL 会出现 `Error: Parse Error: Expected HTTP` 的异常

当关闭DEBUG后，则可以正常返回 `204 No Content`

如果通过路由去定义控制器已定义的URL，此时再去以 OPTIONS 请求无论是否为DEBUG模式，都能正常返回

**Comment by yunwuxin** [comment]
详细的错误信息发一下

**Comment by kainonly** [comment]
例如，定义的控制器：

![image](https://user-images.githubusercontent.com/9986159/85946024-2a956480-b974-11ea-84eb-f73c902441ae.png)

GET请求

![image](https://user-images.githubusercontent.com/9986159/85946056-5fa1b700-b974-11ea-9edf-7699a4915a47.png)

当 `env` 内的 APP_DEBUG=true时，以OPTIONS请求失败

![image](https://user-images.githubusercontent.com/9986159/85946101-9677cd00-b974-11ea-9b7d-c5b71c48253a.png)

当 APP_DEBUG=false时，以OPTIONS请求正常

![image](https://user-images.githubusercontent.com/9986159/85946137-c626d500-b974-11ea-8e0d-975bbfc990ff.png)

如果使用路由定义覆盖控制器URL，则OPTIONS请求无论是否为DEBUG模式都可以正常

![image](https://user-images.githubusercontent.com/9986159/85946214-63820900-b975-11ea-80c3-41e13ab004a0.png)
![image](https://user-images.githubusercontent.com/9986159/85946225-7eed1400-b975-11ea-87bc-cd23b39821c6.png)

**Comment by edenleung** [comment]
确实有这情况

**Comment by yunwuxin** [comment]
测试下来 是think-trace的bug  把这个扩展卸载掉就可以了

**Comment by liu21st** [comment]
已经改进think-trace

**Comment by kainonly** [comment]
好的
