### ISSUE TITLE
6.0.3版本的URL生成问题

### ISSUE THREAD

**Issue by midsmr** [top-think/framework#2313]
多应用模式下生成URL
index应用
`Route::get('test', 'index/index')->name('index')`
config/app.php设置应用映射
映射index应用为test
在index应用使用url生成
`Route::buildUrl('index')`
会生成`index/test`而非`test/test`
也就是说6版本是采取应用目录名来生成
并不是按照应用映射里的应用名来生成
这就导致了映射过后的应用
前端ajax地址以及跳转地址无法通过url生成来生成绝对地址

**Comment by liu21st** [comment]
已经修正
