### ISSUE TITLE
关于多域名布署时路由分组失效的问题

### ISSUE THREAD

**Issue by 5ini99** [top-think/framework#232]
刚更新代码后发现之前配置的路由失效了，对比了一下文件发现是\library\think\Route.php的第928行引发的

```
$url = (empty(self::$domain) ? $bind . '/' : '') . ltrim($url, '/');
```

我的路由配置文件类似这样的

```
return [
    '__domain__' => [
        'a' => 'api',
        'b' => 'admin',
    ],
    '[admin]'    => [
        'bbs/index'         => '/bbs.html',
        'index/index'       => '/index.html',
    ],
];
```

如果将\library\think\Route.php的第928行
还原成

```
$url = self::$bind['module'] . '/' . ltrim($url, '/');
```

即正常。希望官方能看一下是不是bug

**Comment by liu21st** [comment]
域名绑定不支持绑定到分组了，直接把域名的路由规则定义就行，例如：
~~~
'__domain__' =>[
 'b'=>[
    'bbs/index' => '/bbs.html',
    'index/index' => '/index.html',
 ]
]
~~~

**Comment by liu21st** [comment]
关于这部分 官方的开发手册中有更新说明的

**Comment by 5ini99** [comment]
@liu21st 
老大，我用了上面的方法确实可以用了，但是
`'__domain__' =>[
‘b’=>'api',
 'b'=>[
    'bbs/index' => '/bbs.html',
    'index/index' => '/index.html',
 ]
]`
第一行的域名部署规则和域名的路由规则就冲突了，不知道是不是我理解的不对

**Comment by liu21st** [comment]
在第二个里面单独定义 '__auto__'=>'api' 外面的 'b'=>'api' 去掉

**Comment by 5ini99** [comment]
@liu21st 老大英明，我配置好了。有个小问题就是auto貌似是带双下划线的
```
'__domain__' =>[
 'b'=>[
    '__auto__'  => 'admin',
    'bbs/index' => '/bbs.html',
    'index/index' => '/index.html',
 ]
]
```
还有就是用url方法生成的链接有问题，都是带模块名的。
