### ISSUE TITLE
TP6代理转发的时候，如何拿到真实ip   proxyServerIp

### ISSUE THREAD

**Issue by aogg** [top-think/framework#2330]
request()->ip()根本无法获取真实ip  
哪怕nginx代理都设置正确，还要代码里设置proxyServerIp，但为什么proxyServerIp属于却不提供public的设置方法，也没有环境变量  
而且文档说明也没有  

![image](https://user-images.githubusercontent.com/8998031/88260857-ca39de80-ccf7-11ea-89f4-a71d1bf6e71d.png)

**Comment by qq475281441** [comment]
这很明显是一个bug，官方还没修复

**Comment by liu21st** [comment]
Request类是没有配置参数的 proxyServerIp属性就是在你的项目的Request类里面定义

**Comment by qq475281441** [comment]
意思是我用动态加速或者cdn还得找运营商拿到他们的服务器IP吗

**Comment by yunwuxin** [comment]
app下也有个Request里  重写下这个属性就可以了
