### ISSUE TITLE
tp6 withjoin查询报错问题

### ISSUE THREAD

**Issue by rehack** [top-think/framework#2357]
报错信息：
<pre>
message: "SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'create_time' in where clause is ambiguous"
</pre>
报错代码：
<pre>
public function clientinfo(){
        $prams = Request::param();
        $where = [];
        if($prams['create_time']){
            $where[] = ['create_time', 'between time', $prams['create_time']];
        }
        $res = CustomerModel::withJoin(['developer'=>['realname']])->where($where)->paginate([
            'list_rows'=> $prams['pageSize'],//每页数量
            'var_page' => 'currentPage',
            'query' => Request::param()
        ]);
        return json($res);
    }
</pre>
问题排查：
可能是因为withJoin关联模型developer用也存在一个create_time字段和CustomerModel的create_time字段冲突了
尝试把withJoin中的关联模型换成一个没有create_time字段的模式，此报错就没有了
不知道这是否是一个bug.

![1](https://user-images.githubusercontent.com/9047357/90976115-010c4a00-e56d-11ea-8578-7485858edfa8.png)
![2](https://user-images.githubusercontent.com/9047357/90976119-05d0fe00-e56d-11ea-9160-d5f9578ec54a.png)

**Comment by big-dream** [comment]
字段重复的情况下，可以加入表名/表别名
