### ISSUE TITLE
hasMany后边跟group

### ISSUE THREAD

**Issue by liokami** [top-think/framework#2358]
```
class User extends Model
{
    public function getinfo(){
        return  $this->hasMany('Info')->group('gr')->field("*,group_concat(info_name),group_concat(info_id)");
    }

    public function userinfo(){
        return $this->with(['getinfo'])->select();
    }

}
```
数据表及数据结果：https://s1.ax1x.com/2020/08/24/dBbLTI.jpg
是不支持这种写方法还是怎么样，如果我想要达到这样的结果需要怎么写。
版本：5.0.21

**Comment by yzh52521** [comment]
public function getinfo(){
        return  $this->hasMany('Info')->group('uid,gr')->field("*,group_concat(info_name),group_concat(info_id)");
    }
