### ISSUE TITLE
2006 MySQL server has gone away  翻源码找到问题了

### ISSUE THREAD

**Issue by doesDWQ** [top-think/framework#2375]
: General error: 2006 MySQL server has gone away[/var/www/vendor/topthink/think-orm/src/db/PDOConnection.php:1403]

在配合使用think-swoole think-orm长链接的时候使用create，并且连续存储数据时会导致后续数据无法插入，空闲时间超过mysql的interactive_timeout时(测试时将这个参数设置成了5，超时时会报这个错)，
发现代码的一处问题，递归写法导致：

旧的代码：
![image](https://user-images.githubusercontent.com/24455112/93472313-0e77e280-f927-11ea-8ed1-2964484ac252.png)
修改后的代码：
![image](https://user-images.githubusercontent.com/24455112/93472437-39623680-f927-11ea-8567-3cc211bee264.png)

**Comment by liu21st** [comment]
这个问题早就修正过的
