### ISSUE TITLE
缓存标签无法清理。redis驱动多了一行代码。就一行

### ISSUE THREAD

**Issue by k713927** [top-think/framework#2386]
`Cache::tag('tag')->set('name1','value1');
Cache::tag('tag')->set('name2','value2');

// 清除tag标签的缓存数据
Cache::tag('tag')->clear();`

数据的key是删除了，redis里面还会残留tag:，发现是https://github.com/top-think/framework/blob/9cb47919f59f080e39ec2b8401e4f9c11c8548fb/src/think/cache/driver/Redis.php#L196      这里重复计算了一次getCacheKey

因为这个key的md5已经在这里计算了一次  https://github.com/top-think/framework/blob/9cb47919f59f080e39ec2b8401e4f9c11c8548fb/src/think/cache/TagSet.php#L122

**Comment by liu21st** [comment]
其实是没问题的，或者你用最新的开发版再测试下
