### ISSUE TITLE
serialize序列化的问题

### ISSUE THREAD

**Issue by kingfer30** [top-think/framework#2389]
版本：TP6
背景：由于底层的cache的序列化机制是用的serialize和unserialize，这会有个问题就是，当我们把数组存入cache中，取出来的时候没法以数组的形式来使用，而是对象的形式。
而配置文件中，提供了一个'serialize'参数设置，可以设置其他序列化机制，使用了'json_encode', 'json_decode'，但实际上没有生效，原因是底层调用json_decode实际上它需要传第二个参数“json_decode($data, true)”，而底层并没有，能否做下优化？

![image](https://user-images.githubusercontent.com/34082198/96074654-c9ba7980-0edb-11eb-94a6-61a399228f25.png)

https://github.com/top-think/framework/blob/6.0/src/think/cache/Driver.php#L248

**Comment by hongfs** [comment]
自己在公共文件写个函数应该可以的

```php
function _json_decode($data) {
  return json_decode($data, true);
}
```

**Comment by kingfer30** [comment]
> 自己在公共文件写个函数应该可以的
> 
> ```
> function _json_decode($data) {
>   return json_decode($data, true);
> }
> ```

它已经被反序列化了, 底层取出来已经是对象了，我目前的处理方式是在那个底层方法里面稍微改了一下:
return $unserialize($data, true);
这个cache配置提供的serialize参数配置, 实际上还是比较鸡肋的

**Comment by liu21st** [comment]
你可以用闭包作为序列化方法的
