### ISSUE TITLE
composer update topthink/framework 报错

### ISSUE THREAD

**Issue by codefoot** [top-think/framework#2403]
当前framework版本是：v6.0.2，执行升级命令报错：
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Root composer.json requires topthink/framework ^6.0.0, found topthink/framework[v6.0.2] in lock file but not in remote repositories, make sure you avoid updating this package to keep the one from lock file.

哪位大神能给指导一下，不胜感激！！！

**Comment by ewwerpm** [comment]
我也遇到类似问题，如何解决的啊？
D:\xampp\htdocs\Learn-Laravel-5-laravel5.5>composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires fideloper/proxy ~3.3, found fideloper/proxy[3.3.4] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
  Problem 2
    - Root composer.json requires laravel/framework 5.5.*, found laravel/framework[v5.5.2] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
  Problem 3
    - Root composer.json requires laravel/tinker ~1.0, found laravel/tinker[v1.0.2] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
  Problem 4
    - Root composer.json requires filp/whoops ~2.0, found filp/whoops[2.1.10] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
  Problem 5
    - Root composer.json requires fzaninotto/faker ~1.4, found fzaninotto/faker[v1.7.1] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
  Problem 6
    - Root composer.json requires mockery/mockery 0.9.*, found mockery/mockery[0.9.9] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
  Problem 7
    - Root composer.json requires phpunit/phpunit ~6.0, found phpunit/phpunit[6.3.0] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.

**Comment by ShuiPingYang** [comment]
换成阿里云的镜像就可以了。
```php
composer config -g repo.packagist composer https://mirrors.aliyun.com/composer
```
