### ISSUE TITLE
query.php查询会丢失表名导致查询失败

### ISSUE THREAD

**Issue by season886** [top-think/framework#241]
db里面的Query.php 如果使用 Db:table('XXX_XXX')->field('XXX',true)->find()会找不到表名；
原因是程序执行getTableInfo 然后调用getTable，由于没有传入name，导致返回$tableName =$this->table;
但是
`public function table($table)
    {
        $this->options['table'] = $table;
        return $this;
    }`
并没有给$this->table赋值

**Comment by season886** [comment]
我在那里临时加了句$this->table = $table 没有问题了！
可能官方还有更完美的解决方案吧，我也是菜鸟不敢乱说

**Comment by season886** [comment]
没人理。。。。( ▼-▼ )

**Comment by liu21st** [comment]
改进了
