### ISSUE TITLE
$pk 属性在模型里面设置自定义的问题

### ISSUE THREAD

**Issue by Caiyi-LI** [top-think/framework#2421]
看到模型很多属性都是通过trait方式去设置引入，是否有考虑到我们后期设置自定义属性的时候。跟trait引入的重名冲突的问题。虽然能运行，但是本着严谨的代码风格，应该改变一下模型基础属性的设置方式吧？

**Comment by liu21st** [comment]
你要自定义什么基础属性？你要自定义属性 肯定要核心本身提供了哪些属性的吧？哪能随意设置的

**Comment by Caiyi-LI** [comment]
到底有没认真看我的问题？我翻你们手册的时候，明确有说明每个模型可以设置自己的$table表名。这算不算基础属性？然后你们是通过trait去设置的。有没有去认真的翻过php的手册 trait是怎么样用的？有没想到我们后面继承了基础类之后。重命名不一样会导致冲突的问题？
