### ISSUE TITLE
$pk 属性冲突

### ISSUE THREAD

**Issue by Caiyi-LI** [top-think/framework#2422]
https://github.com/top-think/framework/issues/2421#issue-757596227
到底有没认真看我的问题？我翻你们手册的时候，明确有说明每个模型可以设置自己的$table表名。这算不算基础属性？然后你们是通过trait去设置的。有没有去认真的翻过php的手册 trait是怎么样用的？有没想到我们后面继承了基础类之后。重命名不一样会导致冲突的问题？

**Comment by liu21st** [comment]
你不妨举个例子说明下 具体有什么问题吧

**Comment by heqichang** [comment]
他大概说的是这个意思：
<img width="900" alt="WX20201222-173934@2x" src="https://user-images.githubusercontent.com/717699/102874058-eabfbd80-447c-11eb-8cab-c2d49e647503.png">

如果在子类使用 pk 属性，最新版 (phpstorm 2020.3) 会报错

<img width="543" alt="WX20201222-174009@2x" src="https://user-images.githubusercontent.com/717699/102874194-1b9ff280-447d-11eb-8c50-d4ba26b88e07.png">

虽然运行时是没有问题的

**Comment by liu21st** [comment]
我测试运行没有问题 至于IDE报错 都是可以设置的

**Comment by yunwuxin** [comment]
这个是最新版phpstorm的一个bug
