### ISSUE TITLE
TP5.1会考虑更新兼容PHP8嘛？

### ISSUE THREAD

**Issue by etjson** [top-think/framework#2428]
TP5.1会考虑更新兼容PHP8嘛？

**Comment by liu21st** [comment]
如果工作量不大的话 可能会考虑下的

**Comment by 8108905** [comment]
Tp6 现在支持php8 吗

**Comment by etjson** [comment]
> Tp6 现在支持php8 吗

刚更新6.0.6已经支持了。

**Comment by 8108905** [comment]
谢谢。thinkphp-view 希望支持一下 谢谢。刚测试模版不行以一个小错误

**Comment by etjson** [comment]
> 谢谢。thinkphp-view 希望支持一下 谢谢。刚测试模版不行以一个小错误

这个我反馈了，等作者更新吧！[/top-think/think-template/issues/11#issue-783035853](https://github.com/top-think/think-template/issues/11#issue-783035853)

**Comment by 8108905** [comment]
谢谢你
