### ISSUE TITLE
PHP8 中 `substr_replace` 报 TypeError

### ISSUE THREAD

**Issue by hongweipeng** [top-think/framework#2429]
TP6中:
```
Db::table(static::$table_name)->where('id', 1)->find();
```
在PHP8环境中报：
![20201214005337](https://user-images.githubusercontent.com/7546325/102018218-dc9bde00-3da6-11eb-8772-a39396cb4b69.png)

在一些使用 `str_replace` 的地方也会有此错误，例如生成 url 时:
```
$url = url('index/blog/read', ['id' => 1])->domain(true)->build();
```
![20201214005802](https://user-images.githubusercontent.com/7546325/102018309-83807a00-3da7-11eb-9702-93c6b734ba76.png)

**Comment by hongweipeng** [comment]
url的生成部分也许可以归结为用户自身的使用问题；而ORM操作部分我认为框架应该处理，毕竟 `$model->where('id', 1)` 的形式十分直观。

**Comment by liu21st** [comment]
这个问题修正过的 orm的开发版测试下
