### ISSUE TITLE
查询不区分大小写问题

### ISSUE THREAD

**Issue by jacklin** [top-think/framework#244]
找出用户名id为’AAMkADExM2M5NjQ2LWUzYzctNDFkMC1h‘的用户的数据： select \* from usertable where id = 'AAMkADExM2M5NjQ2LWUzYzctNDFkMC1h'; 结果出现两条记录。这就奇怪了，id已经设置为主键，怎么会重复呢？原因现在框架中未能区别大小写功能。

能不能帮助添加个区分大小写查询？

**Comment by dingdayu** [comment]
你能确定`select * from usertable where id = 'AAMkADExM2M5NjQ2LWUzYzctNDFkMC1h';`是日志中的查询记录吗？

**Comment by yunwuxin** [comment]
mysql的默认查询本来就是不区分大小写的   自己去查下资料

**Comment by dingdayu** [comment]
如果上面的SQL是从日志中获取的话，那么这个查询是没有问题的，应该是你插入的时候，插入多条了，推测是你的id主键没有设置唯一，否则你插入应该会报错的。

**Comment by jacklin** [comment]
mysql 默认查询不区分大小写是否，可以通过框架对查询数据进行区别大小写选择，我只想建议tp5在这点上进行改进
