### ISSUE TITLE
多应用下url()生成地址的问题.

### ISSUE THREAD

**Issue by Y-A-K-E** [top-think/framework#2443]
## 多应用
admin 应用 

线上模式 绑定 admin.abc.com访问
本地环境调试 通过 test.abc.com/admin访问.

admin视图生成一个登出链接
` {:url('/index/logout')}`

无法自动适配.

线上模式生成的链接为
`https://admin.abc.com/index/logout.html`   (正确)
本地环境生成的链接为
`https://test.abc.com/index/logout.html`  (错误,正确应该是`https://test.abc.com/admin/index/logout.html`)

------
目前我临时修复方案是
`{:url(Request::root() . '/index/logout')}`
它能正确的生成不同模式下的链接.

跨应用模式生成链接用这个办法还是不行.
要手动处理.

**Comment by qilecms** [comment]
我也是遇到这个问题。url生成多个模块！

**Comment by qilecms** [comment]
下载了一个全新的tp6 安装多应用， 测试 默认模块portal.   控制器：  echo url('article/detail/index',['id'=>1])    
模块下路由：Route::get('article/:id', 'article/detail/index');   显示错误结果  ：  /portal/article/1.html      实际正确的结果应该是  /article/1.html    多生成一个无关的模块名。

**Comment by php4world** [comment]
线下线上还用两套路由规则？

**Comment by liu21st** [comment]
开发环境和正式环境应该是建议相同的部署环境和策略的
