### ISSUE TITLE
关于 OPTIONS 的疑问

### ISSUE THREAD

**Issue by edenleung** [top-think/framework#2445]
问题：业务中间件接收到OPTIONS请求。

commit 记录
> https://github.com/top-think/framework/commit/0f4cabf5a0dca6d6d759dfc5fbc0c2c1e9ba2f47#diff-3762beeca2b3611d5c310c44778709f804a6d9f7361cf4782637229679ecb740L60

为啥取消了这个 OPTIONS 返回？

是否交给开发者自己来处理响应？

现在 `OPTIONS`的请求都到了业务中间件

**Comment by yunwuxin** [comment]
自己处理options请求

**Comment by edenleung** [comment]
好的。
