### ISSUE TITLE
 chunk批量处理pk未定义问题

### ISSUE THREAD

**Issue by jacklin** [top-think/framework#245]
`
 public function chunk($count, $callback, $column = null)
    {
        $options   = $this->getOptions();
        $column    = $column ?: ($options['pk'] ?: $this->getPk());
        $bind      = $this->bind;
        $resultSet = $this->limit($count)->order($column, 'asc')->select();

`
建议：$column    = $column ?: ($options['pk'] ?: $this->getPk());改为
$column    = $column ?: (isset($options['pk']) ?: $this->getPk());
 可能会报：未定义索引 : pk

**Comment by liu21st** [comment]
已经改进

**Comment by jacklin** [comment]
OK
