### ISSUE TITLE
5.1.41 Fatal error: Uncaught Error: Call to undefined function React\Promise\resolve() 

### ISSUE THREAD

**Issue by teddy-lu** [top-think/framework#2452]
![image](https://user-images.githubusercontent.com/8829977/104535592-729a8100-5651-11eb-8574-efc1d077e63c.png)
昨天更新项目  docker构建的时候出现  这个错误  点进方法确实没有此方法  原因是？？？？

**Comment by liu21st** [comment]
这个问题修正过了的 重新更新一次
