### ISSUE TITLE
v6.06 更新后 同应用 不同方法 有的可以获取到session 有的不行   回退到v6.0.5正常

### ISSUE THREAD

**Issue by clyde-cn** [top-think/framework#2455]
v6.06 更新后 同应用 不同方法 有的可以获取到session 有的不行   回退到v6.0.5正常

**Comment by zjslqshqz** [comment]
> v6.06 更新后 同应用 不同方法 有的可以获取到session 有的不行 回退到v6.0.5正常

你应该把出问题的代码贴出来啊

**Comment by clyde-cn** [comment]
![1](https://user-images.githubusercontent.com/33918985/105686059-c484b600-5f31-11eb-8b2b-d90140141d8a.png)
![2](https://user-images.githubusercontent.com/33918985/105686069-c8183d00-5f31-11eb-84d0-278fa092d2e1.png)
![3](https://user-images.githubusercontent.com/33918985/105686079-cb132d80-5f31-11eb-9377-75e709762f9a.png)
![4](https://user-images.githubusercontent.com/33918985/105686091-cd758780-5f31-11eb-96d4-9cca37068bde.png)
![5](https://user-images.githubusercontent.com/33918985/105686103-d1090e80-5f31-11eb-9f99-4a388e9b8a9a.png)
![6](https://user-images.githubusercontent.com/33918985/105686109-d36b6880-5f31-11eb-8d79-91598cdb655b.png)

**Comment by clyde-cn** [comment]
think\app 引入问题导致 很奇怪  v6.05 正常     目前 think\App 这样引入恢复正常
