### ISSUE TITLE
Tp6 验证器错误，需要紧急修复

### ISSUE THREAD

**Issue by php4world** [top-think/framework#2457]
`vendor\topthink\framework\src\think\Validate.php`
`filter_var`函数第三个参数应为`array|int`，而现在用的默认值为`null`。导致报错
php.net官方说明 `filter_var ( mixed $value , int $filter = FILTER_DEFAULT , array|int $options = 0 ) : mixed`

现在程序报错 `filter_var(): Argument #3 ($options) must be of type array|int, null given`

**Comment by liu21st** [comment]
你不是最新版本吧

**Comment by php4world** [comment]
> 你不是最新版本吧

```
class App extends Container
{
    const VERSION = '6.0.6';
```

**Comment by liu21st** [comment]
看了下 是开发版修正过的

**Comment by php4world** [comment]
什么时候发布下个版本
