### ISSUE TITLE
路由分组与规则问题-v6.0.6

### ISSUE THREAD

**Issue by zjslqshqz** [top-think/framework#2458]
路由分组与规则名有相似的话，会导致路由规则错误
版本: 6.0.6
> 错误重现
```php
Route::group('user',function (){
    Route::get('userArticleList/:type','Console/articleList');
})
```
> 正常模式
```php
Route::group('user',function (){
    Route::get('ArticleList/:type','Console/articleList');
})
```

**Comment by liu21st** [comment]
这个问题 开发版修正过的 可以测试下

**Comment by mitoop** [comment]
遇到同样的错误 什么时候发布新版本 @liu21st

**Comment by liu21st** [comment]
考虑发布一个小版本更新

**Comment by mitoop** [comment]
@liu21st 尽快发布吧 🙏

**Comment by mitoop** [comment]
@liu21st 我查看了原因 最开始是因为 `think\route\Rule@buildRuleRegex`方法 str_place时 引起的bug ,修复后调整了此处对应的代码，我把调整的代码包括两个文件`Rule` 和 `RuleItem` 复制到我本地 还是不行, 我原始的路由是这样的：`/adminapi/user/user_group/add/0`  您能方便测试一下吗？

**Comment by mitoop** [comment]
回退到 6.0.3 路由正常了 6.0.6 有问题 查看了代码 从6.0.6 路由解析代码发生变更 也就是 6.0.6 版本路由解析有问题

**Comment by raybon-lee** [comment]
> 路由分组与规则名有相似的话，会导致路由规则错误
> 版本: 6.0.6
> 
> > 错误重现
> 
> ```
> Route::group('user',function (){
>     Route::get('userArticleList/:type','Console/articleList');
> })
> ```
> 
> > 正常模式
> 
> ```
> Route::group('user',function (){
>     Route::get('ArticleList/:type','Console/articleList');
> })
> ```

先切换到6.0.3 可以

**Comment by zjslqshqz** [comment]
> > 路由分组与规则名有相似的话，会导致路由规则错误
> > 版本: 6.0.6
> > > 错误重现
> > 
> > 
> > ```
> > Route::group('user',function (){
> >     Route::get('userArticleList/:type','Console/articleList');
> > })
> > ```
> > 
> > 
> > > 正常模式
> > 
> > 
> > ```
> > Route::group('user',function (){
> >     Route::get('ArticleList/:type','Console/articleList');
> > })
> > ```
> 
> 先切换到6.0.3 可以
还好这是新项目，我直接改了

**Comment by zjslqshqz** [comment]
> 这个问题 开发版修正过的 可以测试下

早点发布小版本修复吧，我自己直接改掉了，就一个路由这样
