### ISSUE TITLE
数据库查询语句与LOG中产生的语句不一致

### ISSUE THREAD

**Issue by resnou** [top-think/framework#2462]
生成测试数据库 `testa` ，字段为 `id` 和 `a`。
id类型为`int`，a类型为`varchar`。
测试数据为

id      a
1       3

执行 Db::table('testa')->where('a','>',29)->select(); 
查询结果可以命中测试数据。
log中生成的数据库查询语句为
``SELECT * FROM `testa` WHERE  `a` > 29``
这条语句在mysql执行中应该是无法命中测试数据的，因为条件中的29是int类型，而数据库中的A字段是varchar类型。

``SELECT * FROM `testa` WHERE  `a` > '29'``
这条语句可以命中测试数据。

猜测可能是在数据库查询之前，thinkphp读取了数据库结构，发现了a字段是varchar类型，然后直接将a字段的查询条件改为
字符串查询。

希望不要修改用户传入的数据类型。

**Comment by liu21st** [comment]
最新版本的应该就是你说的后者了

**Comment by resnou** [comment]
> 最新版本的应该就是你说的后者了

可不可以修改一下这个逻辑，或者说给用户一个选择，毕竟数据库有时候会有遗留原因导致varchar存储数字。

 Db::table('testa')->where('a','>',29)->select();

我在这里传入的是int类型，但是最终ThinkPHP却进行了字符串查询，这不符合我使用的本意。

如果我想要进行字符串查询的话，我可以直接传入字符串29。

**Comment by liu21st** [comment]
参考这里 https://github.com/top-think/think-orm/issues/216

**Comment by resnou** [comment]
你好，我去看了一下，这个隐式转换可不可以加个fieldsType参数,类似于下面这样

Db::table('testa')
->where('a','>',29)
->fieldsType([
'id'=>'int',
'a'=>'string'
])
->select();
