### ISSUE TITLE
关于swoole里服务与事件的周期

### ISSUE THREAD

**Issue by wdaglb** [top-think/framework#2464]
我尝试在service里启动一条子进程Process，用来更新配置中心的，但是我每次composer更新扩展时都会启动到服务（我觉得一个服务不能让composer触发的）

然后我又试了一下event，在appInit事件里启动Process，他也失败了；

由此我考虑到是php think service:discover或者php think vendor:publish中进入了command命令，也启动了服务、触发了应用初始化的事件。

我想service与event，不应该让command调用到吧？

**Comment by yunwuxin** [comment]
service里可以判断是console还是http

或者你把composer.json里的scripts内容删掉即可，在你需要的时候自己手动执行

或者composer执行的时候加上 --no-scripts

**Comment by wdaglb** [comment]
> service里可以判断是console还是http
> 
> 或者你把composer.json里的scripts内容删掉即可，在你需要的时候自己手动执行
> 
> 或者composer执行的时候加上 --no-scripts

只要是使用command都会进入service的，个人觉得这并不符合设计service的理念；
现在是每一条命令都会进入service，希望未来的版本能够完善吧。

**Comment by yunwuxin** [comment]
我不知道你理解的service理念是什么
command指令也是应用程序的一部分 当然也需要service了  有些应用可能都没有http，就是纯console的

**Comment by wdaglb** [comment]
> 我不知道你理解的service理念是什么
> command指令也是应用程序的一部分 当然也需要service了 有些应用可能都没有http，就是纯console的

嗯，我尝试判断当前执行的指令，是否执行子进程的创建。现在成功实现了。谢谢您的解答。
