### ISSUE TITLE
options请求走了路由中间件

### ISSUE THREAD

**Issue by zhushide** [top-think/framework#2467]
开启跨域请求中间件，options请求走了路由中间件。一个是多走了所有路由中间件逻辑代码；二是路由中间件中抛出的http异常状态码不是20*的会直接导致options请求异常

**Comment by zhushide** [comment]
现在一个解决办法是在所有路由中间件首先判断请求类型是否是options请求，如果是直接返回

**Comment by successgo** [comment]
你是不是可以尝试在 nginx 这一层设置跨域处理呢

**Comment by zhushide** [comment]
@successgo 我知道可以在nginx处理，但是现在说的是代码的问题

**Comment by edenleung** [comment]
官方说自己处理 #2445
