### ISSUE TITLE
\think\db\Query 多表查询和子查询的BUG

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#247]
以如下方式使用子查询时会报错

```
$count = Db::table($child_sql . ' c')->count();
```

错误内容如下:

> [2] ErrorException in Query.php line 1418
> Invalid argument supplied for foreach()

看了下源码, 在 `getFieldsBind` 方法中调用的 `getFieldsType` 的方法会返回 `false`, 即在获取数据表信息时, 检查到 `$tableName` 如果包含 `,` 则返回 `false`. 

对于子查询和多表查询这里均会返回 `false`, 也就导致代码出错

**Comment by liu21st** [comment]
这个问题已经修正

**Comment by Xuchengen** [comment]
子查询还是有问题。
`
$sql = Db::name('order')->order('create_date desc')->buildSql();
                
$total = Db::table($sql . ' a')->count();

`

**Comment by liu21st** [comment]
子查询用数组方式

**Comment by Xuchengen** [comment]
这两种方式我都测试过了，框架是刚刚在github上拉取的最新代码。
[ThinkPHP社区话题](http://www.thinkphp.cn/topic/43495.html)
