### ISSUE TITLE
关于$query对象复用的问题

### ISSUE THREAD

**Issue by studyzhanglei** [top-think/framework#2501]
$query = Model::newQuery()->where('id', 1);

$count  = $query->count();
$list       = $query->field('name,title')->limit(0, 10)->select()->toArray();

这是一段经常用到的分页查询及查询总数量的代码，但是我们会发现$list的字段不是我们所指定的字段，看了一下源码发现是->count()的时候会给field缺省值“*”，然后再次查询的时候会merge所有的field，希望开发者给出指导意见或者解决办法，谢谢～

**Comment by liu21st** [comment]
改进了下 可以重新测试下看看

**Comment by studyzhanglei** [comment]
> 改进了下 可以重新测试下看看

切换topthink/think-orm至2.0.x-dev，以上问题已修复，谢谢
