### ISSUE TITLE
关于“$query对象复用的问题”解决导致的insert问题

### ISSUE THREAD

**Issue by studyzhanglei** [top-think/framework#2505]
#2501 

开发者在解决我提出的这个issue的时候产生了一个新的问题：

#0 [8]ErrorException in Builder.php line 139
未定义数组索引: field

think-orm commit-id：7b1d38425306c61de27a8c42eb90303650a162fa

阅读了一下源码，PDOConnection会在insert之前调用parseOptions这个函数，这个函数之前里面有对field的空值做处理，
但是开发者修改之后删掉了，而后面的代码未对field做判断，出现了undefined的问题。

希望开发者快速解决一下，谢谢。

**Comment by sy-records** [comment]
fixed by https://github.com/top-think/think-orm/commit/34575769f2231c79e64ac8ed158db84cd682c6b2
