### ISSUE TITLE
6.0.6路由匹配错误

### ISSUE THREAD

**Issue by hebzh** [top-think/framework#2515]
举例
路由地址
`^ "/app/admin/test/user/<user_id>/code/userSave"`
通过RuleItem.php转换后的地址
`^ "\/app\/admin\/test\/user(\/(?<user_id>[\w\.\,\-]+))\/code\\/userSave"`

原因是
/user重复匹配输出了双斜杠 导致路由匹配错误

**Comment by hebzh** [comment]
正确的地址
`^ "\/app\/admin\/test\/user(\/(?<user_id>[\w\.\,\-]+))\/code\/userSave"`

**Comment by liu21st** [comment]
你可以用最新版本测试下

**Comment by hebzh** [comment]
> 你可以用最新版本测试下

已经更新到到6.0.7问题解决~谢谢~
