### ISSUE TITLE
文档里面写了facade有response，实际上源码没有实现。

### ISSUE THREAD

**Issue by juukee** [top-think/framework#2519]
文档里面写了facade有response，实际上源码没有实现。![IMG_20210502_232836.jpg](https://user-images.githubusercontent.com/28680837/116818482-2b9faf80-ab9e-11eb-8a60-dc81cd06cf8c.jpg)![IMG_20210502_232846.jpg](https://user-images.githubusercontent.com/28680837/116818489-30646380-ab9e-11eb-9729-fcd0ef084836.jpg)

**Comment by liu21st** [comment]
文档有误 抱歉
