### ISSUE TITLE
希望可以增加text/plain类型的Response

### ISSUE THREAD

**Issue by flyering** [top-think/framework#2526]
虽然可通过text/html达到目的，但是开发过程中没法开启debug模式

**Comment by big-dream** [comment]
可以自己自定义的

**Comment by flyering** [comment]
自定义是指实现一个继承Response的text/plain类，还是通过设置response属性达到返回text/plain的目的？后种方式我尝试了，debug模式下始终会有调试信息输出，没找到好的关闭方式（除非关闭debug模式），还是我没get到正确方法？

**Comment by flyering** [comment]
> 可以自己自定义的

自定义是指实现一个继承Response的text/plain类，还是通过设置response属性达到返回text/plain的目的？后种方式我尝试了，debug模式下始终会有调试信息输出，没找到好的关闭方式（除非关闭debug模式），还是我没get到正确方法？

**Comment by big-dream** [comment]
测试正常，开启调试模式后，右下角没有出现traceDebug信息
代码：
```php
return response('Hello World!', 200, [])->contentType('text/plain');
```
响应：
```http
HTTP/1.1 200 OK
Date: Thu, 10 Jun 2021 03:27:16 GMT
Server: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.19
X-Powered-By: PHP/7.4.19
Content-Length: 12
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/plain; charset=utf-8

Hello World!
```

**Comment by flyering** [comment]
> 测试正常，开启调试模式后，右下角没有出现traceDebug信息
> 代码：
> 
> ```
> return response('Hello World!', 200, [])->contentType('text/plain');
> ```
> 
> 响应：
> 
> ```httpspec
> HTTP/1.1 200 OK
> Date: Thu, 10 Jun 2021 03:27:16 GMT
> Server: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.19
> X-Powered-By: PHP/7.4.19
> Content-Length: 12
> Keep-Alive: timeout=5, max=100
> Connection: Keep-Alive
> Content-Type: text/plain; charset=utf-8
> 
> Hello World!
> ```

确实可以，然后我又试了多次，也没法复现当时的情况了。非常感谢您的解答，此建议我就先关闭了
