### ISSUE TITLE
关于启用跨库事务提示 does not have a method 'transactionXa'

### ISSUE THREAD

**Issue by knightCw** [top-think/framework#2528]
使用 transactionXa 报错
提示如下 ：
call_user_func_array() expects parameter 1 to be a valid callback, class 'think\\db\\connector\\Mysql' does not have a method 'transactionXa'

tp版本：thinkphp6

**Comment by Tinywan** [comment]
我也是提示这个

**Comment by liu21st** [comment]
最新开发版本测试下
