### ISSUE TITLE
关于 url 生成的问题

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#254]
在多域名部署中，可能存在部分域配置了 SSL 的情况
这时就需要从 `http` 跳转到 `https`， 或者从 `https` 跳转到 `http`
这样的话，如何在 `http://` 协议下使用 `Url::build` 生成 `https://` 的链接?

**Comment by hldh214** [comment]
能用服务器配置尽量用服务器配置吧, 性能不是一个级别的
