### ISSUE TITLE
关于今天更新的数据插入insertGetId　找不到改方法了，怎么获取到插入的主键id，insert只能返回插入的数目，求解决，项目实际应用中，

### ISSUE THREAD

**Issue by duchao1990** [top-think/framework#255]
框架能不能不要这么坑啊，快被经理骂死了。。。。。。

直接上上周更新里边没有view试图查询，求介绍，什么地方的框架稳定点，

**Comment by kinosang** [comment]
目前 TP5 处于 RC 状态，不建议用于实际生产环境。

`insertGetId` 还在啊，并没有被删除。

**Comment by duchao1990** [comment]
@kinosang 嗯嗯已经找到了,IDE没有提醒显示这个函数不存在,实际上存在.可以用,多谢
