### ISSUE TITLE
orm update方法报错

### ISSUE THREAD

**Issue by studyzhanglei** [top-think/framework#2554]
```
$result = Model::where([
    'tid'   => $tid,
    'uid'   => $opUid,
   'status' => 1,
])->findOrEmpty();

if ($result->isExists()) {
    $result->update(['status' => 0]);
}
```

#0 [10500]DbException in BaseQuery.php line 1029
miss update condition

把update换成save可以，但是我在明确不需要新增数据的情况下用save方法是不是有点不合适

**Comment by liu21st** [comment]
模型本来就只有save方法

**Comment by studyzhanglei** [comment]
> 模型本来就只有save方法

ide提示是有的，或者我上面的写法tp有类似的吗？

**Comment by liu21st** [comment]
因为模型有一个静态的update方法 被你调用了 静态方法的使用方法是不同的 建议看下手册 你改成save就行了 动态调用的话
