### ISSUE TITLE
tp5.1图片上传getImageType方法报错

### ISSUE THREAD

**Issue by varzer** [top-think/framework#2564]
场景:txt文件改名png上传,报错

> 修改如下:

    // 判断图像类型
    protected function getImageType($image)
    {
```
        if ( function_exists( 'exif_imagetype' ) )
        {
            try
            {
                return exif_imagetype( $image );
            }
            catch ( \Exception $e )
            {
                return false;
            }
        }
```

        try
        {
            $info = getimagesize( $image );
            return $info ? $info[2] : false;
        }
        catch ( \Exception $e )
        {
            return false;
        }
    }

**Comment by varzer** [comment]
`        if ( function_exists( 'exif_imagetype' ) )
        {
            try
            {
                return exif_imagetype( $image );
            }
            catch ( \Exception $e )
            {
                return false;
            }
        }`

**Comment by liu21st** [comment]
txt文件名该png上传 报错 这个有问题么？难道不应该报错么？

**Comment by varzer** [comment]
抱歉,我没把问题描述清楚,想想报错也没问题.个人观点:让用户自己去处理可能好点,预期它返回flase,结果不是
