### ISSUE TITLE
6.0.8 开启强制路由后，定义的路由名称和模块名称相同时，找不到路由

### ISSUE THREAD

**Issue by dengzhenhui** [top-think/framework#2569]
1. 开启强制路由
 ```
'url_route_must'        => true,
 ```
2. 定义路由
  ```
  Route::get('test', '\app\admin_api\controller\Index@index');
  ```
3. 新建一个模块 test

4. 访问 http://127.0.0.1/test 报错
![image](https://user-images.githubusercontent.com/24721273/126879172-c9f4f057-8562-445e-8735-9cbc58c43150.png)

**Comment by liu21st** [comment]
路由不是你这样用的 参考手册吧
