### ISSUE TITLE
日志通道能否增加一个开启功能?

### ISSUE THREAD

**Issue by augushong** [top-think/framework#2570]
我做了一个日志驱动,是把日志记录到数据库的驱动,这样查看远程服务器的日志就很方便了,基本逻辑如下:
其实逻辑是很简单的.
```
public function save(array $log): bool
  {
    $create_time = time();

    $create_time_title = date('Y-m-d H:i:s', $create_time);

    $app_name = app('http')->getName() ?: '';

    foreach ($log as $log_level => $log_list) {
      foreach ($log_list as $key => $log_item) {

        if (!is_string($log_item)) {
          $log_item = json_encode($log_item, JSON_UNESCAPED_UNICODE);
        }

        DebugLog::create([
          'level' => $log_level,
          'content' => $log_item,
          'create_time' => $create_time,
          'create_time_title' => $create_time_title,
          'app_name' => $app_name,
        ]);
      }
    }

    return true;
  }
```

一般在fpm的环境下,没什么大问题,但是在cil环境下,`save`方法里的数据库写入操作也会一直触发,导致了死循环.(可能开启实时写入,在fpm也会有问题,我还没测试)

所以我想直接在在`写入数据库时关闭日志`,等我这里在数据库记录完,再`开启日志`

官方已经有了`close`方法,
```
    /**
     * 关闭通道
     */
    public function close()
    {
        $this->clear();
        $this->close = true;
    }
```

希望能增加一个`enable`方法,开启通道的方法.

可以增加这个吗?

(目前我的驱动已经在`cli`环境回退的`File`的驱动了)

**Comment by yunwuxin** [comment]
![image](https://user-images.githubusercontent.com/2168125/126892178-98cae275-2174-4ca9-b4ed-284ffc9d35eb.png)

这里自己加个参数判断应该就可以了吧   

这里写入前开启  写入好关闭，如果已经开启了 就不写入

**Comment by augushong** [comment]
恩,在驱动里增加了一个属性作为开关,可以用了:
```
$this->enableLog = false;
DebugLog::create([
  'level' => $log_level,
  'content' => $log_item,
  'create_time' => $create_time,
  'create_time_title' => $create_time_title,
  'uid' => $log_key,
  'app_name' => $app_name,
]);
$this->enableLog = true;
```

-------------- 以下为原回答 ----------------------


目前我已经做了兼容处理了,如果是`cli`环境,就不会调用数据库的写法.

现在的问题是,当我调用`DebugLog::create()`时,数据库又会触发日志写入`Log::save()`,在日志写入里新增数据,又会触发数据库的日志事件.

我的需求是能够把日志记录到数据库中(开发时),

所以我希望在`DebugLog::create()`写入数据库之前,关闭日志通道,这样无论其他任何地方都不会再调用`Log::save()`,
现在的问题是,确实是有`Log::close()`可以关闭通道,但是没有方法开启通道.我希望有一个开启通道的方法.

试图修改`config/log.php`显然是没有意义的,配置文件只会在初始化实例的时候调用,实例化之后修改没什么意义.

当然,这个地方,还有另一种方法,就是对数据库的日志增加个开关,比如说`Db::disableLog()`和`Db::enableLog()`,但这个方案显然不好.我看了看`Db`源码,这样做改动很大,而且确实是没什么需求.

还有一种方案就是在`Model`里增加一个日志开关属性,也不好,改动太大.

最好是能增加一个`Log::enable()`;

所以想问问可不可以加一个,因为`Log::close()`和`Log::enable()`这个操作在日志通道`Channel`上,不能自定义.

**Comment by hulang** [comment]
这里有个第三方作者扩展的日志数据库驱动：
`composer require yzh52521/think-log-driver`
