### ISSUE TITLE
Call to a member function getSize() on array

### ISSUE THREAD

**Issue by chuxinone** [top-think/framework#2575]
$files = request()->file();
validate(['image'=>'fileSize:1|fileExt:jpg|image:200,200,jpg'])->check($files);
dump([$files,$files->getSize()]);

**Comment by sy-records** [comment]
file需要指定key， 不传的话就是一个带key的数组，需要遍历。

```php
$files = request()->file();
foreach ($files as $key => $file) {
    dump($key, $file->getSize());
}
```
