### ISSUE TITLE
模型获取器定义数据表中不存在的字段的一个问题

### ISSUE THREAD

**Issue by ken678** [top-think/framework#2584]
模型获取器定义数据表中不存在的字段

public function getStatusTextAttr($value,$data){
 $status = [-1=>'删除',0=>'禁用',1=>'正常',2=>'待审核'];
 return $status[$data['status']];
}
只要模型定义了，那么读取数据的field一定带有status,不然会报错status不存在，但是有的时候只读取几个字段不需要输出status，还必须得带上，这样就非常的麻烦，有时候查个数据field我还得找模型里面看有没有定义未存在的字段

**Comment by SunJary** [comment]
这个是你的用法不对，
参考文档：
> 获取器方法的第二个参数传入的是当前的所有数据数组。
就是$data是全部数据，$data中不存在status当然会报错，应当在代码中判断$data['status']是否存在，不存在的话给一个默认值，或者返回空字符串

**Comment by liu21st** [comment]
模型查询的时候 不要用field方法限制 输出的时候用hidden隐藏或append附加额外字段
