### ISSUE TITLE
关于一个中间件执行顺序的问题，请教

### ISSUE THREAD

**Issue by topyao** [top-think/framework#2587]
![image](https://user-images.githubusercontent.com/64066545/132860842-bbc33767-bbae-44f6-be17-6ab0e45075f2.png)
![image](https://user-images.githubusercontent.com/64066545/132860900-7191a728-0b18-41a7-a583-ee3e66613aaa.png)
![image](https://user-images.githubusercontent.com/64066545/132860917-ce5f5d28-7e62-4905-a73f-8691cd1c2ecd.png)

按道理应该是111test222，实际上是111222test

**Comment by liu21st** [comment]
没毛病
