### ISSUE TITLE
url大小写访问的问题

### ISSUE THREAD

**Issue by sp56** [top-think/framework#260]
我的config是这么设置的：
'app_multi_module'       => false,
'controller_auto_search' => true,
 'url_convert'            => true,

比如有个控制器在 /controller/test/Test.php
在Linux下访问的时候 只能 **/test/Test/index**,不能 **/test/test/index**

**Comment by samplecms** [comment]
config我默认 这样是可以访问的，试下改改CONFIG。

**Comment by sp56** [comment]
config 默认的是真不行，麻烦管理看看这个问题：Route.php 1096 行
 $dir    = APP_PATH . ($module ? $module . DS : '') . 'controller';
                $suffix = App::$suffix || Config::get('controller_suffix') ? ucfirst(Config::get('url_controller_layer')) : '';
                $item   = [];
                foreach ($path as $val) {
                    $item[] = array_shift($path);
                    if (is_file($dir . DS . $val . $suffix . EXT)) {
                        break;
                    } else {
                        $dir .= DS . $val;
                    }
                }
                $controller = implode('.', $item);

**Comment by liu21st** [comment]
'controller_auto_search' => true, 最好是搭配 'url_convert' => false

**Comment by sp56** [comment]
$item   = [];
                foreach ($path as $val) {
                    array_shift($path);
                    $tmpV = $val;
                    $underLine = strpos($val, '_');
                    if( $underLine!==FALSE && $underLine!==0 ){
                        $val = join('',array_map('ucfirst',explode('_', $val)));
                    }else{
                        $val = ucfirst($val);
                    }
                    if (is_file($dir . DS . $val . $suffix . EXT)) {
                        $item[] = $tmpV;
                        break;
                    } else {
                        $dir .= DS . $tmpV;
                    }
                    $item[] = $tmpV;
                }
                $controller = implode('.', $item);

这是我更改后的代码，看是否可以采纳
