### ISSUE TITLE
多应用模式有点不伦不类，为什么静态文件不进行区分？简单点直接将public进行区分不好吗？

### ISSUE THREAD

**Issue by oracleKing** [top-think/framework#2603]
我现在是将public移动到应用内了，目测没啥问题，但官方文档上“一旦移动位置，会影响内置的运行指令。”什么指令，有啥影响，这个怎么查啊？
![image](https://user-images.githubusercontent.com/14267316/139212228-84579562-5420-4428-b386-3a313496447a.png)
![image](https://user-images.githubusercontent.com/14267316/139212979-e542f8f4-5776-4cb0-b805-77d5733be06a.png)

**Comment by augushong** [comment]
thinkphp有一个命令
`php think run`,
移动之后,内置的服务器不能用.

**Comment by baoguok** [comment]
这个需求直接用yii2 吧，thinkphp 那个多应用其实就是多模块（module）

**Comment by liu21st** [comment]
前后端分离已经是趋于主流了 框架本身没有太多前端组件的考虑
