### ISSUE TITLE
psr/container 这个引用包11月5日发布了1.1.2版本，要求PHP最低7.4，导致thinkphp的最低版本提高到7.4了

### ISSUE THREAD

**Issue by aweihaitun** [top-think/framework#2607]
psr/container 这个引用包11月5日发布了1.1.2版本，要求PHP最低7.4，导致thinkphp的最低版本提高到7.4了，需要尽快调整下引入规则

**Comment by liu21st** [comment]
这个可以自己调整composer.json 改变依赖的
