### ISSUE TITLE
常驻后台进程内存泄漏问题

### ISSUE THREAD

**Issue by MrCJJW** [top-think/framework#2615]
版本5.0.24
场景
后台rabbitmq消费者进程，使用模型查询，存在内存泄漏
排查是因为Query和Builder之间存在循环引用导致
![image](https://user-images.githubusercontent.com/15009827/144205035-c5ccd2fa-c3bc-4685-9a46-81979fe685df.png)
![image](https://user-images.githubusercontent.com/15009827/144204940-cc5e0979-55d6-4a64-bb66-48c9dff3af22.png)

目前找到的解决办法是每次消费完手动执行```gc_collect_cycles()```

请问有其他解决方案吗

**Comment by yunwuxin** [comment]
参考php的垃圾回收机制
https://www.php.net/manual/zh/features.gc.collecting-cycles.php

缓冲区满了php会自动回收的
