### ISSUE TITLE
v5.0.*db里面的Query.php在php7.4版本会报错

### ISSUE THREAD

**Issue by Sanit1** [top-think/framework#2617]
library/think/db/Query.php 400行

$seq = (ord($value{0}) % $rule['num']) + 1;

php7.4版本移除了通过{}来访问下标的方法，所以这里要改成

$seq = (ord($value[0]) % $rule['num']) + 1;

希望有空修复一下

**Comment by liu21st** [comment]
5.0版本已经不在维护期了哦
