### ISSUE TITLE
env 常规配置末尾包含‘=’ src/think/Env.php 解析抛出异常

### ISSUE THREAD

**Issue by zyimm** [top-think/framework#2627]
tp 版本：6.0.5
```
RABBITMQ_USER=MjphbXFwLWNuLWk3bTJoeWNsNTAwMjpMVEFJNXQ3bVN5YTdBcWVNVm1pc0Z6UVM=

```
因为 RABBITMQ_USER 在.env 配置中对应value值中末尾含有"=" 导致框架`vendor/topthink/framework/src/think/Env.php on line 42`  解析时候发生异常，报错如下：
```
Warning: syntax error, unexpected '=' 
```

**Comment by yzh52521** [comment]
RABBITMQ_USER="MjphbXFwLWNuLWk3bTJoeWNsNTAwMjpMVEFJNXQ3bVN5YTdBcWVNVm1pc0Z6UVM="

**Comment by zyimm** [comment]
> 
是的，但是其他框架不会 hyperf laravel 不会。就还是建议官方换一种实现方式！

**Comment by hongfs** [comment]
或者最快处理方式是放在 config 里面吧。

**Comment by zyimm** [comment]
> 

这种配置都是ci 自动化搞得。不会让开发放到自己配置文件中！

**Comment by liu21st** [comment]
ini配置的规范就是这样

**Comment by zyimm** [comment]
> ini配置的规范就是这样

ini 和 env 还有区别的。

**Comment by Yurunsoft** [comment]
<https://www.php.net/manual/zh/function.parse-ini-file.php>
`parse_ini_file()` 第3个参数可以传 `INI_SCANNER_RAW` 来实现这个需求

**Comment by hongfs** [comment]
.env 让 ci 那边记得把 `=` 替换成某个制定字符串，然后在 config 那边匹配到就替换回 `=`，这样子也不需要改 tp 的文件了。
