### ISSUE TITLE
6.0.10版本  .env 配置文件疑似有bug

### ISSUE THREAD

**Issue by khongshao** [top-think/framework#2629]
true与false会被解析成为字符串，因此'false'在一些判断中会判定为true
查看代码发现在 src/think/Env.php 文件中，load函数中(第42行) ：$env = parse_ini_file($file, true, INI_SCANNER_RAW) ?: [];
INI_SCANNER_RAW参数会导致true和false解析成字符串， 感觉配置文件要使用1和0？

**Comment by sy-records** [comment]
Fixex by d9cadb6971ae92ff85ba5f2be77a40b0ad5718fb
