### ISSUE TITLE
php8.1 trim Passing null to parameter in Request.php

### ISSUE THREAD

**Issue by superlbr** [top-think/framework#2644]
`Passing null to parameter #1 ($string) of type string is deprecated`

https://github.com/top-think/framework/blob/4611cbe7c21e2e7e456828a20228f4e61ca03f5d/src/think/Request.php#L1419

**Comment by augushong** [comment]
这个问题解决了吗,使用php8.1会有这个错误

**Comment by superlbr** [comment]
需要自己加判断，对strlen，trim处理空值时直接返回

**Comment by yangguangwuwu** [comment]
这个啥时候能修复

**Comment by yangguangwuwu** [comment]
我的天 合并错 版本了

**Comment by yangguangwuwu** [comment]
现在合到 5.0去了
