### ISSUE TITLE
关于字段缓存的用法

### ISSUE THREAD

**Issue by augushong** [top-think/framework#2646]
之前文档里写的是:
通过这个命令行生成数据库字段缓存
```
php think optimize:schema
```

但是我最近看代码和使用中发现,现在只需要开启数据库配置`fields_cache`为`true`,就可以使用字段缓存了,不需要运行这个命令,
是这个意思吧.
如果用不到了的话,把这个命令从框架中移除吧.文档也更新一下.

**Comment by augushong** [comment]
如果确实不依赖这个命令了,也不需要移除,更新下文档说明,
这个命令可以用来检查模型的字段缓存是否会出错.

**Comment by liu21st** [comment]
本来就是两种不同的机制 不存在依赖不依赖的问题

**Comment by augushong** [comment]
但是开启了`fields_cache`,就不需要运行这个命令,
关闭了`fields_cache`,运行这个命令也不会生成缓存.

现在的这个命令就只有两个功能:
- 提前生成缓存
- 更新字段缓存

但是目前文档里的介绍,似乎只有使用这个命令才能生成缓存.

我的意思是要不要更新一下文档里的说明.

还是说并fields_cache和命令行并没有关系.
