### ISSUE TITLE
关于代码规范的版本迭代

### ISSUE THREAD

**Issue by jasonfanjun** [top-think/framework#2655]
https://www.php-fig.org/psr/psr-2/

`Deprecated - As of 2019-08-10 PSR-2 has been marked as deprecated. PSR-12 is now recommended as an alternative.`

从官方文档中看到thinkphp6.0框架是遵循PSR-2代码命名规范，但该规范已在2019年08月10日结束支持。
官方是否考虑以PSR-12规范进行跟进？

**Comment by liu21st** [comment]
文档是早些写的 但基本的代码规范都是一直保持更新的
