### ISSUE TITLE
路由中间件传参传不了。照文档使用，控制器打印值为空

### ISSUE THREAD

**Issue by wybwsk** [top-think/framework#2656]
//中间件
class CheckAuth{
    public function handle($request, \Closure $next){
          $request -> hello = 'ThinkPHP';
          dump($request->hello);   //ThinkPHP;
          return $next($request);  
    }
}

//路由
Route::domain('api', function () {
      Route::get('/test','Test/index');
}）->middleware([
        \app\api\middleware\CheckAuth::class
]);
 
控制器
use think\Request;
class TestController {
      public function index( Request $request){
             dump ($request->hello);   //null
      }
}

最终的结果是。
ThinkPHP 
Null

**Comment by augushong** [comment]
会不会是路由没生效.
怎么访问的,应该得是这种格式吧.api.domain.com/Test/index

**Comment by wybwsk** [comment]
api.domain.com/test
路由那，在这里我少写了个/，代码是对的。
能访问，执行其他的都跑。而且不止一个控制器和方法。

**Comment by augushong** [comment]
```
Route::get('/tests','Test/index');
}）->middleware([
\app\api\middleware\CheckAuth::class
]);
```
你把美化路由的`test`改成`tests`试试,会不会是因为跟控制器重名导致的.

**Comment by wybwsk** [comment]
Route::get('/storegoods/add','StoreGoods/add');
正式的是这个，也不行。。
我试着按流程dump....
中间件  checkAuth dump($request->hello)
Thinkphp
请求类  \think\REQUEST    __SET  __GET  都dump 
hello=> thinkphp
然后就到控制器add,      dump('123'),dump($request)....  
结果就是
123
null。
像是在进控制器之前把request重置一下一样。

**Comment by augushong** [comment]
通过`$this->request`访问的可以获取到吗,

版本是多少呢

**Comment by wybwsk** [comment]
php8.0.14
thinkphp v6.0.12LTS
Request
$this->request都试过。  在中间件里面怎么都有。在中间件打印Request类里面的，也有值。。
只要一next，过到控制器，就没有了。

对了，我是域名路由加分组路由+中间件来控制哪些要过中间件，哪些不要过中间件。


Route::domain('adminapi', function () {
    Route::group('',function(){
        Route::get('/storegoods/add','StoreGoods/add');
    })->middleware([
        \app\adminapi\middleware\CheckAuth::class
    ]);
    Route::post('/login','Gateway/login');
});

**Comment by augushong** [comment]
`Route::group()`,

不要加第一个参数,
如果要加的话,不要用空字符串,用`StoreGoods`试试,
使用分组的话,`Route::get('/storegoods/add','StoreGoods/add');`
可以简化为:`Route::get('/storegoods/add','add');`
这样试试

**Comment by wybwsk** [comment]
不加参数。。
route::group(function(){})
一样，拿不到参数。。
然后简化。。也是，拿不到参数。。
我试着重新composer tp。。按同样的路由方式，仅测试传参，也传不了。

**Comment by wybwsk** [comment]
找到原因了。容器定义文件。
provider.php
use app\Request;
'think\Request'          => Request::class,

然后app\Request继承\think\Request;
里面虽然啥内容都没有。但是中间件。路径等一系列值都去除了。把这个取消掉就可以了。
