### ISSUE TITLE
日志配置：apart_level这个配置项不生效

### ISSUE THREAD

**Issue by lottahuang** [top-think/framework#266]
根据官方文档，尝试配置了apart_level，但是sql、error日志并没有独立文件

    // +----------------------------------------------------------------------
    // | 日志设置
    // +----------------------------------------------------------------------

    'log'                    => [
        // 日志记录方式，内置 file socket 支持扩展
        'type'  => 'File',
        // 日志保存目录
        'path'  => LOG_PATH,
        // 日志记录级别
        'level' => [], 
        'apart_level'   =>  ['error','sql'],
    ],

阅读了相关源码，Log.php和File.php，并没有对apart_level这个配置项做处理，所有类型的数据都写入同一个文件。
`$destination = $this->config['path'] . date('Ym') . DS . date('d') . '.log';`

**Comment by guandaxia** [comment]
if (in_array($type, $this->config['apart_level'])) {
                // 独立记录的日志级别
                $filename = $path . DS . $type . '.log';
                error_log("[{$now}] {$server} {$remote} {$method} {$uri}\r\n{$level}\r\n", 3, $filename);
            } else {
                $info .= $level;
            }
这个没问题啊，你是最新的吗？这是对apart_level的处理

**Comment by lottahuang** [comment]
谢谢，最新版确实有了。
