### ISSUE TITLE
系统信息泄露 Information Leakage

### ISSUE THREAD

**Issue by Lyther** [top-think/framework#2665]
Spotted a system information leakage under default configuration.

Detail: https://github.com/Lyther/VulnDiscover/blob/master/Web/ThinkPHP_InfoLeak.md

**Comment by sy-records** [comment]
You should turn off APP_DEBUG.

```env
APP_DEBUG = false
```

**Comment by Lyther** [comment]
It's not necessary for default-level information. Most of the developers won't turn off this config. I recommend setting the default option for APP_DEBUG = false.
