### ISSUE TITLE
在PHP8, 执行指令时不支持多种类型传入，会报错，直接浏览器URL访问就没有问题

### ISSUE THREAD

**Issue by yshengwu** [top-think/framework#2673]
![图片](https://user-images.githubusercontent.com/13916868/158003417-82475242-45e0-44fc-952b-8c9a26c33cb9.png)

![图片](https://user-images.githubusercontent.com/13916868/158003425-3581cea4-be53-4710-8e8d-09466c9e9644.png)

在PHP8, 执行指令时，会报错，直接浏览器URL访问就没有问题

**Comment by augushong** [comment]
你确定命令行和浏览器中是同一个环境吗,命令行也是php8?
