### ISSUE TITLE
更新后 Argument 2 passed to think\Cookie::delete() must be of the type array, int given

### ISSUE THREAD

**Issue by yemaozi999** [top-think/framework#2676]
更新后
Argument 2 passed to think\Cookie::delete() must be of the type array, int given

![image](https://user-images.githubusercontent.com/16147749/159425669-301b4301-ef6c-418c-b620-2ce9808588e7.png)

**Comment by yemaozi999** [comment]
版本  6.0.12lts

**Comment by augushong** [comment]
delete方法第二个参数传的是配置,为什么要传整形呢,之前是怎么用的.
