### ISSUE TITLE
Config类set的意义是什么？

### ISSUE THREAD

**Issue by Yuii-guoguo** [top-think/framework#2678]
set=get+设置获取到数组
不能保存到配置文件这个方法有什么卵用吗？

**Comment by augushong** [comment]
这个只是为了临时切换或者修改一下配置文件,比如从数据库读取覆盖到程序的默认配置,

最佳实践是配置应当在运行前提前设置好,不应该修改.

**Comment by augushong** [comment]
你要是想保存,可以写到缓存或者其他地方,等框架加载时读取覆盖.

**Comment by Yuii-guoguo** [comment]
我现在的需求是修改数据库配置文件来完成安装引导，Config和Env类都不能保存文件。

**Comment by Yuii-guoguo** [comment]
流年这操作属实给我整不会了

**Comment by augushong** [comment]
恩,框架没有内置类似的功能,动态生成代码是很危险的.

作为开发框架,不可能提供这种东西的.

不过你可以参考一下其他产品的解决方案,这种产品满大街都是.

https://gitee.com/ulthon/ulthon_admin/blob/master/public/install.php

**Comment by yunwuxin** [comment]
是你这操作很奇葩  还能在线直接改php文件？
