### ISSUE TITLE
TP6最新版，加了路由地址，PHP获取响应码都是404的问题

### ISSUE THREAD

**Issue by reejue** [top-think/framework#2679]
加了路由之后的地址，PHP获取其响应码都是404的问题

用Thinkphp6开发了api接口，为了该接口地址便于后续维护使用了路由添加上版本号，比如www.aaa.com/api/ip这个接口，路由后是www.aaa.com/api/v1/ip

API地址做主备切换，客户机先判断API地址是否有效，即用curl_getinfo请求www.aaa.com/api/v1/ip的状态码，发现返回404
应该返回200状态码才对，不知道为何返回404（浏览器访问该地址状态码却是正常的200）

下面是PHP查询目标URL状态码的函数
`$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);`

路由设置为：
`Route::get('api/v1/:function', 'api/:function');`

不知道是BUG还是我哪里设置错了？

完整测试代码：
```
$url = 'http://localhost:10000/index.php/api/v1/iplocation?ip=14.153.11.23';
echo get_http_code($url);  // 显示为404
function get_http_code($url)
{
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_TIMEOUT, 3);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_HEADER, true);
    curl_setopt($ch, CURLOPT_NOBODY, true); // remove body
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    $head     = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return $httpCode;
}
```

**Comment by sy-records** [comment]
路由设置的第二个参数是控制器方法，不是路由地址

**Comment by reejue** [comment]
> 路由设置的第二个参数是控制器方法，不是路由地址

浏览器打开是200，但PHP打开就是404，就算使用官方的自带路由也是404，请测试

```
Route::get('think', function () {
    return 'hello,ThinkPHP6!';
});
```


测试代码：
```
$url = 'http://localhost:10000/think';
echo get_http_code($url);  // 显示为404

function get_http_code($url)
{
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_TIMEOUT, 3);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_HEADER, true);
    curl_setopt($ch, CURLOPT_NOBODY, true);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    $head     = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return $httpCode;
}
```

**Comment by sy-records** [comment]
```
    curl_setopt($ch, CURLOPT_NOBODY, true);
```

这个需要移除

**Comment by reejue** [comment]
> ```
>     curl_setopt($ch, CURLOPT_NOBODY, true);
> ```
> 
> 这个需要移除

感谢您的回复，已移除这个参数，同样还是返回404

应该是tp6的bug，我之前使用的5.0.24开发的程序，路由后的地址是能正确返回200的，仅在tp6下出现404问题

**Comment by sy-records** [comment]
我用你 https://github.com/top-think/framework/issues/2679#issuecomment-1080948748 的代码测试，移除掉是正常的。
你加了nobody会发起一个option的请求，路由定义的get，所以会404

**Comment by reejue** [comment]
> 我用你 [#2679 (comment)](https://github.com/top-think/framework/issues/2679#issuecomment-1080948748) 的代码测试，移除掉是正常的。 你加了nobody会发起一个option的请求，路由定义的get，所以会404

谢谢！是我疏忽了，把路由规则的get改成any就可以了，特别感谢！
