### ISSUE TITLE
View 的 assign 方法与 config 方法无效

### ISSUE THREAD

**Issue by gyjcode** [top-think/framework#2680]
![image](https://user-images.githubusercontent.com/45870098/160732811-db507170-f9b6-4e46-beab-4930004b218b.png)
如图，使用 config 临时修改文件后缀为 php 报错：
![image](https://user-images.githubusercontent.com/45870098/160732888-8988951f-f7bb-46d1-9f11-f445ac2f7fad.png)
修改 config.php 没问题，但是这里需要临时修改后缀。
使用 assign 赋值
![image](https://user-images.githubusercontent.com/45870098/160733091-91597f86-af97-46ed-84d1-5f93109af039.png)
报错
![image](https://user-images.githubusercontent.com/45870098/160733124-901f0b7b-0a4a-4ca9-9c6a-93176fdaa902.png)
使用 fetch 赋值无问题。

**Comment by augushong** [comment]
用另一种配置方式,
Config::set()的方式试试.

**Comment by augushong** [comment]
变量的问题,试试
engine和fetch分开写试试,
```
View::engine('php');
View::fetch();
```

**Comment by gyjcode** [comment]
> 变量的问题,试试 engine和fetch分开写试试,
> 
> ```
> View::engine('php');
> View::fetch();
> ```

可以了，非常感谢。能否给说下具体的原理？因为在学习中，想了解下为什么会这样。

**Comment by augushong** [comment]
框架有问题,没达到文档里的预期用法,应该要调整

**Comment by gyjcode** [comment]
> 框架有问题,没达到文档里的预期用法,应该要调整

好的，感谢。
