### ISSUE TITLE
资源路由 delete 控制器中 使用 redirect 重定向使用 Delete 方式是正常的吗？

### ISSUE THREAD

**Issue by gyjcode** [top-think/framework#2683]
如题，想要再数据删除后 路由重定向到资源列表页面，使用的 redirect 方法。但是发现重定向使用的是 DELETE 方式，不是 GET 方式。这是正常的吗？
![delete-m](https://user-images.githubusercontent.com/45870098/161361046-11ce272e-6025-43b1-8f24-178f842632c3.png)

![delete-r](https://user-images.githubusercontent.com/45870098/161361052-b05e2c36-13da-4f14-8b64-2295e938d0bf.png)

另 update 与 save 操作方法中的重定向好像使用的是 GET 方式。

**Comment by augushong** [comment]
资源路由采用restful标准，可以先了解一下restful。
正常。

**Comment by gyjcode** [comment]
> restful



> 资源路由采用restful标准，可以先了解一下restful。 正常。

好的，感谢
