### ISSUE TITLE
tp6.0.3 如何修复这个漏洞？

### ISSUE THREAD

**Issue by baiachen** [top-think/framework#2695]
`/index.php/?s=/index/\think\app/invokefunction&function=call_user_func_array&vars[0]=file_put_contents` 可随意写入文件，怎么修复？

**Comment by sixgodf** [comment]
controller not exists:\think\app
没有啊

**Comment by sixgodf** [comment]
> `/index.php/?s=/index/\think\app/invokefunction&function=call_user_func_array&vars[0]=file_put_contents` 可随意写入文件，怎么修复？

controller not exists:\think\app   没有啊

**Comment by baiachen** [comment]
很遗憾没人回复，暂时这样处理了
```
$url = $_SERVER['REQUEST_URI'];
if(strpos(strtolower($url),"invokefunction") !== false)
{
    die("thinkphp没人维护了？");
}
if(strpos(strtolower($url),"call_user_func_array") !== false)
{
    die("thinkphp已经凉凉了吗？");
}
```

**Comment by liu21st** [comment]
有问题就更新到最新版本

**Comment by augushong** [comment]
我之前也试过，也并没有执行成功啊。
更新到新版本不就行了么
