### ISSUE TITLE
一对多预载入查询缓存问题

### ISSUE THREAD

**Issue by 1459416736** [top-think/framework#270]
$data =GoodsSpec::all($id,'SpecItem',false);
//今天更新最新TP5库后，这里是否缓存只是false，改成true会报错
我看了下输出的数据格式，头一次执行是正常的，第二次就只会返回当前数据表的数据，不会返回关联表的数据了

**Comment by liu21st** [comment]
预载入查询是不支持查询缓存的

**Comment by liu21st** [comment]
这个问题我今天修正了下
