### ISSUE TITLE
使用 axios 请求TP6.0.12接口数据，Request 内容为空？

### ISSUE THREAD

**Issue by gyjcode** [top-think/framework#2702]

**Comment by banlancegit** [comment]
这个跟think没有关系,主要还是请求方式问题,直接搜索axios请求后端接收不到数据,

**Comment by augushong** [comment]
axios 默认使用json提交数据，而不是form，$Request->post()获取不到数据，通过$Request->json()或者->input获取数据；

**Comment by gyjcode** [comment]
> axios 默认使用json提交数据，而不是form，$Request->post()获取不到数据，通过$Request->json()或者->input获取数据；

感谢可以了。input 不限制提交数据的类型码？其他方式是不是都需要提交的数据是 x-www-form-urlencoded

**Comment by gyjcode** [comment]
> axios 默认使用json提交数据，而不是form，$Request->post()获取不到数据，通过$Request->json()或者->input获取数据；

另外，直接使用 input 可以获取数据，使用 $request->input() 获取不到数据。

**Comment by augushong** [comment]
恩，说错了，$Request->getInput()
