### ISSUE TITLE
【Bug反馈】关于多语言get获取指定语言包的值

### ISSUE THREAD

**Issue by xiaoxing1617** [top-think/framework#2703]
[tp6_demo.zip](https://github.com/top-think/framework/files/8568363/tp6_demo.zip)
上面是简单写的demo示例

关于第三个参数指定语言后，就获取不到值的问题，我看Lang类里面的get方法，就是Lang类文件的第261行，$this->lang[$range][strtolower($name)]取不出下标，不清楚到底是什么问题，我php版本是7.3.4。。官方可以看看~~~~

**Comment by xiaoxing1617** [comment]
忘了说，这个是tp6.0.3版本，看示例代码就知道了

**Comment by sy-records** [comment]
Duplicate of #2704
