### ISSUE TITLE
使用 axios 请求 thinkphp 接口返回 422 错误？如何让它返回 200

### ISSUE THREAD

**Issue by gyjcode** [top-think/framework#2712]

**Comment by gyjcode** [comment]
![image](https://user-images.githubusercontent.com/45870098/167548588-1c5002b0-d782-45cb-a03c-8fb1718df179.png)

应该是内置验证 validate 返回的状态码。
有没有办法自定义系统消息的状态码？同时求一份框架默认的 code 与 httpStatus 的清单。

**Comment by augushong** [comment]
自己捕捉异常，按自己的规则返回

**Comment by gyjcode** [comment]
解决了，非常感谢
