### ISSUE TITLE
多语言设置关闭，仍然设置相关cookie

### ISSUE THREAD

**Issue by forLing** [top-think/framework#272]
在配置文件中对多语言设置（`lang_switch_on`）关闭时，仍然会设置相关cookie
问题可能出现在`library/think/exception/Handel.php`的 `208`行

```
// 导入语言包
if (!Config::get('lang_switch_on')) {
    Lang::load(THINK_PATH . 'lang' . DS . Lang::detect() . EXT);
}
```

是否应该去掉判断前的`！`？

**Comment by liu21st** [comment]
异常是忽略该配置 自动侦测语言后 输出错误信息的

**Comment by forLing** [comment]
@liu21st 
恩 ,这个理解了
但是没有开启多语言,不应该写入多语言使用的cookie : `think_var`吧?
