### ISSUE TITLE
thinkphp6 获取器报错 【未定义数组索引: status】

### ISSUE THREAD

**Issue by gyjcode** [top-think/framework#2720]
使用thinkphp 创建用户后紧接着用获取器获取状态的值 status_text 会报错  未定义数组索引: status，但是实际上用户已经创建成功了，status 使用的是默认值，未传参。

**Comment by big-dream** [comment]
自行判断$data 是否包含 `status`，框架不会读取表结构中的默认值。如果需要获取添加后的完整数据，可以创建后调用`refresh`。
```php
$model = Model::create([]);
$model->refresh();
```
