### ISSUE TITLE
model 类 all方法

### ISSUE THREAD

**Issue by 1459416736** [top-think/framework#275]
model 类 all方法 根据条件查询所有数据sql语句会带limit 1问题

**Comment by liu21st** [comment]
给出具体的用法代码参考

**Comment by 1459416736** [comment]
例如：一个用户的购物车添加了10个商品，用户ID 为2，我现在在模型里查询用户为2的所添加的商品只能查询出一条数据
$map['uid']=2;
 $data=$this::get($map)->toArray();

**Comment by 1459416736** [comment]
稍等，我看到问题了
