### ISSUE TITLE
url中存在日期格式 2022-02-02 找不到路由

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [top-think/framework#2751]
http://127.0.0.1:9501/manager/v1/register/todo/2022-08-28

Route::group('manager/v1', static function () {
    Route::group('register', static function () {
         Route::get('/todo/:date', 'getRegisterToDoList');
     })->prefix('manager_v1.register.register/');
});

**Comment by augushong** [comment]
框架好像不支持url中包含短横线`-`，之前我遇到过，后来放弃使用短横线了。
不知道开启完全路由能不能支持，可以试一下。

**Comment by SunJary** [comment]
参考官方文档 变量规则[https://www.kancloud.cn/manual/thinkphp6_0/1037496](url)

> 系统默认的变量规则设置是\w+，只会匹配字母、数字、中文和下划线字符，并不会匹配特殊符号以及其它字符，需要定义变量规则或者调整默认变量规则。
可以在路由配置文件中自定义默认的变量规则，例如增加**中划线**字符的匹配：
'default_route_pattern'	=>	'[\w\\-]+',
支持在规则路由中指定变量规则，弥补了动态变量无法限制具体的类型问题，并且支持全局规则设置。使用方式如下：

> 局部变量规则
局部变量规则，仅在当前路由有效：
 // 定义GET请求路由规则 并设置name变量规则
Route::get('new/:name', 'News/read')
    ->pattern(['name' => '[\w|\\-]+']);

相同问题 #2632

**Comment by ZhangTianyi-1998** [comment]
> 
感谢
