### ISSUE TITLE
禁止 Thinkphp6 默认转换 create_time 等时间格式由 int 转换为日期格式？

### ISSUE THREAD

**Issue by gyjcode** [top-think/framework#2752]
如题，请求的接口数据默认将时间戳格式的日期转换为了便于阅读的格式，导致数据更新错误。
如何禁止 thinkphp 6 的这种默认转换，直接返回前端时间戳格式即可。
![image](https://user-images.githubusercontent.com/45870098/187165180-658e3d98-a63b-471d-80b1-3605e7b9fd55.png)

![image](https://user-images.githubusercontent.com/45870098/187165044-a3916f48-29e7-43a1-9db6-e0ed0b225d5a.png)

![image](https://user-images.githubusercontent.com/45870098/187164938-170cec3f-2f53-424f-a8b7-dadd53f80a65.png)

**Comment by augushong** [comment]
https://www.kancloud.cn/manual/thinkphp6_0/1037592

think默认是关闭的，但是生成的项目配置中默认是开启的。试试

**Comment by gyjcode** [comment]
datetime_format 设置为 false 可以了，感谢
