### ISSUE TITLE
看不懂源码中二维数组校验逻辑

### ISSUE THREAD

**Issue by YogiLai** [top-think/framework#2761]
![validate](https://user-images.githubusercontent.com/7279541/190988282-78362f13-6ad9-406f-bd0c-2049f97a0602.png)

**Comment by augushong** [comment]
为啥要看懂，你想干啥，

基本就是：`一维.二维.三维`的写法

**Comment by YogiLai** [comment]
> 为啥要看懂，你想干啥，
> 
> 基本就是：`一维.二维.三维`的写法

你教一下我，怎么校验二维数组的数据

**Comment by augushong** [comment]
比如你提交的数据是这样的：
```
[
    a=>1,
    b=>2,
    c=>[
        A=>1,
        B=>2
    ]
]
```

你希望验证c.A，那就写规则的时候，写：`c.A`。

应该是这样的，三维数组也是这样。

你试试，文档没写的话，回头给补充上

**Comment by YogiLai** [comment]
> 比如你提交的数据是这样的：
> 
> ```
> [
>     a=>1,
>     b=>2,
>     c=>[
>         A=>1,
>         B=>2
>     ]
> ]
> ```
> 
> 你希望验证c.A，那就写规则的时候，写：`c.A`。
> 
> 应该是这样的，三维数组也是这样。
> 
> 你试试，文档没写的话，回头给补充上

$data = [
   ['name1'=>'value1'],
   ['name1'=>'value2']
];
这种二维数组怎么验证，我相信这种数据结构需要验证的比较多

**Comment by augushong** [comment]
那你最好验证之前套一层，比如：
```
[
    'data'=>$data
]
```

到时候验证器就这样写。

或者你试试`0.name1`的写法。

你这种情况，就好像这样：
```
$phone = xxx;
```

这时想验证手机号怎么办呢，实际上就是外面套一层数组：

```
[
    'phope'=>$phone
]
```

之前我是这样处理的。

**Comment by YogiLai** [comment]
> 那你最好验证之前套一层，比如：
> 
> ```
> [
>     'data'=>$data
> ]
> ```
> 
> 到时候验证器就这样写。
> 
> 或者你试试`0.name1`的写法。
> 
> 你这种情况，就好像这样：
> 
> ```
> $phone = xxx;
> ```
> 
> 这时想验证手机号怎么办呢，实际上就是外面套一层数组：
> 
> ```
> [
>     'phope'=>$phone
> ]
> ```
> 
> 之前我是这样处理的。

套多一层？不明白这是什么写法，我看不出能解决我的问题，二维数组元素长度是动态的，这么写可以校验吗？0.name1这种写法有什么用，多了一条数据就验不了了？

**Comment by augushong** [comment]
不是的，这段逻辑实现了一个效果。

```

[
  'a'=>[
    'b'=>[
        'c'=>'username'
    ]
  ]

]

```
通过这段逻辑可以通过`a.b.c`访问到username.

我的意思是，你要验证的数据本身是一个二维数组。tp的验证器支持验证数组。所以应该把你的二维数组，当做验证数组的其中一项。

···

$post_data = [
    'a'=>username,
    'b'=>$data  // 你的二维数组
]
···

可以利用tp的验证器，验证b必须为数组，如果想验证里面的元素，那就一个一个指定。

**Comment by augushong** [comment]
需要把：

```
$data = [
['name1'=>'value1'],
['name1'=>'value2']
];
```

转换成：

```
$data = [
'name1'=>'value1',
'name2'=>'value2'
]
```

如果是你这种写法的话，`0.name1`，`1.name2`的写法了，如果外面再套一层，那就更麻烦了。

**Comment by SunJary** [comment]
> 
> $data = [ ['name1'=>'value1'], ['name1'=>'value2'] ]; 这种二维数组怎么验证，我相信这种数据结构需要验证的比较多

这个需求是对 一堆相同对象 重复多次验证，应该自己写代码循环进行验证，不能期待框架把这种验证也封装好，写好单条数据的验证规则，循环调用一下就是了。

**Comment by augushong** [comment]
是的，还是我理解错例子了。。

**Comment by YogiLai** [comment]
> > $data = [ ['name1'=>'value1'], ['name1'=>'value2'] ]; 这种二维数组怎么验证，我相信这种数据结构需要验证的比较多
> 
> 这个需求是对 一堆相同对象 重复多次验证，应该自己写代码循环进行验证，不能期待框架把这种验证也封装好，写好单条数据的验证规则，循环调用一下就是了。

tp就是模仿lavavel不彻底，为什么laravel这块做得挺好的，很多场景需要这种验证，不是项目所逼我是不想用tp

**Comment by augushong** [comment]
模仿不是目的，该参考参考，该吸收吸收。

框架应该是没有提供现成的方案。需要自己写个循环。

**Comment by YogiLai** [comment]
> 模仿不是目的，该参考参考，该吸收吸收。
> 
> 框架应该是没有提供现成的方案。需要自己写个循环。



> 模仿不是目的，该参考参考，该吸收吸收。
> 
> 框架应该是没有提供现成的方案。需要自己写个循环。

挺low的一个操作
