### ISSUE TITLE
6.1核心框架中的Filesystem是不是没去除干净啊，导致程序报错 "class not exists: filesystem"

### ISSUE THREAD

**Issue by tjztj** [top-think/framework#2777]
![image](https://user-images.githubusercontent.com/17394651/198170993-ea80494a-9e7f-45d3-a9b7-546681699a27.png)

**Comment by tjztj** [comment]
求赶快修复吧

**Comment by yzh52521** [comment]
用开发版 6.1.x-dev

**Comment by tjztj** [comment]
> 用开发版 6.1.x-dev

我不可能在我生产环境中安装开发版的，还是快出一个正式版本吧

**Comment by yzh52521** [comment]
> > 用开发版 6.1.x-dev
> 
> 我不可能在我生产环境中安装开发版的，还是快出一个正式版本吧

为什么呢？ 发布一下就可以用，不发布就不能用？

**Comment by tjztj** [comment]
> 

因为我比较追求新版，经常直接composer update 更新所有的依赖。如果这次安装了这个开发版，那么以后执行composer update的时候就topthink/framework也会更新成最新的开发版，那个时候的开发版不知道有没有其他bug

**Comment by yzh52521** [comment]
> > 
> 
> 因为我比较追求新版，经常直接composer update 更新所有的依赖。如果这次安装了这个开发版，那么以后执行composer update的时候就topthink/framework也会更新成最新的开发版，那个时候的开发版不知道有没有其他bug

等发布了 改正式版啊

**Comment by tjztj** [comment]
> 。。。强迫症，等这个bug修复好了，以后有正式版本了，再升级6.1吧

**Comment by yzh52521** [comment]
> > 。。。强迫症，等这个bug修复好了，以后有正式版本了，再升级6.1吧

那就等

**Comment by shu102ming** [comment]
> Contributor



> 用开发版 6.1.x-dev

开发版现在也是一样报错吧

**Comment by yzh52521** [comment]
> > Contributor
> 
> > 用开发版 6.1.x-dev
> 
> 开发版现在也是一样报错吧

我都升级了上线了
