### ISSUE TITLE
更新到tp6.1.0后filesystem没有了，再单独安装filesystem2.0.x的最新扩展，还是报错，不能用啊

### ISSUE THREAD

**Issue by shu102ming** [top-think/framework#2778]
到底要怎么办，要怎么搞呢， 具体要怎么操作也没有一个文档呀。

**Comment by yzh52521** [comment]
使用 开发版 6.1.x-dev

**Comment by shu102ming** [comment]
> 使用 开发版 6.1.x-dev

我看开发版的版本号也是6.1.0，内容是有区别的吗？

**Comment by yzh52521** [comment]
> > 使用 开发版 6.1.x-dev
> 
> 我看开发版的版本号也是6.1.0，内容是有区别的吗？

已经发版了 update

**Comment by shu102ming** [comment]
> > > 使用 开发版 6.1.x-dev
> > 
> > 
> > 我看开发版的版本号也是6.1.0，内容是有区别的吗？
> 
> 已经发版了 update

恩  收到了，6.1.1的filesystem版本是v1貌似

**Comment by shu102ming** [comment]
更新6.1.1 再手动安装官方filesystem2.0 .x正常了。
