### ISSUE TITLE
TP6 swoole环境下上传图片报 Undefined index: name 问题

### ISSUE THREAD

**Issue by rockyhu** [top-think/framework#2780]
1、上传图片的业务代码为：
`
try {
            // 接收文件
            $files = $this->request->file('file');

            if(!$files) {
                return Response::error('请选择要上传的文件');
            }

            // 验证
            validate(['file' => [
                // 限制文件大小(单位b)，这里限制为4M
                'fileSize' => 4 * 1024 * 1024,
                // 限制文件后缀，多个后缀以英文逗号分割
                'fileExt'  => 'jpg,png,gif,jpeg,pdf,docx,doc,xlsx'
            ]])->check($files);
            // 多文件数组
            $filesArr = [];
            foreach ($files as $file) {
                // 获取上传后的文件路径
                $qiniu_file = Filesystem::disk('qiniu')->putFile('',$file, 'generateUploadFileName');
                $filesArr[] = [
                    'url'=>config('qiniuyun.domain').$qiniu_file,
                    'name'=>$qiniu_file
                ];
            }

            return Response::success($filesArr);
        } catch (Exception $e) {
            return Response::error($e->getMessage());
        }
`

2、报错位置
<img width="727" alt="image" src="https://user-images.githubusercontent.com/15012307/198494022-95baa750-bd03-4f73-b5d0-915996bbdad6.png">

排查后发现，非swoole环境上传图片的$this->file数据转json后为：
`{
    "file": {
        "name": [
            "logo.500.png"
        ],
        "type": [
            "image\/png"
        ],
        "tmp_name": [
            "\/Applications\/MAMP\/tmp\/php\/phpdwymbY"
        ],
        "error": [
            0
        ],
        "size": [
            70172
        ]
    }
}`

swoole环境上传图片的$this->file数据格式转json后为：
{
    "file": [
        {
            "name": "logo.500.png",
            "type": "image\/png",
            "tmp_name": "\/tmp\/swoole.upfile.ykOuNm",
            "error": 0,
            "size": 70172
        }
    ]
}
导致dealUploadFile方法中，$file是一个数组，导致$file['name']报错。

期望官方能够修复！

**Comment by rockyhu** [comment]
/**
     * swoole图片上传数据转非swoole环境上传数据格式，看后续官网是否可以修复
     * @param array $data
     * @return array[]|\array[][]
     */
    public static function normalizeSwooleUploadFile(array $data): array
    {
        // 文件上传格式化
        $array = ['name' => [], 'type' => [], 'tmp_name' => [], 'error' => [], 'size' => []];
        foreach ($data as $files) {
            if (is_array($files)) {
                foreach ($files as $file) {
                    $array['name'][] = $file['name'];
                    $array['type'][] = $file['type'];
                    $array['tmp_name'][] = $file['tmp_name'];
                    $array['error'][] = $file['error'];
                    $array['size'][] = $file['size'];
                }
            }
        }
        return ['file' => $array];
    }

**Comment by yunwuxin** [comment]
你是用的think-swoole么  哪个版本

**Comment by rockyhu** [comment]
临时的解决方案是添加了一个function，针对swoole环境下上传的文件数据按照非swoole环境的数据格式要求进行处理后，可正常实现swoole环境的单文件上传和多文件上传。

`/**
     * swoole图片上传数据转非swoole环境上传数据格式，看后续官网是否可以修复
     * @param array $data
     * @return array[]|\array[][]
     */
    public static function normalizeSwooleUploadFile(array $data): array
    {
        // 文件上传格式化
        $array = ['name' => [], 'type' => [], 'tmp_name' => [], 'error' => [], 'size' => []];
        foreach ($data as $files) {
            if (is_array($files)) {
                foreach ($files as $file) {
                    $array['name'][] = $file['name'];
                    $array['type'][] = $file['type'];
                    $array['tmp_name'][] = $file['tmp_name'];
                    $array['error'][] = $file['error'];
                    $array['size'][] = $file['size'];
                }
            }
        }
        return ['file' => $array];
    }`

**Comment by rockyhu** [comment]
临时的解决方案是添加了一个function，针对swoole环境下上传的文件数据按照非swoole环境的数据格式要求进行处理后，可正常实现swoole环境的单文件上传和多文件上传。

/**
     * swoole图片上传数据转非swoole环境上传数据格式，看后续官网是否可以修复
     * @param array $data
     * @return array[]|\array[][]
     */
    public static function normalizeSwooleUploadFile(array $data): array
    {
        // 文件上传格式化
        $array = ['name' => [], 'type' => [], 'tmp_name' => [], 'error' => [], 'size' => []];
        foreach ($data as $files) {
            if (is_array($files)) {
                foreach ($files as $file) {
                    $array['name'][] = $file['name'];
                    $array['type'][] = $file['type'];
                    $array['tmp_name'][] = $file['tmp_name'];
                    $array['error'][] = $file['error'];
                    $array['size'][] = $file['size'];
                }
            }
        }
        return ['file' => $array];
    }

**Comment by rockyhu** [comment]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/15012307/198536235-68467c82-7ca1-405c-987d-f477951ef9a6.png">
@

> 你是用的think-swoole么 哪个版本

<img width="697" alt="image" src="https://user-images.githubusercontent.com/15012307/198536320-16cdfc21-a8da-49e9-b48b-d6377458ff43.png">

**Comment by yunwuxin** [comment]
不是swoole的版本    我是问  你是用了think-swoole 这个库么  还是自己对接的swoole

**Comment by rockyhu** [comment]
> 不是swoole的版本 我是问 你是用了think-swoole 这个库么 还是自己对接的swoole

"topthink/think-swoole": "3.1.3"这个版本

**Comment by lait233** [comment]
蹲一下

**Comment by yunwuxin** [comment]
think-swoole提交了一个版本  可以测试了看看    使用dev版本

**Comment by rockyhu** [comment]
> think-swoole提交了一个版本 可以测试了看看 使用dev版本

dev版本问题解决！是否考虑发布一个3.1.4的版本？
