### ISSUE TITLE
我可以求求你不要写框架吗？

### ISSUE THREAD

**Issue by AnkoGo123** [top-think/framework#2785]
你的职业就是生产bug是吧？

**Comment by augushong** [comment]
额，写不写框架，跟你有什么关系

**Comment by AnkoGo123** [comment]
> 额，写不写框架，跟你有什么关系

我也是才知道有这么一个坑B的框架，连个orm对接mysql的crud都写不好，跟我当然没关系，过渡的宣传却提供了一堆坑B的orm方法，真的秀出天际，模仿Laravel框架起码要模仿到位吧？连个update方法都不知道应该返回什么，写个J8的框架，搬砖去吧，这个适合这个框架的作者

**Comment by AnkoGo123** [comment]
php奇人真多，奇葩坑逼的框架也如此坑人，

**Comment by augushong** [comment]
没关系就一边去。

**Comment by AnkoGo123** [comment]
> 没关系就一边去。

这是我的帖子，应该是你一边去，搞笑~~

**Comment by AnkoGo123** [comment]
> 没关系就一边去。

我是发给作者的，跟你有毛线关系？傻zi

**Comment by augushong** [comment]
发个帖子可真了不起，去别的地方发帖吧。

**Comment by AnkoGo123** [comment]
> 发个帖子可真了不起，去别的地方发帖吧。

不服你gun一边去发个帖子，求求你快gun

**Comment by augushong** [comment]
你这种话就是发错地方了。还以为理所应当呢

**Comment by AnkoGo123** [comment]
> 你这种话就是发错地方了。还以为理所应当呢

没发错，你是作者？不是的话请不要搭话，一边去

**Comment by augushong** [comment]
懂不懂什么是开源，张口闭口找作者。

**Comment by AnkoGo123** [comment]
> 懂不懂什么是开源，张口闭口找作者。

肯定比你懂啦，你一边去吧孩子，先把头发梳干净点

**Comment by augushong** [comment]
开源就是冤没有头，债没有主。你咋就没明白呢？

**Comment by AnkoGo123** [comment]
> 开源就是冤没有头，债没有主。你咋就没明白呢？

我都说了，你赶紧一边去，

**Comment by augushong** [comment]
你咋还没明白呢，我没说你说错了，我只是说你说错地方了。你要是在知乎骂，绝对一堆赞，而且没人烦你。
我也没说tp多好，那么多issue和pr摆在这呢，自己得有数。
这是反馈具体问题的地方。不是帖子，也不是留言，也不是评论。

**Comment by AnkoGo123** [comment]
> 你咋还没明白呢，我没说你说错了，我只是说你说错地方了。你要是在知乎骂，绝对一堆赞，而且没人烦你。 我也没说tp多好，那么多issue和pr摆在这呢，自己得有数。 这是反馈具体问题的地方。不是帖子，也不是留言，也不是评论。

我知道这里是干什么的，但是这些问题你解决不了，当然你先跟我讨论，你先回答我一个问题，一个orm框架，update方法应该返回什么？你回答我
