### ISSUE TITLE
框架多处bug

### ISSUE THREAD

**Issue by AnkoGo123** [top-think/framework#2786]
框架多处bug

**Comment by augushong** [comment]
具体问题，你后来又删掉了，咋讨论。

tp有三种更新。
数据库update更新，返回影响行数。
模型save更新，返回布尔。
模型静态update，返回影响行数。

好像是这三，具体看文档。我数据库用的比较少，忘了什么样了。

**Comment by augushong** [comment]
关问题走人吧

**Comment by AnkoGo123** [comment]
> 具体问题，你后来又删掉了，咋讨论。
> 
> tp有三种更新。 数据库update更新，返回影响行数。 模型save更新，返回布尔。 模型静态update，返回影响行数。
> 
> 好像是这三，具体看文档。我数据库用的比较少，忘了什么样了。

你看你回答的完全没问题，你再看下tp框架update返回什么，真的是搞笑的框架

**Comment by augushong** [comment]
咋了，不是吗？有问题吗？

**Comment by AnkoGo123** [comment]
![de80e1ed22ef39f22e50aea8a1edef7](https://user-images.githubusercontent.com/84855094/200178797-85ce73e6-576c-412c-82bd-9f951d9309df.png)
你看下这个update一定成功吗？save做返回值处理了吗？

**Comment by AnkoGo123** [comment]
![Uploading 53c05fdd29626a105cfadb4ba166f3d.png…]()

再看一下这个，login的逻辑，update一定成功？并不一定

**Comment by augushong** [comment]
额，这个文档好像有写，你看下吧。
其他一些链式调用的用法和传参用法的不同表现。但最终都会回到这三个基本地操作上。

**Comment by AnkoGo123** [comment]
![8042508f4db21c97c3bbcc6eaa1a69a](https://user-images.githubusercontent.com/84855094/200178975-5c57eca3-d63b-4bac-b8b2-77c2ced92d2a.png)
再看下这个save，事件触发一定会触发吗？并一定，处理了么？没有

**Comment by augushong** [comment]
你代码没传上来。

但是按文档来，没问题的。事件也都能用。

**Comment by AnkoGo123** [comment]
> 你代码没传上来。
> 
> 但是按文档来，没问题的。事件也都能用。

我这里都上传上去了，你的github被屏蔽图片了。自己开个加速

**Comment by augushong** [comment]
你这个用法，就不是tp文档的用法。文档也有写，你可以看看。
其他人也咨询过。可以找找。

**Comment by AnkoGo123** [comment]
我tm真的是一肚子气，看到这种框架

**Comment by augushong** [comment]
哈哈，气什么，tp3那个时代的思维没转过来吧。
要么纯模型用，要么纯数据库操作。
你这个用法不会触发事件，是走得db的操作。跟模型完全没关系。看看文档，有写的

**Comment by AnkoGo123** [comment]
![0324dc7b2fe3b4935b330353424c16a](https://user-images.githubusercontent.com/84855094/200179436-4bbcb255-9b25-43ba-b2bd-d12ca0a371d2.png)
再看下这个json，同理

**Comment by AnkoGo123** [comment]
> 哈哈，气什么，tp3那个时代的思维没转过来吧。 要么纯模型用，要么纯数据库操作。 你这个用法不会触发事件，是走得db的操作。跟模型完全没关系。看看文档，有写的

我截图全部是tp6的源码，没有任何一处是我自己写的，除非我下载错了tp6?

**Comment by augushong** [comment]
我知道，这些源码我也看过，只能说，漏了关键得几点。

先说你的tojson怎么用的

**Comment by AnkoGo123** [comment]
> 我知道，这些源码我也看过，只能说，漏了关键得几点。
> 
> 先说你的tojson怎么用的

这个跟使用者没有任何关系，但凡有一双手我都不会这么写函数，丢弃本应该处理的错误

**Comment by augushong** [comment]
tojson这个好像算，模型好像没有处理结果为null的后续链式操作。

**Comment by AnkoGo123** [comment]
> 我知道，这些源码我也看过，只能说，漏了关键得几点。
> 
> 先说你的tojson怎么用的

我还能举出很多这种本应该处理错误却没有处理的函数，真的是一大堆，所有的crud方法或者函数都有问题，

**Comment by AnkoGo123** [comment]
> tojson这个好像算，模型好像没有处理结果为null的后续链式操作。

查询也有问题，你要的话我还能继续截图，只求作者给一个这样写的理由

**Comment by AnkoGo123** [comment]
一个小学生都不会这么写框架，你懂吧？

**Comment by augushong** [comment]
你之前截得代码和生气的点：
当update方法前面有db 的query操作时，走得是db的用法，而不是模型，此时模型只是贡献表名等。

这个文档有写。不是bug。

**Comment by augushong** [comment]
具体的问题，我愿意讨论讨论。
至于设计标准，测试覆盖率等代码工程问题，我觉得有个度。合适就行，至于怎么样最好，就是项目定位了。

**Comment by AnkoGo123** [comment]
> 你之前截得代码和生气的点： 当update方法前面有db 的query操作时，走得是db的用法，而不是模型，此时模型只是贡献表名等。
> 
> 这个文档有写。不是bug。

这个很明显不是bug，为什么这么说呢，但凡有个正常人的逻辑，都知道应该返回update的影响行数，成功与否，是否出错，这些还需要人教吗。。。我刚看到一个帖子，一个初二的中学生都在问为什么update不返回影响行数，写出这种代码，只有2种可能，一种是有意为之，一种是真的不知道，没写过几年代码，要不是现在我购买的项目中使用这个框架，我真的是连一眼我都懒得看这个框架，当然不只是这个框架，我发觉好多php其他框架也很多错误都忽略，我得 承认我是第一次接触php，但是，这个东西压根跟我熟不熟悉php没有任何关系，我熟悉go,rust,js,ts,c#，python等等语言，从来没碰到过这么明显的不了了的bug，一看就能知道作者是故意写bug，要不就是压根就只懂php（而且还是没写过几行代码的人），你懂我的意思吧？

**Comment by AnkoGo123** [comment]
> 你之前截得代码和生气的点： 当update方法前面有db 的query操作时，走得是db的用法，而不是模型，此时模型只是贡献表名等。
> 
> 这个文档有写。不是bug。

你仔细看下update函数，跟设计 没关系，就是纯纯的不想处理可能出现的错误，压根就不是bug，是故意不处理异常，但，这个是本应该处理的异常

**Comment by augushong** [comment]
昨天一开始我说的几种用法，有些不准确，具体可以看一下文档。

你直觉认为数据库的更新返回影响行数，所以框架的更新也要返回影响行数，否则就是哪里出了问题。这样是不对的。

框架有一种返回影响行数的用法：
![图片](https://user-images.githubusercontent.com/31880431/200202768-b14a0a8f-1907-43c7-ac29-4fff02ba91a6.png)

最基本的Db的update操作是这样的。

框架的第二种基本更新方法是模型的save：
![图片](https://user-images.githubusercontent.com/31880431/200202811-05deb034-b3b3-4cf6-b33e-e35f3411b5f8.png)

这是面向对象的思维。

其他的都是基于以上两种用法的不同调用。
其中，如果在模型后使用Db的query操作，则按照Db的query表现来，不再是模型的概念。

模型的Update静态方法，只是对模型的save模型的调用封装。

我说了很多次了，看文档，看文档，看文档。意思就是说，这些操作没有按照你直觉的来。你可以说这样的设计违反了朴素的用法，但违反了朴素的用法不是bug。

你有没有想过，所谓的直觉的朴素的用法可能并不是最佳的方案。

另外关于tojson的问题，我看了一下，因为toArray返回的永远是可靠的数组，所以json_encode接收的永远是正确的数据，不会出现false的情况。

不是只有你聪明，其他人也都不蠢。

现在update返回行数的用法不常用了，只有面对批量操作数据才会用一下。

现在用模型的查询更新操作，代码很丝滑，理解很容易，可读性更高。

**Comment by AnkoGo123** [comment]
> 

我真的服了你这波强行解释，你先看下这个update函数里面的save方法一定会成功吗？如果不成功呢？返回值是什么？如果成功，返回值是什么？怎么判断是否成功了还是失败了？
![image](https://user-images.githubusercontent.com/84855094/200204796-244fcad0-298a-4754-86cb-73a035543ec2.png)

**Comment by AnkoGo123** [comment]
> 昨天一开始我说的几种用法，有些不准确，具体可以看一下文档。
> 
> 你直觉认为数据库的更新返回影响行数，所以框架的更新也要返回影响行数，否则就是哪里出了问题。这样是不对的。
> 
> 框架有一种返回影响行数的用法： ![图片](https://user-images.githubusercontent.com/31880431/200202768-b14a0a8f-1907-43c7-ac29-4fff02ba91a6.png)
> 
> 最基本的Db的update操作是这样的。
> 
> 框架的第二种基本更新方法是模型的save： ![图片](https://user-images.githubusercontent.com/31880431/200202811-05deb034-b3b3-4cf6-b33e-e35f3411b5f8.png)
> 
> 这是面向对象的思维。
> 
> 其他的都是基于以上两种用法的不同调用。 其中，如果在模型后使用Db的query操作，则按照Db的query表现来，不再是模型的概念。
> 
> 模型的Update静态方法，只是对模型的save模型的调用封装。
> 
> 我说了很多次了，看文档，看文档，看文档。意思就是说，这些操作没有按照你直觉的来。你可以说这样的设计违反了朴素的用法，但违反了朴素的用法不是bug。
> 
> 你有没有想过，所谓的直觉的朴素的用法可能并不是最佳的方案。
> 
> 另外关于tojson的问题，我看了一下，因为toArray返回的永远是可靠的数组，所以json_encode接收的永远是正确的数据，不会出现false的情况。
> 
> 不是只有你聪明，其他人也都不蠢。
> 
> 现在update返回行数的用法不常用了，只有面对批量操作数据才会用一下。
> 
> 现在用模型的查询更新操作，代码很丝滑，理解很容易，可读性更高。

还有这个save方法一定成功？
![image](https://user-images.githubusercontent.com/84855094/200204885-4d8be83f-09dd-469b-8bcc-b160ae0a6252.png)

**Comment by AnkoGo123** [comment]
![image](https://user-images.githubusercontent.com/84855094/200205173-386b7d4a-91b3-41ae-ba43-231e0ea4e12e.png)

**Comment by AnkoGo123** [comment]
![image](https://user-images.githubusercontent.com/84855094/200205272-305b6fff-b7ef-4d04-9fff-b33963914500.png)

**Comment by augushong** [comment]
save失败，直接异常。
![图片](https://user-images.githubusercontent.com/31880431/200205232-ce40a786-ba33-4778-a36c-bda521a824ac.png)

事件中可以设法中断执行。
![图片](https://user-images.githubusercontent.com/31880431/200205094-f688d42a-ae8d-4931-b8ac-785aaded1909.png)

我说这么多，还一句不愿意听进去吗？还觉得自己的想法才是对的？
是先有用法，再有实现。用法参考文档，而不是你的直觉。

好自为之吧，等发下文档里的有问题了，我再来看看，有可能是文档落后了，也有可能代码实现问题。

**Comment by AnkoGo123** [comment]
![image](https://user-images.githubusercontent.com/84855094/200205370-0decda0c-930c-44ee-bab7-eaa71412600c.png)

**Comment by AnkoGo123** [comment]
> 

我完全明白你说的钩子事件中可以处理，但是，你要明白，我是业务层需要处理失败的情况，不是在钩子事件中同意处理，看来你压根就没实际开发过几年代码，我真的服了你的这波解释，这些异常是要返回每个具体的业务层面，而不是统一的钩子处理，

**Comment by AnkoGo123** [comment]
> save失败，直接异常。 ![图片](https://user-images.githubusercontent.com/31880431/200205232-ce40a786-ba33-4778-a36c-bda521a824ac.png)
> 
> 事件中可以设法中断执行。 ![图片](https://user-images.githubusercontent.com/31880431/200205094-f688d42a-ae8d-4931-b8ac-785aaded1909.png)
> 
> 我说这么多，还一句不愿意听进去吗？还觉得自己的想法才是对的？ 是先有用法，再有实现。用法参考文档，而不是你的直觉。
> 
> 好自为之吧，等发下文档里的有问题了，我再来看看，有可能是文档落后了，也有可能代码实现问题。

你真的跟我不是一个层面的，压根就跟文档关系不大，整个框架不是一点半点的不处理错误，是完全就不懂得写框架，你明白我的意思没？我先说明我写了6年代码，阅读过的框架无数，像tp这么奇葩的框架，我是头一回见

**Comment by augushong** [comment]
新tp很多地方都是用异常的，不处理返回值，用抛出异常的思维些业务，所以一般这样做：
![图片](https://user-images.githubusercontent.com/31880431/200205657-f2445187-6e1e-4c28-92c7-aea92dee94b6.png)

**Comment by AnkoGo123** [comment]
> 新tp很多地方都是用异常的，不处理返回值，用抛出异常的思维些业务，所以一般这样做： ![图片](https://user-images.githubusercontent.com/31880431/200205657-f2445187-6e1e-4c28-92c7-aea92dee94b6.png)

对，处理异常的方式是正确的，我不是说他的实现方式有问题，你看下我上面的update方法中的save采用了try...catch。。。来处理了吗？没有，你看到没？你仔细看一下，不只是save

**Comment by augushong** [comment]
你咋还没明白我说的呢。

这个异常就是抛给开发者的。他不会通过try catch 来返回true或false，就是抛给开发者。

**Comment by augushong** [comment]
我就不跟你讨论一个框架应该怎么样了。

**Comment by AnkoGo123** [comment]
> 你咋还没明白我说的呢。
> 
> 这个异常就是抛给开发者的。他不会通过try catch 来返回true或false，就是抛给开发者。

你真的有看过源码吗？我表示怀疑。。
![image](https://user-images.githubusercontent.com/84855094/200206236-923f01d9-bb7e-4e75-b2a3-00858233977d.png)
你看下save并不是一定会抛出异常，他的返回值是bool，当他返回false时候是不是就是失败的情况？这种情况压根不会触发异常，而update里面调用save方法是没处理save的返回值的，这不就是一个再明显不过的bug了吗？你这都不明白我真的不知道改怎么给你解释了
![image](https://user-images.githubusercontent.com/84855094/200206394-b4b63ef8-8a9a-4f00-857e-ab5059549dde.png)

**Comment by AnkoGo123** [comment]
> 我就不跟你讨论一个框架应该怎么样了。

还有一个问题，也是被你强行解释，我发觉你真的跟我不再一个层次（真的不是贬低你，捂脸），你甚至不了解php里面的参数
![image](https://user-images.githubusercontent.com/84855094/200207480-f43c596e-c8cb-48d2-b5a2-74da958dd862.png)
![image](https://user-images.githubusercontent.com/84855094/200207562-910e9b6a-9240-4065-b131-d1b36d0d5534.png)
可以看到json_encode这个方法里面是否返回false或者抛出异常并不只是由第一个参数来决定的，还由flags参数决定，所以，在未知的情况下，即使你传入数组，如果由于某些不可见的因素导致json超时，也是会返回false或者抛出异常的情况，我们不能预知程序会怎么运行，该处理的返回值类型不要擅自改动，特别是自己水平不咋地时候，你懂吧。。。

**Comment by AnkoGo123** [comment]
其他我就不跟你讨论了，叫作者出来，真的是菜到不行的框架，一个毕业生都不如，还学人家写框架！！！

**Comment by AnkoGo123** [comment]
> 其他我就不跟你讨论了，叫作者出来，真的是菜到不行的框架，一个毕业生都不如，还学人家写框架！！！建议赶紧送外卖去

**Comment by AnkoGo123** [comment]
行吧，我就尽量压制住心中的怒火，说实话我真的挺想作者把我教育一顿，而不是像现在这样，一句话不说

**Comment by AnkoGo123** [comment]
再来看一下这个函数
![image](https://user-images.githubusercontent.com/84855094/200209819-d4e37c7c-9792-4990-88b8-a81b8e8348a8.png)
![image](https://user-images.githubusercontent.com/84855094/200209890-6d9b35d2-113a-4096-b701-d6421623c2c9.png)
![image](https://user-images.githubusercontent.com/84855094/200209937-997c0287-6f63-4c09-b4bc-76823616666b.png)
看上图，如果是jsonEncode抛出异常，而且没被处理，那么login执行时候是会导致程序崩溃的

**Comment by yunwuxin** [comment]
> 再来看一下这个函数 ![image](https://user-images.githubusercontent.com/84855094/200209819-d4e37c7c-9792-4990-88b8-a81b8e8348a8.png) ![image](https://user-images.githubusercontent.com/84855094/200209890-6d9b35d2-113a-4096-b701-d6421623c2c9.png) ![image](https://user-images.githubusercontent.com/84855094/200209937-997c0287-6f63-4c09-b4bc-76823616666b.png) 看上图，如果是jsonEncode抛出异常，而且没被处理，那么login执行时候是会导致程序崩溃的

你这个不是应该去问卖你这套程序的人么    他不处理可能出现的异常    跟框架有啥关系  你举例的这个方法  根本不是框架里的

**Comment by AnkoGo123** [comment]
> > 再来看一下这个函数 ![image](https://user-images.githubusercontent.com/84855094/200209819-d4e37c7c-9792-4990-88b8-a81b8e8348a8.png) ![image](https://user-images.githubusercontent.com/84855094/200209890-6d9b35d2-113a-4096-b701-d6421623c2c9.png) ![image](https://user-images.githubusercontent.com/84855094/200209937-997c0287-6f63-4c09-b4bc-76823616666b.png) 看上图，如果是jsonEncode抛出异常，而且没被处理，那么login执行时候是会导致程序崩溃的
> 
> 你这个不是应该去问卖你这套程序的人么 他不处理可能出现的异常 跟框架有啥关系 你举例的这个方法 根本不是框架里的

上面所有截图都是think_orm框架里面的代码，麻烦你看清楚点

**Comment by yunwuxin** [comment]
> > > 再来看一下这个函数 ![image](https://user-images.githubusercontent.com/84855094/200209819-d4e37c7c-9792-4990-88b8-a81b8e8348a8.png) ![image](https://user-images.githubusercontent.com/84855094/200209890-6d9b35d2-113a-4096-b701-d6421623c2c9.png) ![image](https://user-images.githubusercontent.com/84855094/200209937-997c0287-6f63-4c09-b4bc-76823616666b.png) 看上图，如果是jsonEncode抛出异常，而且没被处理，那么login执行时候是会导致程序崩溃的
> > 
> > 
> > 你这个不是应该去问卖你这套程序的人么 他不处理可能出现的异常 跟框架有啥关系 你举例的这个方法 根本不是框架里的
> 
> 上面所有截图都是think_orm框架里面的代码，麻烦你看清楚点

你自己看清楚点吧 ，麻烦你把这3张截图的代码在https://github.com/top-think/think-orm这个库里找给我看看

**Comment by yunwuxin** [comment]
还有  就算控制器里不处理异常   框架本身还有个统一的异常处理机制    不需要所有的地方都去try-catch  可以统一在exception handler里处理

**Comment by AnkoGo123** [comment]
> > > > 再来看一下这个函数 ![image](https://user-images.githubusercontent.com/84855094/200209819-d4e37c7c-9792-4990-88b8-a81b8e8348a8.png) ![image](https://user-images.githubusercontent.com/84855094/200209890-6d9b35d2-113a-4096-b701-d6421623c2c9.png) ![image](https://user-images.githubusercontent.com/84855094/200209937-997c0287-6f63-4c09-b4bc-76823616666b.png) 看上图，如果是jsonEncode抛出异常，而且没被处理，那么login执行时候是会导致程序崩溃的
> > > 
> > > 
> > > 你这个不是应该去问卖你这套程序的人么 他不处理可能出现的异常 跟框架有啥关系 你举例的这个方法 根本不是框架里的
> > 
> > 
> > 上面所有截图都是think_orm框架里面的代码，麻烦你看清楚点
> 
> 你自己看清楚点吧 ，麻烦你把这3张截图的代码在https://github.com/top-think/think-orm 这个库里找给我看看

确实不是，我的锅，我服了，不知道哪里冒出来的框架，艹！

**Comment by AnkoGo123** [comment]
在这里对官方诚挚道个歉

**Comment by AnkoGo123** [comment]
当然上面的save方法，update和其他几个函数是think-orm里面的，这个确实是会异常，还有一个我所需要说的：异常不能统一处理，是不对的这样，比如update查询不到数据也异常吗？对吧？所以这个肯定是有问题的，还望及时改进，作为update返回值返回影响的行数才是可行的！

**Comment by hongfs** [comment]
1. Model 下的 update "直接更新（静态方法）"，返回的确实是行数，我们线上业务确实是这样子判断的（刚刚重新验证也是返回行数）。
2. AfterWrite 是写入后的事件，这时数据“已经”入库了，所以 AfterWrite 执行失败也不应该影响到（如需要应该放在 BeforeWrite 更合适）
3. toJson 要结合上下文的，toArray 返回的是一个数组
4. transaction 当闭包中的代码发生异常会自动回滚

框架不可能满足所有的，可以 fork 自己改一下。

**Comment by lty628** [comment]
1. 哇～，见过世面了
2. 开了天眼
3. 可惜closed
4. 我要是作者我不关

**Comment by AnkoGo123** [comment]
关不关对我影响不大，php还是一门bug贼多的语言，tp框架还是数一数二多bug的框架



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月19日(周三) 下午5:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [top-think/framework] 框架多处bug (Issue #2786)




  
哇～，见过世面了
 
开了天眼
 
可惜closed
 
我要是作者我不关

**Comment by liuwave** [comment]
虽然关闭了，但我白嫖了这么多次，还是要说句，理解文档之后，TP6很用起来丝滑，比tp3、tp5好用太多了。

**Comment by AnkoGo123** [comment]
不影响我对他的垃圾评价，一坨shi的php和php生态



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月10日(周三) 上午8:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [top-think/framework] 框架多处bug (Issue #2786)




 
虽然关闭了，但我白嫖了这么多次，还是要说句，理解文档之后，TP6很用起来丝滑，比tp3、tp5好用太多了。

**Comment by hongfs** [comment]
> 1. Model 下的 update "直接更新（静态方法）"，返回的确实是行数，我们线上业务确实是这样子判断的（刚刚重新验证也是返回行数）。
> 
> 2. AfterWrite 是写入后的事件，这时数据“已经”入库了，所以 AfterWrite 执行失败也不应该影响到（如需要应该放在 BeforeWrite 更合适）
> 
> 3. toJson 要结合上下文的，toArray 返回的是一个数组
> 
> 4. transaction 当闭包中的代码发生异常会自动回滚
> 
> 
> 
> 框架不可能满足所有的，可以 fork 自己改一下。

可最终，不是你对框架的理解或者使用有问题吗？可能，你在为自己能力不行的时候甩锅，我们应该闭嘴

**Comment by liuwave** [comment]
你应该重新审视一下你的编程能能力了，你六年都在吃shi么😂。
觉得不好，你可以fork一份自己改呀。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月10日(周三) 上午8:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [top-think/framework] 框架多处bug (Issue #2786)




 不影响我对他的垃圾评价，一坨shi的php和php生态 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年5月10日(周三) 上午8:43 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [top-think/framework] 框架多处bug (Issue #2786) 
 
 
 
 
   
 虽然关闭了，但我白嫖了这么多次，还是要说句，理解文档之后，TP6很用起来丝滑，比tp3、tp5好用太多了。

**Comment by AnkoGo123** [comment]
我又不用，为什么要用这个框架。我吐槽它垃圾，不代表我要用它或者去改它，你脑子不清晰还是弥漫着一股屁？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月10日(周三) 下午5:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [top-think/framework] 框架多处bug (Issue #2786)




 你应该重新审视一下你的编程能能力了，你六年都在吃shi么😂。 
 觉得不好，你可以fork一份自己改呀。 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年5月10日(周三) 上午8:56 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [top-think/framework] 框架多处bug (Issue #2786) 
 
 
 
 
  不影响我对他的垃圾评价，一坨shi的php和php生态  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2023年5月10日(周三) 上午8:43  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [top-think/framework] 框架多处bug (Issue #2786)  
   
   
   
   
     
  虽然关闭了，但我白嫖了这么多次，还是要说句，理解文档之后，TP6很用起来丝滑，比tp3、tp5好用太多了。

**Comment by liuwave** [comment]
算了，我不和傻子争论。

你是对的，我错了。
你是对的，我错了。
你是对的，我错了。




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年5月10日(星期三) 下午5:05
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [top-think/framework] 框架多处bug (Issue #2786)





 我又不用，为什么要用这个框架。我吐槽它垃圾，不代表我要用它或者去改它，你脑子不清晰还是弥漫着一股屁？ 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年5月10日(周三) 下午5:00 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [top-think/framework] 框架多处bug (Issue #2786) 
 
 
 
 
  你应该重新审视一下你的编程能能力了，你六年都在吃shi么😂。  
  觉得不好，你可以fork一份自己改呀。  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2023年5月10日(周三) 上午8:56  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [top-think/framework] 框架多处bug (Issue #2786)  
   
   
   
   
   不影响我对他的垃圾评价，一坨shi的php和php生态   
     
     
     
   ---原始邮件---   
   发件人: ***@***.***&amp;amp;amp;gt;   
   发送时间: 2023年5月10日(周三) 上午8:43   
   收件人: ***@***.***&amp;amp;amp;gt;;   
   抄送: ***@***.******@***.***&amp;amp;amp;gt;;   
   主题: Re: [top-think/framework] 框架多处bug (Issue #2786)   
     
     
     
     
       
   虽然关闭了，但我白嫖了这么多次，还是要说句，理解文档之后，TP6很用起来丝滑，比tp3、tp5好用太多了。
