### ISSUE TITLE
关于TP6版本号6.1.0 Request 接收参数

### ISSUE THREAD

**Issue by pangxianfei** [top-think/framework#2798]
例子：
获取url参数：www.**.com/?id=123456
传统方式获取值：$request->param["id"];
我的想法：
可以使用对象方式：$request->id,获取id值？
测试了不支持这种方式取值。是否兼容下呢？

**Comment by Rodots** [comment]
请正确参考文档的使用方法，在Thinkphp6.1中你应该使用如下代码获取
`$request->param('id')`
