### ISSUE TITLE
- - 突然model 改动好大   生产环境 宕机好久

### ISSUE THREAD

**Issue by yovei** [top-think/framework#28]
- - 突然model 改动好大   生产环境 宕机好久

**Comment by liu21st** [comment]
既然用于生产环境，最好不要随便更新版本

**Comment by yovei** [comment]
而且现在没有代码提示   希望搞个ide_helper

**Comment by yovei** [comment]
= =! 吃到教训了

**Comment by kinosang** [comment]
TP 5 仍然处于 RC 状态，不推荐用于生产环境。

另外这次 model 重构在分支里面弄了好久之后才合并

**Comment by yovei** [comment]
GIT 提交  自动composer了下    无奈。。。

**Comment by yovei** [comment]
顺道问下   这个版本什么时候能确认下来？
