### ISSUE TITLE
between表达式bug

### ISSUE THREAD

**Issue by lichihua** [top-think/framework#2803]
$orders=\app\admin\model\Order::where([
                [ 'id','between', [1]],
            ])->select();
$orders=\app\admin\model\Order::where([
                [ 'id','between', "1"],
            ])->select();
我这样写,会报找不到下标得错误,这个应该不是故意这样搞得吧

**Comment by augushong** [comment]
between至少得两个值吧。一个算怎么回事，实在不行用in
