### ISSUE TITLE
thinkphp8 使用命令行报错

### ISSUE THREAD

**Issue by yzh52521** [top-think/framework#2828]
PHP Fatal error:  Uncaught ReflectionException: Class "console" does not exist in /vendor/topthink/framework/src/think/Container.php:377

**Comment by liu21st** [comment]
什么命令报错？

**Comment by yzh52521** [comment]
> 什么命令报错？

php think 就报错了

**Comment by yzh52521** [comment]
自定义的命令行 运行就报错了

**Comment by augushong** [comment]
composer install 过了吗

**Comment by yzh52521** [comment]
thinkphp6 没问题的

**Comment by yzh52521** [comment]
我知道什么问题了，打扰了
