### ISSUE TITLE
请问 Db::table 有没有办法实现类似模型的获取器类似的功能？根据某个字段值计算另一个字段值

### ISSUE THREAD

**Issue by gyjcode** [top-think/framework#2830]
如题：Db::table 有没有办法实现类似模型的获取器类似的功能？根据 status 字段值计算 status_text 的值以方便前端获取？
![db-table](https://user-images.githubusercontent.com/45870098/218304618-389968c8-0283-4c26-8dd5-a28804d4c156.png)

**Comment by liu21st** [comment]
https://www.kancloud.cn/manual/thinkphp6_0/1037572
