### ISSUE TITLE
子查询的一个问题，或者还有别的方法？

### ISSUE THREAD

**Issue by molong** [top-think/framework#284]
代码示例如下：
`
		$map['id'] = array('NOTIN', db('TaskCustomer')->where('task_id', $id)->field('customer_id')->select(false));
		$list = model('customer')->where($map)->fetchSql(true)->paginate(20, false, array(
			'query' => $this->param,
		));
`
生成的子查询：
`SELECT * FROM `sent_customer` WHERE  `id` NOT IN ('SELECT `customer_id` FROM `sent_task_customer` WHERE  `task_id` = \'2\' ') LIMIT 0,20`
多了一对引号

**Comment by WeakSun** [comment]
其实这种问题没必要在ORM上死磕，ORM是简化常规操作，不是完全替代原生。
比较复杂的语句，直接手写，替换表名即可，高效实用。

**Comment by liu21st** [comment]
没有这种写法的 可以用闭包

**Comment by molong** [comment]
好吧，用where(拼接字符串)解决

**Comment by liu21st** [comment]
子查询的结果都是用来拼接字符串的 不是用来直接查询的
