### ISSUE TITLE
TP6.1多应用模式下生成数据表字段缓存的问题

### ISSUE THREAD

**Issue by oyvfhp** [top-think/framework#2854]
TP6.1有两种字段缓存模式，命令模式和开启配置 fields_cache 的自动模式，当前在多应用下有这样的问题。
1. 多应用命令模式下生成缓存问题
`php think optimize:schema worker`
生成worker应用下的字段缓存，从源码中看到当前主要是扫描Model目录下的文件来生成对应的表字段缓存，但如果目录下有多级目录，就无法生成多级目录下的字段缓存。
![image](https://user-images.githubusercontent.com/4404279/226076210-74e119dc-c322-41c6-9b88-13af4180f690.png)
源代码只进行了一次 scandir ，没有扫描子目录。
![image](https://user-images.githubusercontent.com/4404279/226076238-9b078e5d-e5a7-40c8-a14d-bd1762e91d2c.png)

2. fields_cache模式下的缓存问题
自动生成缓存的机制很方便，但没有自定义缓存目录设置，只能使用cache中的default配置，会导致表中有新字段无法及时更新，如果能统一将字段缓存放置一个位置，可以统一进行清除。

@liu21st   麻烦赐教。

**Comment by liu21st** [comment]
之所以设计如此 主要是模型并不推荐使用多级 （控制器有多级需求）
第二个问题 数据库配置文件支持设置 cache_store 来定义使用某个连接

**Comment by oyvfhp** [comment]
好的，根据您的指点，我把代码都翻了一下，发现使用命令模式也必须要开启fields_cache才可以，他们最终使用的是同样的机制，只是使用命令可以同时将使用的所有的Model生成缓存文件，不然开启fields_cache=true只能根据请求来生成缓存，这里我有个疑问，如果单纯了开启fields_cache=true，从再有的代码上看，更改字段类型后不会对缓存进行更新，这块没有考虑其缓存更新的问题吗？ @liu21st

**Comment by liu21st** [comment]
你仔细看下 命令行的代码就会明白 指令方式生成每次都是强制重写读取的

**Comment by liu21st** [comment]
最新的修改 指令执行方式不依赖fields_cache配置了
