### ISSUE TITLE
framework/src/think/File.php，默认命名bug

### ISSUE THREAD

**Issue by yuyachong** [top-think/framework#2858]
6.1.2
PHP8.0.26
Filesystem::disk('public')->putFile(xxx, xxx , 'date')

File.php line 192
date() expects at least 1 argument, 0 given

![94383cf0cf0a96c0f3d17a2e2bfe5e7b_37591c6061a94cffc0e9c3eafb22bbb3](https://user-images.githubusercontent.com/73475361/227754331-9751b536-9816-4ed0-a363-f7528cab576a.jpg)

按照文档所说，有3种默认规则，
如果date识别为函数，直接自己写闭包，或者直接自定义文件名即可，
这里不应被识别为date()因为需要有参数，与文档描述不符

**Comment by liu21st** [comment]
默认就是date 我修正下文档吧
