### ISSUE TITLE
关于TP8，我有话说

### ISSUE THREAD

**Issue by Rodots** [top-think/framework#2868]
刚刚留意到新增了8.0分支，看完README后，发现最低支持PHP8.0版本，但是我个人认为，我们可以更加的激进一点，直接采用PHP8.2起步，以下是我的理由：
* PHP8.2版本是目前最新的发行版，性能肯定是目前最优的版本了。
* 从Beta版本的更新日志可以看出，目前的计划还是处于单纯的重构，结合第一点，我认为采用最新的技术来重构可以大大的延长程序的生命周期。
* 再从特性的角度来说说原因，比如从8.1开始新增的联合类型特性：允许函数和方法参数、返回值的类型可以是多个类型之一。
* 从8.1开始的str_contains()函数，替代了以前一直在用的strpos()函数，就跟match替换了switch一样，舒服很多。
* 从8.1开始的允许在定义类属性时直接初始化，而不需要在构造函数中初始化。
* 从8.2开始新增的安全随机数拓展random函数，以安全的角度来看，用于代替mt_rand。
* 从8.2开始，弃用掉了动态属性和弃用`${}`字符串插值，可以大大的避免屎山的产生。

**Comment by liu21st** [comment]
基于PHP8.0是有考虑的 首先企业环境都有特定的（第三方或扩展）依赖 我们必须要保证最低运行环境。
其次 很多高版本的特性对框架自身来说意义不大 但可以用于自己的项目开发 不冲突，因为项目完全可以依赖PHP8.2
最后，框架也会不断的更新 必要的时候也许会逐步提高对PHP版本的依赖

**Comment by Jiaoma** [comment]
想问一下TP8对于PHP8.2.x兼容吗？我看了readme只看到最低支持版本

**Comment by JaguarJack** [comment]
> 想问一下TP8对于PHP8.2.x兼容吗？我看了readme只看到最低支持版本

兼容，PHP 是向下兼容的，应该没啥问题

**Comment by liu21st** [comment]
要说兼容8.2 早在6.x版本就已经兼容了 没什么可担心的

**Comment by liu21st** [comment]
另外有一点必须说明 框架基于8.0和项目是否必须要基于8.0 没有关系 项目可以自己根据环境制定自己的项目规范

**Comment by liu21st** [comment]
> 想问一下TP8对于PHP8.2.x兼容吗？我看了readme只看到最低支持版本

要说兼容8.2 早在6.x版本就已经兼容了 没什么可担心的
