### ISSUE TITLE
TP8考虑过模型实体化吗

### ISSUE THREAD

**Issue by lshfong** [top-think/framework#2871]
命令行工具中生成模型时也生成对应表字段的实体，这样配合验证器对入口数据的处理就会方便很多！
入口数据=》验证器=》合法数据=》后续处理入库.

**Comment by lshfong** [comment]
当表字段很多时，写验证器是一个体力活，如果配合实体验证，会方便很多。

**Comment by augushong** [comment]
这个不需要ThinkPHP去做，太重了。这种东西扩展开了，可以实现实体文件生成模型、实体文件生成数据库安装文件、实体文件生成接口、实体文件生成html表单等等，不需要底层框架去做。

如果有需要，可以自己写一套规则，或者用curd的后台，让curd的后台去生成。我现在有个后台可以生成model，同时会把字段生成phpdoc，以后可以基于此生成验证器，接口说明等等。

![ae075249_1529589](https://user-images.githubusercontent.com/31880431/231933704-02bfc33b-a02e-4e5c-9a8a-66dc27716e8e.png)

**Comment by liu21st** [comment]
字段很多 实体模型的验证 难道就轻松很多？

**Comment by lshfong** [comment]
php8已支持原生注解，实体模型和验证器完全可以合并成一个文件，不管是维护还是开发确是要方便很多啊！

**Comment by augushong** [comment]
验证还是很复杂的，要跟场景结合在前一起，相同的模型，不同的权限或许也有不同的验证。没比较集成进去，有需要的话，自己实现类似的机制就行了。

**Comment by yuyachong** [comment]
不建议，自己写就行了  框架有框架的工作

**Comment by liu21st** [comment]
最新版本的ORM支持在实例化和保存数据的时候传入实体对象了的 剩下的工作自己处理即可
