### ISSUE TITLE
thinkphp 试用 filed 标识要返回或者操作的字段时，可以将 PHP 变量$cur_date作为某个字段的值返回吗？

### ISSUE THREAD

**Issue by gyjcode** [top-think/framework#2882]
![N~%K$9KF VEKXV5DKBC_IOH](https://github.com/top-think/framework/assets/45870098/3c1c6114-1826-4341-85ac-4afb46cdf783)
如图，$cur_date 是一个变量，想要在返回的结果中都包含该变量应该如何处理？

**Comment by hongfs** [comment]
其实你应该学一下基础，比如 变量要怎么被识别(另外还有特殊符号问题)...或者最简单的方式，用 foreach 自己加上去.

**Comment by gyjcode** [comment]
> 其实你应该学一下基础，比如 变量要怎么被识别(另外还有特殊符号问题)...或者最简单的方式，用 foreach 自己加上去.

是我迷了，感谢回复
