### ISSUE TITLE
v6.1.3版本开启route_rule_merge后报错

### ISSUE THREAD

**Issue by qiyo** [top-think/framework#2887]
v6.1.3版本开启 route_rule_merge 后报错
[error] [0]Cannot use object of type think\route\RuleItem as array [/vhost/vendor/topthink/framework/src/think/route/RuleGroup.php:271]

**Comment by 1923998238** [comment]
我也是

**Comment by apigx** [comment]
他显示报错是271行，但是实际错误应该是/vendor/topthink/framework/src/think/route/RuleGroup.php的getRules函数第494~497行。这里返回的数组有问题

**Comment by 1923998238** [comment]
我暂时先回退版本了

**Comment by yangxiansheng1993** [comment]
![image](https://github.com/top-think/framework/assets/20346917/c44382b1-b89b-4a1f-bb09-1cdb8dc0de3e)
![image](https://github.com/top-think/framework/assets/20346917/5a50eedf-2512-4910-aedc-20872050c5e9)
此错误为使用数组方式操作对象，导致报错，直接把[1]删除即可正常访问。

**Comment by 805964774** [comment]
#2908
