### ISSUE TITLE
v6.1.3对OPTION请求与allowCrossDomain设置不同步

### ISSUE THREAD

**Issue by oyvfhp** [top-think/framework#2888]
升级到v6.1.3后，发现所有API请求都出现CROSS跨域报错，对比源码发现已经取消了auto模式。
![WechatIMG3178](https://github.com/top-think/framework/assets/4404279/f2fee197-aec4-4af0-ac7b-64cf3a9dc8a5)
![WechatIMG3180](https://github.com/top-think/framework/assets/4404279/5f259c2d-5e9c-4e0b-a624-cf0d5f15305a)
为何要取消，主要是出于什么问题才进行取消的，当下要让所有请求支持OPTIONS请求要怎么操作？
@liu21st  麻烦了，望请指教一下。

**Comment by oyvfhp** [comment]
建议是不是在执行了allowCrossDomain操作时，同时都能对OPTIONS进行配置

**Comment by augushong** [comment]
嗯，之前的options会直接响应http的标准结果，但这个响应要不要跨域呢？
框架就不该这样处理。之前我还专门自定义了一个provider去定制这个东西。
就应该去掉。

**Comment by oyvfhp** [comment]
现在默认miss就对OPTIONS设置成不允许跨域，但现在allowCrossDomain操作后的OPTIONS并没有一起调整。
@liu21st  麻烦关注一下。

**Comment by oyvfhp** [comment]
这个没有好的解决方案吗？ 发现route::options()不能设置全部，domain()->middleware()也无效

**Comment by qeq66** [comment]
8.0也有此问题 @liu21st @yunwuxin

**Comment by yunwuxin** [comment]
可以自己注册类型为options的miss路由的

**Comment by qeq66** [comment]
手动注册options路由太费劲了。已经通过全局中间件解决了。
`\think\middleware\AllowCrossDomain::class`

**Comment by oyvfhp** [comment]
> 

好的，我试试

**Comment by oyvfhp** [comment]
@qeq66   全局中间件可以共享一下代码吗？我在多应用模式下，domain()-> middleware()设置时不生效，我试一下使用options的miss路由

**Comment by qeq66** [comment]
@oyvfhp  就是官方库里面的跨域中间件，`\think\middleware\AllowCrossDomain::class`

**Comment by oyvfhp** [comment]
![image](https://github.com/top-think/framework/assets/4404279/9908c963-68eb-4c8b-8b9a-625e89f19f2b)
这样写感觉好怪，控制了options的miss，但每个文件都要写一次，多应用模式下的domain()-> middleware()设置也无效。
@qeq66  我测试了一下使用中间件，没有效果
@yunwuxin  注意options的miss有更方便的方式吗？

**Comment by qeq66** [comment]
@oyvfhp  [https://github.com/top-think/think-cors](url) 
`composer require topthink/think-cors=dev-master`

**Comment by oyvfhp** [comment]
收到，感谢，原来把这个cors独立出去了

**Comment by oyvfhp** [comment]
搞定，感谢大家的回答。
