### ISSUE TITLE
6.1.3使用路由分组报错

### ISSUE THREAD

**Issue by y1834257499** [top-think/framework#2889]
![image](https://github.com/top-think/framework/assets/47782692/f49af162-d7e5-4bc8-84a7-7ff87b2732b9)
![image](https://github.com/top-think/framework/assets/47782692/5d18e2db-34a2-4087-96b7-fe5f155f594a)

**Comment by oyvfhp** [comment]
像你这个用法，干吗不直接用资源路由？

**Comment by 805964774** [comment]
#2908
