### ISSUE TITLE
新Model的BUG

### ISSUE THREAD

**Issue by yovei** [top-think/framework#29]
protected static function db()

if (!isset(self::$links[$model])) {
            self::$links[$model] = Db::connect(static::$connection);
            self::$links[$model]->setTable(static::$tableName);
            $name = basename(str_replace('\\', '/', $model));
            self::$links[$model]->name($name);
        }

self::$links[$model]  多个model 共享了同一条链接

导致self::$links[$model]->name($name);会覆盖之前的name

**Comment by yovei** [comment]
$user1 = User::get(1);
$extract = UserExtract:get(1);
$user2 = User::get(2);

$user2 的数据 取得居然是UserExtract 表里面的数据

**Comment by ucc862** [comment]
今天我也遇到了 ( ╯□╰ )

**Comment by liu21st** [comment]
这个问题 最新版本已经修正过的

**Comment by ucc862** [comment]
我今天更新最新版了 还是数据错误 我是在模型类里面静态调用其它的模型的数据，因为是在一个循环里面 有多个模型数据的切换，数据还是混论的。但是我指定了模型的数据库表名就没有问题了。应该是根据模型的文件名称解析数据库表名混乱了。望查看一下。 @liu21st
