### ISSUE TITLE
6.1.1 升级到6.1.3 报错， 官方不修复以下吗？

### ISSUE THREAD

**Issue by yaody123** [top-think/framework#2900]
6.1.1 升级到6.1.3 报错， 官方不修复以下吗？

#0 [64]ErrorException in Url.php line 71
D:\WWW\app\vendor\topthink\think-multi-app\src\Url.php
Declaration of think\app\Url::build() must be compatible with think\route\Url::build(): string

![image](https://github.com/top-think/framework/assets/29880762/8a71d604-d092-47d2-b33a-8f6a9dc76b58)

**Comment by liu21st** [comment]
更新下多应用扩展
