### ISSUE TITLE
6.1.1 升级到6.1.3 报错 Declaration of think\app\Url::build() must be compatible with think\route\Url::build(): string

### ISSUE THREAD

**Issue by yaody123** [top-think/framework#2901]
**6.1.1 升级到6.1.3 报错如下：**

#0 [64]ErrorException in Url.php line 71
D:\WWW\app\vendor\topthink\think-multi-app\src\Url.php
Declaration of think\app\Url::build() must be compatible with think\route\Url::build(): string

![image](https://github.com/top-think/framework/assets/29880762/a50bff8c-8f97-4fb6-a3b6-169cc1ddff66)

**Comment by liu21st** [comment]
更新多应用扩展

**Comment by yaody123** [comment]
怎么更新？
composer update topthink/framework
我只执行了这条命令

**Comment by yaody123** [comment]
composer update topthink/think-multi-app
需要执行这行命令吗？
