### ISSUE TITLE
tp8.0.0缓存Cache::remember报错

### ISSUE THREAD

**Issue by fengmangbl** [top-think/framework#2905]
Cache::remember('name','thinkphp');
Cache::remember('name','thinkphp',3600);
报错:
think\cache\Driver::getExpireTime(): Argument #1 ($expire) must be of type DateTimeInterface|DateInterval|int, string given, called in /www/tp8/vendor/topthink/framework/src/think/cache/driver/Redis.php on line 143

Cache::set('name','thinkphp');
Cache::set('name','thinkphp',3600);
正常

**Comment by liu21st** [comment]
缓存配置里面的参数是什么

**Comment by fengmangbl** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我不在电脑前，无法亲自回复您的邮件。我将尽快给您回复。
