### ISSUE TITLE
数据集对象 toArray 方法效率太低

### ISSUE THREAD

**Issue by liuwave** [top-think/framework#291]
模型查询设置的默认返回数据集，但toArray()效率太低；
如
`$result=model('Region')->where($where)->select()->toArrray();`

和
`$result=model('Region')->where($where)->column('*');`

数据量3500行，前者执行时间4s+ ,后者执行时间0.4S

**Comment by liu21st** [comment]
模型方法首要考虑的不是性能，否则模型还有什么意义存在，全部用Db类操作了

**Comment by liuwave** [comment]
我算是THINKPHP新手，有点困惑，因为上项目肯定要考虑到性能，如果模型方法性能不好，那我该如何选择呢？ 用Db类操作？或者有折中的办法？求解 @liu21st

**Comment by slince** [comment]
只要不是设计方面的缺陷，比如多次tcp连接、死循环等；其它方面对效率的影响都是微乎其微的不需要过多考虑。

**Comment by liu21st** [comment]
模型的性能和方便性是一个平衡设计，牺牲一点性能带来更好的开发和稳定性值得，况且这点性能损耗还比不上一条糟糕的sql
