### ISSUE TITLE
修改下文档被 大佬

### ISSUE THREAD

**Issue by 504750975** [top-think/framework#2915]
https://doc.thinkphp.cn/v8_0/connect.html 文档的这个地方 

\think\facade\Db::connect('demo')
	->table('user')
    ->find();

改一下，不然测试的时候一直为null！！！

如果没有任何的查询条件 并且也没有调用order方法的话 ，find查询不会返回任何结果。

**Comment by hongfs** [comment]
> 如果没有任何的查询条件 并且也没有调用order方法的话 ，find查询不会返回任何结果。

这是 BUG 了吧。

**Comment by 504750975** [comment]
> > 如果没有任何的查询条件 并且也没有调用order方法的话 ，find查询不会返回任何结果。
> 
> 这是 BUG 了吧。

不是BUG 纯纯文档 上下不对应。
