### ISSUE TITLE
[8.0] 缓存设置报错

### ISSUE THREAD

**Issue by ChinaMoli** [top-think/framework#2916]
### 框架版本
`v8.0.1`

### PHP 版本
`8.1.13`

`Cache::set('name', $value, new DateTime('2019-10-01 12:00:00'));`
报错：
`think\Cache::set(): Argument #3 ($ttl) must be of type DateInterval|int|null, DateTime given`

8.0 修改了方法 `Cache::set`  `$ttl` 参数的类型。

**Comment by hongweipeng** [comment]
psr 里定义 cache 的接口：
```
public function set(string $key, mixed $value, null|int|\DateInterval $ttl = null): bool;
```

**Comment by yzh52521** [comment]
文档误导的，tp8 缓存 第三个参数 不支持 传递  DateTimeInterface  类型了

**Comment by yzh52521** [comment]
你可以这样设置 
```
Cache::set('name', $value, DateInterval::createFromDateString('2019-10-01 12:00:00'));
```

**Comment by ChinaMoli** [comment]
> 你可以这样设置
> 
> ```
> Cache::set('name', $value, DateInterval::createFromDateString('2019-10-01 12:00:00'));
> ```

在此之前是可以使用 `Cache::set('key', 'value', Carbon::now()->addMinutes(10));`，这种更为优雅的方式去设置缓存。

我反馈这个 issue 的主要目的是文档并没有标记出来不再支持 `DateTime` 类型，导致项目中很多地方的报错。
在框架的升级指导里面写着
> 8.0版本支持6.*版本的无缝升级
这样导致出现了这种清空，这个也怪我们项目没有建立完整的单元测试。

我希望能够继续支持 `DateTime` 类型，具体可以参考 [laravel/framework](https://github.com/laravel/framework) 的 `Cache::put()` 方法的实现

**Comment by yzh52521** [comment]
> > 你可以这样设置
> > ```
> > Cache::set('name', $value, DateInterval::createFromDateString('2019-10-01 12:00:00'));
> > ```
> 
> 在此之前是可以使用 `Cache::set('key', 'value', Carbon::now()->addMinutes(10));`，这种更为优雅的方式去设置缓存。
> 
> 我反馈这个 issue 的主要目的是文档并没有标记出来不再支持 `DateTime` 类型，导致项目中很多地方的报错。 在框架的升级指导里面写着
> 
> > 8.0版本支持6.*版本的无缝升级
> 
> 这样导致出现了这种情况，这个也怪我们项目没有建立完整的单元测试。
> 
> 我希望能够继续支持 `DateTime` 类型，具体可以参考 [laravel/framework](https://github.com/laravel/framework) 的 `Cache::put()` 方法的实现

laravel  为什么用 put 应该就是不和PSR规范冲突吧

**Comment by yzh52521** [comment]
你也可以 \DateInterval::createFromDateString('10 minutes')

**Comment by ChinaMoli** [comment]
> > > 你可以这样设置
> > > ```
> > > Cache::set('name', $value, DateInterval::createFromDateString('2019-10-01 12:00:00'));
> > > ```
> > 
> > 
> > 在此之前是可以使用 `Cache::set('key', 'value', Carbon::now()->addMinutes(10));`，这种更为优雅的方式去设置缓存。
> > 我反馈这个 issue 的主要目的是文档并没有标记出来不再支持 `DateTime` 类型，导致项目中很多地方的报错。 在框架的升级指导里面写着
> > > 8.0版本支持6.*版本的无缝升级
> > 
> > 
> > 这样导致出现了这种情况，这个也怪我们项目没有建立完整的单元测试。
> > 我希望能够继续支持 `DateTime` 类型，具体可以参考 [laravel/framework](https://github.com/laravel/framework) 的 `Cache::put()` 方法的实现
> 
> laravel 为什么用 put 应该就是不和PSR规范冲突吧

是的，Laravel 并没有 set 方法，但是大部分用户使用 ThinkPHP 时都是直接使用 Cache 的门面类方法，门面实际调用的是 `\think\Cache`，只用在这个类的 `set` 方法做一下适配，将 `DateTime` 类型，转为 `int` 就行

**Comment by ChinaMoli** [comment]
> 你也可以 \DateInterval::createFromDateString('10 minutes')

你这个方法完全可以实现，但更为复杂的场景下我觉得 `Carbon` 可能跟适合我，例如：

`Cache::set('key', 'value', Carbon::now()->addHour()->addMinutes(30));`

可以很直观看出来，`key` 的有效期为 1 小时 30 分钟

而且使用 `Carbon` 会有友好的 IDE 提示😀

**Comment by yzh52521** [comment]
> > 你也可以 \DateInterval::createFromDateString('10 minutes')
> 
> 你这个方法完全可以实现，但更为复杂的场景下我觉得 `Carbon` 可能跟适合我，例如：
> 
> `Cache::set('key', 'value', Carbon::now()->addHour()->addMinutes(30));`
> 
> 可以很直观看出来，`key` 的有效期为 1 小时 30 分钟
> 
> 而且使用 `Carbon` 会有友好的 IDE 提示😀

这个问题 你直接找 作者去吧

**Comment by yzh52521** [comment]
只有一个办法 增加一个 put 方法

**Comment by yzh52521** [comment]
最新版已经支持了
