### ISSUE TITLE
column()方法中的索引参数不支持 别名

### ISSUE THREAD

**Issue by liuwave** [top-think/framework#292]
// 以id为索引
User::where('status',1)->column('name','id');

如果有别名,如

model('Regions')->where(['a.region_id'=>['in',$parent],'p.level'=>$level ])->alias('p')->distinct(true)->field('p.*')->join('regions a',
                'a.parent_id=p.region_id ')->column('p.*','p.region_id');
            $parent=array_column($res,'p.region_id');

会提示错误 ：
未定义数组索引: p.region_id
in Query.php line 462：

                $resultSet = $pdo->fetchAll(PDO::FETCH_ASSOC);
                if ($resultSet) {
                    $fields = array_keys($resultSet[0]);
                    $count  = count($fields);
                    $key1   = array_shift($fields);
                    $key2   = $fields ? array_shift($fields) : '';
                    $key    = $key ?: $key1;
                    foreach ($resultSet as $val) {
                        if ($count > 2) {
                            $result[$val[$key]] = $val;
                        } elseif (2 == $count) {
                            $result[$val[$key]] = $val[$key2];
                        } elseif (1 == $count) {
                            $result[$val[$key]] = $val[$key1];
                        }
                    }
                } else {
                    $result = [];
                }

**Comment by liu21st** [comment]
最终的查询结果里面是不会出现别名的

**Comment by liuwave** [comment]
可以改进么？
