### ISSUE TITLE
在路由中间件中，对复杂请求类型的OPTIONS预检请求不能正确响应

### ISSUE THREAD

**Issue by qq263402128** [top-think/framework#2937]
在路由中间件中，对于跨域的处理，当跨域请求是复杂请求类型(带了自定的request header)的时候无法正确响应，整个请求都不会进入中间件，直接响应的 Allow:GET, POST, PUT, DELETE 导致无法跨域
现在只能是在全局中间件中注册解决。

**Comment by hongfs** [comment]
跨域在 nginx 层进行处理吧。

**Comment by liu21st** [comment]
全局中间件不就是一个解决方案么
