### ISSUE TITLE
能否考虑让Jump支持跳转到自定义Scheme的URL

### ISSUE THREAD

**Issue by 86849180** [top-think/framework#294]
能否考虑让Jump支持跳转到自定义Scheme的URL，例如跳转到**tencent://message/?uin=800010000**

$this->error('请联系客服', 'tencent://message/?uin=800010000');

**Comment by liu21st** [comment]
这个前台自己解析就行 如果用的是系统模板，跳转模板也是可以修改的

**Comment by 86849180** [comment]
@liu21st error()方法里会用Url::build()会把我想要跳转的地址变为/uin/800010000，所以修改跳转模板也是没用的。不知能否考虑改进下
[https://github.com/top-think/framework/blob/master/library/traits/controller/Jump.php](url)
` /**
     * 操作错误跳转的快捷方法
     * @access protected
     * @param mixed     $msg 提示信息
     * @param string    $url 跳转的URL地址
     * @param mixed     $data 返回的数据
     * @param integer   $wait 跳转等待时间
     * @param array     $header 发送的Header信息
     * @return void
     */
    protected function error($msg = '', $url = null, $data = '', $wait = 3, array $header = [])
    {
        $code = 0;
        if (is_numeric($msg)) {
            $code = $msg;
            $msg  = '';
        }
        if (is_null($url)) {
            $url = 'javascript:history.back(-1);';
        } elseif ('' !== $url) {
            $url = preg_match('/^(https?:|\/)/', $url) ? $url : Url::build($url);
        }
        $result = [
            'code' => $code,
            'msg'  => $msg,
            'data' => $data,
            'url'  => $url,
            'wait' => $wait,
        ];
        $type = $this->getResponseType();
        if ('html' == strtolower($type)) {
            $result = ViewTemplate::instance(Config::get('template'), Config::get('view_replace_str'))
                ->fetch(Config::get('dispatch_error_tmpl'), $result);
        }
        $response = Response::create($result, $type)->header($header);
        throw new HttpResponseException($response);
    }`

**Comment by liu21st** [comment]
这个地方 我改进了下

**Comment by 86849180** [comment]
Thanks^_^
