### ISSUE TITLE
Validate验证器 一些方法统一一下吧

### ISSUE THREAD

**Issue by yuyachong** [top-think/framework#2947]
比如：
'in' => [1,2,3]  或  'in' => '1,2,3'

而还有些requreIf只能用string方式
都统一一下吧，我习惯都用数组方式，看起来方便

说起来string方式还需要explode一次感觉没啥必要的

**Comment by ajiho** [comment]
如果官方目前还没增强之前，建议使用第三方的，composer上太多了。

**Comment by liu21st** [comment]
出于兼容性考虑 目前不会取消字符串方式 但基本都支持数组方式的 在使用过程中保持统一风格即可
