### ISSUE TITLE
TP8不支持 form-data 格式的请求数据吗？只支持 x-www-form-urlencoded ？

### ISSUE THREAD

**Issue by gyjcode** [top-think/framework#2988]
如题，想问下：TP8不支持 form-data 格式的请求数据吗？只支持 x-www-form-urlencoded ？
这边通过 apifox 发起请求时 form-data 后端接收不到数据，x-www-form-urlencoded 可以正常接收数据。

**Comment by big-dream** [comment]
支持 `form-data`

**Comment by gyjcode** [comment]
> 支持 `form-data`

我记得也支持来着，之前 tp6 正常，现在升级 tp8 请求就出问题了。我再排查下是不是升级哪里搞错了。

**Comment by gyjcode** [comment]
额，是网页版 ApiFox 的问题，客户端版本请求正常。
