### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '41' for key 'PRIMARY'

### ISSUE THREAD

**Issue by 1459416736** [top-think/framework#299]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '41' for key 'PRIMARY'
$orderModel=new OrderModel();
			foreach ($orders as $order){
				$id = $orderModel->allowField(true)->isUpdate(false)->save($order);
循环保存save方法就报上面的错误

**Comment by liu21st** [comment]
用法有问题，参考手册
