### ISSUE TITLE
8.0.3 路由跨域设置 不生效

### ISSUE THREAD

**Issue by 8-8-18** [top-think/framework#2993]
### 所属功能组件

路由(Route)

### ThinkPHP 版本

8.0.3

### 操作系统

windows

### 其它说明

Route::get('new/:id', 'News/read')
    ->ext('html')
    ->allowCrossDomain(); // 不生效
Route::group(function () {
.....
})->allowCrossDomain(); // 不生效
Route::group(function () {
.....
})->allowCrossDomain(
['Access-Control-Allow-Headers' => '*']
); // 不生效

**Comment by qeq66** [comment]
请阅读最新手册。跨域已经调整为单独扩展了
