### ISSUE TITLE
collection  下分页输出不能使用

### ISSUE THREAD

**Issue by duchao1990** [top-think/framework#300]
当database.php 设置'resultset_type' => 'collection',  分页时候没法用 $list->render(); 请问如何解决,
'resultset_type' => 'collection',这个值我肯定是不能改了,请问其他解决方案

**Comment by yunwuxin** [comment]
报什么错误

**Comment by duchao1990** [comment]
@yunwuxin 显示是500错误,页面错误,点render().是到Collection类里边了,这个类里边是没有这个方法的

**Comment by yunwuxin** [comment]
我测试没问题啊  你查询语句是什么

**Comment by duchao1990** [comment]
@yunwuxin         
        $Video=new VideoModel();
        $list=$Video->where($where)->paginate(20);

**Comment by yunwuxin** [comment]
测试了 没问题  你跟踪调试下呢
