### ISSUE TITLE
composer安装thinkphp8安装失败

### ISSUE THREAD

**Issue by 956569011** [top-think/framework#3007]
### 所属功能组件

其它

### ThinkPHP 版本

8.0.3

### 操作系统

windows

### 错误信息

PHP版本是8.2.16,
执行 composer create-project topthink/think tp
composer安装thinkphp8安装失败,报如下错误

### 其它说明

![php8](https://github.com/top-think/framework/assets/16367625/2ad6d0cd-0703-4682-9e29-4bf4f5dbbe50)

**Comment by big-dream** [comment]
检查composer镜像源

**Comment by 956569011** [comment]
镜像源是官方镜像源

**Comment by big-dream** [comment]
看图是没找到 topthink/framework:^8.0，目前只能断定为缓存问题。
这边测试是正常的，无法复现，建议再自行检查下。
```bash
composer config -g --list | findstr "repositories.packagist"
```
