### ISSUE TITLE
cache 使用redis,并使用getex指令，无法获取前缀

### ISSUE THREAD

**Issue by sorshion** [top-think/framework#3009]
### 所属功能组件

缓存(Cache)

### ThinkPHP 版本

8.0.3

### 操作系统

ubuntu

### 错误信息

![image](https://github.com/top-think/framework/assets/12489667/835e89ff-36d4-4b9e-8ddc-7225a4962f12)

这里为何把prefix置空，使用我使用  getex，无法获取实际前缀

**Comment by sorshion** [comment]
使用predis组件，而不是redis扩展

**Comment by big-dream** [comment]
![image](https://github.com/top-think/framework/assets/9215157/f09f95f2-4969-474a-ac0e-efcecbce04a5)

Predis 就是这么用的，实际测试也没发现问题。
