### ISSUE TITLE
数据验证类 validate 有关mobile格式

### ISSUE THREAD

**Issue by wugg** [top-think/framework#3018]
### 所属功能组件

验证器(Validate)

### ThinkPHP 版本

6

### 操作系统

windows,linux

### 错误信息

手机号验证我们系统出现11开头的手机号，验证器内  'mobile'      => '/^1[3-9]\d{9}$/', 的验证无法满足手机号的匹配规则

**Comment by augushong** [comment]
假的号码吧，10开头的是电信服务号码，比如10010/10086等联通移动，11开头的是特种服务，比如报警、火警等，你这个手机号能打通，能发短信吗？
