### ISSUE TITLE
 [bug]获取主机名方法 `request()->domain()` `request()->host()` 的返回，都没有带端口号

### ISSUE THREAD

**Issue by cffycls** [top-think/framework#3027]
### 所属功能组件

路由(Route)

### ThinkPHP 版本

8.0.3

### 操作系统

Windows11 / Debian12

### 错误信息

vendor/topthink/framework/src/think/Request.php
第1756行
```
    public function host(bool $strict = false): string
    {
        if ($this->host) {
            $host = $this->host;
        } else {
            $host = strval($this->server('HTTP_X_FORWARDED_HOST') ?: $this->server('HTTP_HOST'));
        }

        return true === $strict && str_contains($host, ':') ? strstr($host, ':', true) : $host;
    }
```
这里 `request()->domain()` `request()->host()` 的返回，都没有带端口号。缺少SERVER_PORT

**Comment by big-dream** [comment]
获取端口用 `request()->remotePort()`

**Comment by cffycls** [comment]
> 获取端口用 `request()->remotePort()`

remotePort获取的是一个临时的端口，这里应该加上SERVER_PORT

**Comment by big-dream** [comment]
还有一个是 `request()->port()`

**Comment by cffycls** [comment]
> 还有一个是 `request()->port()`

应该加到那里去的

**Comment by cffycls** [comment]
不然获取的始终没有端口

**Comment by big-dream** [comment]
非标端口才会获取到端口号。具体可以自行测试下在 `80` 和非 `80/443` 端口下获取的 `$_SERVER['HTTP_HOST']`。框架是从这里面读的

**Comment by cffycls** [comment]
能测出来这个问题，重现使用的就是非80/443端口号，因为使用域名没这种问题。这时候（使用非80/443端口），使用`request()->domain()`获取的是没带端口号的，而此时应该带上

**Comment by big-dream** [comment]
麻烦直接看看 `$_SERVER['HTTP_HOST']` 有没有带端口号，如果有，但是框架获取的没有，这边再进一步排查问题。
