### ISSUE TITLE
think\log\driver\File 问题

### ISSUE THREAD

**Issue by 17771258** [top-think/framework#303]
现在我在 index/index/index 控制器代码如下
```
<?php
namespace app\index\controller;
class Index
{
    public function index()
    {
        return "222";
    }
}
```
此时页面输出222 之后程序报错 
```
:  Uncaught exception 'think\exception\ErrorException' with message 'mkdir(): Permission denied' in /Work/Git/think/library/think/log/driver/File.php:46
Stack trace:
#0 [internal function]: think\Error::appError(2, 'mkdir(): Permis...', '/Work/Git/think...', 46, Array)
#1 /Work/Git/think/library/think/log/driver/File.php(46): mkdir('../runtime/log/...', 493, true)
#2 /Work/Git/think/library/think/Log.php(149): think\log\driver\File-&gt;save(Array)
#3 /Work/Git/think/library/think/Error.php(84): think\Log::save()
#4 [internal function]: think\Error::appShutdown()
#5 {main}
  thrown in 
```
看报错信息是 library/think/log/driver/File.php `mkdir('../runtime/log/...', 493, true)` 报错说程序没有权限建立目录，但是我查看源代码代码为 `!is_dir($path) && mkdir($path, 0755, true);` 这并不是493。

另外我修改Index.php 代码如下
```
<?php
namespace app\index\controller;
use think\Log;
class Index
{
    public function index()
    {
        Log::save([]);
        return "222";
    }
}
```
此时访问 程序正常执行 日志文件正常建立。并且程序不会报错！请问这是什么问题。

**Comment by 17771258** [comment]
问题补充
在我的入口文件 define("APP_PATH", '../application') 的时候出现的这个问题
如果我修改为 define("APP_PATH", __DIR__ . '/../application') 就不存在这个问题
这样的话就是说 我的APP_PATH必须是绝对路径

**Comment by xiasf** [comment]
问题解决了没有？

**Comment by 17771258** [comment]
现在看 APP_PATH 必须是绝对路径 不能是相对路径
不知道这个是框架就这么设计的还是 在程序处理中有了写bug

**Comment by liu21st** [comment]
应该是你的环境问题 你换个环境测试下

**Comment by 17771258** [comment]
我的系统是 mac 集成环境mamp

**Comment by kinosang** [comment]
如果使用相对路径，有些环境下程序不能正常定位目标文件。

建议使用绝对路径定义 `APP_PATH` 以确保在不同环境下表现一致。

**Comment by 17771258** [comment]
嗯 我又使用了windows的 phpStudy 测试了一下 
我使用相对路径依然存在问题
在我 `define("APP_PATH", '../application')` 的时候 runtime文件夹不知道创建到哪里去了 
如过 `define("APP_PATH", __DIR__ . '/../application')` 的时候 runtime 文件夹创建了在application 的同级目录

@liu21st 请确认下这里的逻辑是否有问题！ 还是我们的 APP_PATH 必须绝对路径

**Comment by liu21st** [comment]
@17771258 你说的问题我修正了下
