### ISSUE TITLE
路由规则变量使用post接收list数据时传递的变量会变成list的第一个，传递object的时候正常

### ISSUE THREAD

**Issue by Muspcn** [top-think/framework#3041]
### 所属功能组件

路由(Route)

### ThinkPHP 版本

8.0.3

### 操作系统

Centos 7.9 php 8.1

### 错误信息

```php
     // 路由规则
    Route::post('config/:key', 'addon\musp_cms\app\adminapi\controller\Config@setConfig');
    
    public function setConfig($key)
    {
        dd($key);
    }
```

    // object 时
    url = config/MUSP_CMS_PROMOTION_CONFIG
   // object key的值正常 MUSP_CMS_PROMOTION_CONFIG
   {"name":"","url":"","desc":"","image":""}
 
   // list key的值异常值为 {"name":"","url":"","desc":"","image":""}
   [{"name":"","url":"","desc":"","image":""},{"name":"测试数据","url":"http://xxxx.com","desc":"","image":""},{"name":"中国移动","url":"https://10068.com","desc":"","image":""}]

**Comment by big-dream** [comment]
```HTTP
POST /config/MUSP_CMS_PROMOTION_CONFIG
Content-Type: application/json

{"name":"","url":"","desc":"","image":""}
```

`$key` 结果为 `MUSP_CMS_PROMOTION_CONFIG`，结果正常。

```HTTP
POST /config/MUSP_CMS_PROMOTION_CONFIG
Content-Type: application/json

[{"name":"","url":"","desc":"","image":""},{"name":"测试数据","url":"http://xxxx.com","desc":"","image":""},{"name":"中国移动","url":"https://10068.com","desc":"","image":""}]
```

`$key` 结果为 `{"name":"","url":"","desc":"","image":""}`，结果异常。

---

是这个意思吧？

**Comment by Muspcn** [comment]
是的

> ```httpspec
> POST /config/MUSP_CMS_PROMOTION_CONFIG
> Content-Type: application/json
> 
> {"name":"","url":"","desc":"","image":""}
> ```
> 
> `$key` 结果为 `MUSP_CMS_PROMOTION_CONFIG`，结果正常。
> 
> ```httpspec
> POST /config/MUSP_CMS_PROMOTION_CONFIG
> Content-Type: application/json
> 
> [{"name":"","url":"","desc":"","image":""},{"name":"测试数据","url":"http://xxxx.com","desc":"","image":""},{"name":"中国移动","url":"https://10068.com","desc":"","image":""}]
> ```
> 
> `$key` 结果为 `{"name":"","url":"","desc":"","image":""}`，结果异常。
> 
> 是这个意思吧？
对

**Comment by big-dream** [comment]
刚用最新开发版测试，问题应该解决了。关联：https://github.com/top-think/framework/commit/d693769ef825342b4e4f3affc9d5ee28a1a80bd4
