### ISSUE TITLE
使用域名绑定的一个问题

### ISSUE THREAD

**Issue by ken678** [top-think/framework#3046]
安装最新8.0  framework，thin-view，think-captcha

1. 默认控制器app\controller\Index.php下的hello方法改成`return $this->fetch();`  
2. 添加对应view\index\hello.html视图文件
代码：`<img id="verify" src="{:captcha_src()}" alt="验证码" class="captcha">`
3. 这时候访问www.域名.com/index/hello出现验证码图片,没有任何问题
----
这时候需求访问demo.域名.com/img打开验证码
route\app.php添加路由代码
```
Route::domain('demo', function () {
    Route::rule('img', 'index/hello');
});
```
这时候访问demo.域名.com/img验证码图片显示不出来

**Comment by ken678** [comment]
意思是不是就是说我用了域名绑定了demo ，demo.域名.com就只能访问他绑定的路由  demo访问其他路由他是无效的

**Comment by big-dream** [comment]
截图代码，可用信息不足。大概率是使用问题

**Comment by ken678** [comment]
> 截图代码，可用信息不足。大概率是使用问题

代码就上面的  全新安装3个包   就只改我上面3个地方

**Comment by big-dream** [comment]
`{:captcha_src()}` 跟域名无关，看你改的路由对它也没影响。

**Comment by ken678** [comment]
> `{:captcha_src()}` 跟域名无关，看你改的路由对它也没影响。

我测试用了域名绑定 比如demo.域名.com  普通路由就无法访问
```
www.域名.com/captcha 有验证码
demo.域名.com/captcha 就没有
```

**Comment by big-dream** [comment]
你看看验证码图片的URL是什么，然后直接打开这个URL，看看显示什么

**Comment by yunwuxin** [comment]
需要你在绑定域名下自己手动注册一个验证码显示的路由

**Comment by ken678** [comment]
> 需要你在绑定域名下自己手动注册一个验证码显示的路由

对 我目前就是这么做的  但是有别的解决办法吗  普通路由只能这么弄？
10个域名应用的话  我得绑定10遍验证码

**Comment by yunwuxin** [comment]
不是支持泛域名么  绑到泛域名就可以了
