### ISSUE TITLE
topthink/framework无法升级到v8.0.4的版本，topthink/think-orm无法升级到v3.0.25的版本

### ISSUE THREAD

**Issue by rockyhu** [top-think/framework#3051]
本地环境：Mac MAMP PRO + php 8.1.13
项目配置：如下图。
<img width="536" alt="image" src="https://github.com/user-attachments/assets/1f590e59-41e6-4b6f-87d0-818a4b047042">
<img width="962" alt="image" src="https://github.com/user-attachments/assets/c579ebd2-c199-4f4a-9ea5-1bf76e646eac">
composer镜像源：https://mirrors.aliyun.com/composer/
终端执行composer update，运行结果如下图所示。
<img width="664" alt="image" src="https://github.com/user-attachments/assets/defa2e0e-03af-4949-a9cd-1b29335857f7">
请问应该如何配置才能升级到最新版本，谢谢！

**Comment by big-dream** [comment]
取消使用镜像源，或者换镜像源

**Comment by rockyhu** [comment]
> 取消使用镜像源，或者换镜像源

取消镜像源（composer config -g --unset  @repos.packagist）后，成功升级到最新版本，感谢。

**Comment by rockyhu** [comment]
> 取消使用镜像源，或者换镜像源

取消镜像源（composer config -g --unset  repos.packagist）后，成功升级到最新版本，感谢。 @big-dream
