### ISSUE TITLE
建议调试按钮增加z-index

### ISSUE THREAD

**Issue by ken678** [top-think/framework#3057]
**您的功能请求与问题相关吗？**
没有z-index，有的时候会被其他层覆盖，下面是我加了才没有被覆盖
![image](https://github.com/user-attachments/assets/ac61eaf0-b011-411d-968f-5225e0690d3b)

**描述您想要的解决方案**
[有的话请在此描述]

**描述您考虑过的替代方案**
[有的话请在此描述]

**其它信息**
[其它相关信息或截图]

**Comment by big-dream** [comment]
默认好像已经是 `999999` 了

**Comment by big-dream** [comment]
可选解决方案，在 trace.php 配置文件中，自定义模板。
```
return [
    // 内置Html和Console两种方式 支持扩展
    'type'    => 'Html',
    // 读取的日志通道名
    'channel' => '',
    // HTML 模板文件
    'file'         => '自定义模板路径',
];
```

**Comment by ken678** [comment]
> 默认好像已经是 `999999` 了

按钮点击的弹出框是9999999  但是按钮我这边看是没有的  我还一直奇怪按钮怎么点不了  审核看了下是被我的透明层覆盖了

**Comment by big-dream** [comment]
感觉是无底洞，因为 `z-index` 并没有一个最大值，今天改成8个9，明天就有人用9/10/11个9

**Comment by ken678** [comment]
> 感觉是无底洞，因为 `z-index` 并没有一个最大值，今天改成8个9，明天就有人用9/10/11个9

兄弟 我谈的是细节优化  你别搁着钻牛角 本身不加z-index就能应对大部分情况 加了更兼容更多 正常也没有网站搞11个9    就算你说的对 那为什么按钮点击的弹窗加了z-index：9999999，为什么不一起统一呢  正常要调试肯定按钮优先级最高

**Comment by big-dream** [comment]
没留意到不一致(手动狗头)，不过可以确定改法的话，建议可以直接提交PR
