### ISSUE TITLE
请教一个分页与子查询结合的问题

### ISSUE THREAD

**Issue by slmhvip** [top-think/framework#306]
如果运行下面语句：

$sub_query = \think\Db::('member')->('proxy',1)->field('member_id')->select(false);
$query = Order::where('member_id','in',$sub_query)->where('type',1)->paginate(15);

得到的语句是正确的

SELECT * FROM `order` WHERE `member_id` IN (SELECT `member_id` FROM `member` WHERE `proxy` = 1) AND `type_id` = 1  LIMIT 0,15;

但得到的数据是不正确的，如果把这语句直接在命令行下运行又是正确的。

但如果使用闭包查询：

$proxy_id = 1;
$query = Order::where('member_id','in',function($query) use ($proxy_id){
    return $query->name('member')->where('proxy',$proxy_id)->field('member_id');
})->where('type',1)->paginate(15);

得到的数据又是正常的，这是怎么回事呢？

**Comment by slmhvip** [comment]
是必须使用闭包吗？

**Comment by liu21st** [comment]
分开查询总记录数 然后传入分页方法的第二个参数即可 有些复杂查询建议如此处理
