### ISSUE TITLE
日志记录的时间不准确

### ISSUE THREAD

**Issue by hongweipeng** [top-think/framework#3073]
### 所属功能组件

日志(Log)

### ThinkPHP 版本

8.0.0

### 操作系统

Ubuntu

### 其它说明

比如：
```
Log::info('info1');
Log::error('error1');
sleep(1);
Log::info('info2');
Log::error('error2');
```
记录到文件里的时间都一样，格式化时应在调用时而不是等到写文件的时候。相关问题 #2922

**Comment by liu21st** [comment]
基于性能考虑日志是统一写入的 通常对于一个请求来说 这个差别不影响 你可以配置或使用实时写入日志记录的方式

**Comment by hongweipeng** [comment]
格式化在调用时进行不影响日志的统一写入

**Comment by augushong** [comment]
你这个想法，简单的理解来看没问题，但是从实际的角度看，还是有问题的。

当我们看日志的时候，日志的时间记录的应该是写入日志的时间，而不是日志的产生时间。如果需要记录产生时间，那么就像文档中说的，开启实时日志就可以了。

否则就会出现，日志文件中，时间并没有连续增长的情况，这样是不对的。

关于日志有很多奇技淫巧，比如高性能、分布式、数据统计、数据库队列等等，但可能已经不是内置的日志要考虑得了。

**Comment by liu21st** [comment]
> 格式化在调用时进行不影响日志的统一写入

这个会影响目前的结构 主要是是否值得去改进。 一般的日志分析并不在意你说的这些细节 包括同一个请求下的记录顺序，如果需要业务相关日志你完全可以实时写入

**Comment by liu21st** [comment]
> 你这个想法，简单的理解来看没问题，但是从实际的角度看，还是有问题的。
> 
> 当我们看日志的时候，日志的时间记录的应该是写入日志的时间，而不是日志的产生时间。如果需要记录产生时间，那么就像文档中说的，开启实时日志就可以了。
> 
> 否则就会出现，日志文件中，时间并没有连续增长的情况，这样是不对的。
> 
> 关于日志有很多奇技淫巧，比如高性能、分布式、数据统计、数据库队列等等，但可能已经不是内置的日志要考虑得了。

日志是可以支持扩展驱动来满足不同的需求
