### ISSUE TITLE
thinkphp是否支持mysqli

### ISSUE THREAD

**Issue by Creedowl** [top-think/framework#308]
第一次用tp 看官方文档好像用的是mysql 新版php不推荐用mysql 请问是否会支持mysqli

**Comment by liu21st** [comment]
已经全面采用pdo了 不支持其它非pdo驱动

**Comment by xiasf** [comment]
你看的3.2吧，都是pdo，可能你是看到了驱动下面的mysql类，那是有些特性使用的，实际是继承db类使用的，你看db类就知道了，都是用的pdo哦。

**Comment by Creedowl** [comment]
哦 懂了
