### ISSUE TITLE
Request only循环内值类型使用后未重置导致异常格式化

### ISSUE THREAD

**Issue by LonelySally** [top-think/framework#3081]
### 所属功能组件

请求(Request)

### ThinkPHP 版本

8.0.x-dev

### 操作系统

centos

### 其它说明

PR [fix:Request only循环内值类型使用后未重置导致异常格式化](https://github.com/top-think/framework/pull/3080)

**Comment by big-dream** [comment]
感谢您的 PR

**Comment by LonelySally** [comment]
> 感谢您的 PR

是我上个提交pr的bug,未注意到是在for循环中对val进行格式转化.当非最后一个key设置为 /d 时会导致后续的key也会执行对应的格式转化.直到遇见下一个格式化标识.因此这里需要重新修正下.
```
param([
            'store_passport/s',//字符串
            'store_password',//原始类型
            'store_type/d',//整数
            'store_contact_name',//这里发生问题 store_contact_name也会变成整数
            'store_contact_phone/s',//字符串
        ])
```

**Comment by big-dream** [comment]
了解的，附在 PR #3080 下就行 😄

**Comment by liu21st** [comment]
已重新优化过 类型转换会在filterData中统一处理
