### ISSUE TITLE
为了获得tp团队的反馈，在这里提出我的一些问题，希望快速得到答案

### ISSUE THREAD

**Issue by ajiho** [top-think/framework#3084]
关于tp的文档，https://doc.thinkphp.cn/v8_0/preface.html，能否允许把内容搬运到我自己的git仓库？我可能会使用一些开源的文档生成工具，比如https://github.com/facebook/docusaurus 来生成tp的文档， 我不知道tp的文档是否是开源的，或者是什么格式的，我打算手动一点点的复制，写成markdown文件，托管到自己的github仓库，请问这样的行为是否是否违法行为？团队是否允许这样做？

**Comment by sy-records** [comment]
> 未经版权所有者明确授权，禁止发行本文档及其被实质上修改的版本。 
> 未经版权所有者事先授权，禁止将此作品及其衍生作品以标准（纸质）书籍形式发行。 
> 如果有兴趣再发行或再版本手册的全部或部分内容，不论修改过与否，或者有任何问题，请联系版权所有者 thinkphp@qq.com。

复制自文档中，你可以发邮件咨询。

**Comment by liu21st** [comment]
这是什么需求 你的仓库应该是你的产品文档 如果是单纯的搬运TP文档 是没有意义的 而且是需要授权的 当初就曾经发生过php中文网采集我们的官方文档 然后功能不全（比如搜索不能用）然后用户居然反馈给我们官方说 文档有问题。建议你直接链接到官方文档地址即可，官方文档始终在保持更新

**Comment by ajiho** [comment]
并没有恶意的什么想法，单纯的喜欢tp框架吧，也用了很久了，需求的就是想使用更漂亮的静态文档生成工具(hugo、vuepress、Docusaurus、MkDocs)来生成用户体验更好更漂亮的文档，同时又是托管到git仓库，如果公开仓库的话可以让更多人一起通过pr的方式快速更新内容(比如可能有的人想增加一些国际化翻译的)，还有前几天你们的网站到期了，整整一个晚上都打不开。 

@liu21st  老大，我可以这样做吗？

**Comment by liu21st** [comment]
官方文档本来就是基于git版本库的 只是不公开而已 有意愿参与文档贡献的可以联系我们 官方的角度并不希望用户在网上搜索到一堆无用或过时的文档。作为官方手册主要是阅读、搜索和内容持续更新，而不是多好看，放任何地方都不能保证比官网更可靠（只要TP还在维护，文档就能正常使用），谁能保证你托管tp的文档一直同步更新和维护？还是那句话 如果需要商业合作请联系授权 wx topthink

**Comment by ajiho** [comment]
@liu21st 知道了，老大，我就是尊重tp团队才特意询问的，换做别人直接已经复制完了
