### ISSUE TITLE
视图使用$Request.cookie的问题

### ISSUE THREAD

**Issue by ken678** [top-think/framework#3085]
### 所属功能组件

视图(View)

### ThinkPHP 版本

8.0.3

### 操作系统

windows

### 错误信息

![image](https://github.com/user-attachments/assets/2874207f-5e37-4a78-9314-10ed976e71c7)
{$Request.cookie.theme-dark}报错
{$Request.cookie.theme_dark}这种格式才行

**Comment by ken678** [comment]
![image](https://github.com/user-attachments/assets/089c86de-97c5-4125-9c66-ed24daeb69fd)
这个也是报错的

**Comment by ken678** [comment]
实际被解析成这种
![image](https://github.com/user-attachments/assets/a0b0545c-5699-4ab0-967e-ea584d767873)

**Comment by big-dream** [comment]
用下换线 `_` 这种吧，用减号 `-` 确实是不怎么符合规范

**Comment by ken678** [comment]
> 用下换线 `_` 这种吧，用减号 `-` 确实是不怎么符合规范

{$Request.header.accept-encoding}这个获取正常的写法  文档也是这样写了  这是规范问题？
{$Request.header.accept_encoding}改成这样的话 这获取的是啥鬼

**Comment by big-dream** [comment]
用下划线应该也能获取，建议就是先用 `_` 解决问题。`-` 问题，再议

**Comment by liu21st** [comment]
只有header参数会有- 而且框架内部处理过的 其它变量基本上不会用这个规范的，文档部分已经修正
