### ISSUE TITLE
怎么能在保持app目录正常识别的情况下增加一个应用目录？

### ISSUE THREAD

**Issue by 490626721** [top-think/framework#3087]
**您的功能请求与问题相关吗？**
[是的话请在此描述]

**描述您想要的解决方案**
[我希望在保持app多应用自动识别的情况下，能支持额外的应用目录，比如system目录，因为我想框架后台相关应用与业务相关应用代码分开]

**描述您考虑过的替代方案**
希望能通过修改配置文件能支持上面的方法

**其它信息**
thinkphp8

**Comment by big-dream** [comment]
你指的是代码共用？我们是面相对象编程，直接调用对应类即可，而且支持路由到类。

**Comment by 490626721** [comment]
> 你指的是代码共用？我们是面相对象编程，直接调用对应类即可，而且支持路由到类。

我是想在框架根目录下创建一个system目录，来处理系统相关的控制器、路由、模型等；
app目录是正常的多应用目录、自动识别、主要存放业务相关的应用；


因为目前业务上会存在多个业务应用的需求，现在系统相关的应用也放在app目录下；
虽然这样并不影响使用，但是在规范上总感觉不太对😀

**Comment by big-dream** [comment]
如果你要system能被请求，那就是app/system嘛。
如果不能被请求，支持禁止应用访问。

> 你如果不希望某个应用通过URL访问，例如，你增加了一个common子目录用于放置一些公共类库，你可以设置

> 'deny_app_list' =>    ['common']
>多应用模式并非核心内置模式，官方提供的多应用扩展更多是抛砖引玉，你完全可以通过中间件来扩展适合自己的多应用模式

**Comment by 490626721** [comment]
> 如果你要system能被请求，那就是app/system嘛。 如果不能被请求，支持禁止应用访问。
> 
> > 你如果不希望某个应用通过URL访问，例如，你增加了一个common子目录用于放置一些公共类库，你可以设置
> 
> > 'deny_app_list' =>    ['common']
> > 多应用模式并非核心内置模式，官方提供的多应用扩展更多是抛砖引玉，你完全可以通过中间件来扩展适合自己的多应用模式

嗯嗯，谢谢，我再去看看代码🙏
