### ISSUE TITLE
php8.4.1，think\response\View::getVars(): Implicitly marking parameter $name as nullable is deprecated, the explicit nullable type must be used instead

### ISSUE THREAD

**Issue by 2606062632** [top-think/framework#3089]
### 所属功能组件

视图(View)

### ThinkPHP 版本

8.1

### 操作系统

windows

### 错误信息

think\response\View::getVars(): Implicitly marking parameter $name as nullable is deprecated, the explicit nullable type must be used instead

**Comment by big-dream** [comment]
感谢反馈，已修复！https://github.com/top-think/framework/commit/ee82f248fb95e6431fda46d20776a768d51b1205
