### ISSUE TITLE
8.1.0 参数绑定，不认 post 传的参数

### ISSUE THREAD

**Issue by qh-wells** [top-think/framework#3090]
### 所属功能组件

请求(Request)

### ThinkPHP 版本

8.1.0

### 操作系统

Centos

### 错误信息

方法参数错误:id

### 其它说明

    public function test2($id)
    {

        if ($this->request->isPost()) dump($id);
        return '<form method="post" action="test2"><input type="text" name="id" value="20"><button type="submit">提交</button></form>';

    }

**Comment by big-dream** [comment]
改路由配置中的`action_bind_param` 为 `param` 试试，相关提交：https://github.com/top-think/framework/commit/011e8eafba873f3a5d1d639574e418af52b928de

**Comment by qh-wells** [comment]
我的疏忽，没看到更新日志中的“路由配置增加action_bind_param参数 设置操作方法的参数绑定方式”这句，sorry
