### ISSUE TITLE
路由middleware混用会失效

### ISSUE THREAD

**Issue by Muspcn** [top-think/framework#3096]
### 所属功能组件

路由(Route)

### ThinkPHP 版本

8.0.4

### 操作系统

liunx

### 错误信息

`
topthink/framework                8.0.4              The ThinkPHP Framework.
topthink/think-captcha            3.0.10             captcha package for thinkphp
topthink/think-filesystem         2.0.2              The ThinkPHP6.1 Filesystem Package
topthink/think-helper             3.1.8              The ThinkPHP6 Helper Package
topthink/think-image              1.0.8              The ThinkPHP5 Image Package
topthink/think-multi-app          1.0.17             thinkphp multi app support
topthink/think-orm                3.0.28             the PHP Database&ORM Framework
topthink/think-template           3.0.1              the php template engine
topthink/think-trace              1.6                thinkphp debug trace
topthink/think-view               2.0.0              thinkphp template driver

`

![图片](https://github.com/user-attachments/assets/5ad45467-9fc2-4cc4-b846-7d669e81987d)

**Comment by liu21st** [comment]
不建议两种方式混合使用 要么全部单个定义 要么统一一次性批量定义
或者你必须混合定义的原因是什么？

**Comment by Muspcn** [comment]
> 不建议两种方式混合使用 要么全部单个定义 要么统一一次性批量定义 或者你必须混合定义的原因是什么？

我以为这个是个bug，sorry
