### ISSUE TITLE
现在这个框架架构是否还会重构?

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#31]
`RT.`
如果不再重构, 我就把现有的代码结构改成新版的了

**Comment by yovei** [comment]
应该会

我前几天因为重构问题   导致生产环境 挂了好久

**Comment by cbwfree** [comment]
就是现在重构完的版本 不知道还会不会重构

**Comment by amehime** [comment]
上周迁移了一部分，然后这周跑来看到模型（废弃）这样的，整个人都不好了

**Comment by kinosang** [comment]
之后应该不会有更大的变动了。

这种大变动都会在分支保持一段时间才合并进master，理论上来说是给出了缓冲时间的。

另外，不推荐设置 min-stable 为 dev。

**Comment by momoca** [comment]
@kinosang 说的对,只要天天关注dev和master的commits就知道了.

**Comment by kinosang** [comment]
@momoca 其实只要在更新框架之前来看一眼就好。
