### ISSUE TITLE
多应用模式下，api模块不能自动跨域，即使设置了中间件也失败

### ISSUE THREAD

**Issue by wdwlrz** [top-think/framework#3101]
### 所属功能组件

请求(Request)

### ThinkPHP 版本

6.1.4

### 操作系统

windows

### 错误信息

比如 /api/login/login ，我从独立部署的前端网页上来访问登录接口，提示跨域，token不在允许的头信息字段里，其实我后台都设置过了，6.1.1版本是可以的。然后我改下路由 /api/v1/login/login ，这样可以登录。很神奇。具体的有个代码我也跟踪了，vendor/topthink/framework/src/think/Response.php:139，第139行，header($name . (!is_null($val) ? ':' . $val : '')); 这里只要写死content-type: json...就没问题，但是引用name或者val变量就会导致bug，即使用if判断，执行不到的分支里写这个也会有问题。

**Comment by big-dream** [comment]
可以考虑使用 [top-think/think-cors](https://github.com/top-think/think-cors) 来设置跨域。目前 ThinkPHP 6 不再进行更新（结束安全更新时间：2024年10月24日）
