### ISSUE TITLE
数据库生成UPDATE语句整型替换值会赋空

### ISSUE THREAD

**Issue by season886** [top-think/framework#319]
`public function getRealSql($sql, array $bind = [])
{
if ($bind) {
foreach ($bind as $key => $val) {
$value = is_array($val) ? $val[0] : $val;
$type = is_array($val) ? $val[1] : PDO::PARAM_STR;
if (PDO::PARAM_STR == $type) {
$value = $this->quote($value);
}
// 判断占位符
$sql = is_numeric($key) ?
substr_replace($sql, $value, strpos($sql, '?'), 1) :
str_replace(
[':' . $key . ')', ':' . $key . ',', ':' . $key . ' '],
[$value . ')', $value . ',', $value . ' '],
$sql . ' ');
}
}
return $sql;
}`
以前不管数值还是字符，都会SQL指令安全过滤，形成"''"这样插入数据库，现在只有字符才这样，数字会变成空，导致不能替换空值！
虽然可以用其他方法解决，但是我感觉这应该是框架应该解决的问题，请各位开发者酌情修改!看数值型字段如何默认赋值

**Comment by liu21st** [comment]
你的意思是 数字类型的字段 如果为空使用0 插入？

**Comment by season886** [comment]
0或者null,或者传进来是''也这样添加或更新进去，不然就会造成生成SQL语句错误！
例如：
Data['id'] =1;
Data['a'] = 'hello'; 字符型
Data['b'] = ''; 数字型(表示字段可以为null，或者用户没填写数据)
结果以现在的程序生成的SQL是:
update XX
set b=,
     a='hello'
where id = 1;
b那里就空了,因为没有执行$value = $this->quote($value); 
具体请看http://www.thinkphp.cn/topic/42714.html 我截取了生成的日志！
这我很困扰！烦请看下如何解决

**Comment by liu21st** [comment]
我改进了下 你再测试下吧

**Comment by season886** [comment]
已经正常，多谢
