### ISSUE TITLE
关于测试的问题,求用过phpunit的帮忙解答一下

### ISSUE THREAD

**Issue by dongasai** [top-think/framework#320]
刚接触单元测试这个东西,在ubuntu系统全局安装了一个PHPunit,在对该框架进行测试的时候遇到了;
Class "JohnKary\PHPUnit\Listener\SpeedTrapListener" does not exist

已进行composer install

**Comment by machenchi0207** [comment]
我遇到的问题跟你一样 我在mock.php里面加了require autoload.php就好了
不过我觉得不应该这么做啊 这个mock.php是官方自带的phpunit.xml里面引用的启动文件，不应该没有加载这个文件啊

**Comment by kinosang** [comment]
使用 `php think test` 进行测试

**Comment by machenchi0207** [comment]
我发现是我是用的phpunit 5，换成3 或者4就ok了

php think test 提示我没有think这个文件
