### ISSUE TITLE
一条sql语句两个相同的变量需要绑定两次

### ISSUE THREAD

**Issue by froyot** [top-think/framework#327]
$sql ="select * from message left join message_status on message.id=message_status.msg_id where message.uid=:id or message_status.uid=:id";
$model->where($sql)->bind(["id'=>$uid]);
默认这样会报绑定参数数目不正确，是pdo报错。如果配置数据库 PDO::ATTR_EMULATE_PREPARES  => true，则不会报错，但是获取到的数据都会转成string类型，即使数据库中时int类型

**Comment by liu21st** [comment]
这个本身PDO就不支持这样的绑定
