### ISSUE TITLE
使用模型类时发现一些由注释引起的问题

### ISSUE THREAD

**Issue by clyoko** [top-think/framework#328]
问题背景：如下所示使用模型类时，IDE（PHPStorm 2016.2.1）会给出警告。
```
$user=User::get(['id'=>1]);
echo $user->name;// 这句会提示警告
```
PHPStorm 2016.2.1

>Field 'name' not found in static less... (Ctrl+F1) 

>Referenced field is not found in subject class.  

>Note: Check is not performed on objects of type "stdClass" or derived.

查看Model类的get()方法的注释，发现@return 是static。同样，发现all()方法写的是static[]。更新数据等很多写的则是$this。scope()方法返回的又变成了Model。

我非常清楚注释不是为IDE而写的，是为人写的。于是我想了解下，对@return的书写有没有相关规范，以及混合使用static和$this的用意是什么？

**Comment by WeakSun** [comment]
不同的编辑器对注释的解释不一样，比如PHPStorm和NetBeans，主流编辑器对注释理解基本一致，只是细节上还是有差异。
如果你是重度强迫症患者，你可以多多参与开源贡献，把所有代码注释改成兼容你所使用的编辑器的标准；如果你很忙没空，你也可以换一个可以兼容当前注释的编辑器；当然还有第三种选择，等热心的贡献者帮你解决这个问题。
如果你不是一个强迫症患者，我只想说：程序员的本职是让电脑听人话，作为一个程序员，是否有点本末倒置？

**Comment by clyoko** [comment]
哈哈，已经就类似问题的其他代码贡献过了。只是一再出现，所以才有点疑惑。我大概明白是什么意思了，谢谢。
