### ISSUE TITLE
同时使用model的whereOr()和SoftDelete生成SQL问题

### ISSUE THREAD

**Issue by kukj** [top-think/framework#329]
model('Organization')->where('admin_id',101)->whereOr('owner_id',101)->select()
问题SQL语句
`SELECT * FROM `organization` WHERE `admin_id` = 101 AND `delete_time` IS NULL OR `owner_id` = 101 ORDER BY `id` DESC LIMIT 0,20`
期望SQL语句
`SELECT * FROM `organization` WHERE (`admin_id` = 101  OR `owner_id` = 101) AND `delete_time` IS NULL ORDER BY `id` DESC LIMIT 0,20`

**Comment by momoca** [comment]
看手册吧,用法不对.
$map['admin_id']=101;
$map['owner_id']=101;
model('Organization')->whereOr($map)->select()
我记得应该是这样.没验证...

**Comment by kukj** [comment]
刚发现手册上确实给了正规用法
model('Organization')->where(function ($query) {
    $query->where('admin_id', 101)->whereor('owner_id', 101);
})->select();
@momoca 这么写似乎不如直接用 model('Organization')->where('`admin_id`=101 OR `owner_id`=101')->select();更简单些
