### ISSUE TITLE
数据验证Validate对象的一个小BUG

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#33]
Validate对象中, 自带的 `unique` 验证源码中获取数据使用是 `Db::table($rule[0])` 
也就是说我在写 `unique` 验证的时候, 必须指定完整的数据表名称, 这样不太友好吧
这里应该用 `Db::name($rule[0])` 才对

**Comment by liu21st** [comment]
Db::name() 这种写法是数据库和模型重构之后才有的 之前是没有的 验证类重构已经很久了
