### ISSUE TITLE
controller 助手函数的问题

### ISSUE THREAD

**Issue by 17771258** [top-think/framework#330]
目前我们这边有这么一个需求
分组方式为 `wechat`  `index` 两个分组
wechat 使用数据库A 连接信息 
127.0.0.1 root pwd 3307 db_wechat

index 使用数据库B 连接信息 
127.0.0.1 root pwd 3306 db_index
现在 `wechat` 分组下已经有 User/list 方法显示微信关注用户

如果现在我在 `index` 分组调用wechat分组的方法 
app/index/controller/Index.php 代码如下
```php
namespace app\index\controller;
class Index{
      function wechatUser(){
           $list = controller("wechat/user")->list();
           dump($list)
      }
}
```
此时在我的wechat/user控制器下使用的还是index的数据配置，此处是否可以进行优化，因为这个场景应该在很多场合都会使用到。

如果按照目前这样就要在每个Model里面都写好数据库的配置信息，这样在开发过程中确实不是很方便，另外一个方法就是在调用 wechat/user 之前手动的去设置数据库配置A，之后返回数据的时候又要再次手动切换回数据库B的配置。

这块是否可以优化。方便开发。

**Comment by momoca** [comment]
php类不是可以继承的吗?你继承一个你的(比如mymodel)类把数据定义放到mymodel里面.mymodel再继承model就行了呀.

**Comment by 17771258** [comment]
@momoca 继承解决不了这个问题啊 因为现在 index 和wechat 是分两个项目组在开发的，双方给对方提供接口，我继承 Mymodel 的话 Mymodel 里面又需要在配置文件里面获取 数据库配置 `database` 选项， 此时我在 index 模块调用 wechat 模块，使用的 `database` 配置依然是 app/index/database.php的配置项， app/wechat/database.php 里面的配置不生效。

app/index/controller/Index.php 代码如下
```php
<?php
namespace app\index\controller;
class Index {
      public function wechatUser(){
          $list = controller('wechat/user')->getList();
          dump($list);
      }
}
```

app/wechat/controller/User.php 代码如下
```php
namespace app\wechat\controller;
class User {
      public function getList()
     {
           dump(config());
     }
}
```
直接访问 localhost/wechat/user/getlist.html
页面输出的是  app/wechat/database.php 配置内容
访问 localhost/index/index/wechatUser.html
页面输出的是 app/index/database.php 配置内容

我的意思是这里是否可以进行下优化操作，目前这样多模块，垮数据库确实操作起来比较复杂。

**Comment by liu21st** [comment]
这种方式的调用是不规范的 定义好模型 模型可以定义自己的数据库链接

**Comment by 17771258** [comment]
@liu21st 好的 看来这样的只能是每个定义 model 之后在 model 中定义数据库连接了。
只是这样会比较费时  团队之间配合比较费劲

**Comment by liu21st** [comment]
很简单啊 数据库配置统一放到应用配置 例如 db1_config db2_config 然后模型里面写上配置参数名

**Comment by 17771258** [comment]
@liu21st 好的  谢谢了
