### ISSUE TITLE
session_handler设置为redis后，如何从redis删除整个session？

### ISSUE THREAD

**Issue by sessionstart** [top-think/framework#333]
TP5的Session类只提供了清空某个session的值的方法，没有提供删除整个session的方法。

虽然可以使用session_id()获取这个session的名称，然后再使用redis的del删除，但是必须先开启session_start()，然后redis里面出现了2条session。

在没有手动开启session_start()时，redis里的session名称为6u00ltubtvukb4j5sj042fej52；
在手动开启后，redis里面多了一条：PHPREDIS_SESSION:6u00ltubtvukb4j5sj042fej52

请问如何解决？谢谢。

**Comment by sessionstart** [comment]
不过可以从cookie中获取sessionid，或许还有更好的方式？

**Comment by liu21st** [comment]
清空session不是有clear方法么？

**Comment by sessionstart** [comment]
<img width="442" alt="session" src="https://cloud.githubusercontent.com/assets/4160306/19771329/2a30f41e-9c95-11e6-8baa-1fd481433c03.png">

使用Session::clear()后，也只是清空了里面的值，这个key还是存在。如何将key也删除？

**Comment by yunwuxin** [comment]
强迫症又犯了吧  
这种数据根本不需要你去删  
内存不够的时候  redis自己会去释放

**Comment by sessionstart** [comment]
好吧！谢谢回复。 tp5很好用！
