### ISSUE TITLE
一对一关联时，方法名带下划线会使关联失效

### ISSUE THREAD

**Issue by yeahTibbers** [top-think/framework#335]
$User = User::get(1014252);
$result = $User->user_action;

<?php
namespace app\index\model;

use think\Model;

class User extends Model
{
    // 定义关联方法（此处关联失效）
    public function user_action()
    {
        return $this->hasOne('UserAction');
    }
}

**Comment by yunwuxin** [comment]
方法名都是驼峰   
~~~
public function userAction()
{
return $this->hasOne('UserAction');
}
~~~
