### ISSUE TITLE
REST 抽象类中，构造函数 $this->_initialize(); 改到什么地方了

### ISSUE THREAD

**Issue by foxiswho** [top-think/framework#341]
think\controller\Rest 中
现在 用于
```
// 控制器初始化
$this->_initialize();
```
 这个功能，改用那种方式初始化了

**Comment by liu21st** [comment]
rest类没有支持初始化方法 因为没有继承Controller类 另外不建议再使用rest控制器 而是直接使用资源路由，将来这个估计会被废弃的
