### ISSUE TITLE
验证 length 中文不友好

### ISSUE THREAD

**Issue by chuoke** [top-think/framework#343]
### 验证 length 中文不友好  
编码的原因，含中文的长度验证很不方便，建议添加一个`mblength` 专门用于含有中文的长度验证。

**Comment by 86849180** [comment]
/**
     * 验证数据长度
     * @access protected
     * @param mixed     $value  字段值
     * @param mixed     $rule  验证规则
     * @return bool
     */
    protected function length($value, $rule)
    {
        if (is_array($value)) {
            $length = count($value);
        } elseif ($value instanceof File) {
            $length = $value->getSize();
        } else {
            $length = mb_strlen((string) $value);
        }

        if (strpos($rule, ',')) {
            // 长度区间
            list($min, $max) = explode(',', $rule);
            return $length >= $min && $length <= $max;
        } else {
            // 指定长度
            return $length == $rule;
        }
    }
length规则用的就是mb_strlen()

**Comment by chuoke** [comment]
@86849180   它这里面没有明确编码格式，而是使用内部编码，这个就不方便了，

**Comment by liu21st** [comment]
@chunice 内部编码也是可以统一设置的 你一般不太可能混合使用多种编码吧
