### ISSUE TITLE
关联查询的字段限制问题

### ISSUE THREAD

**Issue by tksmai** [top-think/framework#350]
在使用 `$model->hasMany('Foo')->field(['bar', 'top'])` 定义模型方法，最后查询时发现生成的 sql 语句为
`select bar, top, foo.* from ... `
这样的查询导致字段限制失效了
请告知如何修复，并尽快提交到 composer

**Comment by he426100** [comment]
要用withField

**Comment by he426100** [comment]
你去看看关联预查询

**Comment by tksmai** [comment]
并不行
按照 关联预载入 的说明使用 withField 之后，sql 语句生成大致为
~~~
SELECT `table_b`.*,pivot.table_a_id AS pivot__table_a_id,pivot.table_b_id AS pivot__table_b_id FROM `table_b` INNER JOIN `table_a_table_b` `pivot` ON `pivot`.`table_b_id`=`table_b`.`id
~~~
不能达到预期效果

希望能找到方法，可以限制下关联表的字段限制（除了直接写原生 sql 语句外

**Comment by he426100** [comment]
`class User {
//关联模型
    public function role(){
        return $this->hasOne('role', 'id', 'role_id', [], 'left');
    }
    /**
     * 根据搜索条件获取列表信息
     * @param $where
     * @param $offset
     * @param $limit
     */
    public function lists($where, $offset, $limit)
    {
        return $this->field(['id','username','login_num','last_login_ip','last_login_time','real_name','tel','email','certificate','status','type','balance','create_time'])->with(['role'=>function($query){ return $query->withField('rolename'); }])->where($where)->limit($offset, $limit)->order('user.id desc')->select();
    }
}`
