### ISSUE TITLE
一对多关联批量添加没办法replace into操作

### ISSUE THREAD

**Issue by season886** [top-think/framework#351]
子表中已经存在了记录，执行saveAll会遇到主键重复，Relation.php saveAll怎么增加个参数$replace = true
模型类中的saveAll就有这样的参数

**Comment by season886** [comment]
为啥总是没人理我捏

**Comment by season886** [comment]
看了以前的回答，说是为了考虑数据库通用才这样的，但是为啥model里面的saveAll就可以呢？
如果是单表还好，如果是这样关联的话，更新非常麻烦，想了2天了，以后还有很多这样的界面，一对多，有些是老数据修改，有些又是新增加的，一起提交

**Comment by season886** [comment]
能否将Relation.php 里面的saveAll 变成加载外键的值后，执行model->saveAll($data)
不就完美解决了批量添加或者批量修改的问题了？

**Comment by momoca** [comment]
恩.你的意思是想反工作都推给thinkphp的model来做.不如告诉它:"就这些数据,你看着办吧..."
我个人理解这个框架应该满足需求,但不是满足所有需求.
另外还有一些问题是您没有理解开发者的意识(约定)或是根本没看手册.
这样也难怪没人理拉.

最后我个人对您的建议:如果您发现了问题.可以阅读相关文档.如果还是不理解就去看看相关部分的原码.只有更好的理解thinkphp后才能更快速的帮助你开发.
