### ISSUE TITLE
软删除deleteTime应该可以自定义默认值

### ISSUE THREAD

**Issue by chuoke** [top-think/framework#354]
个人习惯，很不喜欢字段设为null，删除字段的正常值一般是0，非0就是删除，然后框架的软删除字段默认值强行为 null，太不灵活了，应该改为可以自定义。

**Comment by season886** [comment]
强迫症又犯了^_^

**Comment by liu21st** [comment]
有些类型不允许设置默认值为0 这个官方早就考虑过的

**Comment by chuoke** [comment]
我还是认为这个默认值可以自定义的好

**Comment by teddymail** [comment]
为什么软删除却被真实的删除了？
