### ISSUE TITLE
建议增加读取缓存标签下的缓存数据  Cache::tag('tag')->get('name');

### ISSUE THREAD

**Issue by guandaxia** [top-think/framework#355]
建议读取缓存时可以读取已经设置缓存标签的数据，如：
Cache::tag('tag')->set('name1','value1');
Cache::tag('tag')->set('name2','value2');

Cache::tag('tag')->get('name1');  //读取tag标签下的缓存

现在的缓存标签感觉只是统一删除的时候可以用一下，用处不太大。

**Comment by liu21st** [comment]
缓存读取没必要通过tag方法的 本来就是唯一的
