### ISSUE TITLE
建议修改下File类关于[存在同名文件]的提示

### ISSUE THREAD

**Issue by yirenxin** [top-think/framework#356]
`$this->error = '存在同名文件' . $filename;` 
//建议改成
`$this->error = '存在同名文件' . $saveName;`

原提示信息如下，会暴露项目路径：
存在同名文件/mnt/hgfs/Web/yxx_pc/public/../public/uploads/20161111/b3b5a512f3bb96489b67e2969aa3ab77.png

建议改成：
存在同名文件20161111/b3b5a512f3bb96489b67e2969aa3ab77.png

**Comment by kinosang** [comment]
生产环境应当关闭debug开关，框架报错越详细越利于修复bug，至于是否展示出来要靠上层逻辑来捕获处理。
