### ISSUE TITLE
获取自增ID的BUG

### ISSUE THREAD

**Issue by konts** [top-think/framework#357]
获取自增ID的值是0，使用过create，获取的user_id的值是0，而save和insert获取的user_id的值是是1？

**Comment by liu21st** [comment]
给出你的代码吧

**Comment by konts** [comment]
$user = new User;
$user_create_result = $user->create(['username'=>'admin',,'password'=>'654321']);
// 获取自增ID
echo $user_create_result->user_id;//结果是null
$user->data(['username'=>'admin','password'=>'654321']);
$user->save(); // 结果是1

$user->insert(['username'=>'admin','password'=>'654321']); // 结果是1
