### ISSUE TITLE
核心类库里的文件上传类 File.php，检测文件是否是图片BUG

### ISSUE THREAD

**Issue by Kevinner** [top-think/framework#359]
代码如下
`    /**
     * 检测图像文件
     * @return bool
     */
    public function checkImg()
    {
        $extension = strtolower(pathinfo($this->getInfo('name'), PATHINFO_EXTENSION));
        /* 对图像文件进行严格检测 */
        if (in_array($extension, ['gif', 'jpg', 'jpeg', 'bmp', 'png', 'swf']) && !in_array($this->getImageType($this->filename), [1, 2, 3, 4, 6])) {
            return false;
        }
        return true;
    }`
会出现一直返回true的情况，测试环境：windows10,php7(xampps套件)
经测试改成如下即正常

`    /**
     * 检测图像文件
     * @return bool
     */
    public function checkImg()
    {
        $extension = strtolower(pathinfo($this->getInfo('name'), PATHINFO_EXTENSION));
        /* 对图像文件进行严格检测 */
        if (in_array($extension, ['gif', 'jpg', 'jpeg', 'bmp', 'png', 'swf']) && in_array($this->getImageType($this->filename), [1, 2, 3, 4, 6])) {
            return true;
        }
        return false;
    }`

**Comment by liu21st** [comment]
没有问题的 这个方法不是检查是否图像 而是检查图像文件上传的安全性

**Comment by 0yingteam** [comment]
这个逻辑转不过的程序员会直接认为返回false是错误的文件

**Comment by 0yingteam** [comment]
这个逻辑好像确实有问题啊

**Comment by 0yingteam** [comment]
审代码传上去了 可能程序员直接用默认的了
