### ISSUE TITLE
关于验证器唯一验证的问题

### ISSUE THREAD

**Issue by benaheng** [top-think/framework#36]
唯一验证这块 'mobile'      =>'require|unique:api_ucenter_user',
查询的时候 我看sql老是select id from.... 实际上这个表的主键并不是id
并且我看手册上也没写明这块该怎么处理  试过下面的方式都不行

// 表示验证name字段的值是否在user表中唯一
'name'   => 'unique:user',
// 验证其他字段
'name'   => 'unique:user,account',
// 排除某个主键值
'name'   => 'unique:user,account,10',
// 指定某个主键值排除
'name'   => 'unique:user,account,10,user_id',

另外还有个不方便的地方 这里的表还得写表前缀  在做成通用产品的时候这块会很不方便
因为通用产品安装的时候会让用户在配置文件里自定义表前缀

**Comment by liu21st** [comment]
这块已经改进了~
