### ISSUE TITLE
时间查询whereTime方法生成的sql没有解析

### ISSUE THREAD

**Issue by codesboy** [top-think/framework#360]
`$data=$user
...
->whereTime('u.create_time','d')
->select();`

使用模型查询 生成的sql 是AND `u`.`create_time` >  'today'，貌似没有解析
查询出来的结果也不是今日的数据
php5.6.27+mysql5.0+ tp5.0.3

**Comment by liu21st** [comment]
是因为关联查询的问题 这个问题今天改进了下 可以再测试下

**Comment by codesboy** [comment]
@liu21st 经测试已经可以了
