### ISSUE TITLE
模型saveAll小建议

### ISSUE THREAD

**Issue by chuoke** [top-think/framework#362]
![tpsaveall](https://cloud.githubusercontent.com/assets/17611457/20337054/97ff4a76-ac09-11e6-9ea3-e870f1b22d4c.png)  
  
这个 `isset($data[$pk])` 建议改成 `!empty($data[$pk])`，这样感觉更合理点，因为有时候确实定义了主键，只是没有值，如果是`isset`就会出问题。

**Comment by liu21st** [comment]
主要是会有主键为0的情况

**Comment by chuoke** [comment]
那可不可以再加个条件

**Comment by season886** [comment]
顶上去。。这个问题很好

**Comment by liu21st** [comment]
这个问题已经处理过了的
