### ISSUE TITLE
【warnning】float类型字段查询出错

### ISSUE THREAD

**Issue by chuoke** [top-think/framework#363]
> 使用版本 5.0.2和5.0.3  

float类型字段，查询出的结果总是被格式化的，比如 4324 会变成 5000或4400，测试double和int正常，无论是通过模型查询，还是Db，都这样。具体情况请看测试:
发现问题后，我只是简单的测试了下
![floatjiegou](https://cloud.githubusercontent.com/assets/17611457/20340703/dc33aeee-ac1d-11e6-8040-887bfddf6afb.png)   

![floatshuju](https://cloud.githubusercontent.com/assets/17611457/20340751/fe92644e-ac1d-11e6-8a78-0aa2a2604288.png)  

![floatjieguo](https://cloud.githubusercontent.com/assets/17611457/20340806/5200cf3a-ac1e-11e6-9b88-8b5f55df2316.png)

**Comment by liu21st** [comment]
我测试未发现你的问题 告知下 数据库的类型和版本？

**Comment by chuoke** [comment]
MySQL 5.5.40  Community Server (GPL)

是否存在配置的原因？

**Comment by six-days** [comment]
我也遇到同样的问题，数据库中存储float的值为0.524，使用TP取出来后就成float 0.52399998903275

**Comment by kpsanmao** [comment]
我也遇到这个问题了。

**Comment by sir-he** [comment]
mysql版本5.1.69 innodb float字段类型查询出来会被转换成int
如345.56查询后的结果是345，目前没有发现解决方案。我把数据库字段变成decimal是正常的
