### ISSUE TITLE
UNION操作的数组用法有错误

### ISSUE THREAD

**Issue by 86849180** [top-think/framework#364]
$result = Db::field('name')
            ->table('user')
            ->union('SELECT name FROM admin')
            ->fetchSql(true)
            ->select();
        //SELECT `name` FROM `user` UNION SELECT name FROM admin
        dump($result);
        $result = Db::field('name')
            ->table('user')
            ->union(['field'=>'name','table'=>'admin'])
            ->fetchSql(true)
            ->select();
        //SELECT `name` FROM `user` UNION name UNION admin
        halt($result);
第二个数组用法生成的SQL语句错误

**Comment by liu21st** [comment]
什么错误 能尽量明确点么

**Comment by liu21st** [comment]
文档有问题 不支持这种方式的定义 可以使用闭包定义不过
