### ISSUE TITLE
join表使用chunk 指定order字段无效

### ISSUE THREAD

**Issue by 786259135** [top-think/framework#367]
`Db::table('sites s')
            ->order('s.id')
            ->join('taba pkey', 's.id = pkey.sid')
            ->join('tabb ts', 's.id = ts.sid')
            ->join('tabc t', 't.id = ts.tid')
            ->chunk(3, function ($rows) {
                foreach ($rowsas $row) {
                    //
                }
            });`

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in order clause is ambiguous

join的每张表都有id字段，目测因此冲突

**Comment by liu21st** [comment]
chunk方法默认采用主键处理，你这种情况需要添加第三个参数 s.id

**Comment by liu21st** [comment]
我之前修正了一个地方 应该是没问题了现在

**Comment by 786259135** [comment]
可以了，不过有个疑问，为何改进的不是->order方法，而是给chunk增加参数呢

**Comment by liu21st** [comment]
和order无关，因为 chunk方法本身在处理数据的时候 就有一个排序规则
