### ISSUE TITLE
多对多关联(belongsToMany)的中间表的前缀问题

### ISSUE THREAD

**Issue by Yun-Shan** [top-think/framework#369]
似乎belongsToMany指定了中间表名之后，会执行两次查询，然而一次不加前缀，另一次次却自动加了前缀

模块的database.php中定义表前缀`'prefix' => 'account_';`
在模型中定义
```
public function roles() {
    return $this->belongsToMany('Role', 'user__role');
}
```
然后建立数据表`user__role`
然后执行`$user->roles`的时候就会报错，无法找到表`account_user__role`

然而如果把数据表名改成`account_user__role`
在执行`$user->roles`的时候又会报错，无法找到表`user__role`

只有当数据表名为`account_user__role`，并且使用`belongsToMany('Role', 'account_user__role')`调用的时候才能正常运行

但是我认为对`belongsToMany`的调用不应该需要知道database.php中定义的表前缀
当使用是`belongsToMany('Role', 'user__role')`调用的时候，两次查询都应该使用`account_user__role`这个表名，或者加个参数指定是否要加前缀也行

**Comment by liu21st** [comment]
第二个参数是完整表名，如果不希望固定前缀，可以使用 __USER_ROLE__ 或者干脆留空

**Comment by Yun-Shan** [comment]
嗯这样可以，但是我还是有疑问，对于同一次调用，为什么框架内两次解析表名的逻辑不同呢？这不应该吧

**Comment by liu21st** [comment]
最新版本中间表名称不需要添加前缀
