### ISSUE TITLE
Model toArray 的BUG

### ISSUE THREAD

**Issue by ucc862** [top-think/framework#37]
![image](https://cloud.githubusercontent.com/assets/4344635/14776828/8bd2b634-0afb-11e6-8bd8-2a4681cc2f21.png)
当使用了类型转化 设置一个array的字段，如果是个空数组，这个时候toArray的时候会报没有index 0的错误 
建议在前面加一个isset($val[0]) 避免错误

**Comment by ucc862** [comment]
![image](https://cloud.githubusercontent.com/assets/4344635/14778257/89ee7084-0b04-11e6-80ac-4b874b3c1cda.png)
 
BUG2 当值是NULL的时候不输出
BUG3 toArray不能使用自动类型转换

**Comment by liu21st** [comment]
已经修正
