### ISSUE TITLE
使用TP5发现的几处问题

### ISSUE THREAD

**Issue by 1459416736** [top-think/framework#384]
1.在验证类的构造方法里的$this->field = $field;
应该改成$this->message = array_merge($this->field , $field);
不然在自定义的验证类里面定义的 field一直会为空
2.model类的save方法
// 获取自动增长主键 isset（$this->data[$pk]）应该修改成empty($this->data[$pk])
因为id="" isset 判断为真，所以就一直不会获取id
if ($result && is_string($pk) &&  empty($this->data[$pk])) {
                $insertId = $this->db()->getLastInsID($sequence);
                if ($insertId) {
                    $this->data[$pk] = $insertId;
                }
}

**Comment by liu21st** [comment]
第二个问题之前也反馈过 主要是考虑到可能会有id为0的情况 暂时还没想到更好的办法，规范来说 不应该存在id = ‘’ 的情况
