### ISSUE TITLE
Merge模型定义$mapFields后 save操作会报错

### ISSUE THREAD

**Issue by benaheng** [top-think/framework#39]
```
protected $mapFields=[
    'uid'     =>'UcenterUser.uid',
    'info_uid'=>'UcenterUserInfo.uid',
];
```

会报sql语句错误 

经过排查 是因为 merge的save操作中的$data = $this->parseData($name, $this->data, true);后
把主键给弄丢了

**Comment by benaheng** [comment]
目前暂时加了句 $data[$this->pk]=$this->data[$this->pk];

**Comment by liu21st** [comment]
你设置了 pk的值么？

**Comment by benaheng** [comment]
@liu21st  设置了  下面是全部

    protected $pk='uid';

    protected $fk='uid';

    protected static $relationModel=['UcenterUserInfo'];

    protected $mapFields=[
        // 为混淆字段定义映射
        'uid'     =>'UcenterUser.uid',
        'info_uid'=>'UcenterUserInfo.uid',
    ];

    protected $autoTimeField=['reg_time'];
    protected $insert       =['reg_time','password'];

**Comment by benaheng** [comment]
这个问题还没修复，难道是我的用法有问题？ 请指教

**Comment by liu21st** [comment]
我这边测试没有问题啊
