### ISSUE TITLE
关于生成URL方法中的urldecode问题

### ISSUE THREAD

**Issue by GordonLife** [top-think/framework#390]
```
 // 添加参数
if (Config::get('url_common_param')) {
    $vars = urldecode(http_build_query($vars));
    $url .= $suffix . '?' . $vars . $anchor;
}
```
Url::build()方法中生成的url参数字符串用了urldecode导致有些生成的链接输出在`<a>`标签中的时候会打乱html样式，如：
Url::build('index/index', ['str' => '">']);
生成链接是：`http://localhost/index/index.html?str=">`
放到`<a>`标签中：`<a href="http://localhost/index/index.html?str=">">链接</a>`，这个时候链接中的双引号会截断`<a>`标签；
去掉urldecode后：`<a href="http://localhost/index/index.html?str=%22%3E">`，这样子就正常了

**Comment by jackboys000** [comment]
原来奇葩用户不止我一个。。。

**Comment by jackboys000** [comment]
一般这种问题，参数放到url::build中没啥意义，so就是多写两行代码的事。不叫问题。
