### ISSUE TITLE
验证器规则requireIf的建议

### ISSUE THREAD

**Issue by caiweiming** [top-think/framework#391]
首先，这个规则很有用，但是只能验证某个字段为某一个值时才有效，建议能判断多个值，因为经常有些地方需要用到。

比如

`'password'=> ['requireIf' => 'account,1|2']`

这样表示当account字段为1或者2时，password字段必须。

或者这种形式

`'password'=> 'requireIf:account,1^2'`

也表示当account字段为1或者2时，password字段必须。

**Comment by liu21st** [comment]
可以使用requireCallback验证规则

**Comment by caiweiming** [comment]
好的，只是感觉如果有'password'=> ['requireIf' => 'account,1|2']这种方式也挺方便的。
