### ISSUE TITLE
这个地方语法错误$this->success()/error()

### ISSUE THREAD

**Issue by FFCZ** [top-think/framework#392]
今天开发的时候发现这两家伙有问题。环境php7.0.1
$this->success(); $this->error();
=================================
语法解析错误: syntax error, unexpected ' ', expecting case (T_CASE) or default (T_DEFAULT) or '}'
<?php switch ($code) {?>
            <?php case 1:?>
            <h1>:)</h1>
            <p class="success"><?php echo(strip_tags($msg));?></p>
            <?php break;?>
            <?php case 0:?>
            <h1>:(</h1>
            <p class="error"><?php echo(strip_tags($msg));?></p>
            <?php break;?>
        <?php } ?>
=======================================
应该是缺少default语句造成的，建议用if语句判断，文件位置，thinkphp\tpl\dispatch_jump.tpl

**Comment by FFCZ** [comment]
3.2版在这个位置是使用if判断，没有碰到异常。

**Comment by jackboys000** [comment]
。。。
毛线啊。。。少default。。。
19行少了一个空格
<?php switch ($code) {?>改为<?php switch ($code) { ?>
在?>前面加一个空格
@momoca

**Comment by FFCZ** [comment]
加空格也没用啊，本来这个位置就两个判断，用if else解决，非要搞成switch语句。
最新V5.0.4还是没解决这个问题，其它人没碰到吗？

**Comment by momoca** [comment]
并没有,用和很久了.

**Comment by FFCZ** [comment]
![001](https://cloud.githubusercontent.com/assets/3875024/21470164/7139e992-cab7-11e6-8413-ee273617137a.jpg)
像这种情况，是什么原因造成的呢？？ @momoca

**Comment by jackboys000** [comment]
。。。。基本语法错误，是  code)这里加空格 ?>    问号前面加空格

**Comment by jackboys000** [comment]
｛这里

**Comment by momoca** [comment]
理解你的意思了.但你说的问题并不存在.是不是和你php配置有关.因为在使用swith():由于case前面不能有空格才引起的.这里的case已经在{}内了.我做过不下三十个网站各种国内国外的服务商的空间均没有提示过此报错.而且自建服务器使用wamp默认配置,也没有此错误.所以我判断问题出在你的机器上.

另附一个此类错误的文档:http://blog.163.com/sujoe_2006/blog/static/335315120149332515876
btw:你完全可以自己重写jump配置文件也支持呀.不必纠结.

**Comment by FFCZ** [comment]
@momoca 感谢你的回复。
我本地的开发环境，已经用3.2写过6-7个系统了，没想到第一次使用5.0就这么多坑，连基本的error和success都有坑。

**Comment by momoca** [comment]
恩.是的我也都是自己写错误页面(dispatch_jump.tpl)的.因为要配合网站的样式.
但总体来说使用5.0开始确实会比3.2快很多.
