### ISSUE TITLE
BUG获取数据表信息getTableInfo方法中未写入缓存，可能导致不可预知问题

### ISSUE THREAD

**Issue by jacklin** [top-think/framework#393]
BUG获取数据表信息getTableInfo方法中未写入缓存，可能导致不可预知问题，请进尽修复问题：
源在代源位置：Query.php

`    // 读取缓存
            if (is_file(RUNTIME_PATH . 'schema/' . $schema . '.php')) {
                $info = include RUNTIME_PATH . 'schema/' . $schema . '.php';
            } else {
                $info = $this->connection->getFields($guid);
            }`
改为
`            // 读取缓存
            if (is_file(RUNTIME_PATH . 'schema/' . $schema . '.php')) {
                $info = include RUNTIME_PATH . 'schema/' . $schema . '.php';
            }else if (Cache::has('schema_'.$schema)) {
                $info = Cache::get('schema_'.$schema);
            }
             else {
                if ($this->getConfig('debug')) {
                    $info = $this->connection->getFields($guid);
                }else{
                    $info = $this->connection->getFields($guid);
                    Cache::set('schema_'.$schema,$info);
                }
            }`
以上是我自己修改过方法，根据数据配置是否打开调试模式。选择是否读写缓存数据。

**Comment by liu21st** [comment]
你说的不可预知的问题指的是什么？
