### ISSUE TITLE
library/think/log/driver/File.php 60-62行写法不妥当

### ISSUE THREAD

**Issue by woshibushibu** [top-think/framework#397]
PHP Fatal error:  Uncaught think\exception\ErrorException: A non well formed numeric value encountered

thinkphp/library/think/log/driver/File.php(62): number_format('11,904.50366497...', 6)
在cli模式下，程序可能长时间运行，进而执行时间超过1000s，这是就会有number_format中含有“,”.

thinkphp/library/think/log/driver/File.php 60行附近：
        $runtime    = number_format(microtime(true) - THINK_START_TIME, 10);
        $reqs       = $runtime > 0 ? number_format(1 / $runtime, 2) : '∞';
        $time_str   = ' [运行时间：' . number_format($runtime, 6) . 's][吞吐率：' . $reqs . 'req/s]';

60行的 $runtime 不再是（不一定，超过1000就不是了）数值类型，导致 62行的number_format函数报错。

**Comment by woshibushibu** [comment]
建议修改   为  $runtime = round(microtime(true) - THINK_START_TIME, 10);

**Comment by liu21st** [comment]
感谢反馈，已经修正！
