### ISSUE TITLE
thinkphp 5 没有自己的RPC

### ISSUE THREAD

**Issue by Hongic** [top-think/framework#399]
分布式服务很流行，RPC是常用的内部服务通信方式，TP什么时候才有自己的RPC插件

**Comment by kinosang** [comment]
个人理解RPC属于API的一种形式，似乎不应该是框架应该包揽的工作

**Comment by Hongic** [comment]
不算是框架的部分，只是一个插件，我只是觉得应该拥有一个更适合tp的rpc插件，生态发展会需要的。

**Comment by kinosang** [comment]
你可以通过 composer 安装 packagist 上的包，其中不乏优秀的 RPC 扩展。

**Comment by Hongic** [comment]
好吧，可以推荐一下吗？

**Comment by kinosang** [comment]
稍微搜索了一下

PHP 自身提供

- XML-RPC
- SoapClient

Composer 包

- fguillot/json-rpc
- besimple/soap-client

PHP 扩展

- laruence/yar
- swoole

**Comment by Hongic** [comment]
好的，谢谢。

**Comment by phpyii** [comment]
hprose拿去不谢
