### ISSUE TITLE
在5.0.4版本中，如果开启了别名路由引发的url生成地址不正常

### ISSUE THREAD

**Issue by 5ini99** [top-think/framework#409]
在系统是配置了alias别名路由后，在某个模块中使用url生成链接时会将
url() 生成为 根地址

url('a') 生成为 /a.html
url('a/b') 生成为 /a/b.html
在5.0.3以前的版本中都是

url() 生成为 /模块名/控制器名/当前方法.html
url('a') 生成为 /模块名/控制器名/a.html
url('a/b') 生成为 /模块名/a/b.html

**Comment by liu21st** [comment]
已经修正
