### ISSUE TITLE
使用 mongodb 数据库时 软删除打开后查询不出数据

### ISSUE THREAD

**Issue by GuoDapeng** [top-think/framework#416]
```
class Test extends Model
{
    use SoftDelete;
    protected $deleteTime = 'delete_time';


    protected $insert = [
        'delete_time' => 'null',
    ];

    public function __construct($data = [])
    {
        // 设置当前模型对应的完整数据表名称
        $this->table = DBTableName::$test;
        parent::__construct($data);
    }
}
```

使用 **mongodb** 数据库时，SoftDelete 的 getDeleteTimeField 方法，这一行 `$field = $this->db(false)->getTable() . '.' . $field; ` 会给查询的键加上集合名。这样就查询不出的数据了。

PS:'delete_time' => 'null', 必须设置成这个值么？？？

**Comment by momoca** [comment]
文档中并没有你这样的写法呀.

**Comment by GuoDapeng** [comment]
@momoca 啥意思？正确的写法是啥样子的？？？

**Comment by liu21st** [comment]
mongodb需要 自己在模型类里面设置下 deleteTime字段名 默认的设计没有针对mongodb处理

**Comment by liu21st** [comment]
目前的做法可以在你自己的模型基类里面 重新定义getDeleteTimeField方法处理

**Comment by GuoDapeng** [comment]
使用 mongo 数据库时，删除数据就真的删除了。兼容软删除功能是应该在这个项目做还是 top-think/think-mongo 项目做？

**Comment by liu21st** [comment]
这个问题最新版本已经解决了
