### ISSUE TITLE
探讨模版的$this

### ISSUE THREAD

**Issue by joewulf** [top-think/framework#417]
现在在模版中{$this|dump}，$this的类型是 \think\template\driver\File

提议将模版中的$this的类型改变成当前控制器
简单实现
在 \think\template\driver\File 中增加 public static $include_func = null;
read 方法修改为
    public function read($cacheFile, $vars = [])
    {
        //载入模版缓存文件
        if (self::$include_func !== null && (self::$include_func instanceof \Closure)) {
            call_user_func(self::$include_func, $vars, $cacheFile);
        } else {
            if (!empty($vars) && is_array($vars)) {
                // 模板阵列变量分解成为独立变量
                extract($vars, EXTR_OVERWRITE);
            }
            include $cacheFile;
        }
    }

然后在控制器的基类的 _initialize 方法中加入
		\think\template\driver\File::$include_func = function ($vars, $cacheFile) {
			extract($vars, EXTR_OVERWRITE);
			//dump($vars);
			//dump($cacheFile);
			include $cacheFile;
		};
这样就可以

上面只是简单的实现，至于为什么将$vars传过来，因为我试过没传过来是传不到视图模版的

$this 改为当前运行的控制器，可以方便的调用控制器相关的内容和方法

**Comment by kinosang** [comment]
MVC 框架对 Model、View、Controller 作隔离是刻意为之。

另，避免 View 层访问 Controller 层能有效提升系统的安全性。

传值用 assign，逻辑尽可能放在控制器中。

**Comment by joewulf** [comment]
M/V/C的隔离只不过是理想化的状况
实际上 CV 链，你是不可能破的，必须经过C然后V，M可以没有

**Comment by slince** [comment]
如果需要在视图层调用控制层逻辑 显然是不可能的，视图层只承担运算结果的输出作用
