### ISSUE TITLE
session在模板中使用问题

### ISSUE THREAD

**Issue by hulang** [top-think/framework#423]
官方没有人回答我。只能在这里发了。
php版本：5.4.26
` 
$login_info=[
       'id'          => $id,
        'img'         => $data['img'],
         'nickname'    => $data['nickname'],
];
Session::set('user',$login_info);`

模板里面的标签
`        {empty name="Think.session.user.id"}
        <li class="layui-nav-item"><a href="{:url('Account/login','type=weibo')}">微博登录</a></li>
        <li class="layui-nav-item"><a href="{:url('Account/login','type=flyme')}">Flyme登录</a></li>
        {else /}
        <li class="layui-nav-item"><a href="javascript:;" onclick="logout();">退出登录</a></li>
        {/empty}`
提示错误。
Can't use function return value in write context

是不是php版本太低了。。
![5867663d01ffa](https://cloud.githubusercontent.com/assets/4961831/21598611/7008f7c2-d19a-11e6-8a49-ef0d6782e6ac.png)

**Comment by 786259135** [comment]
换了是我也不理你，文档也不看看

http://www.kancloud.cn/manual/thinkphp5/125004

**Comment by hulang** [comment]
什么叫我没有看文档。。我就是看着文档写的。。
你第2个的URL里面有：
`{empty name="Think.get.name"}
$_GET['name']为空值
{/empty}`
难道我的：
`{empty name="Think.session.user.id"}{/empty}`
错了？？？


我再告诉你下。我在php 5.5版本下。运行正常。这怎么解释？ @786259135

**Comment by momoca** [comment]
呀,我也忍不住要说两句了.
http://php.net/manual/zh/migration55.new-features.php
这是个问题.
btw: @liu21st empty确实是php5.5才支持表达式的.官方更新一下composer的require.php=>5.5吧.

**Comment by hulang** [comment]
@momoca 
那到底是我写错了？还是？？我确实在php 5.5版本下运行正常。php 5.4下。就出错嘛。。。
尤其是第1个回复我的。居然说我木有看文档。。莫名其妙。。。

**Comment by momoca** [comment]
1.你就不应该使用empty,应该用if所以那个人才说让你看文档.刚刚还把回复删除了.真是是奇怪.
2.如果官方使用empty内使用函数确实应该改成最底要求需要是php5.5.或是改变模版对empty函数的支持.
能解决你的问题不.你想用empty就要升级php5.5,或使用改成if/esle.我不是已经@管理员了吗.希望他能看到吧.

**Comment by hulang** [comment]
@momoca 
知道了。。那我使用if处理吧。。

**Comment by hulang** [comment]
@momoca 
可以的。使用if了。。一直习惯empty

**Comment by momoca** [comment]
@hulang恭喜拉.我感觉你应该在编程中使用中更加贴近自然语言.而当这样的判断时使用"如果"更贴切.再说empty根个else理解也容易出偏差.

**Comment by hulang** [comment]
@momoca 嗯。。。。
