### ISSUE TITLE
CLI模式下  Error while sending STMT_CLOSE packet

### ISSUE THREAD

**Issue by woshibushibu** [top-think/framework#429]
cli模式下 触发  Uncaught think\\exception\\ErrorException: Error while sending STMT_CLOSE packet. PID=

触发位置  thinkphp/library/think/db/Connection.php(344): think\\db\\Connection->free()

**Comment by woshibushibu** [comment]
上次查询是很久之前，隔了1天多

**Comment by 5ini99** [comment]
我也发现这个问题了，我目前是在free方法中try{}catch()了一下正常了
