### ISSUE TITLE
Model中的save函数判断增加还是修改异常 

### ISSUE THREAD

**Issue by woshibushibu** [top-think/framework#430]
还是CLI 模式下 ，当执行过一次后（比如首次是插入，第二次也应为插入，其实两次都一样where传入空），第二次isUpdate是默认的true

首次执行触发  773行：
            // 标记为更新
            $this->isUpdate = true;
第二次执行，到681行，这个判断为false，但是此时的isUpdate已经是true了，导致第二次save为insert时错误
if (!empty($where)) {
                $this->isUpdate = true;
            }

**Comment by momoca** [comment]
手动设置isUpdate呀.之前好像有人问过.

**Comment by woshibushibu** [comment]
我觉得框架应该是值得信赖的，如果是符合常规的逻辑，应该不需要多余的设置（设置了，就违背ThinkPHP的初衷了）
何况，不知道此状况的人，浪费不必要的调试时间。
对此问题，我重新继承了基础类，等待官方改过来，我就基础的。
同时  多谢建议 ^-^

**Comment by liu21st** [comment]
@woshibushibu  谁告诉你：比如首次是插入，第二次也应为插入 这个逻辑是正常的？

**Comment by liu21st** [comment]
官方的默认设置就是因为 是符合常规的逻辑

**Comment by momoca** [comment]
恩.我也认为官方的设计是没问题的.创建一个事件后默认应该是操作这个事件.
你哪种应用场景其实可以使用其它的方式,比如如果多行添加应该使用saveall.而不是一条一条的save.这样效率也不高呀.

@woshibushibu
