### ISSUE TITLE
config 配置加载不会加载 "场景配置“

### ISSUE THREAD

**Issue by stenote** [top-think/framework#44]
https://github.com/top-think/framework/blob/master/library/think/App.php#L272

进行了模块配置后加载了应用状态配置， 并没有体现出文档中 http://www.kancloud.cn/manual/thinkphp5/118024  所述的场景配置。

如下为简单代码片段:

```
if ($config['app_status']) {
    $config = Config::load(APP_PATH. $config['app_status']. EXT);
}
```

放置到 274 行后即可保证文档、框架一致。

**Comment by liu21st** [comment]
不是有么？

**Comment by stenote** [comment]
@liu21st 文档里有，这段逻辑没有啊

**Comment by liu21st** [comment]
![image](https://cloud.githubusercontent.com/assets/1111670/14851534/22ae8ff2-0cb3-11e6-8a0a-b40341d6a60c.png)
你自己看有没有

**Comment by stenote** [comment]
@liu21st  场景配置呢？

**Comment by liu21st** [comment]
应用状态就是场景配置啊

**Comment by stenote** [comment]
文档中这么写的:

```
每个应用都可以在不同的情况下设置自己的状态（或者称之为应用场景），并且加载不同的配置文件。

举个例子，你需要在公司和家里分别设置不同的数据库测试环境。那么可以这样处理，在公司环境中，我们在应用配置文件中配置：

'app_status'=>'office'
那么就会自动加载该状态对应的配置文件（位于application/office.php）。
```

但是代码逻辑中并没有加载 APP_PATH/config.php 的代码

**Comment by liu21st** [comment]
请问你有测试过么？

**Comment by liu21st** [comment]
反馈问题 起码要自己实际测试下吧？

**Comment by stenote** [comment]
明白了。错误理解 MODULE_NAME 了，以为 MODULE_NAME 初始化都会设定为 index 等。

测试后确认可用。

**Comment by stenote** [comment]
补充, 避免别人踩坑

* thinkphp 初始化会 initModule, 会先加载 COMMON_MODULE, 再尝试通过配置加载  default_module.
* thinkphp 加载 module 的过程中会进行 `Config::load`
* 当 module 为 COMMONT_MODULE 时, `$module` 为空，故  https://github.com/top-think/framework/blob/master/library/think/App.php#L272 会进行加载 config 配置中的 app_status 对应的配置文件。
