### ISSUE TITLE
Validate类的ip验证多了个参数了

### ISSUE THREAD

**Issue by zhl006006** [top-think/framework#441]

**Comment by liu21st** [comment]
什么意思？

**Comment by zhl006006** [comment]
我提及代码了，你可以看下

**Comment by zhl006006** [comment]
// 是否为IP地址
 -                $result = $this->filter($value, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 | FILTER_FLAG_IPV6);
 +                $result = $this->filter($value, [FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 | FILTER_FLAG_IPV6]);

// 是否为布尔值
 -                $result = in_array($value, [0, 1, true, false]);
 +                $result = in_array($value, [0, 1, '0', '1', 'true', 'false', true, false], true);
