### ISSUE TITLE
Validate类的ip验证参数错误

### ISSUE THREAD

**Issue by zhl006006** [top-think/framework#453]
// 是否为IP地址
$result = $this->filter($value, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 | FILTER_FLAG_IPV6);
改为
$result = $this->filter($value, [FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 | FILTER_FLAG_IPV6]);

**Comment by liu21st** [comment]
感谢反馈，已经修正
