### ISSUE TITLE
框架 query 配置覆盖了 top-think/think-mongo 的 query 配置，产生了错误。

### ISSUE THREAD

**Issue by GuoDapeng** [top-think/framework#457]
```
Argument 1 passed to think\db\Query::__construct() must be an instance of think\db\Connection, instance of think\mongo\Connection given, called in /var/www/html/purchase_dev/vendor/topthink/think-mongo/src/Connection.php on line 195 and defined
```

我在 database.php 文件添加了一项配置 'query'=>'\think\mongo\Query'，由于框架没对好 Connection.php 和 Query.php。在我使用 'type'=>'\think\mongo\Connection' 时，[query] => \think\db\Query 一直这样。
所以，我这样靠谱么？？？

**Comment by liu21st** [comment]
最新的mongo库已经修正过的

**Comment by GuoDapeng** [comment]
使用 composer update 命令好像不太管用，下载的完整包后才好的。composer 这东西是不是不太靠谱啊。

**Comment by kinosang** [comment]
如果你使用中国镜像，或网络不稳定导致使用过期的本地缓存，会无法正常更新到最新版本

**Comment by liu21st** [comment]
之前并没有更新composer包，另外检查下你的composer.json文件中的require依赖关系 最新的mongo包是1.2版本号
