### ISSUE TITLE
$this->redirect无法使用with

### ISSUE THREAD

**Issue by terranc** [top-think/framework#461]
当使用`$this->redirect()->with('aa', 123)`时并不能正常获取到`session('aaa')`，而只使用helper里的`redirect()->with()`才可以正常使用**flash**功能，不知道这是bug还是我使用上有错误。

**Comment by liu21st** [comment]
$this->redirect() 返回的并不是response对象了 而是抛出一个特殊的异常了

**Comment by terranc** [comment]
是特意为之咯？如果要用with就必须用helper？

**Comment by liu21st** [comment]
redirect方法我增加了一个with参数的
