### ISSUE TITLE
$model->save($data, $map)的$data如果是赋值0时，不会更新成功

### ISSUE THREAD

**Issue by terranc** [top-think/framework#462]
$model->save($data, $map)的$data如果是赋值0时，不会更新成功。
$map是非主键条件，如果$data里面赋值是0（字段类型是varchar），这时更新不会成功。

追踪了一下，好似是下图这里导致的：
![image](https://cloud.githubusercontent.com/assets/224353/22543871/6aced2e6-e96d-11e6-84ef-4f2aff7d8414.png)

**Comment by liu21st** [comment]
测试未能重现你的问题

**Comment by terranc** [comment]
额 发现compser安装结果安装了一个5.1的版本。。晕死。
