### ISSUE TITLE
think template driver里能增加一个不解析某个变量的标识符吗？

### ISSUE THREAD

**Issue by terranc** [top-think/framework#464]
如果项目里既有vue之类的前端模板标识，就可能产生冲突，虽然可以更换其一的标识符来解决，但也会带来不够通用的缺点，比如每次用一些移植代码或者第三方的东西都要手工转一遍，能否考虑提供一个类似 blade 里面的`@{{ $xxx }}`之类的特殊标识来标识是否要后端模板解析。

**Comment by kinosang** [comment]
你可以修改模板变量开始标记和变量结束标记

**Comment by terranc** [comment]
已经说了不想那么干，原因在上面

**Comment by liu21st** [comment]
目前的内置模板引擎设计已经有所过时了 不过现代主流开发模式也不需要模板引擎了

**Comment by terranc** [comment]
求教主流的模式用什么模式？

**Comment by kinosang** [comment]
直接把vue或者angular等之类的静态文件丢web根目录，PHP负责API，前端MVC(VM)负责UI。

大概……

**Comment by terranc** [comment]
@kinosang 总有一些情况不适合前后分离的，比如一些要seo的，对吧，总归还是要留条路吧。

**Comment by yunwuxin** [comment]
https://github.com/yunwuxin/think-twig
