### ISSUE TITLE
小建议：think template driver的变量非要去除前后的空格吗？

### ISSUE THREAD

**Issue by terranc** [top-think/framework#465]
关于`{$name}`才能解析，`${ $name}`或`${ $name }`就不能解析的问题：
1、可能习惯了vue和blade的一些模板语言，不巧一个空格不舒服，而且也认为多一个空格更清晰
2、类似用visual studio和phpstorm来开发，没有足够好的插件来支持thinkphp的模板编写，如果可以做次调整的话，blade的插件也能凑合着来处理think template了。

**Comment by liu21st** [comment]
完全可以用第三方模板引擎的 twig已经有扩展支持了
