### ISSUE TITLE
使用模型时报错：Cannot execute queries while other unbuffered queries are active

### ISSUE THREAD

**Issue by yuan1994** [top-think/framework#468]
### 错误如下：
```
SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
```

### 部分trace：
1. in Mysql.php line 63
2. at PDO->query('SHOW COLUMNS FROM `r...') in Mysql.php line 63
3. at Mysql->getFields('xxx...') in Query.php line 1731
4. at Query->getTableInfo('xxx...', 'type') in Query.php line 1779
5. at Query->getFieldsType(['multi' => ['AND' => ['userid' => ['xxx']]], 'where' => ['AND' => ['userid' => 'xxx']], 'table' => 'xxx...', ...]) in Query.php line 1785
6. at Query->getFieldsBind(['multi' => ['AND' => ['userid' => ['xxx']]], 'where' => ['AND' => ['userid' => 'xxx']], 'table' => 'xxx...', ...]) in Builder.php line 245
7. at Builder->buildWhere(['AND' => ['userid' => 'xxx']], ['multi' => ['AND' => ['userid' => ['xxx']]], 'where' => ['AND' => ['userid' => 'xxx']], 'table' => 'xxx...', ...]) in Builder.php line 223
8. at Builder->parseWhere(['AND' => ['userid' => 'xxx']], ['multi' => ['AND' => ['userid' => ['xxx']]], 'where' => ['AND' => ['userid' => 'xxx']], 'table' => 'xxx...', ...]) in Builder.php line 817
9. at Builder->delete(['multi' => ['AND' => ['userid' => ['xxx']]], 'where' => ['AND' => ['userid' => 'xxx']], 'table' => 'xxx...', ...]) in Query.php line 2587
10. at Query->delete() in MyModel.php line 27

### 最终尝试可行解决方案：
修改 `\think\db\Connection` 的第356行，将
```
if (!empty($this->PDOStatement) && $this->PDOStatement->queryString != $sql) {
```
修改为
```
if (!empty($this->PDOStatement)) {
```

希望官方能查明原因修复此bug

**Comment by liu21st** [comment]
我暂时无法重现

**Comment by liu21st** [comment]
或者你设置 PDO::MYSQL_ATTR_USE_BUFFERED_QUERY 参数后试下再

**Comment by yuan1994** [comment]
我设置过，没有用，我这代码很复杂，也无法贴代码，如果您遇到请您修复一下，目前临时解决办法只能是按我上面那样修改了，但不知道所以然

**Comment by liu21st** [comment]
是否有使用事务？

**Comment by yuan1994** [comment]
没有
