### ISSUE TITLE
通过 router.php 作为入口文件开启 web 服务器后，Route 无法使用

### ISSUE THREAD

**Issue by stenote** [top-think/framework#48]
通过router.php 作为入口文件开启 web 服务器后，Route 无法使用。

如下：

https://github.com/top-think/framework/blob/master/library/think/App.php#L343

只尝试进行了 `$_SERVER['PATH_INFO']` 的匹配判断。

实际上 php -S 不会有 `$_SERVER['PATH_INFO']`.

Bug ?

**Comment by liu21st** [comment]
router 仅供没有环境的时候测试 学习 可以使用兼容模式访问

**Comment by stenote** [comment]
简单测试了下，发现，如果判断 PHP_SAPI cli-server 的时候，使用 $_SERVER['REQUEST_URI'] 可正常进行 Route 使用。

貌似上面所述的 `可以使用兼容模式访问` 是说浏览器吧。

**Comment by liu21st** [comment]
这个问题 换回原来的位置后 已经解决了
