### ISSUE TITLE
小建议：更新时自动更新修改时间的问题

### ISSUE THREAD

**Issue by phpyii** [top-think/framework#488]
把autoWriteTimestamp设为true时更新时不能自动更新修改时间
更新的时候一般是先find 再更新的（此时数据已经有更新时间了），而框架源码中是判断修改时间为null时才更新修改时间，这样我就得先把修改时间设为null才可更新

**Comment by liu21st** [comment]
更新时间无论是新增和编辑都会更新的

**Comment by phpyii** [comment]
@liu21st  恩，我处理的问题。 我查出来后和表单接收的数据合并后  用了->save($data)      $data里原来的更新时间戳   汗！
