### ISSUE TITLE
where查询条件BUG

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#49]
`Query.php` 中的 `parseWhereExp` 方法中有如下一段代码:
```
    if (is_string($field) && preg_match('/[,=\>\<\'\"\(`.\s]/', $field)) {
        $where[] = ['exp', $field];
        if (is_array($op)) {
            // 参数绑定
            $this->bind($op);
        }
    }
```

如果 `$field` 中存在 字符 `.` , 则正则表达式就会生效
链表查询时, 使用 `Db::name("table")->alias("t")->where("t.field", 1)->select();`  就会出错, 解析出来的SQL 为 `SELECT * FROM table t WHERE ( t.field )`

**Comment by liu21st** [comment]
感谢反馈 已经修正
