### ISSUE TITLE
建议验证器控制器中length、max、min方法中mb_strlen函数都加上第2个参数

### ISSUE THREAD

**Issue by tlcyeee** [top-think/framework#494]
file:   thinkphp\library\think\Validate.php

$length = mb_strlen((string) $value);
加上第2个参数  改为
$length = mb_strlen((string) $value, 'utf8');

这样在判断中文字符长度的时候， 就不用*3转换了

**Comment by liu21st** [comment]
多字节方法的字符集是可以统一设置的 无需写死
