### ISSUE TITLE
[Enhancement] TP5.5.x

### ISSUE THREAD

**Issue by slince** [top-think/framework#508]
## TP5.5.x 

- 增加DI容器(支持PSR11)
- 进一步拥抱PSR,缓存支持PSR6, Request支持PSR7, 日志支持PSR3,
- 进一步抽象，组件化设计，组件功能从核心包里抽离单独发布
- 移除静态化设计（如果要向下兼容静态的api，尝试引入类似Facade的设计）
- 工程结构重组
- 应用目录再升级，引入bundle概念，方便用户业务代码独立迁移、发布与共享

这些做完，tp的骂声能少一大半

**Comment by liu21st** [comment]
路漫漫而修远兮 issue的管理也需要一起参与和规范化

**Comment by nottellyou** [comment]
支持。
