### ISSUE TITLE
模型中嵌套逻辑查询

### ISSUE THREAD

**Issue by woshibushibu** [top-think/framework#509]
如何构造类似 aa=1 OR (bb=2 AND cc=3) 的查询，不使用原生查询的情况下

**Comment by slince** [comment]
这不是一个帮助论坛，如果你是寻找有关如何实现功能或更好地了解的帮助
如何正确使用框架，您可以访问以下链接：

- [官网论坛](http://www.thinkphp.cn/topic)
- [SegmentFault](https://segmentfault.com/t/thinkphp)

谢谢!
