### ISSUE TITLE
framework/library/think/Request.php 第230行左右 BUG

### ISSUE THREAD

**Issue by liuwave** [top-think/framework#510]
framework/library/think/Request.php 第230行左右
parse_str(html_entity_decode($info['query']), $query);
            if (!empty($params)) {
                $params      = array_replace($query, $params);
                $queryString = http_build_query(**$query**, '', '&');
            } 

应为
parse_str(html_entity_decode($info['query']), $query);
            if (!empty($params)) {
                $params      = array_replace($query, $params);
                $queryString = http_build_query(**$params**, '', '&');
            }

**Comment by slince** [comment]
建议直接PR
