### ISSUE TITLE
子查询问题

### ISSUE THREAD

**Issue by phpyii** [top-think/framework#522]
```
为什么只能使用IN  把IN改成=就不行了？
Db::table('think_user')
->where('id','IN',function($query){
    $query->table('think_profile')->where('status',1)->field('id');
})
->select();
```

**Comment by kinosang** [comment]
你的子查询返回一组数据

更多细节参见 MySQL 手册

**Comment by phpyii** [comment]
@kinosang  不是子查询返回一组属性的问题 我换成 > 也不行  
是框架报错不是mysql报错  
Object of class Closure could not be converted to string

**Comment by kinosang** [comment]
子查询返回数组，是不能进行 > < = 之类的运算的。

**Comment by phpyii** [comment]
@kinosang  不好意思刚才说错了  代码贴的是tp5例子  
我看源码了原来['=', '<>', '>', '>=', '<', '<=']  不支持闭包  那就说明不能这样写了
 https://github.com/top-think/framework/blob/master/library/think/db/Builder.php#L340  
最终这样写ok了    yii2没有限制> < = 之类的运算  就是子查询多条报mysql错误
```
$subQuery = Db::table('attribute')->where('attrid',$attrid)->field('parent_attrid')->buildSql(true);
$parentAttr = Db::table('attribute')->where('attrid', 'exp', '='.$subQuery.'')->field('attrid,attr_name')->find();
```

**Comment by liu21st** [comment]
已经改进支持 @phpyii
