### ISSUE TITLE
thinkphp 5.0.6  当调用模型的save 或者 update，时出现  method not exist

### ISSUE THREAD

**Issue by woshibushibu** [top-think/framework#523]
当调用模型的save 或者 update，时出现 
Uncaught think\Exception: method not exist:think\db\Query->udpate in /home/thinkphp/library/think/db/Query.php:93 

Uncaught think\Exception: method not exist:think\db\Query->save in /home/thinkphp/library/think/db/Query.php:93

**Comment by woshibushibu** [comment]
模型是正常的new 出来的

**Comment by yunwuxin** [comment]
update 应该是有的 ，   save方法本来就没有，save方法是在模型上 不在Query上

**Comment by woshibushibu** [comment]
如果model 直接调用可以；如果是使用了快捷操作 如$user->name('test1')->save(....)
这时候就出现这个问题了

**Comment by yunwuxin** [comment]
$user->name('test1')返回的是个Query对象  当然只能使用Query上的方法了
补下基础
