### ISSUE TITLE
模型通过主键查询问题

### ISSUE THREAD

**Issue by phpyii** [top-think/framework#527]
ProductModel::get($product_id)
$product_id = 0 查不出  
$product_id = null 会把第一个查出来

**Comment by liu21st** [comment]
教程手册中明确提出 这个地方需要自己验证 0 是可以查询出来的

**Comment by phpyii** [comment]
@liu21st  恩，我可能没仔细看教程。  那就是参数得自己验证null了？ 不然null就会查出第一条数据了

**Comment by liu21st** [comment]
是的
