### ISSUE TITLE
关于group by跟count没法一起使用的问题

### ISSUE THREAD

**Issue by Sanit1** [top-think/framework#550]
$query = $model->where('xxx')->group('xx');
如果下面用
$count = $query->count();
得到的结果不正确

我现在的解决方案是
$subQuery = $query->buildSql();
$count = Db::table($subQuery.' z')->count()
这样虽然能得到正确的结果，但是总感觉应该你们think的ORM再该封装的好一点

**Comment by liu21st** [comment]
这个问题最新版本已经解决了啊

**Comment by Sanit1** [comment]
@liu21st 我这边用的是5.0.4 请问你们在哪个版本修复的

**Comment by liu21st** [comment]
V5.0.5 详细参考官方更新日志 http://www.kancloud.cn/manual/thinkphp5/209035
