### ISSUE TITLE
tp5对路由的判断,是bug么?

### ISSUE THREAD

**Issue by yhuaqiang** [top-think/framework#554]
如果在route.php中定义了一个路由
'home/ok/:id'=>['index/Home/ok',method=>'*'], 
但是通过pathinfo访问时,index.php/home/ok/123 访问时,却提示404,非法请求. 
查找源码发现在think\Route.php中的判断逻辑是: 如果该path在路由中定了,就会抛出404异常. 1258行.
是不是路由定义不能与pathinfo的路径一致?
 if (isset(self::$rules['name'][$name]) || isset(self::$rules['name'][$name2])) {
             throw new HttpException(404, 'invalid request:' . str_replace('|', $depr, $url));
   }

**Comment by yhuaqiang** [comment]
经过测试,路由定义是不能与module/controller/action定义成一致的.
请问这个是正确的吗?
正常逻辑不是应该路由优先于完整路径么?
因为路由可以设定method.

**Comment by liu21st** [comment]
一旦某个路由地址定义了路由访问规则后 原来对应的路由地址就不能访问 只能使用路由访问

**Comment by yhuaqiang** [comment]
文档中也没有说明,这个问题好一顿找...
好吧. 按照框架的规则

**Comment by liu21st** [comment]
怎么会没说明 你们看个文档都是走马观花

**Comment by liu21st** [comment]
一定定义了路由 原先的地址当然就不能访问了 否则就出现一个页面两个不同的URL了

**Comment by yhuaqiang** [comment]
本意是这样：,路由定义是不能与module/controller/action定义成一致的.
请问这个是正确的吗?
