### ISSUE TITLE
tp5的几个bug. 后两个与mongodb有关

### ISSUE THREAD

**Issue by yhuaqiang** [top-think/framework#555]
1.Model->save($data = [], $where = [], $sequence = null): 
    如果$data为空数组,则不进行validate,设置require的属性将无法检测
2.Model->readTransform($value, $type)
    当设置字段为object类型时,写入数据中是对象.
    但在读取的时候,却提示json_decode() expects parameter 1 to be string, array given
    是因为$value是对象,却没有判断,直接当做字符串
     case 'object':
        $value = empty($value) ? new \stdClass() : json_decode($value);
        break;
3.字段类型array
    如果字段类型为array,则会被转化为json,但是mongodb支持数组.代码如下,'array'之后没有break;
    case 'array':
        $value = (array) $value;
    case 'json':

**Comment by liu21st** [comment]
嗯 mongodb的几个bug会在下一个版本解决 第一个问题 如果不传入data数据 表示数据赋值之前就已经验证过了 其实框架的建议是在控制器中就对数据进行验证。

**Comment by yhuaqiang** [comment]
因为Model和字段是接触最紧密的, 所以我是把字段验证在model中验证.
通过validate(true). 
问下下个版本什么时候发布
