### ISSUE TITLE
\model\SoftDelete有bug

### ISSUE THREAD

**Issue by Sanit1** [top-think/framework#570]
情况是这样的
启用软删除功能之后
我设置了delete_time int(11) default 0
但是只要我的delete_time 有值 你就当我删除
这个不合理吧 希望官方能修复一下！！！

**Comment by kinosang** [comment]
delete_time 請默認 null

其他不同的框架對軟刪除的支援也都是判斷 null or not

**Comment by Sanit1** [comment]
@kinosang 
我用过其它的框架可以设置默认值为0的。关于字段默认值设为null不能索引 然后还会带来意向不到的后果，所以尽量能避免。曾经有个dba就让我不要默认值为null 希望tp5能修复 3Q

**Comment by liu21st** [comment]
下一个版本支持自己设置软删除条件

**Comment by liu21st** [comment]
这个问题已经解决了 master版本可以用useSoftDelete方法自定义软删除的条件
