### ISSUE TITLE
自动写入bug

### ISSUE THREAD

**Issue by 1057585044** [top-think/framework#577]
create_time timestamp 格式的数据
当我开启 datetime_format = false
protected $autoWriteTimestamp = 'timestamp';
protected $createTime = 'create_time';
protected $updateTime = 'u_time';
这个情况下自动写入创建时间是 时间戳并不是 date("Y-m-d H:is:")格式数据
数据不自动合并的场景应该是查询而不是写入

**Comment by liu21st** [comment]
你关闭了datetime_format 自然写入数据会有问题
