### ISSUE TITLE
当get和 find 没有传参或者参数为 null 时，也会返回数据的 bug

### ISSUE THREAD

**Issue by terranc** [top-think/framework#592]
version: 5.0.7

```php
Activity::find($prize->activity_id);
```

上面的语句如果 activity_id是空，会查询出第一个活动，这应该与预期不符吧？

**Comment by liu21st** [comment]
需要自己判断下再传入get方法 db类的find方法也是一样

**Comment by terranc** [comment]
@liu21st 如果是特意为之，就 close 吧。不过这个逻辑感觉与我的自然思维的预期不一致，什么业务场景会需要这样的设计？

**Comment by liu21st** [comment]
这个地方 我已经改进了
