### ISSUE TITLE
Cannot use 'Null' as type name as it is reserved (since PHP7) Null.php 

### ISSUE THREAD

**Issue by tekintian** [top-think/framework#6]
thinkphp\library\think\console\output\Null.php 这里的这个类名 Null 在PHP7里面是系统保留关键字,  会提示错误,需要更改这个类名

------------PHP7提示错误信息如下:

Description	Resource	Path	Location	Type
Cannot use 'Null' as type name as it is reserved (since PHP7)	Null.php	/bjesc/trunk/thinkphp/library/think/console/output	line 17	PHP 7 Problems

**Comment by tekintian** [comment]
这个问题没人解决?

**Comment by kinosang** [comment]
问题已了解，目前还在就如何修改进行讨论

**Comment by yunwuxin** [comment]
已经提交了
