### ISSUE TITLE
success 函数报异常

### ISSUE THREAD

**Issue by jinliming2** [top-think/framework#603]
我在调用`$this->success('操作成功！');`会出现成功页面，但是在成功提示的上面有一个异常提示，定位在这个位置：
https://github.com/top-think/framework/blob/master/library/traits/controller/Jump.php#L63
请问这是有意的还是无心的？还是我的用法有问题？

**Comment by ganlvtech** [comment]
使用HttpResponseException是为了让程序跳出层层调用，异常最终会被应用程序catch住

<https://github.com/top-think/framework/blob/master/library/think/App.php#L124>

这不是问题所在，你需要提供更细致问题反馈。
