### ISSUE TITLE
\think\Validate 进行验证操作

### ISSUE THREAD

**Issue by huyouheng** [top-think/framework#624]
在使用\think\Validate 进行验证操作,定义规则max:25的时候,出现致命错误: Call to undefined function think\mb_strlen(),把类Validate中的mb_strlen(),方法改为strlen就不报错了，请问这是怎么回事，到处找了mb_strlen()这个方法，不存在啊，能有人回复下吗?

**Comment by momoca** [comment]
我这很正常.并没有出错.你用的是最新版吗?
换句话(再)说任何版本都没出过类似的问题.

**Comment by liu21st** [comment]
你没有安装mbstring库导致
