### ISSUE TITLE
访问URL参数问题

### ISSUE THREAD

**Issue by jinliming2** [top-think/framework#625]
定义控制器：
```
class Index extends Controller {
    public function index() {
    }
}
```
访问：`xxx.com/index/index/index?code=123&state=456`是正常的，但是访问`xxx.com/index/index/index.html?code=213&state=123`就提示“方法不存在:app\index\controller\Index->index.html()”

**Comment by liu21st** [comment]
检查你的其它配置参数

**Comment by essaying** [comment]
看了下好像是request->path方法的问题
`$this->path = preg_replace('/\.(' . ltrim($suffix, '.') . ')$/i', '', $pathinfo);`
这里没有去掉.html, 不清楚有没有配置文件来解决

**Comment by essaying** [comment]
@liu21st
