### ISSUE TITLE
建议在relation中支持common下model中的类

### ISSUE THREAD

**Issue by momoca** [top-think/framework#645]
framework/library/think/model/relation/*.php中
我发现在relation默认是只使用了当前模块下的模型类.如果当前模块下没有默认应该去common中查找.

**Comment by liu21st** [comment]
支持的 你可以指定模型的完整命名空间

**Comment by momoca** [comment]
@liu21st 是的我知道如果写完整空间名是可以的.但是我想如果可以支持自动去common里的类.不是更好吗?

**Comment by liu21st** [comment]
你的模型类不应该到处放 统一放一个地方应该是 只有特殊的模型才需要指定完整的命名空间这样

**Comment by momoca** [comment]
好的.确实如此.只怪我强迫症犯了.期待5.1
