### ISSUE TITLE
模板解析有问题

### ISSUE THREAD

**Issue by zhl006006** [top-think/framework#650]
源代码：
function iframeHref(e){$iframe.prop("src")!=e&&($adminSpinner.show(),
解析后代码:
function iframeHref(e)<?php echo $iframe['prop']("src")!=e&&($adminSpinner['show'](),

方法的大括号没了

**Comment by momoca** [comment]
```
function iframeHref(e){ $iframe.prop("src")!=e&&($adminSpinner.show(),
```
要么别用$.要么在{和$中加个换行或空格.
