### ISSUE TITLE
Db类  连贯操作 where 内不能嵌套Db查询

### ISSUE THREAD

**Issue by liuwave** [top-think/framework#654]
测试代码如下：
    
     Db::name('cart')
            ->where([
                'user_id'=>Db::name('users')->where(['user_name'=>'jjjdsf'])->value('user_id'),
                'sku'=>'16009'
            ])
            ->find();

实际执行的sql语句为

SELECT `user_id` FROM `yl_users` WHERE `user_name` = 'jjjdsf' LIMIT 1;
SELECT * FROM `yl_users` WHERE  `user_id` = :where_user_id  AND `sku` = '16009' LIMIT 1 

最外层的 cart表 被 users替代了。

不知这算不算个bug？ 还是不能这样使用？

实际使用是不会这么直接，但有可能是这样

     Db::name('cart')
            ->where([
                'user_id'=>User::getUserId(),
                'sku'=>'16009'
            ])
            ->find();

其中 如果User::getUserId() 中包含Db查询，也会出现这样的情况，即外部的cart表被内部的user替代。

**Comment by liuwave** [comment]
测试版本为 5.0.7

**Comment by liu21st** [comment]
这个是5.0数据库设计的一个缺陷 5.1版本中已经解决了 遇到这种情况只能先在外面赋值给变量 然后传入

**Comment by liu21st** [comment]
5.0最新git版本该问题已经修正
