### ISSUE TITLE
模型属性问题

### ISSUE THREAD

**Issue by mrjnamei** [top-think/framework#657]
1.Model里面有个$type ，如果我数据库有这个字段，在模型里面设置了$this->type = "xx" ; type这个字段不能更新
2.name 也是，这两个是常见的字段，不应该如此设计。

`
$this->name = $goods->goods_name ;
        $this->url = '/goods/' . $goods->id ;
        $this->image = $goods->thumb ;
        $this->type = self::GOODS ;
        $this->user_id = $data ['user_id'] ;
        $this->pk = $data ['goods_id'];
`
`
"INSERT INTO `xx_collect` ( `url` , `image` , `user_id`) VALUES ('/goods/40' , 'https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=4100148126,3517297325&fm=117&gp=0.jpg' , 4)"
`

**Comment by liu21st** [comment]
用法问题 模型属性赋值是在模型外部操作的 在内部操作使用setAttr方法 仔细参考文档
