### ISSUE TITLE
保存日志问题，是否是bug？还是故意这样设计的

### ISSUE THREAD

**Issue by 1057585044** [top-think/framework#661]
app_debug = false;
    'log'                    => [
        // 日志记录方式，内置 file socket 支持扩展
        'type'  => 'File',
        // 日志保存目录
        'path'  => LOG_PATH,
        // 日志记录级别
        'level' => ['error'],
    ],

随便访问一个url都会生成一条 空的日志
[ 2017-05-02T23:10:56+08:00 ] 
---------------------------------------------------------------

**Comment by liu21st** [comment]
是哪个版本？

**Comment by 1057585044** [comment]
if (!empty(self::$log)) {
            if (is_null(self::$driver)) {
                self::init(Config::get('log'));
            }

            if (!self::check(self::$config)) {
                // 检测日志写入权限
                return false;
            }

            if (empty(self::$config['level'])) {
                // 获取全部日志
                $log = self::$log;
                if (!App::$debug && isset($log['debug'])) {
                    unset($log['debug']);
                }
            } else {
                // 记录允许级别
                $log = [];
//TODO :: 这里 会把log过滤成 $log = [];
                foreach (self::$config['level'] as $level) {
                    if (isset(self::$log[$level])) {
                        $log[$level] = self::$log[$level];
                    }
                }
            }

                $result = self::$driver->save($log);
            if ($result) {
                self::$log = [];
            }

            return $result;
        }
