### ISSUE TITLE
Query类在模型里执行$this->select(false)后不是应该直接返回拼接的sql语句吗

### ISSUE THREAD

**Issue by weeisc** [top-think/framework#662]
报错信息
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-5/63692350-file_1493954476505_10777.png)
代码
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-5/57244235-file_1493954538565_10e25.png)

**Comment by liu21st** [comment]
计划取消select(false) 用法 不太规范 统一使用 fetchsql(true) 方法最好

**Comment by weeisc** [comment]
ok
