### ISSUE TITLE
Connection.php报不存在prefix属性的错误

### ISSUE THREAD

**Issue by weeisc** [top-think/framework#664]
原因是自定义模型类里边使用了__TABLE__的格式？，
自己暂时把 Connection.php那块的代码改成了$prefix = $this->config['prefix'];
报错信息如下：
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-5/88234352-file_1493980340052_aab0.png)
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-5/72871461-file_1493980722542_34d1.png)
在connector/Mysql.php，Connection.php 文件看了下，只看到Connection类的 $config 里的 prefix
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-5/34319619-file_1493980364551_1488.png)

**Comment by liu21st** [comment]
这个应该有修正过的

**Comment by weeisc** [comment]
我使用的版本是 5.1beta-1 ,我看代码里的判断还是这个，这个是正常的吗，但是我测试了，还是会报我之前提的那个错误啊。
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-8/76950956-file_1494210096791_bcd8.png)

报错的SQL代码
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-8/49513940-file_1494210728011_3a79.png)

**Comment by liu21st** [comment]
你用的是下载版还是git的5.1分支版本

**Comment by weeisc** [comment]
git上的Tags v5.1-beta.1

**Comment by liu21st** [comment]
tags一旦打了标记是不会变化的 ，所有的改进都会在下一个tags生效 建议你使用5.1分支的版本开发 更新及时

**Comment by weeisc** [comment]
哦哦哦，脑抽了，，忘记是Tag了
