### ISSUE TITLE
5.1路由设置别名后，出现报错

### ISSUE THREAD

**Issue by weeisc** [top-think/framework#665]
路由设置代码：
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-8/6032911-file_1494219630184_1723c.png)
报错信息如下：
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-8/79005555-file_1494219577891_17af9.png)

**Comment by liu21st** [comment]
感谢反馈 已经修正
