### ISSUE TITLE
嵌套关联数组方式定义时报错

### ISSUE THREAD

**Issue by yeahTibbers** [top-think/framework#667]
![image](https://cloud.githubusercontent.com/assets/10751521/25809437/8fbe0384-343f-11e7-9ed8-7a97b9b17228.png)
![image](https://cloud.githubusercontent.com/assets/10751521/25809461/9f5ac5a2-343f-11e7-9228-e86b6b50b5a8.png)

![image](https://cloud.githubusercontent.com/assets/10751521/25809423/84ff6b0e-343f-11e7-957f-a9199a6d2cc3.png)

**Comment by liu21st** [comment]
感谢反馈 已经修正
