### ISSUE TITLE
 版本5.1分支，定义资源路由，只有 index 标识的有效？

### ISSUE THREAD

**Issue by weeisc** [top-think/framework#668]
路由配置：Route::resource('test', 'admin/test');

**测试 localhost/test：**
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-9/67793241-file_1494324088394_abdd.png)
***
**测试 localhost/test/45：**
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-9/52155138-file_1494324204011_b235.png)
正确的应该是到 read方法吧
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-9/81752546-file_1494324253678_6a08.png)

其他的也试过了都转到了miss路由处理逻辑了

**Comment by liu21st** [comment]
已经修正
