### ISSUE TITLE
db/builder/Sqlsrv.php中的selectInsert方法定义有BUG

### ISSUE THREAD

**Issue by weeisc** [top-think/framework#669]
selectInsert 方法重写参数应该遵循Builder父类吧，
报错如下：
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-10/65516273-file_1494387594098_10af3.png)

**Comment by liu21st** [comment]
感谢反馈 已经修正

**Comment by weeisc** [comment]
刚刚更新了代码，看到了所有的方法参数都加了 Query类型限定。
但是builder子类文件里并没有use think/db/Query 还是有报错
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-10/45512423-file_1494413144553_17a2a.png)

**Comment by liu21st** [comment]
@weeisc 好了
