### ISSUE TITLE
嵌套关联用数组方式时不支持闭包

### ISSUE THREAD

**Issue by yeahTibbers** [top-think/framework#670]
![image](https://cloud.githubusercontent.com/assets/10751521/25882723/313932fe-3578-11e7-8a33-935cf2e01ac9.png)
![image](https://cloud.githubusercontent.com/assets/10751521/25882732/3751cfe8-3578-11e7-86b7-5a9e9131002d.png)

**Comment by liu21st** [comment]
建议分开来写 目前不支持这种混合方式 可以调用两次with方法 分开实现
