### ISSUE TITLE
当使用【a/structures】注册资源路由时会出现路由BUG，

### ISSUE THREAD

**Issue by weeisc** [top-think/framework#672]
测试出有问题的资源路由：
```
$rest = [
    'a/structures'=>'admin/test',
    'ad/structures'=>'admin/test',
    'adm/structures'=>'admin/test',
    'admi/structures'=>'admin/test',
    'admin/structures'=>'admin/test',
    'admin/structure'=>'admin/test',
];
```
当访问数组中任意一个 且地址为 `localhost/admin/structures`  这种格式时，都会路由到 对应控制器下边
的`create`方法，正常应该是路由到 `index` 方法
资源路由测试类代码
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-12/36040709-file_1494567075300_f94f.png)
测试结果：
![](http://ooqv5ghsp.bkt.clouddn.com/17-5-12/20324453-file_1494567138419_12ca3.png)
测试了下问题应该在Resource.php 里的 
`$item = ltrim(ltrim($rule . $val[1], '/'), $this->name . '/');`这里，
变量`$item`的结果，`index`跟`create`的情况一样都是空字符串，
那在 `$this->router->rule($item, $this->route . '/' . $val[2], $val[0], $option);`这里，`create` 的情况就把 `index`的情况覆盖掉了

**Comment by liu21st** [comment]
资源路由怎么会支持 admin/structure 这种定义呢？

**Comment by liu21st** [comment]
就算是多级嵌套资源路由 也是应该写成 admin.structure

**Comment by weeisc** [comment]
没看过专讲路由的手册，5.0的时候像下边这样写没发现有问题，
```
    // 定义资源路由
    '__rest__'=>[
        'admin/rules'		   =>'admin/rules',
        'admin/groups'		   =>'admin/groups',
        'admin/users'		   =>'admin/users',
        'admin/menus'		   =>'admin/menus',
        'admin/structures'	   =>'admin/structures',
        'admin/posts'          =>'admin/posts',
    ],
```

**Comment by liu21st** [comment]
已经修正 @weeisc
