### ISSUE TITLE
发现修复的几个bug，主要涉及关联模型数据绑定到主模型

### ISSUE THREAD

**Issue by zhyaphoo** [top-think/framework#675]
1.文件/thinkphp/library/think/model/concern/Conversion.php

添加：
use think\Loader;
use think\Model;
use think\Exception;

把：
$model    = $this->getRelation($relation);
        if ($model instanceof Model) {
            foreach ($append as $key => $attr) {
                $key = is_numeric($key) ? $attr : $key;
                if ($this->__isset($key)) {
                    throw new Exception('bind attr has exists:' . $key);
                } else {
                    $this->setAttr($key, $model->$attr);
                }
            }
        }
替换为：
$model    = $this->getAttr($relation);

-----------------------------------------------------------------------------

2.文件/thinkphp/library/think/model/concern/RelationShip.php

把：
if (method_exists($this, $relation))
替换为：
if (method_exists($this, $relation) && $this->$relation() instanceof Relation)

-----------------------------------------------------------------------------

3.文件/thinkphp/library/think/model/concern/Attribute.php

把：
$this->relation[$name] = $value;
替换为：
$this->relation = array_merge($this->relation, $value->getData());

-----------------------------------------------------------------------------

4.文件/thinkphp/library/think/Model.php

把__isset函数里：
$this->getAttr($name);
return true;
替换为：
return false;

**Comment by ganlvtech** [comment]
如果本地测试通过了，直接发Pull Request吧。通过Issue这样改代码是违背git的理念的。
