### ISSUE TITLE
软删除的withTrashed和onlyTrashed返回值

### ISSUE THREAD

**Issue by simphp** [top-think/framework#678]
软删除的withTrashed和onlyTrashed返回值是Query而不是Model，用起来很不方便，在模型里写的方法都不能用，还要再处理一次。建议能不能统一都返回Model实例呢？

**Comment by simphp** [comment]
暂时修改了一下，不知有没有问题
`    /**
     * @var int
     * 0:不包含软删除 $model->select()
     * 1:包含软删除 $model->withTrashed()->select()
     * 2:仅软删除 $model->onlyTrashed()->select()
     */
    protected $softDeleteType = 0;

    /**
     * 查询软删除数据
     * @access public
     * @return Model
     */
    public function withTrashed()
    {
        $this->softDeleteType = 1;
        return $this;
    }

    /**
     * 只查询软删除数据
     * @access public
     * @return Model
     */
    public function onlyTrashed()
    {
        $this->softDeleteType = 2;
        return $this;
    }

    /**
     * 查询默认不包含软删除数据
     * @access protected
     * @param Query $query 查询对象
     * @return void
     */
    protected function base($query)
    {
        $field = $this->getDeleteTimeField(true);
        if ($this->softDeleteType == 0) {
            $query->useSoftDelete($field);
        } elseif ($this->softDeleteType == 1) {
            $query->removeOption('soft_delete');
        } elseif ($this->softDeleteType == 2) {
            $query->useSoftDelete($field, ['not null', '']);
        }
    }`

**Comment by kinosang** [comment]
withTrashed() 和 onlyTrashed() 都是 Query，后面可以做 where join 等操作，然后要用 get() 等方法取 Model
