### ISSUE TITLE
多模型的事务怎么操作

### ISSUE THREAD

**Issue by yangkaiqi21** [top-think/framework#680]
事务能不能回滚多个模型操作，我试过只能用db回滚，还有单个模型的回滚。怎么处理有多个模型操作，其中一个失败，其他模型操作全部回滚啊。

**Comment by liu21st** [comment]
回滚是针对数据库的 既不是针对表 也不是针对模型 是你自己的写法问题

**Comment by yangkaiqi21** [comment]
用model的update和create方法，如果其中一个失败，其他不能回滚吗？只能用DB::update这样的方法去更新和写入数据  才能回滚吗？
