### ISSUE TITLE
cli 模式下反复出现下面的错误

### ISSUE THREAD

**Issue by tobeway** [top-think/framework#681]
PDO::beginTransaction():send of 22bytes failed with errno=10053 你的主机中的软件中止了一个已建立的连接。[c:\wamp64\www\rfid\thinkphp\library\think\db\Connection.php:638]
每天早上的第一个操作就会出现。还有官网发表话题提示发表成功，但是列表中没有显示，或者提示浏览页面错误。

**Comment by dingdayu** [comment]
好像是数据库链接超时的问题啊。

**Comment by tobeway** [comment]
嗯 有可能。我现在是在报错的地方用try catch捕获 并重新连接。不知道能否解决

**Comment by liu21st** [comment]
我修正了下 可以测试下最新版本的

**Comment by ming200825** [comment]
是5.0.15 版本吗 我改了  break_reconnect=true
//下面 这些代码  应该是 query   execute 里做断线重连处理的 ,我的列队work 如果长时间没有任务时,突然来一个任务  就会 出错 ,有时又有用.有时也没用不会重连,队列直接退出了  ,
 } catch (\PDOException $e) {
            if ($this->isBreak($e)) {
                return $this->close()->query($sql, $bind, $master, $pdo);
            }
            throw new PDOException($e, $this->config, $this->getLastsql());
        } catch (\Throwable $e) {
            if ($this->isBreak($e)) {
                return $this->close()->query($sql, $bind, $master, $pdo);
            }
            throw $e;
        } catch (\Exception $e) {
            if ($this->isBreak($e)) {
                return $this->close()->query($sql, $bind, $master, $pdo);
            }
            throw $e;
        }

**Comment by ming200825** [comment]
![qq 20180224165102](https://user-images.githubusercontent.com/4900401/36627781-f1fdf288-1982-11e8-8c59-93afa0457b78.png)
现在 我用了个时间 看 一下 多久 会失败  如果 一直没有会务的话 ..用的是 think-queue
