### ISSUE TITLE
File类buildSaveName问题

### ISSUE THREAD

**Issue by nagatoyk** [top-think/framework#694]
返回的是
文件夹\文件名
正常来说
应该是
文件夹/文件名
搜索了一些相关信息
发现 在win环境下 的DS 会变成\(反斜杠)
而在非win环境下 的DS 就是正常的/正斜杠()

![Uploading QQ截图20170605071825.png…](http://kloli.tk/img/7c5fc00578bcb5189fda42dc059da79d.png)

**Comment by liu21st** [comment]
返回的是文件的服务器地址 不是URL地址
