### ISSUE TITLE
软删除不生效！

### ISSUE THREAD

**Issue by JunJun-Love-Amber** [top-think/framework#696]
Model 已启用软删除，但是下面的两个例子却和我得到的SQL与我的认知发生矛盾，请作者看看，如果确实无BUG，请 关闭这个 issue.
1：
Code：UserModel::where(['status' => 1])->update(['status' => 0]);
SQL：UPDATE `user`  SET `status`=0  WHERE (  `status` = 1 ) AND `paycenter_user`.`delete_time` IS NULL
2：
Code：(new UserModel)->save(['status' => 0],['status' => 1])
SQL：UPDATE `user`  SET `status`=0,`update_time`=1496675660  WHERE  `status` = 1

同样用一个Model 为什么用 【update】 有加入软删除查询，而用【save】就没有呢？
thinkphp : 5.0.9; php 5.6

伤心欲绝！！删除也没有正确调用软删除
1： 为什么这里就DELETE 掉了，要死人了！！！！惨绝人寰，是不是我理解文档有误？
Code：(new UserModel)->where(['status' => 0])->delete();  Or ：UserModel::where(['status' => 0])->delete()
SQL：DELETE FROM `paycenter_user`    WHERE (  `status` = 0 ) AND `paycenter_user`.`delete_time` IS NULL  
2：UserModel::destroy(['status' => 0])
SQL：UPDATE `paycenter_user`  SET `delete_time`=1496677297,`update_time`=1496677297  WHERE  `id` = 1788

**Comment by Antisunny** [comment]
软删除的::destory只接受array/function，不过文档中说还接受主键，fuck

**Comment by JunJun-Love-Amber** [comment]
两份文档都没有写过，直接批量 delete 软删除是不生效的。那么究竟是bug还是就是这样，好疑惑啊！

**Comment by liu21st** [comment]
首先 软删除功能是模型的操作，你调用数据库的删除方法必然无效
其次 你要用面向对象的思想去操作（这个需要慢慢体会）才能写出规范的代码

@Antisunny 请认真看代码
