### ISSUE TITLE
$this->redirect 第二参数$params的bug

### ISSUE THREAD

**Issue by lenuse** [top-think/framework#697]
$this->redirect("/user/index",["a"=>1,"b"=>2]);页面会直接跳转到host/user/index，没有携带参数。
如果是$this->redirect("user/index",["a"=>1,"b"=>2]); 我在host/api/index/index下调用会到host/api/user/index/a/1/b/2.html。

**Comment by liuwave** [comment]
这个bug，很早就存在了。不知什么原因，提交过，一直没改....
https://github.com/top-think/framework/pull/655/commits/c26aa96edaa583740ea0e20a27e58254c8892c51

可能老大比较忙吧
