### ISSUE TITLE
路由逆向解析不正确

### ISSUE THREAD

**Issue by leunggamciu** [top-think/framework#7]
例如我有一组路由

`Route::get('foo/bar/baz', '@aaa/bbb.CCC/index');`

当我使用

`Url::build('@aaa/bbb.CCC/index')`

得出来的值是：`/aaa/bbb.CCC/index`

而不是：`/foo/bar/baz`。

这种情况在RC2中并没有出现，最近升级到最新版本时才出现

**Comment by leunggamciu** [comment]
应该是这样里的修改导致的：https://github.com/top-think/framework/blob/master/library%2Fthink%2FUrl.php#L208

**Comment by liu21st** [comment]
主要你的路由定义中没有任何的变量 我提交修正了

**Comment by momoca** [comment]
我也遇到了...我刚刚试了下,好像还是楼主的问题呀.并没有解决...

**Comment by leunggamciu** [comment]
@momoca 在29a5fa935025ad5d22b1bc513b687b0a573857dc和d5516d7200890bdbe104d179574ffb9d502981e9这两个提交里修正了，你更新一下试试。
