### ISSUE TITLE
模板使用默认值不支持多级嘛？

### ISSUE THREAD

**Issue by shenfakuan** [top-think/framework#72]
`
<td>{:$menu.parent.title | default = "无"}</td>
<td>{$menu.group | default = "无"}</td>
`

解析结果
`
Parse error: syntax error, unexpected 'default' (T_DEFAULT) in /wwwroot/newthink/runtime/temp/90b101dda1e9f74a4e15ff139d759c7e.php on line 155
0.039758s ShowPageTrace
[4] ErrorException in 90b101dda1e9f74a4e15ff139d759c7e.php line 155
syntax error, unexpected 'default' (T_DEFAULT)
<td><?php echo $menu['parent']['title'] | default = "无"; ?></td>
                    <td><?php echo (isset($menu['group'] ) && ($menu['group']  !== '')?$menu['group'] : "无"); ?></td>
`
往下一级没有问题，$menu.parent.title 不行

**Comment by momoca** [comment]
{:$menu.parent.title...}
{:$xxx}的写法会被解析成<?php echo ...?>所以如下两种方法是正确的.
```php
{:$menu['parent']['title']}
//或
{$menu.parent.title|default = "无"}
```

**Comment by shenfakuan** [comment]
我又一次输在了符号上面，：是之前打印了一下，o(╯□╰)o
