### ISSUE TITLE
 配置项 exception_handle 设置不生效

### ISSUE THREAD

**Issue by zero0-1one** [top-think/framework#722]
按文档进行实现，但不生效
// 异常处理handle类 留空使用 \think\exception\Handle
'exception_handle' => '\\app\\common\\exception\\Http'，

<?php
namespace app\common\exception;
use think\exception\Handle;
use think\exception\HttpException;
class Http extends Handle
{
public function render(\Exception $e)
{
if ($e instanceof HttpException) {
$statusCode = $e->getStatusCode();
}/
/TODO::开发者对异常的操作
//可以在此交由系统处理
return parent::render($e);
}
}

**Comment by tic8** [comment]
没问题啊
