### ISSUE TITLE
redirect('/index.html')->getTargetUrl()会出现双后缀

### ISSUE THREAD

**Issue by ganlvtech** [top-think/framework#724]
redirect(url('index/Index/index'))->getTargetUrl() 的值修改前后不一样

v5.0.9-v5.0.10无缝升级错误。

错误来两次commit

<https://github.com/top-think/framework/commit/274666f7c5e7065696d79c9ce472fbf51859c774>

<https://github.com/top-think/framework/commit/b50084099be9571bb380fa748342e98b9b82fa97>

第二次commit没有完全恢复到之前的版本，Url::build可以检测到'://'和'/'，不会处理url，但是仍然会再加一个后缀，变成‘index.html.html'。

希望可以完全恢复为之前的版本

**Comment by liu21st** [comment]
本来这些方法就不需要再调用url方法的 内部会自动调用的

**Comment by ganlvtech** [comment]
redirect(url('index/Index/index'))这个可以我看过代码之后已经理解了，改成了redirect('index/Index/index')，但是如果我想做redirect('/some_page.html')呢，或者redirect('/some_download.exe')呢。

我认为redirect函数应该只处理跳转，而url生成应该交给url函数，所以才那样写的。这个具体怎么办看官方的吧，最好能在手册里提一下。

**Comment by liu21st** [comment]
这个地方我改进了下最新版本
