### ISSUE TITLE
关于tp5多应用设置的一些疑问

### ISSUE THREAD

**Issue by xiaoguo0426** [top-think/framework#727]
你好，我想问下tp5可以像yii2那样设置多应用？大概目录如下：
/
backend
---application
---extend
---static
---runtime
---index.php
frontend
thinkphp
vendor

*****************************
.我的想法是把前台和后台分离成两个应用，互不干扰；以后多一个应用，如api，也能够灵活增加；

**Comment by liu21st** [comment]
互不干扰的两个应用？增加入口文件就行了 每个应用是一个入口 前后台两个模块就行了 无需两个应用，应用之间的交互没有模块之间的数据交互方便
