### ISSUE TITLE
_initialize()中已经使用return $this->error();后程序仍然会渲染下面的模板

### ISSUE THREAD

**Issue by d87904488** [top-think/framework#73]
结果就是这样
![qq 20160512161930](https://cloud.githubusercontent.com/assets/18729228/15208282/50df3682-185d-11e6-81f8-8c8074ea2d06.png)
今天最想下的thinkphp

**Comment by cbwfree** [comment]
因为 `_initialize()` 方法相当于 ` 二次构造函数`, 你在 `__construct` 方法中使用 `return` 将会被 `PHP` 给忽略.
