### ISSUE TITLE
5.1 模板函数###无法解析

### ISSUE THREAD

**Issue by kokororin** [top-think/framework#730]
`<td>{$vo.create_time | date="y-m-d H:i", ###}</td>`
实际编译后的代码为
`<td><?php echo htmlentities(date_format(date_create($vo['create_time']),"y-m-d H:i",###)); ?></td>`

**Comment by kinosang** [comment]
多个函数请继续使用管道符号

参见 https://www.kancloud.cn/manual/thinkphp5/125005

**Comment by kokororin** [comment]
现在不是多个函数……是单函数多个参数
完全是手册上的例子。

**Comment by kinosang** [comment]
这个编译结果没问题啊

**Comment by kokororin** [comment]
#相当于注释，所以直接报语法错误了。

**Comment by kinosang** [comment]
这个 ### 的意思是要你自己填写一个参数……

**Comment by momoca** [comment]
测试一了下这种写法完全没有问题.错误不能复现.

**Comment by kokororin** [comment]
@momoca 5.1版本，我初始化一个新项目也是如此。

**Comment by kinosang** [comment]
烦请检查运行环境

**Comment by kokororin** [comment]
重现步骤
```
git clone https://github.com/kokororin/tp-test

cd tp-test
composer install
cd public
php -S localhost:5000
open http://localhost:5000/index/index/test
```

**Comment by liu21st** [comment]
5.1 模板引擎的date已经作为内置规则了 所以不需要这样用了 参考5.1完全开发手册 https://www.kancloud.cn/manual/thinkphp5_1
