### ISSUE TITLE
thinkphp5.1 调试问题

### ISSUE THREAD

**Issue by slmhvip** [top-think/framework#734]
如果设置      app_debug = true;   情况下没有错误
但如果设置  app_debug = false;   情况下就有错误，把异常抛出后显示错误为
<pre>
object(think\exception\ErrorException)#37 (9) {
  ["severity":protected]=>
  int(64)
  ["data":protected]=>
  array(0) {
  }
  ["message":protected]=>
  string(82) "Cannot use think\model\Collection as Collection because the name is already in use"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(48) "D:\xx\thinkphp\library\think\Debug.php"
  ["line":protected]=>
  int(15)
  ["trace":"Exception":private]=>
  array(1) {
    [0]=>
    array(4) {
      ["function"]=>
      string(11) "appShutdown"
      ["class"]=>
      string(11) "think\Error"
      ["type"]=>
      string(2) "::"
      ["args"]=>
      array(0) {
      }
    }
  }
  ["previous":"Exception":private]=>
  NULL
}
</pre>

自己代码中没有使用过 Collection，请问一下是什么原因

如果把 think\Debug.php 中的 第15行去掉 
并把 185行中 Collection 改成 \think\model\Collection 
问题即可解决

实在是找不到原因才去改动代码的，请哪位大神给个指示

**Comment by slmhvip** [comment]
些情况只在调用数据库的时候发生

**Comment by liu21st** [comment]
已经修正
