### ISSUE TITLE
\think\Response & \triaits\controller\Jump 的一些建议

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#74]
1. 建议在 `Response::instance()` 方法的 `@return` 注释上加上 `static`, 这样在 `PhpStorm` 中才能正常出现 `Response` 方法的代码提示, 即:

```
    /**
     * 初始化
     * @access public
     * @param string $type 输出类型
     * @return \think\Response|static
     */
```
1. 建议 `\triaits\controller\Jump` 中所有的方法都能使用 `return` 返回数据, 再由 `\think\App` 统一进行输出. 
   修改 `success` 和 `error` 方法中的 
   `Response::instance()->send($result, $type)` 
   为
   `return Response::instance()->type($type)->data($result);`
2. 建议 `\triaits\controller\Jump` 中 `redirect` 方法可以自动退出.
   修改 `Response::instance()->redirect($url, $params);` 
   为 `Response::instance()->isExit(true)->redirect($url, $params);`

**Comment by liu21st** [comment]
感谢反馈和建议 response类 我们还会进行一些调整 到时候一并处理下
