### ISSUE TITLE
tp 5.0.10版本 的路由有问题

### ISSUE THREAD

**Issue by kkstun** [top-think/framework#742]
我设置 Route::any 会出现
该网页无法正常运作

127.0.0.1 将您重定向的次数过多。
尝试清除 Cookie.
ERR_TOO_MANY_REDIRECTS

5.0.9没有问题

**Comment by liu21st** [comment]
请给出具体的示例和重现步骤

**Comment by kkstun** [comment]
多次尝试, 可能我之前写的不规范.
Route::any('test','/test');在5.0.10版本之前没问题
5.0.10会报错ERR_TOO_MANY_REDIRECTS
后来看了手册
Route::any('test','test');在5.0.10版本就可以了
