### ISSUE TITLE
如果配置了url_route_must=true，连 public 里面的 php 文件都访问不了了。感觉这里时是不是应该只限定 controller 里的方法呢。

### ISSUE THREAD

**Issue by terranc** [top-think/framework#753]
RT

**Comment by kinosang** [comment]
在 nginx 或 apache 上，写规则时绕过真实存在的文件。

比如 nginx 中 使用 `try_files $uri $rui/ /index.php?s=$request_uri`

Apache 用
```
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
```
不对文件和目录进行rewrite

**Comment by terranc** [comment]
@kinosang 3Q，是可以替换掉官方文档里的咯？

**Comment by terranc** [comment]
```
location / {
    try_files $uri $uri/ /index.php?s=$request_uri;
}
```
改成这样以后，还是没解决。
我是按照workman 的`https://www.kancloud.cn/manual/thinkphp5/235128`文档操作，只是把`server.php`放在了`public`里面。
```
#!/usr/bin/env php
<?php
define('APP_PATH', __DIR__ . '/../application/');
define('BIND_MODULE','index/Worker');
// 加载框架引导文件
require __DIR__ . '/../thinkphp/start.php';
```

结果在浏览器运行会在 server.php打代码运行后连带把路由的根路由只想的方法执行，在命令行`php server.php`就报错

**Comment by liu21st** [comment]
命令行执行的程序干嘛要放入public目录？

**Comment by terranc** [comment]
@liu21st 放 root 也一样

**Comment by kinosang** [comment]
对于 server.php 理解错误

server.php 不是供浏览器使用的
