### ISSUE TITLE
Validate 验证BUG

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#76]
`Validate`类的`checkItem` 方法中的第 `338` 行

```
// 如果不是require 有数据才会行验证
if (0 === strpos($info, 'require') || !empty($value)) {            // TODO 这里的 !empty($value)
    // 验证类型
    $callback = isset(self::$type[$type]) ? self::$type[$type] : [$this, $type];
    // 验证数据
    $result = call_user_func_array($callback, [$value, $rule, &$data, $field]);
} else {
    $result = true;
}
```

在验证数据时, 使用的判断 `!empty($value)` 会将值为 `0` 的情况给忽略掉
比如要验证 `gt:0` 这里将始终跳过验证数据, 直接返回 `true`

**Comment by liu21st** [comment]
对于必须验证字段 必须首先使用require规则

**Comment by cbwfree** [comment]
这里我用的规则是 `require|number|gt:0`，但 `gt:0` 的规则始终无法验证。
不知道 `$info` 在这里应该是全部的规则还是单条规。

**Comment by cbwfree** [comment]
另外，我个人认为，这里的空判断应该是 null 和 '' ，而 0 应该属于不为空

**Comment by samplecms** [comment]
0应该是有值，现在验证规则是有问题的，比如状态字段 0，1这时如果选0就提示必填。。这样不大好。
还有unique在编辑 的时候应该自动判断，而不是用户再传个传在规则 里面。。
