### ISSUE TITLE
CLI下:MySQL has gone away

### ISSUE THREAD

**Issue by BarryBravo** [top-think/framework#760]
因为脚本较长时间未与数据库进行通信，导致数据库连接超时与服务器断开连接，这时使用断开的数据库连接操作数据库，就产生’ MySQLserver has gone away’的错误提示。请问这个如何解决，有没有保持心跳方法或者重连机制呢？

**Comment by liu21st** [comment]
更新到最新版本了么？

**Comment by BarryShieh** [comment]
没有，用的是5.0.6版本，最新版的没有这个问题是吗，我试试看，哈哈！

**Comment by zoujingli** [comment]
需要重新连接，用db方法
