### ISSUE TITLE
 具体模型类里指定表名（$table 这个属性）没有效果

### ISSUE THREAD

**Issue by weeisc** [top-think/framework#761]
如题，而且不指定name也拿不到表名，指定前缀也没有效果。

模型类：
![](http://ooqv5ghsp.bkt.clouddn.com/17-7-27/33372442.jpg)
测试代码：
![](http://ooqv5ghsp.bkt.clouddn.com/17-7-27/76906586.jpg)
结果
![](http://ooqv5ghsp.bkt.clouddn.com/17-7-27/4065050.jpg)

**Comment by liu21st** [comment]
模型的connection属性是不支持设置前缀的
