### ISSUE TITLE
Query类中的chunk()。如果将某个字段设置了倒序时,会出现数据重复

### ISSUE THREAD

**Issue by nonme** [top-think/framework#765]
`SELECT * FROM `yq_report` WHERE ( `report_time` > 1498907040 ) AND `yq_report`.`delete_time` IS NULL ORDER BY report_time DESC,`id` asc LIMIT 100`
这条SQL查询到的最后ID是24505

`SELECT * FROM `yq_report` WHERE ( `report_time` > 1498907040 AND `id` > 24505 ) AND `yq_report`.`delete_time` IS NULL ORDER BY report_time DESC,`id` asc LIMIT 100`
这条SQL查询到的最后ID是24507

倒序之后24505不是最大的ID，但是下一条SQL中条件`id` > 24505 导致查询的数据出现重复。

SELECT * FROM `yq_report` WHERE ( `report_time` > 1498907040 AND `id` > 24507 ) AND `yq_report`.`delete_time` IS NULL ORDER BY report_time DESC,`id` asc LIMIT 100

SELECT * FROM `yq_report` WHERE ( `report_time` > 1498907040 AND `id` > 24606 ) AND `yq_report`.`delete_time` IS NULL ORDER BY report_time DESC,`id` asc LIMIT 100

**Comment by liu21st** [comment]
尽量不要设置额外的排序字段，chunk方法目前只能指定一个排序字段
