### ISSUE TITLE
5.0.10 版本 PDO::prepare(): MySQL server has gone away

### ISSUE THREAD

**Issue by 724442033** [top-think/framework#766]
为什么  5.0.10 版本CLI模式下 已打开数据重连仍偶尔现报错： exception 'think\exception\ErrorException' with message 'PDO::prepare(): MySQL server has gone away' in /app/thinkphp/library/think/db/Connection.php:368

**Comment by AxiosCros** [comment]
在Db类里添加一个clear方法
public static function clear(){
        self::$instance = null;
    }

在cli模式中，执行Db操作前，先用Db::clear()清一下再操作试试。我是这么解决的

**Comment by tic8** [comment]
'break_reconnect' => true
数据库配置中有加断线重连配置项吗

**Comment by AxiosCros** [comment]
这个配置断线重连没用的，我试了好几种方法，最后还是销毁Db类最管用，问题再也没出现过了
