### ISSUE TITLE
v5.0.10 cli模式下偶尔报think\db\Connection::free(): send of 9 bytes failed with errno=32 Broken pipe[/data/www/thinkphp/library/think/db/Connection.php:316

### ISSUE THREAD

**Issue by tic8** [top-think/framework#769]
已经开启断线重连。5.0.10版本中cli模式下偶尔报think\db\Connection::free(): send of 9 bytes failed with errno=32 Broken pipe[/data/www/thinkphp/library/think/db/Connection.php:316

**Comment by ming200825** [comment]
我也是这样的错误  在队列 里面 如果  数据库链接上时间没有使用 就会出现这个错误 不知道 怎么办

**Comment by liu21st** [comment]
更新到最新版本

**Comment by ming200825** [comment]
Db::name($tablename)->where($prepayMap)->update($prepayUpdateData);  是不是这个 我在think-queue 里不会重连...

**Comment by liu21st** [comment]
我改进了下 断线重连的错误判断

**Comment by ming200825** [comment]
试了没用..   队列 是在增加下面这行,后重启队列的..
![qq 20180309205110](https://user-images.githubusercontent.com/4900401/37208256-a730c79a-23db-11e8-83b1-d868e6c97507.png)
![qq 20180309205110](https://user-images.githubusercontent.com/4900401/37208343-081f51c0-23dc-11e8-9dfa-26ddf2bf28fd.png)
![qq 20180309205444](https://user-images.githubusercontent.com/4900401/37208360-1e9b0b4c-23dc-11e8-9d2f-e6662fcb611c.png)  这是日志记录的重连失败时间 和 pm2日志吻合..

**Comment by ming200825** [comment]
是不是要指定 dns 连接才会重连...
我的配置是这样的 是有问题 吧...
![qq 20180309211332](https://user-images.githubusercontent.com/4900401/37209102-ddd91dbc-23de-11e8-834f-37e4101cc174.png)

**Comment by ming200825** [comment]
//埋点监控 断线重连 为什么失败的原因,  程序 一直在重连 但一直没有连上.........
   $this->numRows = $this->PDOStatement->rowCount();
            return $this->numRows;
        } catch (\PDOException $e) {
            if ($this->isBreak($e)) {
                Log::record('b1', 'error');
                return $this->close()->execute($sql, $bind);
            }
            throw new PDOException($e, $this->config, $this->getLastsql());
        } catch (\Throwable $e) {
            if ($this->isBreak($e)) {
                Log::record('b2', 'error');
                return $this->close()->execute($sql, $bind);
            }
            throw $e;
        } catch (\Exception $e) {
            if ($this->isBreak($e)) {
                Log::record('b3', 'error');
                return $this->close()->execute($sql, $bind);
            }
            throw $e;
        }
=====================break_reconnect 埋点============================
foreach ($info as $msg) {
            if (false !== stripos($error, $msg)) {
                Log::error("break_reconnect");
                return true;
            }
        }
========================日志记录============================
[ 2018-03-16T10:19:40+08:00 ][ error ] [8]PDOStatement::execute(): send of 44 bytes failed with errno=32 Broken pipe
[ 2018-03-16T10:19:40+08:00 ][ error ] break_reconnect
[ 2018-03-16T10:19:40+08:00 ][ error ] b2
[ 2018-03-16T10:19:40+08:00 ][ error ] break_reconnect
[ 2018-03-16T10:19:40+08:00 ][ error ] b1
[ 2018-03-16T10:19:40+08:00 ][ error ] break_reconnect
[ 2018-03-16T10:19:40+08:00 ][ error ] b1
中间N行
[ 2018-03-16T10:19:40+08:00 ][ error ] break_reconnect
[ 2018-03-16T10:19:40+08:00 ][ error ] b1
[ 2018-03-16T10:19:40+08:00 ][ error ] [1]Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes)

**Comment by tic8** [comment]
@ming200825 你这段代码是守护进程脚本程序吧？

**Comment by ming200825** [comment]
我的是 mysql  在另一台机器 上 可能是这个原因. 不是localhost,
 'type'            => 'mysql',
    // 服务器地址
    'hostname'        => '192.168.1.39',
    // 数据库名
    'database'        => 'tttttt',
    // 用户名
    'username'        => 'yyyyyy',
    // 密码
    'password'        => 'xxxxx',
    // 端口
    'hostport'        => '3306',
    // 连接dsn
    'dsn'             => '',
    // 数据库连接参数
    'params'          => [],
    // 数据库编码默认采用utf8
    'charset'         => 'utf8',

**Comment by ming200825** [comment]
是框架 的 Connection.php 里的啊 重连 是框架本来就有的

**Comment by tic8** [comment]
@ming200825 我是说出现这个报错的时候是你执行的程序是守护进程脚本吧

**Comment by ming200825** [comment]
是的 @tic8

**Comment by tic8** [comment]
@ming200825 脚本执行时间不要超过8小时，在8小时内保证重启一次就可以了。

**Comment by ming200825** [comment]
@tic8  主要是想明白 为什么重连不上

**Comment by tic8** [comment]
目前我知道这种报错是在脚本执行时间比较长的情况下出现。而mysql的wait_timeout参数默认时间是8小时。超过这个时间的基本就会出现这个错误。改进方案还请 @liu21st 大神看下。

**Comment by ming200825** [comment]
> mysql数据库有一个wait_timeout的配置，默认值为28800(即8小时).
> 在默认配置不改变的情况下，如果连续8小时内都没有访问数据库的操作，再次访问mysql数据库的时候，mysql数据库会拒绝访问。

我想问一下 thinkphp 现在 的断线重连机制 能否受上面的限制  还有如果 mysql 在另一台服务器上 断线重连机制 能否使用
以下是我的 断点 日志     一直尝试 重连 但连不上 最后 内存超了 cli 退出了
![qq 20180608175612](https://user-images.githubusercontent.com/4900401/41152105-476cb5c4-6b45-11e8-98e4-aeac5a424ef6.png)

![qq 20180608175524](https://user-images.githubusercontent.com/4900401/41152130-5c8fcc84-6b45-11e8-9032-fd60ef6b6d68.png)
![qq 20180608175535](https://user-images.githubusercontent.com/4900401/41152137-6012cc26-6b45-11e8-9e0f-3c05d7a36cee.png)
