### ISSUE TITLE
缓存函数设计缺陷导致Getshell漏洞

### ISSUE THREAD

**Issue by IanGely** [top-think/framework#775]
RT 
https://help.aliyun.com/knowledge_detail/57863.html?spm=5176.7720504652.n2.3.rmkBE1

**Comment by liu21st** [comment]
不要随便轻信，官方的部署规范下根本不可能存在问题，如果不按照规范来，而且还被攻击者猜到缓存Key 那和猜到你的密码有啥区别，另外缓存配置有一个prefix参数可以更好的规避这个问题。

**Comment by kinosang** [comment]
所以这就是为什么推荐使用 public 作为 webroot 而非项目根目录。

这种时候就体现出这个要求的优越性了

top-think/think#679
