### ISSUE TITLE
命名范围bug

### ISSUE THREAD

**Issue by yunuo-tech** [top-think/framework#78]
```
public function scopeListInfo($query){
    $query->field('UcenterUser.uid,username,avatar,company_name,idcard_auth,license_auth');
}
```

用命名范围只想调用几个字段  可依然会把表里所有字段都调用出来

SELECT UcenterUser.uid,`username`,`avatar`,`company_name`,`idcard_auth`,`license_auth`,UcenterUser.uid AS uid,`user_type`,`username`,`password`,`weixin`,`qq`,`email`,`mobile`,`group`,`vip`,`avatar`,`score`,`sex`,`age`,`birthday`,`login_total`,`last_login_time`,`last_login_ip`,`reg_ip`,`reg_type`,`reg_time`,`status`,UcenterUserInfo.uid AS info_uid,`company_name`,`province`,`city`,`area`,`address`,`idcard_auth`,`license_auth`,`idcard1`,`idcard2`,`license`,`summary` FROM api_ucenter_user UcenterUser INNER JOIN api_ucenter_user_info UcenterUserInfo ON UcenterUserInfo.uid=UcenterUser.uid WHERE UcenterUser.uid = 1 LIMIT 1

**Comment by liu21st** [comment]
你的完整用法是什么样的？ 因为field方法支持多次调用的

**Comment by benaheng** [comment]
@liu21st  UcenterUser::scope('listInfo')->get(1);
