### ISSUE TITLE
pgsql获取新增主键的问题

### ISSUE THREAD

**Issue by ligg** [top-think/framework#784]
pgsql获取新增主键，通过model目前可以这样获取
$mo->save($data,null,'test_id_seq');
但是为什么
$mo=new Test;
$mo->uid=33;
$mo->type=333;
$mo->save();
$mo->id确没有内容呢？
我们可以看一下model类
 // 获取自动增长主键
            if ($result && is_string($pk) && (!isset($this->data[$pk]) || '' == $this->data[$pk])) {
                $insertId = $this->getQuery()->getLastInsID($sequence);
                if ($insertId) {
                    $this->data[$pk] = $insertId;
                }
            }
这里的$sequence为空，所以getLastInsID是获取不到数据的，pgsql获取新增主键需要采用表名_主键名_seq的方式
这是故意这么设计的还是考虑不周全呢

**Comment by liu21st** [comment]
我改进了下 直接使用 $this->save('test_id_seq'); 暂时不想增加额外方法
