### ISSUE TITLE
isAjax判断不能

### ISSUE THREAD

**Issue by dagang007** [top-think/framework#788]
前端测试用这个
`xmlhttp=new XMLHttpRequest();     
xmlhttp.open("get",‘aja');     
xmlhttp.send(null);    `
然后后端    
tp的isAjax方法返回0，      
用原生的$_SERVER['HTTP_X_REQUESTED_WITH']则是未定义索引

**Comment by kokororin** [comment]
只有jQuery.ajax才有这个头。你需要
```js
xmlhttp.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
```
