### ISSUE TITLE
5.0.11 三元运算不兼容 5.0.10 的写法了吗？

### ISSUE THREAD

**Issue by meishixiu** [top-think/framework#803]
`{$_COOKIE['sidebarMini'] == 'true' ?= 'sidebar-mini'}`

5.0.10 解析出来是：
`if(!empty($_COOKIE['sidebarMini']) && $_COOKIE['sidebarMini']=='true') echo  'sidebar-mini';`

5.0.11 解析出来是：
`if($_COOKIE['sidebarMini']=='true') echo  'sidebar-mini';`

这就会导致 `$_COOKIE['sidebarMini']` 没初始化的时候报 **未定义数组索引: sidebarMini** 的错误

而以前的三元运算解析方式就不会报错

**Comment by liu21st** [comment]
你确定这不是5.1？

**Comment by wangjiaqi** [comment]
确定，composer.json 里配置的就是大于5.0的正式版，不会升级到5.1，而且 composer update 时写的框架升级到5.0.11

**Comment by nottellyou** [comment]
楼主，看下base.php里的版本号，粘上来
