### ISSUE TITLE
field合法检测有卵用

### ISSUE THREAD

**Issue by dagang007** [top-think/framework#808]
手册上说field可以过滤post传递的非法表单域。

$data=[ 'key' => 'value' , 'invalid' => 6 ];      

Db::table('think_user')->insert($data);

这样会报错不存在字段invalid。

$data=[ 'key' => 'value' , 'invalid' => 6 ];     
 
Db::table('think_user')->field('key') -> insert($data);

这样同样会报错。

**Comment by liu21st** [comment]
设置数据库的 fields_strict 参数，默认是开启严格检查 所以会抛异常

**Comment by dagang007** [comment]
蟹蟹刘哥
