### ISSUE TITLE
5.1

### ISSUE THREAD

**Issue by zairoo** [top-think/framework#809]
app.php配置了 'view_depr' => '.', 改为这个，没有效果。如何是好。

**Comment by liu21st** [comment]
应该是在template配置文件中定义

**Comment by zairoo** [comment]
对对，我是在template.php里配置了，但没用。还是/

**Comment by liu21st** [comment]
我测试没问题

**Comment by zairoo** [comment]
// 模板文件名分隔符
    'view_depr'    => '.',//DIRECTORY_SEPARATOR

我用输出仍然不能还是用/而不是. 点。主要是我不想模版目录太多的文件夹，用.分隔会更方便。

**Comment by zairoo** [comment]
我是用这个 return view('', ['title' => '标题']);
用最新的5.1还是提示模板不存在。
