### ISSUE TITLE
并发情况下写日志报错

### ISSUE THREAD

**Issue by tic8** [top-think/framework#819]
框架版本:5.05
报错提示：[2]rename(/data/www/runtime/log/201709/25.log,/data/www/runtime/log/201709/1506346299-25.log): No such file or directory[/data/www/thinkphp/library/think/log/driver/File.php:53]

**Comment by liu21st** [comment]
已经改进

**Comment by leeyisoft** [comment]
:/var/www/html# php think -V
version 6.0.7

还是存在该问题 
vendor/topthink/framework/src/think/log/driver/File.php line:199 error:[rename(/var/www/html/runtime/log/202203/03.log,/var/www/html/runtime/log/202203/1646268541-03.log): No such file or directory]

报错误后，去服务器查看的时候，两个问题都存在
:/var/www/html# ls -l /var/www/html/runtime/log/202203/03.log
-rw-r--r-- 1 www-data www-data 1601181 Mar  3 09:08 /var/www/html/runtime/log/202203/03.log

:/var/www/html# ls -l /var/www/html/runtime/log/202203/1646268541-03.log
-rw-r--r-- 1 www-data www-data 2097522 Mar  3 08:49 /var/www/html/runtime/log/202203/1646268541-03.log

**Comment by leeyisoft** [comment]
> 已经改进

你做的已改进的方法就是添加一个try catch?
`    /**
     * 检查日志文件大小并自动生成备份文件
     * @access protected
     * @param string $destination 日志文件
     * @return void
     */
    protected function checkLogSize(string $destination): void
    {
        if (is_file($destination) && floor($this->config['file_size']) <= filesize($destination)) {
            try {
                rename($destination, dirname($destination) . DIRECTORY_SEPARATOR . time() . '-' . basename($destination));
            } catch (\Exception $e) {
                //
            }
        }
    }`
