### ISSUE TITLE
5.1rc route.php配置泛解析域名无效

### ISSUE THREAD

**Issue by zhiapp-com** [top-think/framework#822]
route.php

Route::domain('admin.xxx.com', 'admin');
Route::domain('*', 'index'); 

application\index\controller\Index.php可以，但是
application\index\controller\Test .php就访问不到了。模块不存在

单独指定如：Route::domain('www.xxx.com', 'index'); 是可以正常访问到的

**Comment by liu21st** [comment]
泛域名一般不包含www

**Comment by zhiapp-com** [comment]
就是用*，会有问题。需要指定二级域名才能正常。你可以试试。5.0正常可以用。

**Comment by liu21st** [comment]
已经修正

**Comment by zhiapp-com** [comment]
还是有问题啊。xxx.com/test 访问不了。只能xxx.com/index/test才行啊。
