### ISSUE TITLE
在base类中无法返回json

### ISSUE THREAD

**Issue by acodercat** [top-think/framework#824]
在base类中无法返回json

**Comment by tic8** [comment]
这个是什么意思

**Comment by acodercat** [comment]
我想在base控制器的构造函数中返回json到客户端。但是如果使用return json()的方法的话，那么它还是会执行子类的方法。我想在在base控制器的构造函数中判断权限，权限不够就直接返回json给客户端

**Comment by tic8** [comment]
@acodercat 嗯，确实如此的。我是重新自己封装的返回。没有用return json()。

**Comment by kinosang** [comment]
构造函数中不能使用 return。
可以考虑抛出 HttpException

**Comment by liu21st** [comment]
继承think\Controller的话 可以使用this->result方法返回 （支持指定类型 而且不需要return）

**Comment by acodercat** [comment]
this->result 给了一个固定的格式，很不爽。比如里面有time什么的

**Comment by liu21st** [comment]
如果觉得格式固定不爽，参考官方result方法的实现自己写个方法就行了
