### ISSUE TITLE
修复Rest资源类型正则匹配错误

### ISSUE THREAD

**Issue by yinggaozhen** [top-think/framework#826]
刘老师，你好：
  之前提了一个Pull Request #820，是对Rest可能存在的bug的修复。但是看了一下文档，Rest被已被标注deprecated。当时觉得即便修复了，似乎并不是很有意义，所以自己Close掉了。
  请问一下，如果这个存在bug，是否有reopen的必要?

**Comment by liu21st** [comment]
嗯 我昨天已经修正了
