### ISSUE TITLE
静态资源加参数访问报错

### ISSUE THREAD

**Issue by eeve** [top-think/framework#839]
`php -S 127.0.0.1:8000 public/router.php` 启动项目

public/文件夹下所有静态资源只要加上参数则报错。例如：

`http://127.0.0.1:8000/public/static/css/base.css?v=1.0.0`

不加 `?v=1.0.0` 参数则正常

报错截图：
![1](https://user-images.githubusercontent.com/16770728/31860004-a2442d6e-b746-11e7-8cbc-d0146a17fcfc.png)

**Comment by liu21st** [comment]
具体版本是什么？

**Comment by eeve** [comment]
@liu21st "version": "v5.0.11"

**Comment by liu21st** [comment]
我改进了下
