### ISSUE TITLE
Validate unique 验证时出现数据中找不到对应字段?

### ISSUE THREAD

**Issue by xiaofengwz** [top-think/framework#84]
我是单独写的验证规则, 用 Validate 类来验证, 前端的字段比如是 userName, unique 规则是: unique:User,username, 此时
if (is_string($rule)) {
            $rule = explode(',', $rule);
        }
        $db    = Db::name($rule[0]);
        $field = isset($rule[1]) ? $rule[1] : $field;
这里的 field 就是 username 了, 而 data 中的是 userName

**Comment by liu21st** [comment]
你的unique规则里面写的是username啊

**Comment by xiaofengwz** [comment]
这个我知道, 就是因为前端的字段名不一样, 我个人理解unique 规则就是: unique:表名,表中字段名

**Comment by xiaofengwz** [comment]
'userName|用户名' => 'require|max:64|unique:User,username', 而 userName 我认为是数据中的字段名, 并不一定是真实的字段名, 所有我认为应该区分一下,  $field = isset($rule[1]) ? $rule[1] : $field; 这句代理处理后就没区分了, 这也许是我理解有问题吧

**Comment by liu21st** [comment]
改进了下你可以再测试下
