### ISSUE TITLE
模型中save方法的第二个参数传array，报框架错误

### ISSUE THREAD

**Issue by zhosoft** [top-think/framework#848]
public function updateLog($logId, $param)
    {
        return $this->allowField(true)->isUpdate(true)->save($param,['receive_id'=>$logId]);
    }
框架报错如下：
[0] Exception in Builder.php line 301
查询表达式错误:'63'
                $str = [];

                foreach ($val as $value) {
                    if (is_array($value)) {
                        if (key($value) !== 0) {
                            throw new Exception('where express error:' . var_export($value, true));
                        }
                        $field = array_shift($value);
                    } elseif (!($value instanceof \Closure)) {
                        throw new Exception('where express error:' . var_export($value, true));
                    }

                    if ($value instanceof \Closure) {
                        // 使用闭包查询
                        $newQuery = $query->newQuery()->setConnection($this->connection);
                        $value($newQuery);
                        $whereClause = $this->buildWhere($query, $newQuery->getOptions('where'));

                        if (!empty($whereClause)) {
**请问这是一个bug吗 ？**

**Comment by liu21st** [comment]
仔细看手册 5.1的查询条件数组格式有变化
