### ISSUE TITLE
遍历处理数据时Model需要重复实例化

### ISSUE THREAD

**Issue by ASK-Lee** [top-think/framework#858]
RT，Model在循环中需要重复实例化（需要将$xxM = new xxModel();写在循环中），不然会出现只更新了第一条数据，后续的更新都没有达到想要的更新，虽然有可能也生成了update语句，但并不同于第一条生成的语句

**Comment by liu21st** [comment]
这种方式并不推荐 模型的更新具有数据变化判断

**Comment by ASK-Lee** [comment]
我说一个应用场景吧：更新文章列表的排序ID，我可能一次性设置了多个，然后打算遍历更新这ids对应的sort值，一条SQL就有点不好写了，所以就需要循环来更新。我本来想到的写法是在循环外面来实例化，里面直接根据条件进行更新，但发现这样写不行，我得将实例化操作写在循环里面，不然就会出现不符合预期的结果。

**Comment by liu21st** [comment]
我增加了一个force方法可以用于强制更新所有数据
