### ISSUE TITLE
5.1前台模板date函数问题

### ISSUE THREAD

**Issue by 8000cabbage** [top-think/framework#861]
数据库中存的是时间戳
$time = 1508982277; //2017/10/26 9:44:37
var_dump(strtotime($time)); //bool(false) 

$time = 1508489607; //2017/10/20 16:53:27
var_dump(strtotime($time)); //int(241058272128)

当前5.1版本替换后
date("Y-m-d H:i:s",strtotime($time) ?: $time);
实际输出

2017-10-26 09:44:37

9607-10-31 15:08:48

第二个不是想要的结果

**Comment by liu21st** [comment]
改进了下 在PHP7下面确实有问题

**Comment by 8000cabbage** [comment]
strtotime支持纯数字的写法，
echo date('Y-m-d H:i:s',strtotime('20170609')); //2017-06-09 00:00:00
echo date('Y-m-d H:i:s',strtotime('20170609112233')); //2017-06-09 11:22:33

$name = 'date(' . $args[1] . ',!is_numeric(' . $name . ')? strtotime(' . $name . ') : ' . $name . ')';
现在这个版本不支持这种写法，觉得应该继续改进或者在手册上说明比较好

**Comment by liu21st** [comment]
有些写法很容易混淆，还是不建议直接传入数字日期格式
