### ISSUE TITLE
关于5.1的获取最后一条数据库sql语句的疑问

### ISSUE THREAD

**Issue by hainuo** [top-think/framework#864]
在5.0.11中 使用`db()->getLastSql()`能够得到最近的一条数据库查询语句
但是在5.1RC中不行 得到的结果位空，是不是在类库的翻转调用中数据返回丢失了

**Comment by liu21st** [comment]
db助手函数是强制重新连接的 所以不要用db函数来获取

**Comment by hainuo** [comment]
明白了
