### ISSUE TITLE
cli模式下Request获取METHOD会报错.

### ISSUE THREAD

**Issue by momoca** [top-think/framework#87]
错误信息
```
  [think\exception\ErrorException]
  Undefined index: REQUEST_METHOD
```
错误日志
`[error] [8]Undefined index: REQUEST_METHOD[D:\servers\vhosts\ThinkPHP\library\think\Request.php:413]`
由于windows的cli下没有$_SERVER['REQUEST_METHOD']变量.

https://github.com/top-think/framework/blob/master/library/think/Request.php#L413

```php
//原为
$method = isset($this->server['REQUEST_METHOD']) ? $this->server['REQUEST_METHOD'] : $_SERVER['REQUEST_METHOD'];
//建议修改为
$method = isset($this->server['REQUEST_METHOD']) ? $this->server['REQUEST_METHOD'] : @$_SERVER['REQUEST_METHOD'];
```
或许你们有更好的解决办法.
@Moobusy @liu21st

**Comment by liu21st** [comment]
感谢反馈 已经改进了
