### ISSUE TITLE
5.1模型关联删除疑问

### ISSUE THREAD

**Issue by 8000cabbage** [top-think/framework#870]
thinphp5.1,php7
模型A hasMany 关联B

A::get(1)->products()->where('id', 24)->delete(); 

model对象中仍有id = 24的数据，其实数据库中已经删除。

觉得正常的逻辑是 数据库和model中都同时删除。或者是我用错了，不能这么用

**Comment by liu21st** [comment]
只有在直接调用模型的delete方法的时候 才会删错模型数据

**Comment by 8000cabbage** [comment]
意思是 模型关联方式 不能删除被关联模型中的数据吗，只能通过B::get(24)->delete() ?
