### ISSUE TITLE
Request 类的 baseUrl 方法计算 baseurl 时出现地址不完整的 bug

### ISSUE THREAD

**Issue by xiaofengwz** [top-think/framework#88]
浏览器 URL: AgentAccount/lists.html?page=1&aid=0&fullname=
分页的 URL: AgentAccount/lists.ht?page=2

lists.html 少了 ml 2个字符; 
$this->baseUrl = rtrim($this->url(), '?' . $this->query()); 是由于此句代码造成的, 麻烦修复, 谢谢

**Comment by liu21st** [comment]
感谢反馈 已经修正~
