### ISSUE TITLE
5.1的验证问题

### ISSUE THREAD

**Issue by acodercat** [top-think/framework#880]
比如一个code字段，我在添加的时候需要验证是否重复，但是再编辑的时候也需要验证重复，但是编辑的时候验证重复的规则不一样。我记得3.2在验证的时候用了一个值来区分是添加时候的重复验证还是编辑时候的重复验证，在5.1没有找到合适的解决方案

**Comment by liu21st** [comment]
定义验证场景方法 改变或者追加额外的验证规则即可
