### ISSUE TITLE
不返回数据集

### ISSUE THREAD

**Issue by qq69154565** [top-think/framework#884]
database 配置 

    // 数据集返回类型
    'resultset_type'  => 'collection',

模型中
    $user = $this::all();
   dump($user);
输出的 依然是一个数组啊

**Comment by liu21st** [comment]
是什么版本？

**Comment by qq69154565** [comment]
5.1 rc3  最新版本

**Comment by liu21st** [comment]
这个不是框架的问题 是5.1版本的dump方法为了更加简单直观对模型和数据集做了toarray处理，你用var_dump输出就知道实际的结果了
