### ISSUE TITLE
(5.0.12改进alias方法)不能对同个表进行多次别名

### ISSUE THREAD

**Issue by dnyz520** [top-think/framework#888]
先看业务需求
`$query
                    ->alias('c')
                    ->field('c.*,count(s.goods_category_id) children_total' . $goodsTotal)
                    ->join('__GOODS_CATEGORY__ s', 's.parent_id = c.goods_category_id', 'left');`

大意就是根据分类ID获取当前ID下的子类,但由于5.0.12版对alias进行了改进.
跟进框架之后发现,在5.0.11时是

`Array
(
    [cs_goods_category] => c
    [__GOODS_CATEGORY__] => s
)`

而在5.0.12时是
`Array
(
    [cs_goods_category] => s
)`

所以导致
`SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table\/alias: 's'`

**Comment by liu21st** [comment]
这种需求 建议使用view方法 会自动处理相同表的别名
