### ISSUE TITLE
助手函数redirect不起作用

### ISSUE THREAD

**Issue by caiweiming** [top-think/framework#89]
在控制器里面调用助手函数redirect没有跳转，也没有报错。
redirect('http://www.baidu.com');
redirect(url('User/signin'));
以上都没有执行跳转，也没有报错，下面就可以正常跳转
$this->redirect('http://www.baidu.com');
$this->redirect('User/signin');

**Comment by liu21st** [comment]
redirect方法需要添加return

**Comment by caiweiming** [comment]
原来如此，谢谢。看来还要多多摸索TP5的新用法。
