### ISSUE TITLE
为什么我的模块下没有这些文件也去加载

### ISSUE THREAD

**Issue by qjly87** [top-think/framework#9]
[info] [ CONFIG ] /Users/lewis/Desktop/htdocs/tp5.local/application/member/config.php
[info] [ CONFIG ] /Users/lewis/Desktop/htdocs/tp5.local/application/member/database.php
[info] [ CONFIG ] /Users/lewis/Desktop/htdocs/tp5.local/application/member/route.php
[info] [ CONFIG ] /Users/lewis/Desktop/htdocs/tp5.local/application/member/validate.php
[info] [ CONFIG ] /Users/lewis/Desktop/htdocs/tp5.local/application/member/auto.php
[info] [ LANG ] /Users/lewis/Desktop/htdocs/tp5.local/application/member/lang/zh-cn.php

**Comment by liu21st** [comment]
你看到的这个信息 其实不是实际加载的 而是执行config类的时候加载行为 （加载内容由配置决定 但不一定存在的）
