### ISSUE TITLE
5.1模型的疑惑

### ISSUE THREAD

**Issue by simphp** [top-think/framework#903]
目前的5.1模型中，每次调用一个魔术方法，就会新建一个Query。
无法这样用：
`
$model->where('id',1');
$model->where('pid',0);
$model->select();
`
只能在一个链式调用中才行，感觉不方便呀。

`public function __call($method, $args)
    {
        return call_user_func_array([$this->db(), $method], $args);
    }`

`
public function db($useBaseQuery = true)
    {
        if ($this->queryInstance) {
            return $this->queryInstance;
        }

        $query = $this->buildQuery();

        if ($useBaseQuery) {
            // 软删除
            if (method_exists($this, 'getDeleteTimeField')) {
                $field = $this->getDeleteTimeField(true);
                $query->useSoftDelete($field);
            }

            // 全局作用域
            if (method_exists($this, 'base')) {
                call_user_func_array([$this, 'base'], [ & $query]);
            }
        }

        // 返回当前模型的数据库查询对象
        return $query;
    }
`

**Comment by liu21st** [comment]
5.1的模型设计是为了避免嵌套查询的混淆问题 相互不会影响

**Comment by liu21st** [comment]
如果你非要这样操作，可以给$model->db() 赋值 然后操作
