### ISSUE TITLE
既然增加了配置目录常量为何不把公共文件也统一一下

### ISSUE THREAD

**Issue by cbwfree** [top-think/framework#91]
RT.
`app` 目录下可能存在 `common.php` , `command.php` , `config.php` , `init.php` 等文件
既然已经把 `command.php` , `config.php` 统一到了 CONF_PATH 中, 为何还单独留着 `common.php` 在`app` 目录中.
有强迫症啊, 不想 `app` 目录下一堆散文件 😂

**Comment by liu21st** [comment]
不同的概念啊 配置归配置
