### ISSUE TITLE
5.1 中发现 Db::table 同时存在 join GROUP_CONCAT group 缓存生成不生效

### ISSUE THREAD

**Issue by ztj1993** [top-think/framework#918]
在 Db::table 查询中，发现每次均生成不同的缓存文件。

$rows = Db::table('tablename')->cache(true)
    ->field("a.*, GROUP_CONCAT(CONCAT_WS('|||',b.name,b.content) separator  '\n')  as namecontent")
    ->alias('a')->join('tablename b', 'a.id = b.sign')
    ->where('a.type', 'aaa')
    ->group('a.id')->limit(10)->select();

**Comment by liu21st** [comment]
你的field写法就有问题 最好是用数组

**Comment by ztj1993** [comment]
@liu21st 经过测试，跟 field 没有关系， join 导致的缓存不生效
