### ISSUE TITLE
U 函数未实现，导致模板中无法使用 url 函数

### ISSUE THREAD

**Issue by stenote** [top-think/framework#92]
https://github.com/top-think/framework/blob/master/library/think/template/taglib/Cx.php#L672

U 函数未实现，无法使用 url 函数。3.2 遗留问题？

**Comment by momoca** [comment]
恩.应该是.等待官方 @liu21st 修正吧.
我全局搜索了一下,好像只有这一处U函数了.

**Comment by stenote** [comment]
fixed !

**Comment by momoca** [comment]
注释...有时间也更正下吧...

**Comment by stenote** [comment]
@momoca 已经更新
