### ISSUE TITLE
v5.0.12 Model使用关联预载入with问题

### ISSUE THREAD

**Issue by yangdongxuan** [top-think/framework#923]
例如模型为
class Article extends Model
{
  public function comments()
  {
    return $this->hasMany('Article', 'id', 'parent_id'));
  }
}
即一对一关联自己，会报以下错误：

SQLSTATE | 23000
-- | --
Driver Error Code | 1052
Driver Error Message | Column 'parent_id' in where clause is ambiguous

在之前的版本是不会报错的

**Comment by liu21st** [comment]
你的关联定义有问题吧 parent_id 不是应该是在第二个参数么
