### ISSUE TITLE
$validate->getError()

### ISSUE THREAD

**Issue by icbd** [top-think/framework#930]
thinkphp source code: 
> thinkphp/library/think/Validate.php
```
    // 验证失败错误信息
    protected $error = [];
```
```
    // 获取错误信息
    public function getError()
    {
        return $this->error;
    }
```

`$validate->getError()` 好像应该返回 Array ? 

现在返回的是字符串, 如果有多个错误只返回了第一个错误的字符串. 
如果能将错误信息绑定到特定的key再一起返回就好了, 这样就更方便前端展示对应的错误了 :)

**Comment by liu21st** [comment]
返回错误信息有很多方式 批量验证返回的是数组

**Comment by ganlvtech** [comment]
https://www.kancloud.cn/manual/thinkphp5/129320 批量验证部分

**Comment by ganlvtech** [comment]
https://www.kancloud.cn/manual/thinkphp5/129320 批量验证部分
