### ISSUE TITLE
File Cache clear异常

### ISSUE THREAD

**Issue by randyli** [top-think/framework#937]
File Cache在清除缓存时抛出异常，array_map第二个参数应该为Array
229：array_map('unlink', glob($path . '/*.php'));

原因：在缓存目录下没有php文件的情况下，glob返回false，导致参数非法
建议修改为：
 $php_files = glob($path . '/*.php');
 if (is_array($php_files)) {
          array_map('unlink', glob($path . '/*.php'));
 }

**Comment by liu21st** [comment]
感谢反馈 已经改进
