### ISSUE TITLE
数据库orm

### ISSUE THREAD

**Issue by chenjiabin** [top-think/framework#946]
belongsTo   setEagerlyType为0 一条SQL

->with()
->withCount()
->select()

最后生成的SQL
子查询count中是带 tp 前缀 如：  `marketing_id` = tp_marketing.id
联合查询中是不带 tp 前缀： 如: `tp_marketing` `marketing` 

导致最终的SQL报错

可以通过withCount第二个参数生成两条SQL成功， 但我想生成 一条SQL该如何改动

**Comment by liu21st** [comment]
with和withCount是不能同时使用的
