### ISSUE TITLE
模型的命名范围(scope)跟关联预载入(with)不能一起使用

### ISSUE THREAD

**Issue by GordonLife** [top-think/framework#95]
由于scope跟with都只能进行模型静态调用，所以两个方法无法同时使用，看是否考虑优化？
比如User模型定义了一个命名范围和一个一对一关联
class User extends Base
{
    protected $pk = 'user_id';

```
public function profile()
{
    return $this->hasOne('Profile', 'user_id');
}

public function scopeList($query)
{
    $query->field('user_id, username')->limit('20');
}
```

}
控制器中我这样用就会报错
User::with('profile')->scope('list')->select();

**Comment by liu21st** [comment]
可以的 User::scope('list')->with('profile')->select(); 
scope是静态调用的 然后范围的是当前的模型对象实例 可以直接调用所有的链式查询
