### ISSUE TITLE
5.0.12自定义application目录失败

### ISSUE THREAD

**Issue by leunggamciu** [top-think/framework#951]
目测是
https://github.com/top-think/framework/blob/5.0/library/think/Loader.php#L541
硬编码了`App::$namespace`

**Comment by liu21st** [comment]
这怎么是硬编码了呢

**Comment by leunggamciu** [comment]
https://github.com/top-think/framework/blob/v5.0.12/library/think/App.php#L421
原来还有个自定义常量。为了重命名`application`目录，我修改了`app_namespace`这个配置选项，也将`APP_PATH`这个常量修改了，可是最终解析出来的控制器的命名空间还是以`app`开头。我搜了一下，好像核心里并没有用到`app_namespace`这个配置选项，反而使用的是连接里标记的那个`APP_NAMESPACE`常量。

**Comment by leunggamciu** [comment]
自定义了`APP_NAMESPACE`就可以了，也就是说，`app_namespace`这个配置选项是没起作用的

**Comment by liu21st** [comment]
最新版本没有app_namespace配置项的

**Comment by leunggamciu** [comment]
我项目里使用的是5.0.12

**Comment by leunggamciu** [comment]
https://www.kancloud.cn/manual/thinkphp5/118013，5.0的文档里并没有说明`app_namespace`配置项废弃了，也没有提到要用`APP_NAMESPACE`常量来替代原来的方案，我觉得可以补充上去

**Comment by liu21st** [comment]
每次升级之前最需要看的是 官方的升级指导 https://www.kancloud.cn/manual/thinkphp5/163239

**Comment by leunggamciu** [comment]
好吧，没想到升个小版本都能挂掉
