### ISSUE TITLE
redis 驱动提交一个bug

### ISSUE THREAD

**Issue by ming200825** [top-think/framework#958]
public function get($name, $default = false)
    {
        $value = $this->handler->get($this->getCacheKey($name));
        if (is_null($value) || false === $value) {
            return $default;
        }
       // $value ='201712182487393978291457';
       //当$value 为长的数字字符串时 $jsonData是一个浮点型。$value的值没有正确返回。
        $jsonData = json_decode($value, true);
        return (null === $jsonData) ? $value : $jsonData;
    }

**Comment by ming200825** [comment]
$jsonData = json_decode($value, true);
$error = json_last_error();
return (null !== $error) ? $value : $jsonData;

**Comment by liu21st** [comment]
redis驱动早就改成serialize序列化了

**Comment by ming200825** [comment]
哦 是的 5.0.13 ,我用的5.0.12， 
//5.0.12 修复方案 待验证
$jsonData = json_decode($value, true);
$error = json_last_error();
return (0 !== $error) ? $value : $jsonData;
