### ISSUE TITLE
模板{volist} 嵌套 {include} 使用, 变量传递问题

### ISSUE THREAD

**Issue by icbd** [top-think/framework#960]
在被include的模板文件内, 是不是只能使用assign过的全局模板变量? 如何才能把父模板中出现的中间变量传入被引入模板呢? 

(类似React组件间通信的方式, 或者像ERB传递一个对象) 

> thinkphp/library/think/Template.php
`private function parseInclude(&$content)`

**Comment by liu21st** [comment]
include标签的解析是在最开始就解析了 不是在解析volist标签的时候 所以是无效的
