### ISSUE TITLE
TP 5.0.13 配置文件中的控制器类后缀配置项 'controller_suffix' => 'Ctl' 会自动变成 Controller

### ISSUE THREAD

**Issue by sochishun** [top-think/framework#961]
TP 5.0.13 配置文件中的控制器类后缀配置项 'controller_suffix' => 'Ctl' 会自动变成 Controller
文件路径：\vendor\topthink\framework\library\think\Loader.php
方法：public static function parseClass();
内容：
官方的源码：
$class = $class . (App::$suffix || $appendSuffix ? ucfirst($layer) : '');
修正的源码：
$classSuffix = '';
if (App::$suffix === true || $appendSuffix === true) {
	$classSuffix = ucfirst($layer);
} else if ($appendSuffix) {
	$classSuffix = $appendSuffix;
} else if (App::$suffix) {
	$classSuffix = App::$suffix;
}
$class = $class . $classSuffix;
建议'controller_suffix'不要做成布尔值，可以自定义字符串比较灵活。

**Comment by liu21st** [comment]
你说的功能是通过配置 url_controller_layer 参数完成的

**Comment by sochishun** [comment]
个人觉得还是controller_suffix可以支持字符串比较灵活哈，用惯了controller作为控制层通用名称，但是控制层后缀又不想用Controller这么长的目录名称，只能通过controller_suffix来配置后缀了。url_controller_layer一个变量来同时设置控制层目录名和后缀，使用上不灵活哈。

**Comment by liu21st** [comment]
这种兼容问题 是不看能随便调整了的

**Comment by sochishun** [comment]
好吧，感谢作者百忙中抽空回复，恭喜TP5.1发布哈！
