### ISSUE TITLE
链式方法field组装字段错误

### ISSUE THREAD

**Issue by itzj86** [top-think/framework#981]
$date['month'] = $model->field('date_format(`create_time,"%m") as month,date_format(create_time,"%Y") as year,date_format(create_time,"%Y-%m") as ym')
                                ->group('ym')
                                ->having('year in ('.implode(',',array_column($date['year'],'year')).')')
                                ->order('month asc')
                                ->select();
报错了sql语句，在field这个链式方法中，把第二个date_format(create_time,"%Y") as year 使用explode给拆分开了后，没有正确组合为date_format(create_time,"%Y") as year

**Comment by liu21st** [comment]
复杂字段用数组 用数组 说了多少遍了 手册也写的很详细

**Comment by itzj86** [comment]
知道了，大神，看了手册，改为数组就可以了。
