### ISSUE TITLE
Validate only bug 反馈

### ISSUE THREAD

**Issue by zuozhehao** [top-think/framework#986]
伪代码
`$validate = new memberValidate;`
`$result     = $validate->only(['password'])->check($data);`

文件
topthink/framework/library/think/Validate.php:1448

function getScene() 里
$this->only = $this->append = $this->remove = [];
把only置空.导致了only这个方法是无意义的.

**Comment by liu21st** [comment]
only不是你这样用的 是用于场景方法的定义的

**Comment by zuozhehao** [comment]
抛开使用方法.感觉这边逻辑有点问题

[public function only($fields)](https://github.com/top-think/framework/blob/5.1/library/think/Validate.php#L322)
这个方法只作赋值. 然后调用check的时候

[public function check($data, $rules = [], $scene = '')](https://github.com/top-think/framework/blob/5.1/library/think/Validate.php#L389)

check的时候会执行
[protected function getScene($scene = '')](https://github.com/top-think/framework/blob/5.1/library/think/Validate.php#L1441)

getScene 方法里又把only给清空.

所以public function only($fields) 这个方法无论传入任何参数都无效的

**Comment by liu21st** [comment]
你可以仔细看下手册场景用法以及源码再来讨论

**Comment by zuozhehao** [comment]
我也是看了check里的

// 场景检测
 if (!empty($this->only) && !in_array($key, $this->only)) {
     continue;
}

仅仅只是建议.因为场景多的时候得定义非常多个 `scene+场景名`

**Comment by liu21st** [comment]
因为only方法是仅仅用于scene+场景名的方法中定义，避免被其它情况干扰
