### ISSUE TITLE
路由为什么不提供钩子呢

### ISSUE THREAD

**Issue by tangzhangming** [top-think/framework#994]
如果我的路由类似wordpress，每篇文章都可以设定别名，这一部分路由直接从根目录匹配，比如    
domain.com/first_article.html
而不是先路由到某个控制器，再匹配后面的参数，如：
domain.com/article/first_article.html

这个时候，first_article参数是数据库中取出来的，如果系统不提供钩子，就只能提前生成路由文件，或者改写框架，第一种方式不够灵活，第二种方式有侵入性。

望指点一下有无其他解决方法，非常感谢

**Comment by liu21st** [comment]
你可以在系统已有提供的任何钩子位置动态注册路由的

**Comment by tangzhangming** [comment]
我不是很理解您的意思，因为我看文档，只提供了这些钩子
app_init | 应用初始化标签位
app_begin | 应用开始标签位
module_init | 模块初始化标签位
action_begin | 控制器开始标签位
view_filter | 视图输出过滤标签位
app_end | 应用结束标签位
log_write | 日志write方法标签位
log_write_done | 日志写入完成标签位（V5.0.10+）
response_send | 响应发送标签位（V5.0.10+）
response_end | 输出结束标签位（V5.0.1+）
没有路由类的钩子

不过我今天尝试了在app\common.php中查询数据库后写路由，发现是可以实现的

非常感谢
